### ISSUE TITLE
[1.10.2] Milking One Cow Milks Them All

### ISSUE THREAD

**Issue by MokahTGS** [capnkirok/animania#100]
We have two Frisian cows but cannot milk them separately.  Milking one then makes it so the other one cannot be milked as well.

**Comment by capnkirok** [comment]
Thx. Not intentional.

**Comment by Tschipp** [comment]
Could it be possible that the milk variable is static?

**Comment by MokahTGS** [comment]
One cow to rule them all, one cow to find them, One cow to bring them all and in the dark barn bind them.

OK....sorry...not helpful.

**Comment by capnkirok** [comment]
Ah ha ha ha ha!

Beware the Milkwraiths...

**Comment by capnkirok** [comment]
Checked on 1.11.2 and it works fine. Now checking 1.10.

**Comment by MokahTGS** [comment]
I think the issue was the flow of food.  We assumed it would be enough for at least two cows.  Once we kept the food going in the trough we could milk all the cows.  Not sure if thats a bug then.

**Comment by capnkirok** [comment]
Ah yes, working as intended. Was just going to say I couldn't reproduce. But yes, if the cow isn't happy, you don't get milk.
