### ISSUE TITLE
[1.10.2] Bulls Not Rendering (Patent Pending on the name "Invisabull")

### ISSUE THREAD

**Issue by MokahTGS** [capnkirok/animania#102]
We are getting an odd issue where bulls are not rendering their models but are in the world:

https://www.dropbox.com/s/k1ymk0cr3ebc0i4/2017-04-11_18.21.12.png?dl=0

https://www.dropbox.com/s/wmttgblkrdvs1uk/2017-04-11_18.26.30.png?dl=0

This seems to be with all bulls.  They are in the world as I got killed by one after killing another cow.

Here's a list of all the mods we are using that you can open in excel:

https://www.dropbox.com/s/y7i176iupdw67cx/All.mods?dl=0

Also, before you ask, I have tried this without optifine and it doesn't make any difference.

**Comment by capnkirok** [comment]
It's a known bug. Will be fixed in next release.

**Comment by MokahTGS** [comment]
Ok...still holding onto the patent.

**Comment by capnkirok** [comment]
Re-opening as it was fixed on 1.11.2 only, not 1.10.

**Comment by capnkirok** [comment]
Fix added to 1.10.2 as well, and now closed :)
