### ISSUE TITLE
Piglet died in the mud

### ISSUE THREAD

**Issue by Galindorf** [capnkirok/animania#103]
Heya! I had a weird glitch--

I've been ranging around my world trying to find a hog for my sows (I have not seen a single one yet, but I only just added the mod and I suspect any pig I find so far are ones that replaced the vanilla pigs already present). I found a piglet out in the field and brought him home on a lead... when I put him in my pig pen he jumped in the mud and immediately began taking damage. I shoved him out and it stopped, but he leapt back in to his doom!

I also had an unrelated crash where I was attempting to fill in some water where a pig was standing and it caused the game to crash.

...boy those bulls really kill the bejeezus out of you, don't they!? They were able to hit me through fences and everything!

Minecraft 1.11.2
Animania 1.0.4.6
Forge 13.20.0.2255

Also
Dynamic Surroundings 1.11.2-3.3.3.0
FoamFixCore 7.7.4
Mercurius_updater 1.0
Uncrafting Table 1.7.1-pre12
Better Foliage 2.1.3
Biomes O Plenty 6.0.2
D3 Core 1.0
Inventory Pets 1.4.9.3
Just Enough Items 4.2.10.248
Lumberjack 1.0
Pet Bat 1.4.6
Rope Bridge 1.11.2-1.4.8
Sound Filters 0.9 for 1.11
Vertical Slabs 1.0
Waystones 3.0.10

**Comment by Tschipp** [comment]
I'm gonna try and recreate this

**Comment by Tschipp** [comment]
I just realized... you have BOP installed. You used the mud from animania, right? Not the one from BOP?

**Comment by capnkirok** [comment]
Yeah, I need to bump their 'bobbing' to be above the block. Thx.

**Comment by Tschipp** [comment]
To stop all possible suffocation you should probably make the block not be solid, like leaves for example.

**Comment by Galindorf** [comment]
Yes I definitely used the Animania mud, not the BOP mud. I managed to find a couple of boars, but they haven't had any babies yet as far as I can tell... or the little ones drowned! I'm attaching a picture of my 'mud setup' with water in the middle.  They spend all day in the mud! I know they're eating though because the slop disappears from the troughs. 

![screen shot 2017-04-13 at 9 20 47 am](https://cloud.githubusercontent.com/assets/17105217/25009129/4c647a50-202b-11e7-8014-a1c97de2eae0.png)

**Comment by capnkirok** [comment]
Thanks @Galindorf for the report. Turns out there was a change in the way block height is handled in 1.11.2. This will be fixed in next release. Unfortunately, it means that you should keep your poor piglets out of the mud for the time being :/

@Tschipp FYI to fix this, I changed block height to .88 (from .70), then changed all the 'in mud' renders as well to adjust for the new mud height. This fixed both dying in mud and rendering the mud splash.
