### ISSUE TITLE
[1.11.2] Problematic milk oredict interaction; Slop

### ISSUE THREAD

**Issue by Rosethorns** [capnkirok/animania#104]
I think it might be wise to not use milk oredict in the slop recipe or possibly change the name of your oredict as currently it interacts with pams.

This is a problem because fresh milk can be used in the slop recipe and fresh milk is not a bucket recipe so you get a free bucket for making slop with pams "fresh milk"

Alternatively you could blacklist other mod items if they are detected.

Although I don't normally suggest accounting for mod interactions as bugs, being the nature of Animania I can see it being paired with pams quite frequently.

Recreate:
1. convert animania milk to standard milk in table
2. convert standard milk into 4 pams fresh milk with 1 returned empty bucket.
3. craft slop using 4 fresh milk items
4. get 4 buckets of slop
5. empty buckets returned when slop used.

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2279
Animania: 1.0.4.6

**Comment by capnkirok** [comment]
Thanks Rosie. I think I can change my oredict so that you can't make slop with freshmilk, but will find a way to close this :)

**Comment by Tschipp** [comment]
Why is this happening? Are you using a custom IRecipe for the slop or just a normal shapelessOredict?

**Comment by capnkirok** [comment]
It's a normal oredict shapeless recipe, but.. fresh milk is part of ListAllMilk, which is what I'm using in the recipe.

**Comment by capnkirok** [comment]
Ok, after looking at the issue, what I will do is this. I will make a new OreDict recipe for Slop, that allows 4x a 'listAllMilk' to be used in place of a Bucket of Milk, plus an empty bucket. And will change the Animania recipe to only use milk buckets.

**Comment by capnkirok** [comment]
Ok this is fixed. One side effect is that you will see one recipe listed that uses four buckets of milk + one empty bucket (+ veg/bread). Don't think there's a way to delist it. I mean, you can make this one if you want, but you'll burn buckets...

**Comment by Tschipp** [comment]
Weird... I'll test this in my dev environment...
