### ISSUE TITLE
1.11.2/1.0.4.6 Watering Pigs Causes Crash

### ISSUE THREAD

**Issue by polartwins** [capnkirok/animania#106]
If I click on a pig with a vanilla bucket of water it causes the game to crash. I am able to feed them slop and vanilla carrots and beets without issue. Watering other animals seems to work just fine but pigs crash every time. I've only tried this in survival. When I start the game back up, the bucket of water has not been consumed. I am using other mods but this is occurring while using vanilla water buckets.

This is the crash report that followed:
https://pastebin.com/S8zKJQUK

Edited by Tschipp: DO NOT POST ENTIRE CRASH LOGS, use pastebin

**Comment by capnkirok** [comment]
Yep. Can confirm. Fixed in dev environment and at next release.

**Comment by SDUBZ** [comment]
[crash-2017-04-18_23.41.22-client.txt](https://github.com/capnkirok/animania/files/930285/crash-2017-04-18_23.41.22-client.txt)

very easy to repeat crash
above is one of my users on the server 
and the one below is mine
[crash-2017-04-19_01.44.59-client.txt](https://github.com/capnkirok/animania/files/930287/crash-2017-04-19_01.44.59-client.txt)

**Comment by capnkirok** [comment]
Yeah, it's fixed in dev.
