### ISSUE TITLE
[1.11.2 - 1.0.4.6] Angus adults have no horns rendering

### ISSUE THREAD

**Issue by VallenFrostweaver** [capnkirok/animania#107]
As seen below.
![angus](https://cloud.githubusercontent.com/assets/13642054/25230867/8465cd76-25cd-11e7-80c9-f3ee3d768496.png)

**Comment by Tschipp** [comment]
What mods are you using and did you change any configs?

**Comment by VallenFrostweaver** [comment]
I'm using 96 mods in the modpack Modded Mischief II for this. Configs were changed to replace vanilla animals.

**Comment by capnkirok** [comment]
Sadly, this is the the way Angus cows are now. They have been bred to not have horns anymore. I was corrected on this early in the release, so yup, that's correct actually. 

https://en.wikipedia.org/wiki/Angus_cattle

Closing this one :)

**Comment by VallenFrostweaver** [comment]
Cool. I wasn't sure and was basing my observation on the image of the horned version that is displayed on your download page. No worries. :)

**Comment by capnkirok** [comment]
oh you are right, that one needs to be updated :)
