### ISSUE TITLE
[1.11.2 - 1.0.4.6] Longhorn Bull head not connected

### ISSUE THREAD

**Issue by VallenFrostweaver** [capnkirok/animania#108]
As seen below:
![longhorn](https://cloud.githubusercontent.com/assets/13642054/25230953/e339a598-25cd-11e7-842d-e98cd5920226.png)

**Comment by capnkirok** [comment]
It's magic!

**Comment by capnkirok** [comment]
Fixed. It is really bizarre to me what broke in 1.11.2 from the 1.10 upgrade...

**Comment by capnkirok** [comment]
Wow. Turns out this was on 1.10.2 as well. Well, fixed in next release.
