### ISSUE TITLE
[Suggestion] Dogs that guard herds

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animania#11]
If you're planning to add more sheep and wolves, I think this might be a nice addition:

Herd Dogs, that stick with the herd, protects them and can lead them around. The dogs would for example protect Sheep from other wild wolves and when telling the dogs to follow, the herd (or some of them) would follow the dog (similarly to the 1.11 Llama mechanic).

On another note, I really love what you did with pigs rolling in mud. May I ask how you made the mud gradually disappear with time?
Also, sorry for spamming your Issues :P

**Comment by capnkirok** [comment]
Interesting suggestion! We'd need a new dog breed for this... but possible.

How I did the fade:
The mud is a layer that appears when a pig is on top of a mud block. I then flag the pig as 'muddy'. Then a timer is started when the pig is no longer on the block. And I gradually change the Alpha value of the mud layer based on the timer. And when the timer expires, I remove the layer. Requires lots of coordination between NBT data, entity counters, and rendering.

**Comment by Guinaro** [comment]
I adding dogs, please provide compatibility for the mods: Sophisticated Wolves and : Wolf Armour and Storage.
Thanks,
Guinaro
