### ISSUE TITLE
[1.11.2 - 1.0.4.6] Cheese Omelette no different from Omelette?

### ISSUE THREAD

**Issue by VallenFrostweaver** [capnkirok/animania#110]
Basing my guess on the results of the super omelette, the cheese omelette should give resistance. Currently it gives the same hunger/saturation as an omelette and no bonus effects. If this is intended behavior please let me know and I will close the issue.

**Comment by Tschipp** [comment]
It is probably intended but your reasoning seems to make sense.

**Comment by capnkirok** [comment]
Cheese Omelette restores health instantly. Try it out :)

Clearly, I need to add tooltips #53
