### ISSUE TITLE
Pigs instantly get clean when entering Water

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animania#113]
When muddy pigs enter water, they automatically get clean again, because they just took a nice bath! Yay! Purely cosmetic of course, low priority.

**Comment by capnkirok** [comment]
You know what's strange... the code is in there to do this... but it doesn't work and I never bothered to fix it. So it's actually a bug!

**Comment by capnkirok** [comment]
Ok, fixed!

It was checking for a water block, which didn't seem to be working properly... so i just changed it to if the entity is wet then it clears up right away.

😃
