### ISSUE TITLE
These bulls hold a grudge longer than my ex girlfriends.

### ISSUE THREAD

**Issue by calloatti** [capnkirok/animania#114]
I mean, guys, I just wanted to kill that creeper, sorry I hit you. Can we let it go already? What do I have to do to make it stop?

Also, all of you team up on me? I just hit you, not any of your pals over there.

animania-1.10.2-1.0.4.7
Minecraft 1.10.2

**Comment by Tschipp** [comment]
Life is tough, so are bulls. Disabling the 'modesty flag' in the config will make them less agressive. (not really tho :P)

**Comment by capnkirok** [comment]
Ha ha ha. Yeah, don't hit the bulls. 

If you sprint away from them, and get out of their range, they will ignore you... or you can logout and log back in.

But... I don't think I'll change this....

**Comment by capnkirok** [comment]
Or you can use a Cloud Pet and turn them into steaks. I do all my testing with Inventory Pets installed 💯

**Comment by capnkirok** [comment]
But... Teaming up... yeah.. that needs to be fixed. That is not the way bulls work.

**Comment by Tschipp** [comment]
@capnkirok I always thought that was intended... Either way I think it fits, I was about to suggest that the bulls also become angry when you hit a cow or a calf. Call it a feature, not a bug! :D

**Comment by capnkirok** [comment]
Yeah.... not a bug. Let's leave it here and put that protective thing in.

**Comment by Jomik** [comment]
The range on the bulls are crazy though. I get hit through fences, when I'm at least 2 blocks away from the fence. (Counting the half block of the fence.)

**Comment by capnkirok** [comment]
Yeah, and they are armor piercing. Because, you know, horns.

**Comment by capnkirok** [comment]
Ok, if you get far enough away they will reset their aggro. Will be in next release.

**Comment by capnkirok** [comment]
Oh and left the group attack on.

**Comment by Jomik** [comment]
@capnkirok For pigs too?
