### ISSUE TITLE
How about you cows get a little out of the way so I can fill your troughs with tasty wheat?

### ISSUE THREAD

**Issue by calloatti** [capnkirok/animania#115]
![image](https://cloud.githubusercontent.com/assets/12817862/25313741/438644d0-280b-11e7-9563-b0928e6283ab.png)

animania-1.10.2-1.0.4.7
Minecraft 1.10.2

**Comment by capnkirok** [comment]
Ha ha ha. They just love you too much.

Well, hopefully, this will be fixed with some automation. By the way, did you know you could throw your wheat (Q) into the trough?

**Comment by capnkirok** [comment]
Closing... leaving to #65
