### ISSUE TITLE
Change the Meats to just Prime Meat vs. Vanilla Meat

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/animania#116]
To reduce clutter in inventory and simplify as we grow into more breeds. Requested by Razz.

**Comment by Guinaro** [comment]
Would it be possible to make this a configuration option? More choice is nice when playing with mods as harvestcraft, ... Recipes can be provided by modmakers with Minetweaker for further integration into a modpack.
Guinaro

**Comment by capnkirok** [comment]
Yes, @Guinaro , good idea.
