### ISSUE TITLE
Unable to add Friesian or Holstein milk to Refined Storage Fluid Grid.

### ISSUE THREAD

**Issue by calloatti** [capnkirok/animania#117]
Vanilla milk works. Animania milks cannot be added to Refined Storage Fluid Grid.

Minecraft: 1.10.2
animania-1.10.2-1.0.4.7
refinedstorage-1.2.25

Other mods fluids work in Refined Storage.

Vanilla milk:
![image](https://cloud.githubusercontent.com/assets/12817862/25317503/331612e8-2850-11e7-91ca-79a2cf48086c.png)

Animania milks:
![image](https://cloud.githubusercontent.com/assets/12817862/25317515/76761bf0-2850-11e7-8b59-31c1b6f8cfa5.png)

**Comment by calloatti** [comment]
Solved by converting Animania milk to vanilla milk in crafting grid.

**Comment by Tschipp** [comment]
Yeah, that's because they are not real liquids, just like slop. I suggest that gets changed in the future to improve compat.

**Comment by capnkirok** [comment]
You would suggest that @Tschipp :)

**Comment by capnkirok** [comment]
Hey this is in the next release :)
