### ISSUE TITLE
Calf Hitboxes are totally messed up

### ISSUE THREAD

**Issue by calloatti** [capnkirok/animania#118]
Minecraft 1.10.2
animania-1.10.2-1.0.4.7

![image](https://cloud.githubusercontent.com/assets/12817862/25320239/a7042b06-287b-11e7-8eb5-01fabc61df10.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25320242/af78d1e2-287b-11e7-88e0-9115ab4cbcc3.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25320245/b5427b8c-287b-11e7-97b1-f5d6ede0bcec.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25320248/bb5a0850-287b-11e7-9a1a-dfa7eff4528d.png)

**Comment by Tschipp** [comment]
That's because the hitboxes don't grow with the calfs. I suggest you make the hitbox dynamic @capnkirok

**Comment by capnkirok** [comment]
I've made them larger in 1.1.3, but they are still not dynamic (yet), so leaving open for now.

**Comment by capnkirok** [comment]
Ok, this is fixed in next release, thanks for patience!
