### ISSUE TITLE
Book of Fauna

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#121]
It would be nice to add a book of life/fauna with fixed pages that uncover when you discover. A book that tracks the different animals and species you've found and gets filled with information the more you find out about that animal. Think bits and bobs of info like favorite food, habitat, special drops.

This would promote exploration for the adventurers and tickle the completionists among us. Though it might be too much work to implement.

**Comment by Tschipp** [comment]
I like this idea, kind of like the lexica botania. I'm not sure how much work it would be though @capnkirok

**Comment by capnkirok** [comment]
@Deshiba this is great idea! It would add a nice new dimension to the mod. It's not a small piece of work, so it will take some time. And we need to get some new animals in first (horses, goats, falcons).

**Comment by darthvader45** [comment]
I'd be tickled pink if the goats were anything like the Mo' Creatures goats in behavior (generally eat anything, don't leave em too close to your drops when you die, that sort of thing).

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#113
