### ISSUE TITLE
Update: Solved my bull "situation": Bulls don't mind being burned alive.

### ISSUE THREAD

**Issue by calloatti** [capnkirok/animania#122]
Minecraft 1.10.2
animania-1.10.2-1.0.4.7
ImmersiveEngineering-0.10-57

Bulls don't react when being burned with an Immersive Engineering  Chemical Thrower:

![image](https://cloud.githubusercontent.com/assets/12817862/25363494/2ccd1b2a-2931-11e7-84f2-c1451532f6e9.png)

Yes, I feel sorry for those poor bulls (not really)

**Comment by Tschipp** [comment]
But why did you have to kill them in the first place...

**Comment by capnkirok** [comment]
Now I'm going to have to make them immune to fire... but only when you are playing.

**Comment by Tschipp** [comment]
How is this a bug? @capnkirok

**Comment by capnkirok** [comment]
Ah, the bull should get angry at the 'thrower' of the projectile.

**Comment by Tschipp** [comment]
This is an issue of Immersive Engineering, not Animania. Try talking to Immersive Engineering's Author.

**Comment by capnkirok** [comment]
I'm going to close this one, as we can't do anything about it animania. Your solution seems to be working 💯

**Comment by calloatti** [comment]
Thanks.

>Try talking to Immersive Engineering's Author.

I will pass on that one.
