### ISSUE TITLE
Suggestion: More fishes

### ISSUE THREAD

**Issue by vrork** [capnkirok/animania#123]
Hello! I like this mod a lot but i would like to ask, can you guys add Fishes to your mod? Like, the models on the water? The sea/rivers are boring. 

Yeah, i know there are other mods that do that, but they always change the way that fishes are caught too much, i would really love fish variations that you can a) hunt with a weapon b) fish with vanilla/thermal expansion fishing rods. 

Also, if you guys add it, try to add the same variations that are in the pam's harvest craft mod. 

Another thing, fish tanks/ponds for colecting and breeding

**Comment by capnkirok** [comment]
Well, fishes are planned, but Animania is focused mostly on animals that can be domesticated.... I like the idea of the fish tank for collecting and breeding though!

**Comment by vrork** [comment]
Well, fishes can be "domesticaded" (sort off, you can breed them) but if you plan to add more water animals, i would really suggest Dolphins too (it would be a cool way of water travel besides the boat too).

**Comment by Deshiba** [comment]
@vrork check out https://minecraft.curseforge.com/projects/just-a-few-fish in the mean time. It makes fish entities that are huntable with weapons. It does add its own fishing mechanic that replaces vanilla fishing rods but that can be changed in the config file.

It also has a fish tank for collecting, no breeding though.

**Comment by capnkirok** [comment]
I'm going to close this one... it's on our suggestion list, and I want to tidy up the git so it's for bugs only.
