### ISSUE TITLE
Yorkshire vs Large White

### ISSUE THREAD

**Issue by abloodyfetus** [capnkirok/animania#124]
I just thought I might mention that Yorkshire pigs and Large White pigs are one in the same.
I don't know why it bothered me enough to write this...

-"You can't wake up dead. Man, that shits redundant."

**Comment by capnkirok** [comment]
Welll... there is debate here. American Yorkshire is what I was thinking... which is directly related to Large White. 

They are listed as different breeds here:
http://www.thepigsite.com/focus/advertiser/3661/the-different-breeds-of-swine-large-white-large-white-pig-breed-large-white-gilts-sows-and-boars

http://www.thepigsite.com/focus/advertiser/3675/the-different-breeds-of-swine-american-yorkshire-american-yorkshire-pig-breed-american-yorkshire-gilts-sows-and-boars

I could rename it the American Yorkshire.

**Comment by capnkirok** [comment]
Ok renamed the Yorkshire -> American Yorkshire
