### ISSUE TITLE
holstein and freisian

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#125]
Suggestions
-Love this mod so much it makes Minecraft more like what I am used to being on a farm and all.
Someone watching my screen happed to say that these two breeds of cattle (Holstein and Friesian ) are the same ,it did not really bother me tho .There are lots of cow breeds I know being from where I am if u ever needed help with them I know most /some of them .
-When feeding hay we also you hay bales which is just a larger quantity of feeding I'm not for sure how this could be in it but 
- an automatic waterer is very much useful I also see then in my in life cows just saying that it would be easier if someone did not want to put open water for them to use
-this is normally just done when trying to really get the cattle fit or any animal by that but have you thought of maybe feeds for the animals in a way where it helps them grow at a more faster rate.
-yea also sorry if I really am talking I live on a farm so this mod is really interesting making minecraft so much more like real life to me **thx for making the mod**

If you ever had question I can help if you don't know any body else that knows them I like see most these animals everyday.

**Comment by capnkirok** [comment]
Thank you for the input! Some good stuff in here. Can you elaborate on what you mean by automatic waterer?

**Comment by capnkirok** [comment]
Oh, and Holsteins and Friesians are listed as different breeds here, though they are definitely related.

Holstein
http://www.thecattlesite.com/breeds/dairy/22/holstein/

Friesian
http://www.thecattlesite.com/breeds/dairy/24/friesian/

I might add a new dairy variant, the Jersey, which is more distinct in color:
http://www.thecattlesite.com/breeds/dairy/23/jersey/

**Comment by 19nrussell** [comment]
-ya I see that the breeds are like that know don't know much about dairy and from only really know popular breeds, but these breeds you have put in is definitely better than the just Minecraft cow
-The automatic water is basically an infinite water source where the animals cannot get in water just be able to drink it , this is also basically the same as a water fountain just for animals to use tho.

**Comment by capnkirok** [comment]
Thanks for the explanation!

**Comment by capnkirok** [comment]
I'm going to close this, as I've added it to the automation enhancement #65
