### ISSUE TITLE
Food effects

### ISSUE THREAD

**Issue by 3DJudi** [capnkirok/animania#126]
Config option for "Foods give bonus effects"=false does seem to remove effects but tooltips remain uneffected which is a little confusing to new users who eat but do not receive the expected effect.

**Comment by capnkirok** [comment]
Yep, good one. Will fix at next release.

**Comment by capnkirok** [comment]
Fixed in dev, and will be published at next release.

**Comment by Tschipp** [comment]
It somewhat works but it also removes the "Edible Anytime" lore, which I think is not nice

**Comment by capnkirok** [comment]
Ok fixed :)
