### ISSUE TITLE
Proper Names for Entities

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animania#128]
When trying to summon Animania Entities and using tab autocompletion you can see that the names for the entities are actually their texture path. This was probably done by accident when registering the entity. Instead of the texture location, provide something like "animania:cow_holstein".

 When I think about it: This could possibly cause all existing entities in the world to be removed, which is not good. You would have to test that first.

**Comment by capnkirok** [comment]
Yes, I'm pretty sure all existing entities would be removed if I did this. That would not be good. 

Will check back after testing.

**Comment by Tschipp** [comment]
I've tested it, it sadly does delete all existing entities. Oh well, I guess we won't fix this.

**Comment by capnkirok** [comment]
We can fix it when we update to 1.12 :)

**Comment by Tschipp** [comment]
Yeah. That's probably not even too far off
