### ISSUE TITLE
Animals can't eat if mobGriefing is set to false.

### ISSUE THREAD

**Issue by crakiMDH** [capnkirok/animania#129]
The title says it all.

I saw a Friesian calf trying to eat a grass block to no avail.

I eventually set block breaking to true and boom. It got its grass block.

Animals should be able to eat/break grass blocks if mobGriefing is set to false, since many players do this to prevent Creeper damage. This is more or less a problem in servers since no one likes Creepers.

**Comment by capnkirok** [comment]
I think it's set so the block doesn't turn to dirt... but the calf still gets credit for eating... I'll double check.

**Comment by crakiMDH** [comment]
Great. Thanks.

**Comment by capnkirok** [comment]
Ok, just verified that the cows get credit for eating even though the grass doesn't 'break'. Even so, I've changed the code to allow grass to turn to dirt even with mobGriefing false.

Will be in the next release.
