### ISSUE TITLE
Can't chickens eat anything other than seeds?

### ISSUE THREAD

**Issue by epicslayer999** [capnkirok/animania#130]
Chickens can't eat anything that isn't seeds placed on the ground/hand fed.

Unless this is intended, chickens should be able to get _something_ out of all that pecking.

**Comment by capnkirok** [comment]
Right now, only seeds. We do plan on adding corn. Leaving this in here, but referring to #8

**Comment by capnkirok** [comment]
I think also seeds should go into troughs.... hmm...

**Comment by capnkirok** [comment]
Just a heads up that Chickens will also be able to eat Frogs. Not that this is closed, but hey, one more thing.

**Comment by RaliaTheWolf** [comment]
I'm just going to pop in here for a second with a suggestion: Bread crumbs. Maybe put bread in a crafting table and get like 5 or so bread crumbs? They could just be recolored seeds and they could function the same way as seeds. Just put them on the ground and the chickens could eat them. Just for some diversity.
