### ISSUE TITLE
Strange Tinkers behavior using piggybackpack

### ISSUE THREAD

**Issue by 3DJudi** [capnkirok/animania#131]
Cows and Pigs seem to be OK though I only put them through a minimal test.
Ferret works but is clipped through the players head.
Chicken works but over time he rolls his head completely around 360 degrees (see pic @ 180 degrees).
Does not seem to work on hamsters (cry!) but not really sure why...

I can post this to Tinkers if needed... just let me know

![image](https://cloud.githubusercontent.com/assets/27922652/25492655/5b5953aa-2b39-11e7-815e-f4ff3f8d16a6.png)

**Comment by capnkirok** [comment]
I don't even know what this feature is, it looks hilarious. Let me check it out.

**Comment by calloatti** [comment]
For the record, as it may be related regarding hamsters:

The [EnderIO Soul Vial](http://wiki.enderio.com/Soul_Vial) works with all animals but not with hamsters also.

Have not tested on ferrets since I did not find any.

Minecraft 1.10.2
Forge Mod Loader version 12.18.3.2281
animania-1.10.2-1.0.4.7
EnderIO-1.10.2-3.1.184
EnderCore-1.10.2-0.4.1.65-beta

**Comment by Tschipp** [comment]
I don't know exactly how the Soul Vial works, but my guess is it's checking if the entity that is clicked extends EntityLiving. Is it possible that the Hamsters don't extend EntityLiving? @capnkirok

**Comment by capnkirok** [comment]
Yeah, I took 'most' of the Entity code from the original Hamsterrific for the Hamster Entity and updated it for 1.10/1.11, so it's missing a few things.. will look into it.

The ferret should work with the Soul Vial, as it's essentially the same as the hedgehog

**Comment by Tschipp** [comment]
Can confirm, the hamsters cannot be picked up with any of those items. I will check why that is the case.

**Comment by capnkirok** [comment]
Ok, took a look. This has to do with the custom Process Interact that was done by the original modder from Hamsterrific. I'll have to re-write the whole section. 

Basically, anything that does a right-click interaction with the Hamster is going to break.

**Comment by calloatti** [comment]
While you are at it, remember we do **need** those Hamster Powered RF Generators...

**Comment by Tschipp** [comment]
> This has to do with the custom Process Interact that was done by the original modder from Hamsterrific. I'll have to re-write the whole section.

Try adding this at the end @capnkirok :
```
else {
            return super.processInteract(player, hand, stack);
        }
```

**Comment by capnkirok** [comment]
Yep, right on! Did that last night :)

**Comment by Tschipp** [comment]
Did it work? @capnkirok

**Comment by capnkirok** [comment]
Partially. The problem with the code was in one of the nested if statements.
