### ISSUE TITLE
[1.11.2 - 1.0.4.7] Hedgehogs/Ferrets not eating eggs from nests?

### ISSUE THREAD

**Issue by VallenFrostweaver** [capnkirok/animania#132]
A while back I saw a tweet where Hedgehogs & Ferrets would eat eggs from a chicken nest (not just if fed) but they do not display this behavior currently. Is this as intended or is something not working as it should?

**Comment by VallenFrostweaver** [comment]
EDIT: Never mind. It just takes a long long time.

**Comment by capnkirok** [comment]
Yeah, they only eat when they are hungry... so it's based on the eat timer :)
