### ISSUE TITLE
(SUGGESTION)gestation ticks

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#134]
-Maybe how the time that they have a baby can be different between species (cows,pigs ) this will be more when there is more animals .
-also a way to be able to tell if they will have a baby so if they are bred.
-so basically a way to keep up age  bred just normal stats we keep on animals

Love the mod so far I was just saying this as a suggestion since irl they have different times(tho if they do change does not really have to change to be near irl times tho)

-this Mod is so awesome -

**Comment by capnkirok** [comment]
Gestation ticks are in now. I may add support for different times later, but keeping it like this for now.
