### ISSUE TITLE
hereford  bull

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#135]
he has a pink spot on a different place then the female.Is the just making sure if it is soppused to be like this

**Comment by Tschipp** [comment]
If you mean the belly then that is probably intended

**Comment by 19nrussell** [comment]
no well where they go is  misplaced well almost on his side

**Comment by Tschipp** [comment]
Ah, that one. Well there's almost no way that this isn't intended

**Comment by Tschipp** [comment]
I just looked at it, you're right, it does look kind of weird. Is this intended @capnkirok?

**Comment by capnkirok** [comment]
Good eye @19nrussell ! Yes, this looks like a bug from when we fixed the butts a month ago 😂

**Comment by capnkirok** [comment]
Ok, Razz fixed it. Thanks guys!

**Comment by Tschipp** [comment]
Can confirm, the butt is at the correct place now xD

**Comment by calloatti** [comment]
Sorry, but I can´t resist adding my 2c: 

"Misplaced as..ole bug" has to be the most hilarious bug I have ever heard about.

**Comment by 19nrussell** [comment]
ok this needs to be opened its yet again in the wrong place I believe

**Comment by 19nrussell** [comment]
sorry pic is bad it would not stay still for me its a pic spot like before except its a the end of its tail area
lol

**Comment by Tschipp** [comment]
you are right

**Comment by capnkirok** [comment]
Yeah, forgot to fix this on the 1.11.2 version. Fixed in next release.
