### ISSUE TITLE
[suggestion]Oredict improvements

### ISSUE THREAD

**Issue by thephoenixlodge** [capnkirok/animania#136]
Tags to add to items:
- "foodMeat" to all the meats (cooked and raw). This is used in recipes by some other mods, so is an easy compat improvement
- "listAll<meat><cooked/raw>" to vanilla meats. You have these on your meats but not on vanilla meats, which seems a bit strange, considering the listAll part of it.
- "feather" to both types of peacock feathers

Changes to recipes for your items:
- Nest recipe: leaves ("treeLeaves") (currently accepts only oak leaves), wool (currently only accepts white)
- Trough recipe: planks ("plankWood") (currently only accepts the vanilla plank id with wildcard meta, so no modded planks work)

**Comment by capnkirok** [comment]
Cheers! These are my favorite to implement because they take < 1 minute 😃
