### ISSUE TITLE
Seeds breaking non-vanilla farmland

### ISSUE THREAD

**Issue by Zygus42** [capnkirok/animania#137]
Right-clicking or shift-right-clicking seeds on a farmland block which is on non-vanilla dirt places the seed down for feeding chickens, instead of planting it.  We're experiencing this with BiomesOPlenty dirts, but probably has the same issues on other special farmland blocks.

**Comment by capnkirok** [comment]
There are already exceptions for Forestry, Agricraft, and vanilla farmland (among others). Will take a look at BOP.

**Comment by capnkirok** [comment]
Ok added to next release, thanks @Zygus42

**Comment by Zygus42** [comment]
just a thought here, but each of those farmlands must have a tag of canbeplanted or some suchsuch, could you look for that rather than hardcoding by mod ?

**Comment by capnkirok** [comment]
IPlantable... doesn't always work (not all of the issues are with 'soils'), but might eliminate some

**Comment by capnkirok** [comment]
Ok, I've added additional check to make sure its not an instance of BlockFarmland... that seemed to do the trick for most blocks... thanks for the practical suggestion @Zygus42
