### ISSUE TITLE
Compatibility with Overlord mod

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/animania#138]
Milk buckets, milking cows...

From TheFireplace:

Is there a convenient way for me to add support for Animania's Milk and Cows to one of my mods? According to a user(I have yet to test this myself), Animania's milk buckets don't work in my Skeleton Makers, and the interaction that would happen with vanilla cows to allow obtaining Milk Bottles also can't be done with Animania cows.

Source is here: http://maven.brainstonemod.com/

**Comment by The-Fireplace** [comment]
Another user let me know today that this is still an issue, so I figured I'd come on here and speed up the resolution.

To resolve this, you'll want to add this(I would do it during FMLInitializationEvent, but anytime after Item Registration works):
`MilkRegistry.getInstance().registerMilk(new ItemStack(ANIMANIA_MILK_BUCKET), new ItemStack(Items.BUCKET));`
That resolves the issue with the skeleton makers. For the milk bottle interaction, you'll need to do something like this:
https://gist.github.com/The-Fireplace/c852730428cc192788c1828eb42e53de
Lastly, to do all of this without making Overlord a dependency, I suggest setting these up through an interface. For examples of this, see how [Overlord interacts with IC2](https://github.com/The-Fireplace/Overlord/blob/master/src/main/java/the_fireplace/overlord/Overlord.java#L222).

**Comment by capnkirok** [comment]
Hey @The-Fireplace this should all be working in 1.11 and 1.12, but we are debating how much work we want to put into 1.10. As of now, I am closing this. Thanks!
