### ISSUE TITLE
Enhancement: Configuration animals eating certain plants

### ISSUE THREAD

**Issue by Guinaro** [capnkirok/animania#139]
If at all possible, maybe allow some configuration options to allow grazing from certain plants? Like Pigs would eat Pam's Harvestcraft Corn, Chickens would love to pick Lettuce, ... . All configurable by the modpack maker.
Configs could be for placing certain items in throughs, possibly combining this with a food value to allow different foods been more or less efficient. (Could drive it as far as Hungeroverhaul-SpiceofLife mechanics, where each animal has a certain food history, but I think it would be overkill, but hey if you've got the time feel free to give us even more options, ...)
Another config option would be allow natural grazing where you can plant certain crops (Agricraft, harvestcraft, ... ) and the animals would automatically eat from them. This could also effect wild animals. Thus maybe providing a mechanism to need a vegetable farmer to protect his crops, otherwise wild boars come ravage your vegetable garden!

Guinaro

**Comment by Tschipp** [comment]
In the next release, you can configure which foods can go into the troughs and which foods the animals can eat.

**Comment by capnkirok** [comment]
This was added to 1.11 and 1.12.
