### ISSUE TITLE
Milking cows takes stacks of buckets.

### ISSUE THREAD

**Issue by JamRobLam** [capnkirok/animania#141]
Playing on the Modded Mischief II mod-pack that has Animania version 1.0.4.7 when holding ~at least~ _exactly_ two buckets and right clicking to milk a cow (Friesian) it takes both buckets and gives me one Animania milk bucket. Tested it twice but was not able to try on another cow.

**Comment by Tschipp** [comment]
Weird, I thought that was fixed ages ago... investigating

**Comment by Tschipp** [comment]
Not able to recreate... The pack is for 1.11.2, right? Can you try and record the issue?

**Comment by JamRobLam** [comment]
Correct, I'll try and get a clip for you shortly.

**Comment by JamRobLam** [comment]
https://drive.google.com/open?id=0B_GugIbytyFYeUMxUWVtVTI2bXc 
is a link to my google drive you can download the video if you need to from there.

**Comment by JamRobLam** [comment]
or if need be i can get it to you another way

**Comment by Tschipp** [comment]
weird... I'm downloading the pack and testing it

**Comment by Tschipp** [comment]
Still not able to reacreate it... can I have your world download?

**Comment by JamRobLam** [comment]
https://drive.google.com/open?id=0B_GugIbytyFYLVhZMXlHa2NTdkk
here is a copy of my entire instance of the mod pack in a zip

**Comment by Tschipp** [comment]
figured it out, it works with exactly 2 buckets

**Comment by JamRobLam** [comment]
Glad i could help.

**Comment by capnkirok** [comment]
Ooohh interesting. 

When using stacks of buckets to milk a cow, use more than 2. Problem solved!

😺

**Comment by capnkirok** [comment]
![image](https://cloud.githubusercontent.com/assets/9628379/25634698/db87cf70-2f7b-11e7-90c5-8f9cbfd38955.png)

Do you see the error? Logic is hard some times. 😵

**Comment by JamRobLam** [comment]
im glad i could help point out a small problem thank you for what you do if i can help any more let me know.

**Comment by Tschipp** [comment]
@capnkirok I just looked at the code for like 3 minutes, still don't see the error. clearly I'm blind xD

**Comment by capnkirok** [comment]
@Tschipp I shrink the stack and then I check to see if the player is holding only 1, which means this code only executes if the user has 2 buckets. Oops. The getCount() should check for 0... or I should shrink the stack after the check...

**Comment by Tschipp** [comment]
Oh yeah lol I thought to myself "why is he shrinking the stack right away" but then forgot about it xD I need more sleep

**Comment by capnkirok** [comment]
I probably wrote this one when I needed sleep :)
