### ISSUE TITLE
Can only find females

### ISSUE THREAD

**Issue by skruis** [capnkirok/animania#143]
So, I've got this issue where I've been exploring for a while now and I can only seem to find females of any species (Cows, Pigs, Chickens). I'm using the Open Terrain Generator/Biome Bundle and I pregenerated some terrain and within that pregenerated section, I was able to find male bulls and pigs but outside of that area: only females. At this point, I'm only suspecting that it has to do with the world pregeneration but I wanted to ask you: is there anything that might cause only females to spawn or are there any logs I could provide that might help indicate what the problem is?

Custom Pack
SMP 1.10.2
Forge 12.18.3.2281
Animania 1.0.4.7

**Comment by capnkirok** [comment]
Well, only the females spawn in world gen. The males and children spawn from the female when it is spawned (I know, complicated).

Is there a mod in your pack that prevents spawning of additional animals? AND... have you tried increasing the spawn rates and limits in the config just to make sure it's not just coincidence?

**Comment by skruis** [comment]
I have not yet played with the config but I will take a look and I'll review the other mods in the pack that might have interfered. It just struck me as odd that there were males around spawn but not further away. I'll continue to see if I can isolate this and get back to you.

**Comment by capnkirok** [comment]
Sounds like it could be worldgen.... anything else besides OTG in there?

**Comment by skruis** [comment]
I can provide a list of all the mods in the pack: https://minecraft.curseforge.com/projects/busventure-1-10/relations/dependencies

Off the top of my head, I'm wondering if it's Hunger Overhaul. That seems to be the only mod that 'might' impact mob behavior?

**Comment by Tschipp** [comment]
Try it in a superflat world

**Comment by capnkirok** [comment]
@skruis as @Tschipp suggests, let us know if this still happens in a superflat world... if so, then it's probably a conflict with one of your mods (prolly OTG). Let us know :)

**Comment by Galindorf** [comment]
I had to travel a significant distance to find a male pig when I first added the mod to my already existing world. It took days of in-game travel! I still only have 2 male pigs for all my gathering.

**Comment by capnkirok** [comment]
Animals only appear in newly generated chunks... or if they are replacements of vanilla. You can always increase the frequency in the config (spawn limits, number of families, spawn probability). See if that helps.
