### ISSUE TITLE
[suggestion] Breeding behavior

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#146]
It would be nice to have realistic breeding behavior that conforms to real life. A few examples below to explain what I mean:
- Cows only giving milk when they have a calf
- Chickens laying eggs till the clutch is full and brooding until chicks hatch (unless the clutch is removed). 
- Chickens not laying eggs till their chicks are chickens themselves.

**Comment by capnkirok** [comment]
Ooooh. These are good suggestions, and a nice challenge to implement.

**Comment by Deshiba** [comment]
I don't know enough about other animals and breeding behaviors to give examples for them, there could be more but I'll leave that up to you guys ;)

**Comment by 19nrussell** [comment]
Cows mostly dairy cows(beef normally don't produce as much milk) are used for milk they will have a calf the calf gets nutrients from mom then after that calves are normally bottle raised while mom can be milked up to about a couple months before she is ready to have her next calf ( cows gestation is 9 months and normally come back in heat a 2-4 months after 
calf Is born

**Comment by RaliaTheWolf** [comment]
While we're talking about this kind of stuff, I thought I might add that pigs have HUGE litters, like 8-12 piglets at a time! I don't know how hard something like that would be to implement, or if it'd make it too easy to get food and whatnot, but I think it'd be good for realism! If anything, at least 2-4 piglets would be nice.

**Comment by crakiMDH** [comment]
Except for the cow thing of them producing milk whenever they have a child, I like these suggestions. The gestation producing milk cow idea wouldn't work all that well, because milk would become much more scarce once players no longer require cows to breed.

**Comment by 19nrussell** [comment]
One cows always have to bred to have milk I was just saying that that's what they do irl they have a dry when they don't milk so that they can get ready for there next calf I just said that was what people did irl in case they wanted to Ben that way in the mod really to be realistic u would not have to do that this I talked about is just when heavily milking the cows

**Comment by Deshiba** [comment]
@crakiMDH cows would not produce milk unless they have a calf. This would require you to breed them before getting milk. In order to breed them or to get milk you have to make them happy in the first place. In the end it's just an extra box to tick in the chain of requirements.

Functionally it would give a time frame where cows can actively be milked triggered by the player, instead of just making the cow happy and having milk for days. This does indeed make milk a tiny bit harder to get, but if the incentive for the produce is high enough its not that much of a hassle.

**Comment by capnkirok** [comment]
This last suggestion re: cows and other animals that give milk will be in the 1.3 release. Cows must breed first to give milk. Also, there is a brief period after giving birth before animals can breed again.

**Comment by capnkirok** [comment]
@Deshiba check out the 1.3 release. Would recommend you use 1.11 or 1.12 (when it's out) as well as TOP or WAILA.

**Comment by Deshiba** [comment]
@capnkirok That's awesome! Keep up the great work.

**Comment by LunariusH** [comment]
Loving all that you're doing mate!  This mod will definitely become a foundational piece of my modpacks.

**Comment by capnkirok** [comment]
Hey guys, going to close this one. Don't think I'll change the chickens due to the complexity. But other changes are in all versions now. Thanks again!
