### ISSUE TITLE
Getting information about animals

### ISSUE THREAD

**Issue by RiverC** [capnkirok/animania#147]
I've had a great deal of difficulty getting cows to breed, which I suspect is because there are relationships between cows (pre-existing) that I'm not aware of. So here's a question.

1. Is there a way to determine, for the pairing animals (currently, pigs, cows) which animals have a committed relationship? 
2. Is there a way to determine happiness level other than the obvious (the particles / effects on unhappy animals.) If there are not multiple relative levels of happiness, I suppose this isn't that important, but it seems to be that there are.

**Comment by capnkirok** [comment]
Not without an NBT Sniffer. We do plan on making something... I'm wondering if we can leverage something like WAILA... (they have an API)

**Comment by calloatti** [comment]
I vote for [The One Probe](https://github.com/McJty/TheOneProbe) integration! McJty is a cool guy and very accesible.

(If voting does anything)

**Comment by capnkirok** [comment]
No reason we couldn't do both

**Comment by RiverC** [comment]
May I suggest (for the first) an occasional particle (like a heart or something) that is small and travels from each pairing animal to its mate? Perhaps it could happen at some triggering event instead of automatically... perhaps some item (like the lead) might do. 

Just a little help as collecting, feeding and watering this many cows just to try to get some mating is quite burdensome 😀  What usually triggers the pairing?

As for the happiness thing, could be similar. They just produce a certain number of hearts when you wave the lead over them. Anyway, trying to think of lightweight ways.

**Comment by capnkirok** [comment]
Nice suggestions. Particles are unfortunately, not lightweight. But they are easy to read for the player. 

What triggers the pairing: well, they have to be nearby (as in < 5 blocks) an unmated animal of the opposite sex. Cross breeding is OK.

**Comment by 19nrussell** [comment]
ya I also have a hard time telling the pairing  and happiness one minute they had a calf the next day some have another calf while others don't . So ya  also hard to know if there are bred going to calf . 
-this is an awesome mod-

**Comment by Tschipp** [comment]
@19nrussell The cows and sows only give birth if the father is near.

**Comment by Galindorf** [comment]
I was also wondering about this... I don't know which animals I I can cull, because I don't know which animals are in a relationship. Also, if I cull an animal in a relationship, will the partner choose again? The breeding is already going so slowly! (except for the chickens, man, those things can really get going!)

**Comment by Tschipp** [comment]
Waila support is coming in the next release!
