### ISSUE TITLE
Duplication Raw Bacon (Duroc, Old Spot, Hampshire) recipes bug

### ISSUE THREAD

**Issue by tntblockman** [capnkirok/animania#15]
Minecraft: 1.10.2
Animania: 0.9.8 BETA
Forge: 12.18.3.2221

BUG
When Crafting pork with Carving Knife into bacon; Duroc, Old Spot, Hampshire "Raw Bacon",  are crafted using "Raw **Bacon**(Duroc, Old Spot, Hampshire)" + Carving Knife = Raw Bacon(Duroc, Old Spot, Hampshire) x4.

FIX
Think the recipes should be "Raw **Pork**(Duroc, Old Spot, Hampshire)" + Carving Knife = Raw Bacon(Duroc, Old Spot, Hampshire) x4.

Recipe for "Raw Pork (Large Black)" + Carving Knife = Raw Bacon (Large Black), works perfect.

Example of recipe error (Duroc, Old Spot, Hampshire):
![2017-02-21_17 42 55](https://cloud.githubusercontent.com/assets/2690994/23177201/e0e2bc8c-f85d-11e6-9cc2-1adad4689cb2.png)

Example of intended recipes (Duroc, Old Spot, Hampshire):
![2017-02-21_17 58 32](https://cloud.githubusercontent.com/assets/2690994/23177651/78d93ba0-f85f-11e6-9fe8-bc3e915855e1.png)

**Comment by capnkirok** [comment]
Yes, already noted and fixed in dev. Thanks!
