### ISSUE TITLE
Placed seeds are not destroyed if Mob Griefing is set to false

### ISSUE THREAD

**Issue by Starza4TW** [capnkirok/animania#151]
If seeds are placed on the ground while the game rule mobGriefing is set to false, the seed block will not be destroyed after chickens eat from the block. This gives chickens an infinite amount of food once a seed block is placed.

Tested with Animania 1.0.4.7 & MC 1.10.2

This issue seems familiar to #129

**Comment by capnkirok** [comment]
Yup. No reason to check for mobGriefing here. Fixed in next release.

**Comment by capnkirok** [comment]
Applied to all AI where this occurred, on both 1.10 and 1.11.2
