### ISSUE TITLE
Troughs sometimes disappear/get destroyed after cows drink water from them. 

### ISSUE THREAD

**Issue by lorennne** [capnkirok/animania#152]
There have been a few instances where troughs get destroyed after a cow drinks water from them, version is 1.11.2, latest update.

**Comment by lorennne** [comment]
Also, in case it's relevant, other mods being used are Pam's Harvestcraft, Just Enough Items, and Fairy Lights Mod by pau101.

**Comment by Tschipp** [comment]
It might be Pam's Harvestcraft. Pam's has had issues with tile entities from other mods, resetting them to their default state. Try to not place Pam's harvestcraft TileEntities and Animania TileEntities in the same chunk

**Comment by darthvader45** [comment]
Pam actually is working to fix this due to a similar thing with Decocraft.
