### ISSUE TITLE
Are name tags not working?

### ISSUE THREAD

**Issue by Phixaen** [capnkirok/animania#153]
Using animania-1.10.2-1.0.4.7 made nametags for my cows and pigs but can't use it to name any.

**Comment by capnkirok** [comment]
Hmm... not having any problems, and not reported elsewhere...

Just out of curiosity... can you tell me which pig breed/genders?

**Comment by Phixaen** [comment]
I couldn't find it after searching a bit either, it's Friesian, Hereford and White and Old Spot.  It's likely one of the other mods on my server if no one else has reported it, I just can't play without animania anymore so it goes with EVERYTHING we do now!   Sorry for wasting your time.

**Comment by capnkirok** [comment]
I just double checked theese breeds and name tags and didn't have a problem. Also, there's nothing in my code for these animals re: name tags. It's just vanilla Minecraft. Could be a hitbox issue? 

Anyway closing this one. Let me know if you run into any more issues.
