### ISSUE TITLE
[Suggestion]: Other animal types

### ISSUE THREAD

**Issue by F0RMATTED** [capnkirok/animania#157]
This was most likely already said somewhere but do you plan on adding different types of animals?
Thinking about atleast Sheep, maybe Goats and Horses?
Im honestly only opening this because it feels weird that theres all these cool different animals everywhere replacing the vanilla ones but sheep stay the same.

**Comment by Tschipp** [comment]
#31, #44, this has been suggested several times, and has been planned from the start. The upcoming features can be viewed on the forum page: 
Upcoming Features:
Draft horses
Ponies
Falconry
Sheep
Goats
Cats
Rabbits
Foxes
Chinchillas
Other Birds
Reptiles
Working dogs
Improved breeding (simple genetics)
Salt licks
Hedgehogs (Now in 1.0.2)

Horses are coming in the next update, which is coming pretty soon
