### ISSUE TITLE
Error: The target entity [ ] is not the owner of the goal

### ISSUE THREAD

**Issue by Heartfyre** [capnkirok/animania#158]
Hey gentleman,

first let me thank you for the amazing mod you are working on. I and we realy love it! We are using your mod on a modded forge/sponge server for version 1.10.2. 

I noticed that the mod or maybe something else together with the mod is causing a lot of error messages on the client console (not server!), when I focus an animal with the crosshair. It spams the error every second (tick) and makes the game in that moment very laggy/choppy.

I did some testing and it seems to happen with all new animals, except pigs (all of them).

Please check out the error log, which can be found here: https://pastebin.com/7K8WV6ar

You can find a list of all of our installed mods via the following link. Sorry, that it is partly german, but it's just the headlines. :) https://docs.google.com/spreadsheets/d/1R2vExBDmw64JzhYFDGRg7mZySbGGAMwu5AFpEk6Hl4c/edit?usp=sharing - Please check out the tabs on the bottom as well for the sponge mods we are using.

If you need any more details or any testing, which I am willing to do, please don't hesitate to let me know!

Thanks for your help in advance!

**Comment by capnkirok** [comment]
Haven't seen this one before. Could be a Sponge thing... we will investigate and get back to you!

**Comment by capnkirok** [comment]
This should have been fixed when we updated 1.10 to use Base Classes... version 1.4.2
