### ISSUE TITLE
Chickens Making Static Noises

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#159]
I was walking past my chickens in a world of mine and I heard this awful static noise. I turned down my "Friendly Creatures" to a lower percent and that made it quieter, but I could still hear it. It wasn't constant, just every few seconds. I tested this with other animals and it was only the chickens that were making this noise. This hadn't happened before, so I wasn't sure why it was happening then. I restarted my Minecraft and that fixed it. Maybe it was just some weird one-time-only glitch, but I'll be sure to let you know if it happens again. I just thought you might like to know this! Thank you for your time! Sorry if I shouldn't have put this here since it has technically been fixed!
P.S. Wonderful mod! I'm super excited to see what you will add in the future!! ^^

**Comment by Tschipp** [comment]
Haven't noticed that, might be a one-time thing, but we'll definently keep an eye out.

**Comment by capnkirok** [comment]
Try downloading a new version of the mod from Curse and closing and restarting Minecraft. Sounds like a corrupted sound file.

**Comment by RaliaTheWolf** [comment]
Will do. Thanks for the help! I'll let you know if it happens again.
