### ISSUE TITLE
[Suggestion] Can you add animals too crowded to lead to suffocation and death?

### ISSUE THREAD

**Issue by le10077** [capnkirok/animania#160]
I think the animals need space to Breeding.

**Comment by Tschipp** [comment]
This is already a feature of 1.11 vanilla. It's called maxEntityCramming and it's default is 24, meaning if there are more than 24 entities in the space of 1 block, they take damage. http://minecraft-de.gamepedia.com/Befehl/gamerule

**Comment by capnkirok** [comment]
Let us know if that works.

**Comment by capnkirok** [comment]
Tested the above gamerule in 1.11 and it works. Closing this one now.
