### ISSUE TITLE
Haste Tooltip

### ISSUE THREAD

**Issue by mreel** [capnkirok/animania#161]
Roast Pork from the old spot has "haste" in the tooltip instead of absorbtion (like the other porks and the old spot bacon), when eaten, it does give you the absorbtion effect. Meaning it is just the tooltip that needs to be changed.

**Comment by Tschipp** [comment]
It's either already fixed or I can't recreate it

**Comment by capnkirok** [comment]
This was on 1.10 only. Will be fixed. Thanks @mreel !

**Comment by Tschipp** [comment]
Oh, ok

**Comment by mreel** [comment]
no problem, next time I'll try to remember to add version numbers and stuff, sorry!
