### ISSUE TITLE
Comparator Issue

### ISSUE THREAD

**Issue by mreel** [capnkirok/animania#162]
using a comparator on a trough only works when placed (with the back) pointing at the block you placed the trough:
![2017-05-23_18 36 03](https://cloud.githubusercontent.com/assets/7822975/26365091/da0b20ae-3fe6-11e7-87fc-63e07310da83.png)

(i placed the trough on the left side, the right was the 'added' part)

mc version 1.10.2
animania version 1.0.4.7

**Comment by Tschipp** [comment]
That is currently the way it works (only the block where you placed the trough has a TileEntity) A change is coming in the latest update, but comparator output is currently only supported for one block. I might add it if I find some spare time

**Comment by mreel** [comment]
yes i am automating this (works very well actually), will this kind of automation still work when hopper/pipe support is added?

**Comment by Tschipp** [comment]
Yes, the old behavior will stay

**Comment by Tschipp** [comment]
Added :)
