### ISSUE TITLE
Two suggestions for frog species

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#164]
1. [Indian Purple Frogs](https://en.wikipedia.org/wiki/Purple_frog)
2. [Budgett's Frogs](https://en.wikipedia.org/wiki/Lepidobatrachus_laevis). Just don't name then any of the following: _Beelzebufo_, Freddy Krueger, "It is Wednesday My Dudes", Dude

**Comment by Tschipp** [comment]
That's some beautiful frogs if I do say so myself

**Comment by capnkirok** [comment]
Love them :)

**Comment by darthvader45** [comment]
Or for a green frog, don't name it Pepe.  God knows that meme is dead.

**Comment by Sunconure11** [comment]
Uh, I think that may already be in.

**Comment by Tschipp** [comment]
.-.

**Comment by darthvader45** [comment]
Wow.  Okay then.  ._.

**Comment by capnkirok** [comment]
Hey @Sunconure11 I've added this to our offline suggestions list. As I mentioned on some others, going to close this one now in an effort so focus our git on bugs only.
