### ISSUE TITLE
Expensive AI tasks

### ISSUE THREAD

**Issue by sfPlayer1** [capnkirok/animania#165]
The animania AI tasks are in general way too expensive, around 25 ms/tick without overly excessive quantities. See http://files.player.to/tmp/animania.nps for VisualVM compatible profiling data.

**Comment by Tschipp** [comment]
I would rather not have to download a program to view a file. Can you send it differently

**Comment by sfPlayer1** [comment]
VisualVM is part of the JVM until recently, so you should already have it. The data in nps files is a complex tree representing the stack frame distribution over an extended period of time, 128 kB compressed in this case, you are not going to view this in plaintext.

**Comment by sfPlayer1** [comment]
This already happens with very few entities, e.g. we have less than 30 cows loaded. Apparently the food/water tasks scan up to 7623 blocks each every second and then try to path to it. Considering there's hundreds/thousands of animals to be expected on a developed server, AI processing takes too long by multiple orders of magnitude.

**Comment by capnkirok** [comment]
The food / water tasks were put on a timer to reduce load. I haven't heard complaints about the performance since we optimized about a month ago, and FPS was reported fine by server admins who posted the original notice.

I used Nallar's tick profiler in our testing and found the results comparable with vanilla mobs.  I was certainly not seeing 25 ms/tick. 

Can probably reduce load further by increasing the delay timer as well as limit the search radius. 

Can you tell me which version of the mod and forge you are using? Also, can you post your full modlist?

**Comment by sfPlayer1** [comment]
We're on 1.0.4.7/latest, Forge 2296. The nps doesn't indicate any external influence.

You may want to increase the initial delay moderately, scan incrementally with saved progress and dynamically increase the delay up to a high limit after scanning or pathing failed, reset to initial after finding something. I assume it checks if there's actually demand first.

```
ActuallyAdditions-1.11.2-r108
ambidextrous-1.1
animania-1.11.2-1.0.4.7
Aroma1997Core-1.11.2-1.2.0.0.b87
Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.b33
Aroma1997s-Misc-1.11.2-0.0.0.0.b18
atg-1.11.2-2.1.7
AutoRegLib-1.1-4
Baubles-1.11-1.4.5
BedBugs-1.11.2-1.1.7
BiomesOPlenty-1.11.2-6.1.0.2227-universal
Botania r1.9-343
buildcraft-7.99.3
Chameleon-1.11.2-3.1.0
Chisel-MC1.11.2-0.0.10.14
chiselsandbits-13.10
combathelp-1.1x-1.1.1
compatlayer-1.11.2-0.2.9
Computronics-1.11.2-1.6.5.142-portabler-tape-drives
Decocraft-2.4.2_1.11.2
deepresonance-1.1x-1.4.8
denseores-1.11-1.0.2
DynamicSurroundings-1.11.2-3.4.5.0
ElecCore-1.11-1.7.420
embers-0.213
extrautils2-1.11.2-1.4.1
FastLeafDecay-v12
flatcoloredblocks-mc1.11-5.1
forestry_1.11.2-5.3.4.99
funky-locomotion-1.11.2-alpha-0.0.1
gearswap-1.1x-1.4.1
GPS-1.11-3.1.0.0.b20
Harvest-1.11-1.2.0-12
hcmw-1.11.2-0.3.1.2-universal
immcraft-1.1x-1.3.2
ImmersiveEngineering-0.11-59-104
immersivepetroleum-1.11.2-1.0.2
industrialcraft-2-2.7.47-ex111
infinityblock-1.0.5
intwheel-1.1x-1.2.6
ironchest-1.11.2-7.0.19.803
itemzoom1.11.2-1.5
IvToolkit-1.3.3
jei_1.11.2-4.3.6.280
journeymap-1.11.2-5.4.6
JustEnoughResources-1.11.2-0.6.4.6
Mantle-1.11.2-1.2.0.26
mcjtylib-1.1x-2.3.11
MCMultiPart-2.0.0
memorybar-1.11.2_1.0.6
middletorch-5.0.6
modnametooltip_1.11-1.7.1
Morpheus-1.11.2-3.2.14
nice-0.1.0
notenoughwands-1.1x-1.5.5
OpenComputers-MC1.11.2-1.7.0.24
Psi-r1.1-47
Quark-r1.2-92
rangedpumps-0.4
RecurrentComplex-1.3.1.1
refinedstorage-1.4.9
rflux-0.1.1
rftools-1.1x-6.02
rftoolsctrl-1.1x-1.6.8
rftoolsdim-1.1x-4.60
roots-2-0.017
sampler-1.70
shearmadness-1.11.2-1.7.0.6
StorageDrawers-1.11.2-4.2.7
Tatw-1.11.2-1.0.0.0.b5
TConstruct-1.11.2-2.7.0.19
theoneprobe-1.1x-1.4.7
Thump-1.11.2-4.6.1.5
Thumpcord-1.11.2-0.1.0.3
Thump-Service-Curse-1.11.2-0.0.3.3
TombManyGraves-1.11.2-3.0.8
travelhut-2.0.8
weirdinggadget-1.11.2-1.0.1-universal
xnet-1.3.2
```

**Comment by capnkirok** [comment]
Cheers.

**Comment by capnkirok** [comment]
Thanks for the suggestions. Big change I've made is if it's already on a path, it no longer checks again until it arrives. Will add a longer initial and repeated delay. Have an update coming out tomorrow or Sunday. Please check it again and see how it does.

**Comment by capnkirok** [comment]
Update: did more testing this morning, and it's a big improvement. A couple of things to note about the changes, in case it helps anyone:
- AI doesn't fire anyway if there's already a path on some other AI node... so no need to check
- Timer now resets if animal is fed/watered already
- Timer now resets if no food is found in area (gives chance for animal to wander to a better area)
- Timer extended to check once/40 loops (about every 6 seconds)

**Comment by capnkirok** [comment]
Hey @sfPlayer1 , how the latest work for you on performance. Any updates?

**Comment by sfPlayer1** [comment]
I haven't seen the problem again yet, but performance bugs usually need quite extensive observation.

**Comment by capnkirok** [comment]
Going to close this one in the next week if I don't hear back :)

**Comment by capnkirok** [comment]
Closing... no performance issues registered and many thousand of downloads.
