### ISSUE TITLE
ServerCrash

### ISSUE THREAD

**Issue by jprocket45** [capnkirok/animania#168]
https://pastebin.com/bvivhh55

I cry so hard :P

**Comment by GeebsRilie** [comment]
Me too.

https://pastebin.com/2SwvfELu

**Comment by capnkirok** [comment]
Sorry guys. Looking at it now.

**Comment by capnkirok** [comment]
Ok @jprocket45 your issue was on 1.10 and was a last minute mistake (by me). Will have an update out in the next 30 mins.

**Comment by capnkirok** [comment]
@jprocket45 see version 1.1.1

**Comment by capnkirok** [comment]
@GeebsRilie this one is also fixed. Waiting on CurseForge for approval. Thanks for the early reporting. Don't know how we missed either of these.

**Comment by Tschipp** [comment]
@capnkirok Probably bad testing by the test people. wait.... 😬

**Comment by GeebsRilie** [comment]
Thanks for prompt reply and fixing it! You can't catch all the bugs! Also
really loving the horse update!

**Comment by capnkirok** [comment]
Thanks @GeebsRilie .. you are right you can't catch all of them... we've already found a few more (non-crashing). Thank you for the quick report, I think you saved frustration from a lot of players.
