### ISSUE TITLE
piglet Rendering bug [world destroying]

### ISSUE THREAD

**Issue by reddler97** [capnkirok/animania#169]
i was starting a new world exploring then everything de-rendered/ un-rendered for a few seconds before crashing. i am playing with other mods but i will shortly be testing it with this mod alone. however in the meantime here's my crash log: 
[crash-2017-05-29_00.35.24-client.txt](https://github.com/capnkirok/animania/files/1034907/crash-2017-05-29_00.35.24-client.txt)

i wasn't playing on a server, and i don't have easy assess to one, so i can't test it, but every time i try to load the single player world from then it would do the same thing: render in the world,  un render the world, then crash. i am using curse/twitch launcher to gather my mods, and as far as i can tell i am using version 1.1

**Comment by capnkirok** [comment]
yes, same bug just reported. working on it

**Comment by capnkirok** [comment]
#168

**Comment by reddler97** [comment]
yep it crashed my fresh install. to duplicate find/spawn a hampshire piglet, here's a clean-er crash log:
[crash-2017-05-29_01.02.11-client.txt](https://github.com/capnkirok/animania/files/1034945/crash-2017-05-29_01.02.11-client.txt)
and if there is better i can upload my crash logs(rather than just drag and drop) let me know

**Comment by capnkirok** [comment]
Ok found the problem. New version coming shortly.

**Comment by capnkirok** [comment]
It's not world destroying. Just install the update, should be fine.

**Comment by reddler97** [comment]
well, it was world destroying... in that specific version(couldn't load world,making it un-playable), but you very quick with getting a fix. and i suppose there is enough of a gap to copy and paste a teleport command, but who's to know if you''ll teleport into another one.

if you think it's too harsh we/i could change the title. i'm going to leave this thread open for your discretion to close..... (i haven't checked if the update is out yet or not)

**Comment by Tschipp** [comment]
It's out
