### ISSUE TITLE
Despawn, Name Tag, Chick Hatch Speed

### ISSUE THREAD

**Issue by GeorgiaGames2** [capnkirok/animania#17]
•If I leave my animals alone for more than a minute they all despawn.
•You can't name tag any of the animals
And my question is: Is there a way that I can change how long it takes for the chicks to hatch? I'm not sure if one of config settings takes care of that or not already. I find that the chicks hatch way too quickly and I start to have a bit of a chicken infestation.  Thanks for the cool mod. I'm looking forward to the possible new additions.

**Comment by capnkirok** [comment]
- Hmmm... you might have a setting that despawns the animal. I can prevent this, but it shouldn't happen (it doesn't happen for most)
- Name Tagging seems to work on Chickens. Other animals look like there are problems. 
- Yes, I agree the hatching is too quick. It's still set to a testing time.

Good feedback, thanks! Will respond when I've got this figured out.

**Comment by capnkirok** [comment]
- Looks like Pigs, Cows, Ferrets were set to allow despawn. This is now turned off.
- Ok, have fixed the Name Tag issue with the Pigs.
- Have also added a randomizer to the hatch time, which can be changed in the config file

Fixed in Dev, will be pushed with 1.0 release

**Comment by GeorgiaGames2** [comment]
Thank you! This is great!

**Comment by capnkirok** [comment]
Ah, I just mean I fixed it in the development environment. We'll release the 1.0 update this weekend :D
