### ISSUE TITLE
Spawn limits not being respected for frogs

### ISSUE THREAD

**Issue by tizubythefizo** [capnkirok/animania#170]
So I spent a few hours beautifying a mountain when I noticed I was getting FPS dips down into the teens (I usually have around 140 -240). 

When I get done with the top, I flew around down to the bottom trying to find why my fps kept dipping (I figured it might be entities since F3 said there were 300 of them) and low and behold there were...apocalyptic amounts of frogs hopping around the valley (~240+).

**Comment by capnkirok** [comment]
Oh my god. What have we done. Will take a look. 

You can always set an army of Ferrets on them in the meantime...

**Comment by capnkirok** [comment]
Ironically, my spawn limit code for Amphibians is checking for Ferrets. So, yah. Bug.

**Comment by capnkirok** [comment]
Fixed in next release. Ferrets, chickens, peacocks and hegehogs can all be used to 'tame' your infestation in the meantime.

**Comment by tizubythefizo** [comment]
Heh, I ended up rolling back a version. The Kill command couldn't even keep up. 

I fully assume you'll be adding locusts to the mod next >.>
