### ISSUE TITLE
Suggestion: Add a link to curseforge in the readme.md file

### ISSUE THREAD

**Issue by calloatti** [capnkirok/animania#171]
Add a link to curseforge in the readme.md file
https://minecraft.curseforge.com/projects/animania

Also, you are at the top on Reddit FeedTheBeast!
https://www.reddit.com/r/feedthebeast/
https://redd.it/6dx740

**Comment by capnkirok** [comment]
Hey, you closed this. Thanks for pointing out reddit, and for the suggestion on the readme.md file!
