### ISSUE TITLE
Draft horses spawn too frequently

### ISSUE THREAD

**Issue by The-Brook** [capnkirok/animania#172]
The draft horses are too common compared to normal horses

**Comment by capnkirok** [comment]
Thanks. For now, you can turn down the limits in the config file.

**Comment by capnkirok** [comment]
Ok, I've also changed the default limit to 24, and enforced a spawn limit. Will be out in next release.

**Comment by capnkirok** [comment]
This is fixed... but you may need to edit your config spawn limits / probability to lower it. (or just delete it and Animania will make a new default)
