### ISSUE TITLE
Riding Mare Draft Horse shows you floating

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#175]
I may have not seen clearly but it seemed to be when u are riding them or mares anyway you kinda have a weird  placement on the horse? like u are floating on the horse,  Not sure if it is intended or not

**Comment by Tschipp** [comment]
Yeah I've seen that too, we are looking into it

**Comment by capnkirok** [comment]
This one is pretty easy. There is a RiderYOffset variable.

**Comment by capnkirok** [comment]
Ok, this will be fixed in next release (coming soon)
