### ISSUE TITLE
Document Syntax for adding drops to mobs?

### ISSUE THREAD

**Issue by thephoenixlodge** [capnkirok/animania#176]
At the moment there is no way of knowing based on the curseforge page, or the config itself what the full syntax for adding custom drops to the mobs are, namely, how metadata is handled, and how to separate entries.
In my case I'm trying to add pig fat from Ars Magica to pig drops, and thus far my attempts have simply resulted in pigs dropping nothing, without even any explanation of it failing to load the drops or anything in the log.
So far I have tried what I would have thought to be the most common syntax options:
modid:item:meta , modid:item:meta
modid:item:meta ; modid:item:meta

Neither of these work, so what is the syntax I should be using??

**Comment by capnkirok** [comment]
Good point about the forums, I really need to update. Check out some of the other drops in the default config to see. But it's just item... not the amount, so "minecraft:stone" or "arsmagica:pigfat" (or whatever). The drop amounts are tied to the happiness of the animal at the time of death, so I did not make that configurable. My guess is that it's the additional info that's causing the problem.

**Comment by thephoenixlodge** [comment]
the default config only has a max of 1 item for each mob, so there's no example of entry separation. And that isn't amount of the item, it's the metadata I'm talking about, in this case the id of the pig fat is arsmagica2:item_ore:8 and again there is no example that includes metadata. I see now that I formatted my examples wrong above, I'll fix those.

**Comment by Tschipp** [comment]
There's currently no support for metadata or nbt. We should probably try and switch to loottables.

**Comment by capnkirok** [comment]
Yeah... well, i meant to implement metadata. I've already done it for Voxels, just missed it. But... I think loot tables is better. Maybe I could add meta data support as a short term solution.

Format would be: "arsmagica2:item_ore#8"

**Comment by capnkirok** [comment]
Hey this has been updated in 1.1.4, using the above example, so:

arsmagica2:item_ore#8
minecraft:wool#5

or just

minecraft:bone (if no metadata)
