### ISSUE TITLE
Prime Bacon not usable for omelettes

### ISSUE THREAD

**Issue by thephoenixlodge** [capnkirok/animania#177]
Omelettes were seemingly forgotten when consolidating to the prime meats, as you can only craft bacon and super omelettes with breed specific bacons, not prime bacon.

**Comment by capnkirok** [comment]
Thanks. Will fix.

**Comment by capnkirok** [comment]
Gonna try to roll out another hotfix tonight.

**Comment by capnkirok** [comment]
Fixed in next release, also added correct Prime Steak and Bacon recipes in 1.11.2
