### ISSUE TITLE
Help! Cows Eat My Bucket!

### ISSUE THREAD

**Issue by TheCoolGuy937** [capnkirok/animania#178]
Sorry if this was already solved...
I had milked a Frezian Cow brought it home and befriended it.......when i tried to milk it again i received a milk bucket for about half a second and then it disappeared. 
I tried it with other Frezian cows......all were the same..
Sorry if i am being dumb.

**Comment by Tschipp** [comment]
What version of Minecraft and Animania are you playing on?

**Comment by Tschipp** [comment]
You are most likely using an old version, correct me if I'm wrong

**Comment by sfPlayer1** [comment]
Quoting Soaryn (we're on 1.1.1, 1.11.2, don't see any related fixes in the .2 changelog):

> When milking the cow there is a chance to lose the bucket
> As well as when crafting the special milk to -> milk it gives 2 buckets...

**Comment by capnkirok** [comment]
It's the bug that would not die! If I told you @Tschipp and I have tried to fix this issue 3 separate occasions and both tested again last night without issue, would you believe us?

Re-opened. 

LET THIS BE THE LAST BATTLE!

**Comment by Tschipp** [comment]
I can't belive this... Where did this happen tl Soaryn? In what modpack, and is there a video of it happening?

**Comment by capnkirok** [comment]
@Tschipp can verify the second bug on 1.11.2 - "when crafting the special milk to -> milk it gives 2 buckets..."

**Comment by Tschipp** [comment]
._. Checking later

**Comment by capnkirok** [comment]
@Tschipp and just verified the first. It took me about 10 milkings of one cow, but it happened. Bucket of milk appeared briefly in inventory and then disappeared. Looks like a nasty one.

**Comment by Tschipp** [comment]
Oohh not good

**Comment by Tschipp** [comment]
Fixed :D

**Comment by capnkirok** [comment]
We'll put it in the next release, maybe a small release this weekend.
