### ISSUE TITLE
Marine life 

### ISSUE THREAD

**Issue by MisterShura** [capnkirok/animania#179]
Plz add  marine life to the game : fishes, sharks, whales with diferent species and their different foods

**Comment by capnkirok** [comment]
Thanks for the suggestion. We have a few people asking for this. We will get there (eventually).

**Comment by Deshiba** [comment]
I'd like to take the time to suggest some other mods that already add some marine life.
- https://minecraft.curseforge.com/projects/just-a-few-fish
- https://minecraft.curseforge.com/projects/mo-creatures
- https://minecraft.curseforge.com/projects/mariculture

Especially Just a few fish is nice in companion.

**Comment by capnkirok** [comment]
I'm going to close this one, as I think Marine life is pretty well covered by other mods, and it's not our priority at the moment. Thanks for the suggestion though :D
