### ISSUE TITLE
[SUGGESTION] Some miscellaneous suggestions, regarding support and animals

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#18]
1. Implement other bovine species, such as yak, water buffalo, aurochsen, and so on. Allow for some hybridization between them and domestic cattle.
2. HarvestCraft support, if it is not already implemented
3. For birds, implement Guinea Fowl. Maybe they could keep some hostile mobs at bay, like llamas do in 1.11. Their favorite foods would be anything that comes from an arthropod, such as spider eyes.
4. Guinea pigs. I mean, if we want a use for them, they could drop meat. South American natives domesticated them for that purpose. Although most players are just going to keep them as pets. They could take hamster food, plus hay.
5. Plants by Shadows of Fire support. (https://github.com/Shadows-of-Fire/Plants)
6. Wagyu Cattle
7. Ankole-Watusi Cattle

**Comment by capnkirok** [comment]
- HavestCraft OreDictionary and recipe support now in place

**Comment by capnkirok** [comment]
Closing some of these older suggestions to keep them in a master sheet.... but here's where it stands.

- HarvestCraft support is in
- We have a lot of birds on the list, just not in yet
- Some other bovines are coming in...
- Guinea pigs are on the list
- Plant support should be in

I think this was your first suggestion?
