### ISSUE TITLE
Chickens Suffocate in a block and die

### ISSUE THREAD

**Issue by TheCoolGuy937** [capnkirok/animania#180]
Sry if this was already fixed...I might be using an old version I'll confirm later
Yeah the problem is that when water source blocks were placed adjacent to a wall as a small pool.... chickens would Hop in and flop about..........when I left them for a while.....I found 1 Raw chicken and feather....... apparently the only rooster I had (which I had to get from far away....don't ask) died.
Also you can sort of push them into blocks and murder them....I only had time to test it on chicks...
Plz fix this if it hasn't already been fixed.
Thnx

**Comment by Tschipp** [comment]
What version are you using ?

**Comment by Rambonata** [comment]
I'm not the original person who reported this, but I do have the same issue with chickens (and pigs). I'm using the latest (1.10.2) version

**Comment by capnkirok** [comment]
Yeah, this is the AI swimming code having issues with currents. Will have to fix.

**Comment by capnkirok** [comment]
Ok, fixed in dev.
