### ISSUE TITLE
Troughs

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#181]
I placed water with a bucket in a trough but u then right click again and its just an empty bucket and trough is this a bug or is this how it is supposed to be.

**Comment by Tschipp** [comment]
What version are you using ?

**Comment by 19nrussell** [comment]
Latest version 1.11

**Comment by capnkirok** [comment]
Could be the same issue @Tschipp

**Comment by Tschipp** [comment]
Unlikely, the water bucket is an item, not ItemStack. @19nrussell, latest version as in 1.1.2?

**Comment by 19nrussell** [comment]
Latest version u can have of 1.11

**Comment by Tschipp** [comment]
Alright I'm checking it out

**Comment by Tschipp** [comment]
Fixed, Numbers are hard
