### ISSUE TITLE
New animals should be added to Curse overview page

### ISSUE THREAD

**Issue by WesCook** [capnkirok/animania#182]
Currently the new animals from the latest update (Draft horses, etc) haven't been added to the [Curse overview page](https://minecraft.curseforge.com/projects/animania).

I'm also not too sure how Draft Horses work.  Could a description be provided on the same page, or is there documentation elsewhere?

Much thanks!  Excited to play with the new content.

**Comment by Tschipp** [comment]
Purp is gonna update it soon™

**Comment by capnkirok** [comment]
Text should be finished tonight... new renders tomorrow.

**Comment by capnkirok** [comment]
Ok, the text is in. We'll new images tomorrow. But closing now :)
