### ISSUE TITLE
Animals Showing Hungry/Thirsty at all times

### ISSUE THREAD

**Issue by Skyshadow324** [capnkirok/animania#184]
For some reason my animals are showing hungry/thirsty even after being hand fed or watered. This also occurs if they use a trough. I am on the latest update. So far the only animals I have tested with are cows, chickens and pigs. Pigs also have the constant tag of 'bored'.

I have noticed if I catch it at just the right angle it will show content/satisfied for a split second then go back to hungry/thirsty. The animals are not unhappy and are breeding, they just continue to show the incorrect tags. 

I am using the Modded Mischief II mod pack and I am not sure if maybe something is conflicting since I haven't seen anyone else having this. 

Edit:Expanded my search. This also is occurring with peacocks and hamsters.

**Comment by 19nrussell** [comment]
ya I have also had this issue but with draft horses

**Comment by 19nrussell** [comment]
latest version of the mod in Minecraft 1.11

**Comment by Skyshadow324** [comment]
I am also newest version of mod and Minecraft

**Comment by Tschipp** [comment]
Yeah I can't seem to recreate this. Can you provide a world download

**Comment by Skyshadow324** [comment]
I also use Twitch client to run the mod pack. I am not sure if that will help any with solving.

**Comment by Skyshadow324** [comment]
I think I found the solution. The mod pack included HWYLA which is an offshoot of WAILA there seems to be a compatibility issue with HWYLA. When I switched to WAILA the issue resolved and the information showed correctly!

**Comment by Tschipp** [comment]
Lol, that would probably be the issue.

**Comment by capnkirok** [comment]
@19nrussell Your issue with Draft Horses was fixed in the latest, so I'm closing this one. Thanks and good to know about HWYLA.

**Comment by esotericist** [comment]
Given that HWYLA is a fork of WAILA that uses the same API and claims to provide 100% compatibility, this is something that probably should work.

**Comment by esotericist** [comment]
Possibly silly question: is Animania using the lowercase 'waila' modID instead of 'Waila'? Lowercase is supposed to be mandatory now, but it looks like ProfMobius didn't do that when porting to 1.11.2.

**Comment by Tschipp** [comment]
yes, it's using lowercase

**Comment by 19nrussell** [comment]
ya I was having the problem disabled mod then re enabled it and I have not seen the problem so far of it again
