### ISSUE TITLE
Cows and Bulls suffocate in blocks and die

### ISSUE THREAD

**Issue by darthvader45** [capnkirok/animania#187]
I've made a cow killer for a slaughterhouse, and can't seem to fit the bulls in for slaughtering, because they keep suffocating and dying.

**Comment by Tschipp** [comment]
We have also noticed this one, working on it.

**Comment by darthvader45** [comment]
Yeah, impossible to fit them in a 1-block wide space.  Thanks for the attention.

**Comment by darthvader45** [comment]
@capnkirok Thanks for investigating this.  Somehow the AI is too smart.  They're trying to prevent more slaughter.  We need to end this before they rise up against us!

**Comment by capnkirok** [comment]
Lolol!

**Comment by capnkirok** [comment]
Yes, because the size of the cows is more accurate, you'll need a two block wide 'chute'.

**Comment by darthvader45** [comment]
Darn, guess I'll need to redo the slaughterhouse.  Maybe I'll try a double row of conveyors going to a crusher that pulverizes them and leaves the raw angus beef in a nearby chest.  Will take longer, due to needing a crapload of iron, but will pay for itself in beef.

**Comment by capnkirok** [comment]
Sorry @darthvader45.  Btw, what conveyor belts mod do you use? Just curious as I have this slick conveyor belt code lying around for a year with no one to enjoy it...

**Comment by Tschipp** [comment]
Or just, you know, let them roam on the fields and slaughter them manually. Meat will taste better ;)

**Comment by darthvader45** [comment]
IE.  It's amazing with dieselpunk themes.

**Comment by darthvader45** [comment]
Plus, automation makes it all better.

**Comment by capnkirok** [comment]
Thanks for the feedback! Closing this one for now.
