### ISSUE TITLE
Server/Client crashes whenever i try to place a Trough  Animania 1.11.2-1.1.2

### ISSUE THREAD

**Issue by ionutsoran** [capnkirok/animania#188]
Hello there !Ever since i upgraded to 1.1.2 animania people on my server and i can't place a trough on the ground anymore or anywhere ,it crashes the server then when i restart the server every player that stands/stood near the trough gets disconnected from the server and can never log back until someone else is quick enough to distroy it.(One important thing to mention is on the server console it doesnt spit out  any errors when the player sits near the trough ,he/she just gets disconnected and it just says the player disconected..)If you could be so kind to take a look at this paste bin that would be great!
I apologize in advance for the long text i didnt know where it would be best to cut it !
https://pastebin.com/wjxPuh4b (This is the log for the client side).

**Comment by capnkirok** [comment]
Looking into this... seems like a compat issue, as it doesn't crash on its own.

**Comment by ionutsoran** [comment]
One more thing that comes to mind ,this didn't occur in the Animania-1.11.2-1.0.4.7  version which i used on my server .I didnt update any other mods except this one and i updated from  Animania-1.11.2-1.0.4.7 to Animania 1.11.2-1.1.2 directly.When i first ran  this update on my local server it said it removed the trough and another item and asked me to fml confirm to continue and i said yes but the troughs remained there they were.Still if i get close to one it disconnects me.. Hope this helpful!.

**Comment by Tschipp** [comment]
Troughs were pretty much completely rewritten in 1.1, that's why it worked before. Is the trough that is crashing you a trough from an old version of animania (pre 1.1), or was it placed in fresh?

**Comment by ionutsoran** [comment]
Old and new placed Troughs act the same,.. i mean they both disconnect the player

**Comment by capnkirok** [comment]
Hey @ionutsoran I *think* you can turn off Trough Automation in the config and this will allow you to play. Meanwhile we are working on a fix.

**Comment by ionutsoran** [comment]
Nope still getting disconnected when placing one and when standing near one with Trough Automation set to false .Again want to thank you so much for taking your time to look into this!I really love this mod and appreciate all the effort you have put to make this mod !Looking forward to hearing news from you!:)

**Comment by capnkirok** [comment]
Thanks for checking. We hope to have a build and fix out late tomorrow.
