### ISSUE TITLE
[Suggestion] Sleeping Animals

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#189]
Since you want this to be realistic (and might I say you are doing a FANTASTIC job!), why not have animals sleep at night and maybe take naps throughout the day? I'm pretty sure that animals don't stay awake 24/7! If this is already planned, then awesome! Can't wait! ^^

**Comment by capnkirok** [comment]
Yep, this is planned :)

And if you have a Rooster, it will wake them up :)

**Comment by RaliaTheWolf** [comment]
Oh, cool! Looking forward to it!

**Comment by RaliaTheWolf** [comment]
Would it be possible to have the chickens go back to their coop at night to sleep? I'm not sure how you could do this... Maybe something with the nests? Like perhaps for hens, if they've laid an egg in the nest that's their new 'home' (it could be a radius though so a ton of hens don't try to go in the exact same spot) and for roosters it could still be the nests but they've helped hatch an egg from it? I'm not a coder so I'm not sure if that's possible or not... Either way, I think this would be a nice feature so we could have free-range chickens that don't run away forever.

**Comment by capnkirok** [comment]
Well... could do a Roost, which is where Chickens and Roosters are supposed to sleep. And if you put this inside a barn/coop, they would find it and walk there. Nest could be a backup.

**Comment by NavyT** [comment]
This would be cool.

**Comment by RaliaTheWolf** [comment]
Oh I've been making roosts for my chickens! (But of course they don't use them XD) That would be perfect!
