### ISSUE TITLE
No Animals Spawning in New chunks

### ISSUE THREAD

**Issue by saraminecraft** [capnkirok/animania#190]
Hi! I have been using your mod for my private dedicated server and just installed the update. However when I install the update no new animals (animania animals) spawn in any new chunk. I tried turning all spawn probabilities up to 100 but I still have nothing spawning. The mod works fine on a NEW server, I tested that myself. I replaced the config file with the new config file as instructed and did everything else required. Is there information or something I could provide that will help you help me?? Please let me know and thanks for the awesome mod!!!
<3 Sara

**Comment by JamRobLam** [comment]
I don't work on the mod but,  a mod list for the server, version of minecraft, and version of the mod your running is good starter info. (but being you said latest I'm assuming MC version 1.11)

**Comment by saraminecraft** [comment]
ok ty! is there an easy way to get a mod list in text format so I can paste it here?

**Comment by saraminecraft** [comment]
OK i asked someone how to make a directory into a text file so here is what my mods are:

1.11.2_deadly_monsters_1.15.jar
aether_legacy-1.11.2-1.0.jar
 animania-1.11.2-1.1.2.jar
AppleSkin-mc1.11-1.0.6.jar
Aquaculture-1.11.2-1.5.0.33.jar
armorplus-1.11.2-10.3.2.3.jar
AutoRegLib-1.1-4.jar
Baubles-1.11-1.4.4.jar
BetterAchievements-1.11.2-0.4.1.44.jar
BetterFps-1.4.4.jar
BiomesOPlenty-1.11.2-6.1.0.2222-universal.jar
Bookshelf-1.11.2-1.5.0.371.jar
Botania r1.9-343.jar
Bullseye-1.11.2-2.0.0.jar
Cavern_1.11.2-v1.7.1.jar
Chisel-MC1.11.2-0.0.10.14.jar
CombinedPotions-1.11-1.0.jar
compatlayer-1.11.2-0.2.8.jar
 CookingForBlockheads_1.11.2-5.3.20.jar
 CoralReef-1.4.jar
 CraftableElytra-1.1-1.11.2.jar
 CrystalCaves-1.0.jar
 cxlibrary-1.11.2-1.4.0.jar
dailies-1.11.2-6.jar
 Dark Roleplay Core Alpha-0.2.0b.jar
 Dark Roleplay Medieval Alpha 0.1.9.jar
DarkUtilities-1.11.2-1.2.0.126.jar
 dendrology-1.11.2-L1.2.1.jar
DoomlikeDungeons-1.9.2-MC1.11.2.jar
 DynamicSurroundings-1.11.2-3.3.3.1.jar
 EbonArts-v2.5.0a-mc1.11.0.jar
 ElecCore-1.11-1.7.420.jar
 embers-0.212.jar
 EnderZoo-1.11.2-1.3.0.46.jar
 EndOres-1.11.2-r1.jar
foamfix-0.6.3-anarchy.jar
Forgelin-1.4.2.jar
 FriendlyFire-1.11-1.4.0.jar
 FunOres-1.11.x-1.5.2c-107.jar
 Guide-API-1.11.2-2.1.1-52.jar
 industrialcraft-2-2.7.33-ex111.jar
 InfernalMobs-1.11.2.jar
 inventorypets-1.11.2-1.4.9.5.jar
 ironchest-1.11.2-7.0.19.803.jar
 IvToolkit-1.3.3.jar
 jei_1.11.2-4.3.5.277.jar
 journeymap-1.11.2-5.4.6.jar
 JurassiCraft-2.0.5.jar
koresample-1.11.2-L1.2.jar
 Levels 2-1.11.2-r1.2.8.jar
 LevelUp!-0.14.4-1.11.2.jar
 leveluphp-1.11-1.0.1.jar
 llibrary-1.7.6-1.11.2.jar
 Mantle-1.11.2-1.2.0.26.jar
MoreFurnaces-1.11.2-1.9.5.jar
 natura-1.11.2-4.2.0.17.jar
 NaturesCompass-1.11.2-1.3.0.jar
 netherrocks-1.10.2-1.5.3.1.jar
 NoMoreRecipeConflict-0.8(1.11).jar
 NotEnoughIDs-1.5.4.jar
 OpenModularTurrets-1.7.10-2.2.10-237.jar
 Ore Core 1.11.2 (v.1.1.2).jar
 OreDictionaryConverter-1.10.0.jar
 Pam's HarvestCraft 1.11.2h.jar
 Plants-1.11.2-beta-0.8.5.jar
Quark-r1.2-92.jar
 QuickLeafDecay-MC1.11.2-1.2.3.jar
RecurrentComplex-1.3.1.1.jar
 redstonepaste-mc1.11.2-1.7.4.jar
 Reliquary-1.11.2-1.3.3.653.jar
 reptilemod-1.11.2-3.6.2-67.jar
 RoguelikeDungeons-1.11.2-1.6.6.jar
 roots-2-0.017.jar
 Ruins-1.11.2.jar
 ShadowMC-1.11.2-3.7.5.jar
 SilentLib-1.11.x-2.1.3-58.jar
 SilentsGems-1.11.x-2.3.12-178.jar
 simplecore-1.11.2-1.4.5.1.jar
 simpleores-1.10.2-1.9.1.3.jar
 SimpleTeleporters-1.11.2-2.1.2.jar
 SophisticatedWolves-3.6.5.jar
 stonehenge-1.11.2-0.2.jar
Substratum-1.11.2-1.9.2.0.jar
TConstruct-1.11.2-2.7.0.12.jar
 thedragonlib-1.11.2-3.2.2.jar
TMC-1.11.2-1.5.jar
Totemic-1.11.2-0.8.6.jar
 ToughAsNails-1.11-2.0.5.jar
 VanillaMagic-1.11.2-0.21.12.0.jar
 villagermarket-0.2-HF.jar
 Waila-1.7.1_1.11.2.jar
weaponcaseloot-1.11.2-5.0.3-beta.jar
 wolfarmor-1.3.3.6.jar
 zz-backpacks 1.11.2 - 3.1.9.jar
[1.11.2]UncraftingTable-1.7.2.jar
 [MC 1.11.X] BetterCombatMod 1.4.jar

im using 1.11.2 minecraft version and newest version of mod

Keep in mind this works on NEW servers or single player games but I cannot get any entities to spawn on my current server that was running the old version of the mod previously.

<3 thanks!!!
<3 Sara

**Comment by capnkirok** [comment]
Thanks Sara. So on the old server, no animals spawn, even in a new chunk. Yeah, that's strange. It will take some time to test this, so bear with us.

**Comment by esotericist** [comment]
As a thought: How many people are on the server? How many animals are in chunks that players tend to stay in? is it possible this is a spawn cap issue?

This happens on vanilla, too, if you've got a server with enough animals in player frequented areas.

**Comment by capnkirok** [comment]
Could also be biome dictionary acting weird in 1.11.2... I'm seeing problems with Biomes o' Plenty ... looking into all possibilities :)

**Comment by capnkirok** [comment]
Yep! Was an issue with the way we implemented BiomeDictionary... fixed in next release!

**Comment by capnkirok** [comment]
See also #191

**Comment by saraminecraft** [comment]
WOW fastest bug fix ever you guys are EPIC!!! I <3 you!! Has new released been released yet? Will I have to start a new server or can I simply update mod and config file and keep playing? 
<3 Sara

**Comment by capnkirok** [comment]
I am not entirely sure. I think you might need to start a new server, but try it first. Update is out on Curse now.
