### ISSUE TITLE
No new type spawn, only vanilla replaced animal spawned

### ISSUE THREAD

**Issue by kokjoo89** [capnkirok/animania#191]
Minecraft 1.11.2 Animania 1.1.2
Create a new world and fly around, found only vanilla replaced type animal.
I do run with Biome O' Plenty mod.
edit:
create a new vanilla world type, i do found other type animal in other biomes.
but with Biome O' Plenty world type animal are rare and found only vanilla replaced type of animal.

**Comment by capnkirok** [comment]
It looks like BiomeDictionary isn't working with 1.11.2 right now, so you will see issues with Biomes of Plenty. Thanks for flagging!

**Comment by capnkirok** [comment]
This is fixed in dev. Will be in next release. Thanks!
