### ISSUE TITLE
Foal won't grow up

### ISSUE THREAD

**Issue by TiffanyDoctorWho** [capnkirok/animania#193]
Hello, I am wondering why a foal to a mare won't grow up even though it seems to be fully grown I can't ride it.

**Comment by darthvader45** [comment]
Have you tried leaving it alone for a bit longer?  I believe it takes quite a few Minecraft days before they're full grown.

**Comment by capnkirok** [comment]
I just tested and the growing up works fine. However! You need to make sure it's fed and watered.

I did find some other issues:
- Changing color when it becomes an adult
- Growing larger than it's adult size before it changes

**Comment by TiffanyDoctorWho** [comment]
Thank you very much. I was very confused.

**Comment by darthvader45** [comment]
@capnkirok Dayum, they mooed?  Reminds me of a nightmare I had when I was 7 or 8.  My rocking horse went right up to the side of my bed, mooed, and then tried to bite me.  I woke up before that happened.  Freaking terrifying back then, still a little creepy now.
