### ISSUE TITLE
Cows having a hard time with water & fences/barriers

### ISSUE THREAD

**Issue by Seth0067** [capnkirok/animania#194]
I know this will come as a huge shock given MC's track record with such things, but irregularities will occur with cows and fences or barriers, when water is involved.  Two test cases to observe, and of course, they may not be symptomatic of the same problem. Also - this may be relevant to other animals or may not be a problem within Animalia itself. :)  Just thought I would report with enough info to possible reproduce.  

Case One:  Cows in an enclosed space with one or more water block running underneath a fence/cobble wall.  The cows will often "leak" underneath the fence and pop-out the other end 

Case Two: In a two-block deep pit (size 3x3), where a corner/ground block is a water flow (he using a water bowl from Actually Additions/+Streams mod to create this), one cow will die off camera, possible from being mashed into a corner.  Note this is a huge assumption on my part, but this was actually observed via Darkosto's test instance on his stream a couple of times. I wonderfed if the entity somehow was forced into the dirt barrier block and suffoctaed.

LMK, and i can perhaps get more info if helpful.

**Comment by Tschipp** [comment]
Case two is already fixed, case one might be related and therefore might also be fixed

**Comment by capnkirok** [comment]
Yeah, these are both fixed in the update coming in a few hours. Thanks for the test scenarios though!

**Comment by capnkirok** [comment]
Related to #180
