### ISSUE TITLE
[1.11.2] Bucket Duplication

### ISSUE THREAD

**Issue by nightlone** [capnkirok/animania#195]
as of version 1.1.2 I was able to duplicate a bucket by milking a Friesian cow, using the built-in recipe to turn Friesian milk into minecraft milk, and drink!

Tested it again, JUST in case, and yup, it works (so, now I can have infinite buckets, thanks ;) )

**Comment by capnkirok** [comment]
Ha ha! This bug is also a dupe! #178 

Will be fixed in 1.1.3 coming in like 15 mins
