### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#196]
I have been playing it in survival and I have not once got the prime meats is that intended ?
playing latest version of mod (1.11.2)

**Comment by capnkirok** [comment]
Sounds like a bug :( Can't test until later...

**Comment by Tschipp** [comment]
Only Longhorn, Hereford and Angus cows drop prime meat. Did you try killing one of them?

**Comment by 19nrussell** [comment]
No it was one of the dairy breeds 
Was not for sure how I got it

**Comment by Tschipp** [comment]
The dairy breeds drop normal meat

**Comment by 19nrussell** [comment]
yes checked the beef breeds do drop them sorry for any confusion was just unsure about dairy breeeds
