### ISSUE TITLE
[Suggestion] Eat items

### ISSUE THREAD

**Issue by Jomik** [capnkirok/animania#199]
I feel like it should be possible to feed the animals by dropping their food on the ground.
This is especially a thing I'd wish for my chickens, as I currently have to run in and spam the area with seeds. I'd rather be able to dispense seeds to them at regular intervals, and they then eat the seeds off the ground.
Or even better, make dropped seeds (if they can) "attach" to the ground if they lay around for a longer while.

**Comment by Tschipp** [comment]
We are gonna implement dispensers being able to place seeds, so that will solve the problem.

**Comment by Jomik** [comment]
Isn't pathing to an entity the same as pathing to a block, if you assume that the entity is stationary? Though, if that is the case. I understand not eating seeds on dropped form.
Dispensers being able to place seeds will somewhat solve the issue. Though, it'd require me to place an ugly (in my eyes) block in my pen.

**Comment by Tschipp** [comment]
you could place the dispenser in the ground, below where the seeds would be placed
