### ISSUE TITLE
Incompatibility with Totemic

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#20]
Totemic has a ritual to turn cow into buffalo, and with the changes this mod makes to them, the specific ceremony used will not work on mobs from this mod.

https://github.com/TeamTotemic/Totemic/issues/45

**Comment by capnkirok** [comment]
As mentioned on the Totemic board, vanilla animals can be enabled in the config.

**Comment by ljfa-ag** [comment]
Fixed that by adding compatibility with Animania cows.

However there is another problem: If the config option you mentioned is not set, Animania will instantly delete Buffalos on spawn, since they extend EntityCow. Maybe you should check if the class is exactly EntityCow and not a subclass.

**Comment by capnkirok** [comment]
Oooh. Good one. Thanks for the tip.

**Comment by capnkirok** [comment]
Done, will be fixed in 1.0 release.

**Comment by ljfa-ag** [comment]
Great, thanks
