### ISSUE TITLE
[Suggestion] Seeds on the ground "grow"

### ISSUE THREAD

**Issue by Jomik** [capnkirok/animania#200]
If you choose to implement #199, I feel like it'd be a nice addition to have the seeds that are stuck on the ground for a longer period become grass/flowers, like the grass/flowers you get from using bonemeal on grass blocks.

**Comment by Tschipp** [comment]
Personally, I'm against that. It would be cool, but we'd have to make the block "tick randomly", which means it could turn to flowers or grass at any random time. If we want it to work like an "age" thing, we would have to make a TileEntity that is also ticking, 20 times per second.
So with the thought in mind of minimizing lag (animania is already pretty resource intensive) i vote against this.

**Comment by Jomik** [comment]
It was more of an afterthought. Your point is good.
