### ISSUE TITLE
Horses don't seem to breed.

### ISSUE THREAD

**Issue by crakiMDH** [capnkirok/animania#202]
I had a Stallion and a Mare of the brownish color that resembles chestnut horses. The Stallion suddenly turned a pure black texture after a bit and the mare remained the same. Also, they never produced a baby foal despite the fact that I tied them both to a fence and they had water and grass right next to them. Version 1.1.2 for Minecraft 1.11.2.

**Comment by Tschipp** [comment]
How long did you wait? There is a newer version out, 1.1.3. Try that version

**Comment by crakiMDH** [comment]
I'm certain I waited around 1 day.

I'm not in a position to test with 1.1.3, but once I get home I'll experiment with it.

**Comment by Tschipp** [comment]
try setting the gestation timer to something low in the config, like 100 ticks

**Comment by capnkirok** [comment]
Couple of things could be happening:
- Some horses may not have been getting credit for eating grass in 1.1.2 (so they weren't fed)
- The horses may not have been mated to each other (did you see hearts when they were near each other)? Right now horses mate for life. 

Would suggest updating to the latest, creating a test world, changing the 'gestation timer' to say 100, and spawn in a male and female, and hand feed and water them. I think you'll it's working.
