### ISSUE TITLE
Suggestion for Rodents.

### ISSUE THREAD

**Issue by epicslayer999** [capnkirok/animania#203]
This is a simple suggestion. 

Seeing how Hamsters are in the mod, I've been thinking that it would be a good idea to include some other rodents. Mouses, gerbils, and rats.

All 3 rodents would be tameable with something like seeds, and you could have them in your shoulder as well. I'm suggesting this because I don't see it in the upcoming features list.

Rodents would be passive and naturally flee, but if you have their food on your hand they won't flee from you. Rodents can also eat some crops, and maybe infiltrate your farms and eat from your troughs, which is why I think the cats you'll add in the mod could possibly attack them.

Hope you include this suggestion, it would really be nice for you to give us a bit of a challenge with animals who eat our crops unless tamed.

**Comment by capnkirok** [comment]
Well, guinea pigs and rats are coming. Rats actually are already modeled, just are not in. Cats are also coming. Just need time :)

**Comment by crakiMDH** [comment]
Will guinea pigs and rats be tameable?

**Comment by capnkirok** [comment]
Yes and yes

**Comment by crakiMDH** [comment]
Animania is one of my favorite mods and how much I love it has increased even more.

**Comment by capnkirok** [comment]
Hey @epicslayer999 haven't forgotten about his one. It's on our to do list. Closing it here so we can focus the git on bugs only. Thanks!
