### ISSUE TITLE
[Suggestion] Eat to regenerate

### ISSUE THREAD

**Issue by Jomik** [capnkirok/animania#204]
This is more me missing a passive animal for the Well of Suffering from Blood Magic.

I think it'd be quite awesome if the animals would eat if they were low on health, to gain health again.
I feel like it kind of does make sense from a realistic point of view. Alternatively, they could get some sort of buff to health regeneration if they're well-fed/happy.

This also makes a nice opposite of starving to death.

I do realize that the suggestion is quite specific for the purpose of Blood Magic, at least for me. I figured I'd toss it in here anyway 😄

**Comment by Tschipp** [comment]
Call me crazy but I think they already do that

**Comment by Jomik** [comment]
They do? I am quite sure I hand-fed a cow that was half health, and it didn't gain health. Is it immediate?
Possible to extend this to when eating from troughs? And make them seek food if they're low on health?

**Comment by Tschipp** [comment]
Sure, we can make it heal when they eat anytime

**Comment by Jomik** [comment]
I can confirm that they do heal if they're hand-fed at least :)
Does this include them seeking food if they're not at full health? I mean, in the sense that they'll eat more frequently?

**Comment by Tschipp** [comment]
I just wanted to go implement this, saw that it already was implemented .-. even for non-manual feeding. They will not actively seek food if they're low, but they eat constantly anyways

**Comment by Jomik** [comment]
@Tschipp 
Okay, understandable. They sadly don't eat/regenerate enough to survive the Well of Suffering from Blood Magic. However, I can understand the logic in not making them actively seek food when wounded. It's not that realistic. 😄
