### ISSUE TITLE
Horses Disappear 

### ISSUE THREAD

**Issue by TiffanyDoctorWho** [capnkirok/animania#206]
The Horses  disappear randomly when I leave the world then come back.

**Comment by capnkirok** [comment]
You are likely at your Spawn Limit for this animal type. You can try increasing the number in the Spawn Limit and see if that works.

What version of game are you on and what version of Animania

(changing your title)

**Comment by TiffanyDoctorWho** [comment]
I am in version 1.10.2 and I am on the newest version , and How do I increasing the number of the spawn limit?

**Comment by capnkirok** [comment]
From the main menu, go into Mods, the choose Animania, then go into the Spawn area and you can adjust numbers there. Make sure you press Done to save.

**Comment by capnkirok** [comment]
How many horses would you say you have?

**Comment by TiffanyDoctorWho** [comment]
Thank you very much

**Comment by TiffanyDoctorWho** [comment]
I had 2 , but there were many out in the wild. Also suggestion , you should make it like they are wild . Like from the mod simply horses.

**Comment by capnkirok** [comment]
Do you mean that they should be harder to approach? What do you mean by wild?

**Comment by TiffanyDoctorWho** [comment]
Like a normal Horse group, like what if there was a main stallion. I will just give you a video of what I mean,  https://www.youtube.com/watch?v=sEPzyDTxCLM&index=14&list=PL68F121C13BA3C151 . It is very cool

**Comment by capnkirok** [comment]
Hey @TiffanyDoctorWho I've finally identified how horses (and other animals) could be disappearing. This will be fixed tonight.
