### ISSUE TITLE
Cursed earth spawns animania bulls

### ISSUE THREAD

**Issue by OrdinatorStouff** [capnkirok/animania#207]
And sometimes those bulls are ridden by skeleton jockies. Makes me wonder if the bull AI is borrowed from the spider "passive until provoked" but otherwise classified as a hostile mob and not a passive mob.

I don't know if this would be an animania issue or an Extra Utilities issue, however.

Also, these "Cursed earth cows" have caused some [crashes](https://pastebin.com/YRnBzecz) on the ATM2 server with an interaction with the MobTotems mod.

**Comment by Tschipp** [comment]
Are the bulls spawning without skeletons or are the skeletons just dying?

**Comment by OrdinatorStouff** [comment]
The report that was brought to us is originally here: https://github.com/AllTheMods/ATM-2/issues/24 stating that the bulls can be spawned in with or without a rider.

**Comment by capnkirok** [comment]
@OrdinatorStouff your crash shows a conflict between MobTotems and ExtraUtils, would check between those authors, whose mods are both try to do something to the Cow. Recent change in Animania is that they now extend vanilla cows, it might be an Animania cow they are having problems with.

Recommend you turn off allowmobriding in the config (under Game Rules) and see if that fixes it.

**Comment by OrdinatorStouff** [comment]
Thanks. I have a ticket open over at [MobTotems](https://github.com/CorwinJV/MobTotems/issues/23) already to look into that more. As for this issue here the config option is a sufficient solution from a modpack standpoint, I think.

**Comment by capnkirok** [comment]
Ok! Closing thx :)
