### ISSUE TITLE
still having problem with titles

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#208]
I have had both cows and horses they say they are mated  then I look again and it don't ,similar  hungry/thirsty but actually are not . I have relogged and came back in and it fixes it but then after a little I've seen another animals messed up.

**Comment by Tschipp** [comment]
Are you using Waila or HWYLA?

**Comment by 19nrussell** [comment]
waila

**Comment by Tschipp** [comment]
are you playing on a server or in singleplayer?

**Comment by 19nrussell** [comment]
Single player

**Comment by Tschipp** [comment]
can you maybe provide a world download where this is happening? I haven't been able to recreate this yet

**Comment by 19nrussell** [comment]
I can exactly how do I do that

**Comment by Tschipp** [comment]
zip your world file and put it on dropbox or somewhere

**Comment by 19nrussell** [comment]
ok https://www.dropbox.com/s/46b6kv7aqjosjl0/New%20World-.zip?dl=0 
I think this is what u needed

**Comment by 19nrussell** [comment]
and I do use mods it is not that many tho

**Comment by capnkirok** [comment]
Can you see what happens if you remove Waila Harvestability (just temporarily for testing)?

**Comment by 19nrussell** [comment]
Ya I can do that

**Comment by 19nrussell** [comment]
no still getting same problems

**Comment by 19nrussell** [comment]
![2017-06-09_13 26 59](https://user-images.githubusercontent.com/28038939/27014136-d718588c-4eb7-11e7-9087-8576a3500076.png)
![2017-06-09_13 27 07](https://user-images.githubusercontent.com/28038939/27014131-d70d633c-4eb7-11e7-90e8-58258e974bea.png)
![2017-06-09_13 27 33](https://user-images.githubusercontent.com/28038939/27014134-d7146e2a-4eb7-11e7-8e0e-d1a83efc8c1c.png)
![2017-06-09_13 27 39](https://user-images.githubusercontent.com/28038939/27014133-d7143bd0-4eb7-11e7-9b58-c45187664820.png)
![2017-06-09_13 27 48](https://user-images.githubusercontent.com/28038939/27014132-d710187a-4eb7-11e7-9e20-d31211c61467.png)
![2017-06-09_13 27 56](https://user-images.githubusercontent.com/28038939/27014135-d7152b58-4eb7-11e7-8695-7082f61859cf.png)
![2017-06-09_13 28 01](https://user-images.githubusercontent.com/28038939/27014137-d71b209e-4eb7-11e7-9c74-12a6500bda4c.png)

**Comment by Tschipp** [comment]
what's wrong with the above pictures?

**Comment by 19nrussell** [comment]
the mating things are messed up and the hungry even tho it is showing hungry I can ride it

**Comment by 19nrussell** [comment]
first 2 showing hunger issues
3,4 is mating problem
5,6, mating problem and last one I reclogged and then it was like it

**Comment by Tschipp** [comment]
And you're sneaking in all of these?

**Comment by 19nrussell** [comment]
yas

**Comment by 19nrussell** [comment]
did u even find anything?

**Comment by Tschipp** [comment]
I did not find what you were describing, but I found some interesting behavior with wawla

**Comment by 19nrussell** [comment]
https://www.dropbox.com/s/p8r6fuavzihj1xs/horse%20vid.MP4?dl=0

**Comment by 19nrussell** [comment]
just trying to figure out what this is or if it is just my computer ?

**Comment by Tschipp** [comment]
Can you try it in a world with only the animania mod?

**Comment by 19nrussell** [comment]
yes I did and I'm still getting the problems

**Comment by Tschipp** [comment]
Yeah I really don't know, hasn't been happening to anyone but you. What version of forge and java are you using?

**Comment by 19nrussell** [comment]
latest u can get of both

**Comment by Tschipp** [comment]
Yeah I really don't know, can you try it on another machine?

**Comment by 19nrussell** [comment]
I think I'm going to play a while on it and see if it happens much more have changed couple things and it seems to be less frequent

**Comment by 19nrussell** [comment]
so  u said u found something interesting  behavior 
I just noticed relog and shift and it says mate missing u can shift let go ,for about 3-4 times then It goes away till u relog again

**Comment by Tschipp** [comment]
What did you change and is it only happening with horses? #IBlamePurp

**Comment by 19nrussell** [comment]
I took out ftb stuff ,combat layer,gravestone, jer,and waila harvestibilty.
been playing about 10-15 min had nothing yet

**Comment by Tschipp** [comment]
Waila harvestability?! That might be the reason!

**Comment by 19nrussell** [comment]
ok I think I figured I out I had forgot to delete config like said to just did not exactly know how

**Comment by Tschipp** [comment]
Ok. Can I close this?

**Comment by 19nrussell** [comment]
I think so playing on a world and seeing if it happens any?

**Comment by 19nrussell** [comment]
not had it any more

**Comment by capnkirok** [comment]
Ahh great news!
