### ISSUE TITLE
Suggestion: Easier Draft Horse Riding

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#209]
I'm not sure if I'm just not good at it or something, but I find riding the draft horses very difficult. I think that it would be easier if the riding mechanic for them was like riding vanilla horses instead of like riding pigs. I do like the riding crop idea for them to go faster though. Perhaps you could use the riding crop to make them speed up from walking to trotting to cantering to galloping etc? I don't know; just a thought I had while playing with them.

**Comment by capnkirok** [comment]
Yeah, it needs improvement. However, I really don't like vanilla horses either. Interesting idea about the different speeds. That sounds like a winner. Also need to improve jumping.

**Comment by capnkirok** [comment]
I assume you mean the controls... as in having to hold the riding crop (or not) to move or stop. Is that what you mean by difficult?

**Comment by RaliaTheWolf** [comment]
Yeah, I meant the controls. Sorry if all of that was a bit confusing!

**Comment by capnkirok** [comment]
Thanks for the feedback. Will continue to work on this :)

**Comment by RaliaTheWolf** [comment]
Awesome! Can't wait! :D

**Comment by darthvader45** [comment]
Yeah, was annoyed when I could control their direction, but not stop them at all.  Occasionally had a bug where when I dismount, I'm visually on the horse and cannot move.  Have to relog to actually get off.
