### ISSUE TITLE
Server RAM usage

### ISSUE THREAD

**Issue by Thyriel** [capnkirok/animania#21]
Not sure if this can really be improved but i noticed that Animania seems to use quite a lot RAM on a server compared with other mods.
I have ~40 mods running on my server and it usually used like 1-1,2GB RAM, sometimes up to 1,5. With Animania added it increased to 1,5-2,5GB. As i temporary had to removed Animania (client crash bug i reported yesterday) i watched the RAM usage closely and it went down again to it's usual load.
It's not a big issue but just thought i'd let you know in case you can do something about it somewhen. At least it doesn't seem to be a memory leak as it's never going above 2,5GB usage.

And it doesn't seem to be related to animal spawnings. As i'm working on a map where the mainworld consists of only one giant ice plains biome, there are not much (if any) animals being spawned there.

**Comment by capnkirok** [comment]
Thanks for the heads up. I'll take a look. I would assume it has to do with spawnings, since there is a ton of AI code in here. It would be good news if its not. 

In any case, I think some optimization is in order.

**Comment by capnkirok** [comment]
So far:
- Have optimized all textures, should save some overhead
- Gonna do some more investigation into spawnings/loops
