### ISSUE TITLE
Suggestion: Elephants & Snakes for the Dynamic Surroundings users

### ISSUE THREAD

**Issue by Seth0067** [capnkirok/animania#210]
The mod Dynamic Surroundings features vivid biome-based sfx - with notable elephant and snake effects in savannah and desert biomes.  

Not your problem to solve, but I desperately need to see some elephants and snakes so this makes some kind of sense!

**Comment by crakiMDH** [comment]
Well, there's always Animania 1.10.2 with Mo'Creatures.. That mod has those animals.

**Comment by Seth0067** [comment]
Of course - but using that mod is problematic in packs (at best).

**Comment by darthvader45** [comment]
Yeah, due to the fact you have to add another mod to control spawning, which is a real pain to finely tune to your tastes.  Especially with the trolls and ghosts.

**Comment by capnkirok** [comment]
Hey, I'm going to close this one. These are both added to our suggestions list, and snakes are on the to do list already. Trying to clean up git so it reflects bugs only. Thanks!
