### ISSUE TITLE
[Suggestion] tracking pairings + identifiers

### ISSUE THREAD

**Issue by Rambonata** [capnkirok/animania#212]
Is it possible to make either a tool that shows which animal is paired with the other? Or even a "dog collar" situation, where we can dye the color of something on the animal to identify them (cow bells, harness, ear tags, bird band... etc) just so it's easier to figure out who's who in a large pen.

**Comment by capnkirok** [comment]
In 1.11.2, if you install WAILA, it will tell you if your animal is mated. If you name your animal, it will also show you the mate's name :) (you have to press sneak to see this)

**Comment by Rambonata** [comment]
Drat. It's only in 1.11.2 . Figures. Thank you for the reply!

**Comment by capnkirok** [comment]
We'll eventually get it into 1.10

**Comment by capnkirok** [comment]
Closing this for now. It's on the todo list.
