### ISSUE TITLE
problems idk?

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#213]
I'm still getting the title issues
- but I also getting the pigs to go and eat they just sit there hungry 
-while the piglets will eat infinitely until u handfed them
-also are u soppused to infinitly milk a cow?
-also foals are still changing colors from foal to full grown 

in newest version of mod and 1.11.2 minecraft

**Comment by 19nrussell** [comment]
all are still having babies even tho the tiltle problems

**Comment by capnkirok** [comment]
- Was a bug in 1.11.2 foals color changing - fixed in next release

**Comment by 19nrussell** [comment]
No other  waila other than a couple of it's extensions and by infinitely milking I had 16 buckets and all of them  where filled
