### ISSUE TITLE
Angus bull missing horns

### ISSUE THREAD

**Issue by Skyshadow324** [capnkirok/animania#217]
My Angus bull is missing horns. The nose ring is there but no horns. Mod and Minecraft up to date.

**Comment by 19nrussell** [comment]
they took off the horns I believe

**Comment by capnkirok** [comment]
Angus Bulls are polled (meaning bred to have horns removed). 
![image](https://user-images.githubusercontent.com/9628379/27008637-19c1ada0-4e77-11e7-8871-0faff67becf5.png)

**Comment by capnkirok** [comment]
Kind of sad, but just keeping it real. The horns were removed after several other comments from players :)

**Comment by Skyshadow324** [comment]
Ahh ok. The pictures on curse still show horns so I was confused!! Thank you
