### ISSUE TITLE
Leads bug around

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#219]
ok so when u get killed (I was trying to reduce number of cattle) if any animals are on leads they start bugging out u relog it fixes it is this a animania problem or just leads in general
![2017-06-11_23 30 31](https://user-images.githubusercontent.com/28038939/27019425-1b11005c-4efe-11e7-9327-778895d999a6.png)

**Comment by Tschipp** [comment]
After some testing, I see that this is a problem of extra utilities. I'm gonna report it.
