### ISSUE TITLE
Bucket Dupe: Slop

### ISSUE THREAD

**Issue by Grayvs** [capnkirok/animania#22]
When crafting Slop you get a second separate bucket of Slop instead of giving you an empty bucket back.

**Comment by capnkirok** [comment]
Thanks! will fix!

**Comment by capnkirok** [comment]
Can you share with me a screenshot of your recipe and result? I can't reproduce.

**Comment by capnkirok** [comment]
Going to close this unless I hear back, cannot reproduce this one.

**Comment by JamRobLam** [comment]
can this be opened back up? 
i also found a bucket dupe however im not sure if the recipe is added by you guys or the pack designer.
im using Animania 1.0.4.7, mincraft 1.11.2, in the Modded Mischief II pack. 

https://drive.google.com/open?id=0B_GugIbytyFYYkYzRW5IdVVjNjQ

**Comment by Tschipp** [comment]
yeah, I'll look into it

**Comment by Tschipp** [comment]
Fixed in dev
