### ISSUE TITLE
White Chicken Eggs Turn into Feathers

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#221]
ok so I have no roosters so I can just collect eggs and when u right click nest to get eggs u get nothing?

**Comment by 19nrussell** [comment]
I think I'm getting feathers instead?

**Comment by Tschipp** [comment]
Chickens now shed feathers from time to time. Did you say you got feathers when collecting the eggs from the nests?

**Comment by 19nrussell** [comment]
Ya

**Comment by capnkirok** [comment]
i bet it's that new feather drop code

**Comment by capnkirok** [comment]
Yep, can confirm this is a bug. If a chicken is within 2 blocks of the nest, your egg will turn into a feather if you try to grab it. I will need to make a fix.

For now, would recommend you somehow distract your chickens when you take the eggs.

**Comment by capnkirok** [comment]
And thanks for the issue reports :)

**Comment by capnkirok** [comment]
Ok, this will be fixed in next release. Thanks again @19nrussell !

**Comment by 19nrussell** [comment]
Np ur the one that is creating this very cool mod and I'm absolutely loving it

**Comment by darthvader45** [comment]
Good to see.  Again, as I said on the bull aggro issue, keep up the good work guys!
