### ISSUE TITLE
Truffle soup crash

### ISSUE THREAD

**Issue by Kearthar** [capnkirok/animania#222]
https://pastebin.com/ar7ejagU
Here is the crashlog I got when I drank some truffle soup, caused instantaneous crashing

**Comment by Tschipp** [comment]
Thanks, shouls be easy enough to fix

**Comment by Tschipp** [comment]
I'm not able to recreate this. I've tried eating every food and nothing unusal happens. You are using an outdated version, but I don't think that's the cause of this, we haven't touched food in ages. Can you describe exactly what happened? Did you have any other status effects on yourself?

**Comment by Kearthar** [comment]
it was in the raxpack 2 using version 1.1.4 of animania me and another person had the issue

**Comment by capnkirok** [comment]
Ok after doing some searching, it looks like it could be a bug in AppleCore. Can you remove AppleCore and do a test? If so, can you post on their github? I see multiple references to this issue on the Interwebs.

**Comment by Tschipp** [comment]
Gonna close this next week if we don't hear back

**Comment by Kearthar** [comment]
Yeah it was apple core that caused it. I've been busy and haven't touched minecraft in a while

**Comment by capnkirok** [comment]
Thanks!
