### ISSUE TITLE
Disable Specific Items

### ISSUE THREAD

**Issue by seilexta** [capnkirok/animania#225]
Is it possible to disable some items?
like when i want to milk a cow it gives the vanilla milk instead animania milk
because we like it simple but still loving the new animals xD

**Comment by capnkirok** [comment]
You can exchange special milk with vanilla milk now. Guess we could add a config option. It would mean no cheese (or other dairy based products) would be available.

**Comment by capnkirok** [comment]
Spoke to the team about this one, and it would break a lot of things to do this, without much upside. Recommend you put any special milk into a crafting grid to get vanilla.  Any other items that are causing issues?

**Comment by seilexta** [comment]
i'm wondering about something that's quite dirty like
setting custom drop from milking, so we can set it both cows to be minecraft:milk_bucket
but yah aside from that there's no other issues, it only takes one extra storage anyway
the conversion via crafting is nice enough already
thanks !

**Comment by capnkirok** [comment]
Thanks for the flexibility. Going to close :)
