### ISSUE TITLE
[Animania-1.11.2-1.1.5] Leghorn Hens feather drop bug

### ISSUE THREAD

**Issue by kreezxil** [capnkirok/animania#226]
I came across a leghorn chicken and she was leaving a trail of feather stacks behind her. And when i got to her she was creating a pile. Killed her and picked up all the stacks she created. It completely filled my personal inventory.

**Comment by jzburda** [comment]
I can confirm this is an issue, though this may be a crossmod issue with Terraqueous and Animania

**Comment by capnkirok** [comment]
Sounds like a compat issue. For now, you can turn off 'ChickensDropFeathers' in the config (under Drops).

**Comment by kreezxil** [comment]
Thanks Will do that.

**Comment by capnkirok** [comment]
I can't even get Terraqueous to work. BUT, from what I read, it does look like it modifies something with Chickens. 

The way Animania works is that it replaces egg drops with feathers (1/3 chance to do so). I believe Terraqueous increases the laying of eggs ... to replicate the sound? (but removes the egg also). It looks like Animania is turning those fake layings into feathers.

Would recommend you stick to the config option for now. I'll post this to the Terraqueous github.

**Comment by capnkirok** [comment]
Also I've made our event at lowest Priority. Don't know if it will fix the bug, but it's worth a try.
