### ISSUE TITLE
Chickens doesn't drop raw_prime_chicken

### ISSUE THREAD

**Issue by seilexta** [capnkirok/animania#227]
the chicken doesn't drop raw_prime_chicken unlike cow / pig when the custom drop is set, they only able to drop minecraft:chicken item even though the rate is quite low

**Comment by capnkirok** [comment]
Which version of the mod and minecraft are you using, please :)

**Comment by seilexta** [comment]
ah sorry, it was Animania-1.11.2-1.1.5

**Comment by Tschipp** [comment]
@capnkirok I just looked at the code and saw that you didn't change the code to the new getItem method xD

**Comment by capnkirok** [comment]
Yup, my bad.

**Comment by capnkirok** [comment]
Fixed in next release.
