### ISSUE TITLE
Suggestions for dogs

### ISSUE THREAD

**Issue by darthvader45** [capnkirok/animania#228]
When you do add dogs, preferably would like to see three main breeds:

Old English Sheepdog: Great for herding sheep.  Big and fluffy.
[Sheepdog](http://cdn3-www.dogtime.com/assets/uploads/gallery/old-english-sheepdog-dog-breed-pictures/laying-4.jpg)

Border Collie:  Great for herding cattle, can keep them in line to allow for moving them long distances.
[Border Collie](http://pbs.twimg.com/media/CVZfK85U4AAy_bG.jpg:large)

English/American Foxhound:  Good for hunting, or as a companion.
[Foxhound](http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23006_american-foxhound-460x290.jpg)

**Comment by capnkirok** [comment]
Nice ones. We have a long list of dogs, but we're still a ways away.

**Comment by NoahNinja** [comment]
Maybe you could have mice that would steal food/water from troughs, and you could have cats to hunt them

**Comment by darthvader45** [comment]
Thanks.  Still have to get horses stable (pun intended)?

**Comment by capnkirok** [comment]
@NoahNinja thanks for the tip. We have a mouse waiting patiently to join the game.

**Comment by NoahNinja** [comment]
Cool!

**Comment by capnkirok** [comment]
Hey @darthvader45 this is on our suggestions list now. In an effort to clean up this git, I'm going to remove it so git only shows bugs.
