### ISSUE TITLE
Horse legs/ troughs

### ISSUE THREAD

**Issue by NoahNinja** [capnkirok/animania#230]
All of The new draft horses' front left legs are dropped down by a few pixels, ignore this part if is intended, troughs seem to have the block air of a ladder and can be climbed by walking into it

**Comment by capnkirok** [comment]
Thanks for posting! 

- Great eye on the Draft Horse Leg. Will fix.
- On the Trough, this is working as intended. If we didn't allow animals to walk over them, the 'eating' animation would occur next to the Trough, which is kind of weird. I agree it's not perfect.

**Comment by capnkirok** [comment]
Ok, the Horse Leg is fixed in dev, and will be in next release.
