### ISSUE TITLE
Sonic Achievement?

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#234]
I was looking at all of the different Animania achievements to see if I had them all and I saw the 'Gotta Go Fast!' and 'No Go Fastr!!!' achievements. Is the way to achieve them to name a hedgehog 'Sonic' and to throw a speed potion at them because I tried that and it didn't work... If that's not it then I apologize... >-< If that is how you do it then those achievements don't work...

**Comment by Tschipp** [comment]
It's not ;)

**Comment by capnkirok** [comment]
That second achievement is working just fine. I think many have just not discovered it yet.

**Comment by RaliaTheWolf** [comment]
Okay. I'll keep searching then!
