### ISSUE TITLE
Suggestion: Config for water drinking

### ISSUE THREAD

**Issue by Terpo** [capnkirok/animania#235]
I would really appreciate if you would add an option that animals don't remove water blocks from the world when drinking. When playing with a finite water mod it can be annoying to fill up the pig pools with fresh water.

**Comment by Tschipp** [comment]
If the gamerule mobGriefing is false, water won't be used up

**Comment by Terpo** [comment]
Thats true, but it affects a whole lot more than drinking animals ....

_Whether creepers, zombies, endermen, ghasts, withers, ender dragons, rabbits, sheep, and villagers should be able to change blocks and whether villagers, zombies, skeletons, and zombie pigmen can pick up items_

**Comment by capnkirok** [comment]
Yes, was going to say that. We can add a config.

**Comment by Terpo** [comment]
That would be awesome. Thanks :)

**Comment by capnkirok** [comment]
Sorry this didn't make it in. I just missed it. We'll get it in the 1.3.2 hotfix.

**Comment by capnkirok** [comment]
This is coming tonight with a bunch of 'water' changes.
