### ISSUE TITLE
hedgehogs on shoulder

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#236]
I tamed hedgehog and when u  go to put it on your shoulder u then rotate ur head and its kind of a weird motion different then hamster and ferret it like gets in your face

**Comment by 19nrussell** [comment]
![2017-06-23_00 58 00](https://user-images.githubusercontent.com/28038939/27468765-684a39cc-57b1-11e7-9cae-92c88a8ead7b.png)

**Comment by capnkirok** [comment]
Thanks, will take a look.

**Comment by capnkirok** [comment]
See how this works on 1.12 for you, @19nrussell

**Comment by capnkirok** [comment]
I'm closing this one now. We changed the way it works going forward in 1.12+ (so, fixed in 1.12 only)
