### ISSUE TITLE
[1.11.2-1.1.5] Feeding & Breeding or Yet Another Battle of the Mods

### ISSUE THREAD

**Issue by kreezxil** [capnkirok/animania#239]
One of my players tried to set up a cow far and discovered that they would starve to death. He also discovered that they won't bread with bulls from the Toroquest mod. 

I have two modpacks that have this combination of mods, Colonial Expansion and Colonial Exploration. Currently this has been reported my Colonial Exploration pack, it won't be long before it is reported in Colonial Expansion.

Comment from my player:

>I was having some problems with this modpack.  I had a bunch of cows around me so I decided to try to set up a **cow farm**.  Unfortunately I soon discovered that while the **cows were animania cows**, all the bulls were toroquest 'toros' which didn't seem to use the same AI.  In addition, the **animania cows were failing to eat or drink from the trough.  All they'd do is stand around being hungry and thirsty.**  There seems to be some problems there.  I couldn't breed cows if I wanted to and I can't really do anything with the cows I have except kill them (assuming the hordes of toros don't finish me off first)

Colonial Exploration Animania.cfg : https://gist.github.com/04520477013906d1b835dba12feb4229

see also: https://github.com/ToroCraft/ToroQuest/issues/163

**Comment by Tschipp** [comment]
@capnkirok I think we need improvement of the eating AI
@kreezxil They don't use the same AI, because our cows work with genetics. I'm not sure it would be possible to offer support, but we'll see

**Comment by capnkirok** [comment]
Yeah, my timers may be too far apart now. I've noticed the same. They almost look like they're too lazy to eat. Ha ha. Will look into it.

**Comment by capnkirok** [comment]
Please try again on the latest version. We've revamped all timers and AI.
