### ISSUE TITLE
Horse Suggestions & Other

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#240]
(been writing these for a while just have forgot to post them)
-steers ( un mate able males )
-males normally bred multiple females (bulls 5-15 depending on bulls age)
-ear tags (any animal)
-twins/triplets possibly (like a very rare chance)
-sleeping
-tranquilizer relates to the sleeping sorta
-silos/grain bins
-mice/rodents (when there is cats anyway)
-age like system possibly
-under certain age drink milk from bottle and or cow (dairy cows normally take and care of many calves )
-better fences sorta wood /metal post and plank fence or wire fence possibly even make it electric?
?maybe (I don't do modding so ) a more real like way of putting up fences.
-bull correct anatomy I mean there is they way to flag it thru config so maybe the 
 I have 2 questions (never asked ?)
_how des the mods do with chunk loading ?
_how laggy does this mod really do ?
![th](https://user-images.githubusercontent.com/28038939/27513557-48cbecbe-5930-11e7-8349-9a34bb4e9b45.jpg

**Comment by 19nrussell** [comment]
When it comes to carts they can be as creative or inventive as u want 
and pulled by horses or cattle this is what I saw the other day a an Amish
![img_5634](https://user-images.githubusercontent.com/28038939/27513584-2312aac0-5931-11e7-9051-f11974f6d13f.JPG)

![img_5633](https://user-images.githubusercontent.com/28038939/27513583-16136594-5931-11e7-9e2a-99e8d15f96f7.JPG)
this is an horse pulled fence post thingy it puts the post in the ground

**Comment by 19nrussell** [comment]
Just saying these are just suggestions I love the mod and none of these are real important
keep up the great work 
#the most awesome mod ever

**Comment by richardhendricks** [comment]
Draft horses definitely need jobs!

Pulling a plow - Hoes and collects/reseeds a large area, perhaps 3 or 5 wide.  Has its own inventory that you can fill with seeds. Has on/off states.

Leveling a road.  Fill cart with blocks, driving horse forward will cause it to fill holes and level ground. Maybe any land +-2 or 3 from where it starts.  OR make it automatically put in dirt stairs as it goes up/down? An option to replace all blocks directly underneath with carried input blocks (dug up blocks go in a different area in inventory) - So one could easily create pretty wide/long paths!

Turning a grinder wheel.  Similar to the Quartz Grindstone, except larger.  Has connections for up to 4 horses.  8 input/output slots, equivalent to a Pulverizer in terms of outputs, including secondaries.  Horses get tired, have to be swapped out/rested every other minecraft day.

Turing an RF power generator - Same as above, but outputs RF. 30 per horse seems fair, with 120 max.

Standard wagon(multiblock) - 3 wide by 5 long by 2 high, comes with lots of inventory slots. 

Conestoga wagon(multiblock) - Covered wagon, slightly less inventory than standard wagon, but has built in furnace and crafting station. Racks for tools and Harvestcraft cooking supplies would be excellent! Bed included! Perfect for long treks across land to explore for new biomes, instead on making ugly disposable huts along the way.

A way of attaching draft horses together, so you could have a road layer in front, then a conestoga, then a standard wagon, and other horses on leads.

**Comment by 19nrussell** [comment]
ok I'm not a mod creator so I think it would be cool for the grass to grow and instead of them eating the grass from the grass block like the grass on the dirt block

**Comment by NavyT** [comment]
Those are some good ideas.

**Comment by NeonWolfie** [comment]
Those sound ideas sound great!Hopefully they add it XD

**Comment by capnkirok** [comment]
Hey @19nrussell I've added this to our offline suggestions list. Going to close this one now in an effort so focus our git on bugs only. Thanks for all of the suggestions!
