### ISSUE TITLE
Config file sheep

### ISSUE THREAD

**Issue by ArtElleys** [capnkirok/animania#241]
# Remove vanilla sheep - there is no such line in the config file

To replace I take in my assembly cotton from another fashion, but sheep, they interfere, because they do not fit your fashion.

**Comment by Tschipp** [comment]
It might have come to your attention that there are currently no sheep implemented in the mod, so we would have nothing to replace them with. They are a top priority and we are working on them. Had you read the forum post to its entirety you would know that.
