### ISSUE TITLE
Suggestion: Allow animals to eat additional food from other mods

### ISSUE THREAD

**Issue by Beardedflea** [capnkirok/animania#244]
As the title says, would it be possible to add additional foods for animals to eat in this mod?

E.g a pig can eat a Pam's Harvestcraft tomato

Or better yet have it hardcoded and have a list of various food from other mods that can automatically be used within this mod.

**Comment by Tschipp** [comment]
The trough is already compatible with simple corn's corn, Pam's rye, barley, corn and all grains. I'm gonna add a config option to add your own food items

**Comment by Tschipp** [comment]
Added it. It's currently only for cows, you can configure what items should be able to be placed in the trough. The cows will eat anything. Pigs currently only eat slop.

**Comment by Tschipp** [comment]
Update: In the 1.3 Release, every animal that eats from the trough has its own list of foods that it can eat, all configurable
