### ISSUE TITLE
eating /drinking sortta (suggestion)

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#247]
I have been manually having to push them to get them to drink /eat is there a way they can be more interested in the trough 

also this is another thing of (suggestions) loving the mode yall are so awesome #240

**Comment by 19nrussell** [comment]
I do not think this is a bug but ill have them right at the trough and they just will do nothing

**Comment by Tschipp** [comment]
yeah, we are reworking AI, gonna close this
