### ISSUE TITLE
Hamster wheel 

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#248]
ok I tried putting tamed hamsters in it and they popped like they were going in and did not

tried 2 more last one went in and it changed color once in it

**Comment by Tschipp** [comment]
Lol I'm starting to wonder what's wrong with your pc xD Could Ou try getting it on video?

**Comment by 19nrussell** [comment]
ya me too my last one did some weird things turns out its hard drive was failing  this one I have not had even a year so?

**Comment by 19nrussell** [comment]
and I could not do it again I guess it was lag or idk minecraft glitchs ill close it
sorry it really did something and I just did not try any more from I was not really using them
