### ISSUE TITLE
[1.11.2, v1.2] Trough returns null for a capability

### ISSUE THREAD

**Issue by BluSunrize** [capnkirok/animania#249]
A critical error someone encountered when trying to use IE's fluid pipes on the bottom of a Trough:

https://github.com/BluSunrize/ImmersiveEngineering/issues/2249
[crash-2017-06-29_13.06.00-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1113113/crash-2017-06-29_13.06.00-client.txt)

From debugging a little on my side, the issue seems to stem from Troughs returning true on `hasCapability(CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY, side)` and then returning null for `getCapability(CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY, side)`. That's against Forge's convention, the return must not be null if the check returned true.

As there isn't any visible source, I can't pinpoint this issue further.

**Comment by Tschipp** [comment]
Yeah sorry, on it
