### ISSUE TITLE
[Suggestion] Make Vanilla meats craftable

### ISSUE THREAD

**Issue by Partonetrain** [capnkirok/animania#25]
In order to support mods that require vanilla meats in their recipes, I suggest you make a recipe that turns Animania meat into vanilla meat. Enable/disable-able via config, of course.

**Comment by capnkirok** [comment]
That's an easy suggestion to implement, thanks.

You can get vanilla meats from some animals (e.g., Yorkshire pigs, Friesian cows, Leghorn chickens), but I think this probably makes sense.

**Comment by capnkirok** [comment]
Ok, this is added in 1.0
