### ISSUE TITLE
Pets won't stay!

### ISSUE THREAD

**Issue by mossylungs** [capnkirok/animania#250]
Great mod, honestly GREAT MOD. The models are so amazingly done and freaking adorable, however I can't get my hamsters, hedgehog (damn you Sanic!!!) to stay in one spot. If I tp anywhere they will appear there, and a lot of the time they will randomly go from sitting to free-roam and it's gotten hard to keep them in one place. May I suggest some sort of pet cage? Something we could put the hamsters and ferrets and hedgehogs in without worrying they will disappear or run off?!?

**Comment by 19nrussell** [comment]
ya i have aslo had a hard time at my base having to look a while I think pet cages would be a good thing espically if more smaller  animals are added.

**Comment by Tschipp** [comment]
Pet cages are planned, but the teleporting sounds weird. Are they teleporting event when sitting?

**Comment by mossylungs** [comment]
Yes they are teleporting even when sitting. My house has a lot of tp command blocks that lead to other places and every time I /tp out both my hamsters and my hedgehog will go with me and are suddenly not in the sitting position

**Comment by capnkirok** [comment]
Definitely not intentional. Well, it's actually default vanilla minecraft behavior for tamed animals. So I'll find a way around it.

**Comment by capnkirok** [comment]
Yeah, this is now working in 1.3
