### ISSUE TITLE
Game lags upon spawning Animania mobs initially

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#251]
Unfortunately, this is all I can get, aside from the fact that upon spawning, your mobs seem to lag a bit at first.

**Comment by Tschipp** [comment]
What are yor pc specs and how much ram do you have allocated to minecraft?

**Comment by Sunconure11** [comment]
Around 6 gigs of RAM allocated to MC. I'll post more of my specs later, but I have 24 gigs of RAM, for starters.

**Comment by capnkirok** [comment]
Can you elaborate on lag? Do you mean the mobs take a while before they start executing their AI? Or do you mean, your server takes a performance hit when a mob is spawned?

**Comment by Sunconure11** [comment]
Currently, singleplayer, but yeah, when a mob is spawned at first, there is a noticeable FPS lagspike.

**Comment by Sunconure11** [comment]
Any news regarding this? The biggest offenders here are horses, in terms of lag.

**Comment by capnkirok** [comment]
I know that at spawning, all of the AI starts up (which is significant, could probably be optimized more), but I still don't see a noticeable spike. I can spawn a hundred mobs without seeing degradation.

Can you post your modlist again? I wonder if this is a compat issue?

Also, can you try in single player mode without any other mods? Let me know if you still see it.

**Comment by Sunconure11** [comment]
http://www.modlister.com/user/Sunconure11

**Comment by capnkirok** [comment]
AI has been optimized considerably for the 1.3 release. Seems to be running much faster and seeing less of a spike on spawning. Hope this does the trick.
