### ISSUE TITLE
Pig texture glitch caused by weather

### ISSUE THREAD

**Issue by nlcraft4life** [capnkirok/animania#252]
Pigs like to stay in the mud... There texture changes when they are laying in mud. But the rain wipes that texture off of them. What happens is: when they lay in the mud. There is an infinate loop between texture changes. Which looks pretty glitchy.

Adding that the texture of the mud wont change when they are in laying position will most definitely fix this issue.

**Comment by capnkirok** [comment]
Ooh good catch. Yes, I know how to fix this :)

**Comment by aelfwyne** [comment]
Wonder if this has anything to do with the recent occurrence of duplicate ID's I'm getting on the pig textures... I didn't get it with older versions, only after I upgraded.

**Comment by capnkirok** [comment]
@aelfwyne was not duplicate IDs. Was a coding issue for sure.
