### ISSUE TITLE
Breeding Suggestion

### ISSUE THREAD

**Issue by Kyrislian** [capnkirok/animania#253]
Absolutely loving this mod! Just added it to my server a few days ago and all my players are adoring it. Thanks so much for your hard work!

Would like to leave some feedback on the breeding aspect though :D 

Currently reflecting on what's happening with the horses, right now it seems that after the mares are mated even after separating them from the stallions as long as they're well fed they continue to produce foals. This is somewhat troublesome when you have a horse farm going and you end up getting endless supplies of horses XD (Feeling somewhat bad to keep culling them!)

May I suggest making it so that after every time the mares (and other animals by extension) produce offspring, they'll need to interact with the stallion again to produce another child? Sorta like how it's done in vanilla. 

Also perhaps lessen the block radius required for the stallions to be close to the mares? 20 seems really huge; I've got my pens pretty far apart and they still keep producing babies XD

ETA: Also! Just remembered. Would it be possible to add the gender of the animal to the WAILA tooltip? Sometimes it's kinda hard to figure out, esp when it comes to the pigs haha.

**Comment by 19nrussell** [comment]
ya I this is a good suggestion to the breeding thing I mean maybe it could be that the females be bred by the male and then the male then does not stay ,this also would go along with the male breeding multiple females.so basically if the male is not like in same pen as them the mare does not get bred and cannot have young  so if u don't know anymore the male could be removed ,another thing that could help in this is a way to steer or geld males (fix males to non breeding males)(by breeding females I would mean like 1 to 2 blocks like touching the females)
