### ISSUE TITLE
Cow lagging (TPS 3~5)

### ISSUE THREAD

**Issue by Eufranio** [capnkirok/animania#254]
Recently Animania cows started lagging my server, even with a few or no players at all in the server. I took this WarmRoast report from the server when it's lagging:

[WarmRoastReport.zip](https://github.com/capnkirok/animania/files/1120846/WarmRoastReport.zip)

As you can see, Animania is taking almost a half of the server tick time. The root method that is taking longer to proccess is `com.animania.common.entities.cows.ai.EntityAIFollowMateCows.shouldExecute()`, it could be either **a lot** of calls to this method, or the method itself taking too long to proccess. Restarting the server fixes the issue, but it will still lag later.

If you need any other info, please let me know.

**Comment by capnkirok** [comment]
Hey @Eufranio , thanks for this. From the code structure in Warm Roast, it looks like you are on the 1.11.2 version. Can you tell me approximately how many cows you have right now? And also how many are bulls? That will help in my testing.

**Comment by Eufranio** [comment]
How can I get that info? I'm not sure how many cows/bulls are loaded tbh.

**Comment by capnkirok** [comment]
Just an approximation, if you can. Are we talking 5, 20, 100 cows?

**Comment by Eufranio** [comment]
About 30~50, and most cows than bulls (only the spawn was loaded when I took this sample). 

Note that this does NOT happens when the server restarted recently. It took some hours to start lagging, 8+ tbh.

**Comment by Tschipp** [comment]
@capnkirok I'm guessing the mated AI goes through every entity that is loaded? I reckon that would cause some major lag. We could make it only go through entities in a certain range, like 30 blocks. I have methods for this in my library, I can bring some over.

**Comment by capnkirok** [comment]
Yes, this is fixed in 1.3 release 👯

**Comment by capnkirok** [comment]
Completely overhauled the AI for efficiency, works so much better :)
