### ISSUE TITLE
Peafowl eggs not hatching, but spawning

### ISSUE THREAD

**Issue by Rambonata** [capnkirok/animania#255]
So uh... the egg in the nest doesn't hatches (disappears) when a chick is spawned, causing quite a overrun nesting area.

**Comment by Rambonata** [comment]
To specify, I'm on the latest 1.11.2 version, and I have an albino female, and a normal male.

**Comment by capnkirok** [comment]
Cheers, this is helpful :)

**Comment by Rambonata** [comment]
I have also tested by removing the female from the pen after she laid an egg. The egg doesn't disappear at all and will spawn multiples as long as male is happy.

**Comment by capnkirok** [comment]
Yep, it was a bug. Fixed now.
