### ISSUE TITLE
Incompatibility with Sound Physics

### ISSUE THREAD

**Issue by WesCook** [capnkirok/animania#256]
Animania is currently crashing alongside SoundPhysics due to pesky EntityAmphibians.

Steps to reproduce:
1. Install the latest 1.10 version of Animania and SoundPhysics
2. Spawn a Frog or Tree Frog
3. Wait a moment, and the game should crash

(Alternatively, there may be a frog nearby on spawn to crash you anyways)

Crashlog: https://pastebin.com/FiPBFMDg

Forge v12.18.3.2316
Minecraft v1.10.2

Bug on SoundPhysics tracker: https://github.com/sonicether/Sound-Physics/issues/2
Bug on modpack tracker: https://github.com/WesCook/Homestead/issues/4

**Comment by capnkirok** [comment]
Well, it's crashing trying to play a Jump Sound. Funny thing is.. there is no Jump Sound :)

**Comment by WesCook** [comment]
Well that might do it.

Nice work.  :)
