### ISSUE TITLE
OreDictionary Recipes Using Dyes

### ISSUE THREAD

**Issue by Darkosto** [capnkirok/animania#257]
Hello!

Could you please consider making all your recipes that require vanilla dye items to use oredictionary instead? Thank you!

Darkosto

**Comment by Tschipp** [comment]
On it, I'm guessing you're primarily talking about the hamster balls

**Comment by capnkirok** [comment]
Yes, that's the only recipe that's not using OreDictionary (copied straight from Hamsterrific, go figure).
