### ISSUE TITLE
Potential DataWatcher problem

### ISSUE THREAD

**Issue by Mailleweaver** [capnkirok/animania#259]
I'm no developer or coder, so please take this as just a request for review rather than an assumption of something wrong in your mod.

A recent modpack update for the Colonial Expansion pack has brought up some client-side crashes that seemed to point to Roots2. After review, the Roots2 author thinks it's a different mod changing something in the DataWatcher that's causing conflicts between the server and client rather than something in Roots2 and pointed me to an explanation where it came up elsewhere with other mods.
https://github.com/RootsTeam/Roots/issues/234
https://github.com/Vazkii/Botania/issues/2114

After making a list of all the mods that were updated when the crashes started, doing searches to the best of my limited ability through the open-source mods on the list, and reviewing changelogs for the rest, Animania (updating from 1.1.5 to 1.2) seems to me the most likely to be the offender. Would you mind looking into it to see if there's something recently added in Animania similar to what the Draconic Evolution team found in their mod?
https://github.com/brandon3055/Draconic-Evolution/issues/545

**Comment by capnkirok** [comment]
I'll check to see if we use Data Watcher (we might be).

**Comment by capnkirok** [comment]
We don't use DataWatcher... but the problem Asie calls out has to do with EntityDataManager, which we do use. I am not entirely sure if we are causing an issue, however. Have reached out to Asie for more insight.

**Comment by capnkirok** [comment]
Ok, heard back. We'll definitely have to make a change.

**Comment by Mailleweaver** [comment]
Thanks for looking into this. It's much appreciated. :)

**Comment by Tschipp** [comment]
Thank you for the detailed information. It really looks like we registered the DataManager to the wrong entity at two instances, fixed now.
