### ISSUE TITLE
Hamster Missing Texture

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#266]
I had updated my Animania mod to the latest version and I went into a world where I had all of the hamster colors. I noticed that one of them has the missing texture, and it is the black hamster. Was the black hamster removed for some reason or is this a bug? I'm in 1.10.2 if that helps.
Here's the hamster:
![2017-07-10_11 07 23](https://user-images.githubusercontent.com/28816115/28027881-5399837c-6560-11e7-9b96-80efef3efea6.png)
Edit: I was able to spawn in one with the correct texture.

**Comment by Tschipp** [comment]
Looks like a one-time bug, I don't know what could have caused it. I suggest you just replace your hamster if you have access to cheats

**Comment by RaliaTheWolf** [comment]
Okay will do. Thanks!

**Comment by capnkirok** [comment]
Actually, this is a bug for anyone who upgrades (my bad).

**Comment by capnkirok** [comment]
Ok, this is fixed
