### ISSUE TITLE
Calf ears

### ISSUE THREAD

**Issue by Rambonata** [capnkirok/animania#267]
So it appears that the model has a small issue where the ears aren't set symmetrically on the head of the calf. Best viewed in this screenshot. http://imgur.com/n6nis9i  I'm assuming this wasn't done intentionally.

**Comment by Tschipp** [comment]
Strange. Not sure if this is intentional. I will double check the models to make sure. Is it like this for every calf?

**Comment by Rambonata** [comment]
I originally noticed it on a different type of calf, but since it refused to sit quietly i had to screenshot the one calf that was still.

**Comment by capnkirok** [comment]
But it's kind of cute in a way..

**Comment by capnkirok** [comment]
Ok, this is now fixed and will be in next release. Good eye!
