### ISSUE TITLE
Load Chunk with animal Animania drop tps and overload ticktime Server

### ISSUE THREAD

**Issue by roulito** [capnkirok/animania#268]
Version animania : animania-1.11.2-1.2.jar

Description Problem : 

The farm animania loaded by the player or during the generation of animania animated animals map cruelly drop the TPS and mounted the charge of the ticktime until arriving at a point of no return.

Temporarily solved by massively killing animal animania: /

Complement : 

Several mod in the console this complains Animania animals during the generation (ReccurentComplex, FastLeaf)

Server thread/WARN [FML]: Fast Leaf Decay loaded a new chunk (43, -89  Dimension: 6) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Or 
 [Server] Server thread/WARN [FML]: Aroma1997sDimension loaded a new chunk (-1, 0  Dimension: 6) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Or

[Server] Server thread/WARN [FML]: Recurrent Complex loaded a new chunk (-2, -38  Dimension: 6) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Other Bug : 

[Server] Server thread/WARN Keeping entity animania:textures/entity/chickens/hen_white.png that already exists with UUID b3597a8f-a4dc-4c6a-b696-edc0ece594053

Modpack : HippyCraft (Curse)

**Comment by capnkirok** [comment]
Animania limits the amount of spawns in a certain area, so there should not be too many animals in any chunk. How many animals are we talking about?

The ServerThreads and warnings you posted about cascading worldgen have nothing to do with Animania, as it does not create structures, nor does it target the edges of chunks for spawns, which is the source of this issue. These bugs should be reported to the mod authors. This would indeed cause massive lag.

The 'other bug' you mention is not a bug, just info that the world kept an entity at reboot.

Recommend you update to the latest version also.

**Comment by VallenFrostweaver** [comment]
The 'other bug' that is only a notification like this:

[Server] Server thread/WARN Keeping entity animania:textures/entity/chickens/hen_white.png that already exists with UUID 684589a9-de42-43a0-a36e-e7fa91824e58)

Seems to happen every few minutes and not just after the reboot.  Is that normal? Some are the same entity but there are others too.

**Comment by darknat** [comment]
Up, I have a same probleme, i have change my map and since, I have this sentence in my log : 

`keeping entity animania.HenLeghorn that already exisye with UUID ....`

I think, if config of spawn mob is disable, the problem dissapear, but how disable spawn mob animania ?

**Comment by darknat** [comment]
up

**Comment by capnkirok** [comment]
@darknat let me know what happens with the 1.3 update
