### ISSUE TITLE
Invisible Draft Horses

### ISSUE THREAD

**Issue by grumplease** [capnkirok/animania#269]
Noticed after downloading the update that I have draft horses who have turned invisible..

They still leave a shadow on the ground and name tags appear above where their model would be.

![2017-07-11_16 53 55](https://user-images.githubusercontent.com/30095148/28095852-a358e41c-6659-11e7-97fe-5a2499f8255a.png)

Upon accidentally hitting one my entire screen tinted red and stayed that way until I fully closed the game and restarted the launcher. Exiting out of the server and coming back didn't get rid of the red screen.

![2017-07-11_16 31 33](https://user-images.githubusercontent.com/30095148/28095888-d41ed660-6659-11e7-9faf-566d085c8144.png)

**Comment by Tschipp** [comment]
We've seen this happen before, unfortunately I don't think there's anything we can do about this. I suggest you kill the horse.

**Comment by capnkirok** [comment]
Well, there is a fix. I'll put it in the next update. But for now... if you kill the horse, it will turn your screen red. This can be fixed by killing another mob (any mob) or completely restarting the launcher...  really bizarre.

**Comment by capnkirok** [comment]
And that's a great name for a horse by the way :)

**Comment by capnkirok** [comment]
Ok, this is fixed in dev environment, and will be in the next update. You would think MC would just render purple/black if it couldn't find the right texture... but hey.

**Comment by grumplease** [comment]
Yeah we went ahead and killed the horses bc we kept accidentally smacking one of them and it would give the red screen to everyone nearby. Didn't think to try killing other mobs though :o

Thanks for the update!
