### ISSUE TITLE
Separated hens and roosters can breed through the separating fences. (1.10.2 version)

### ISSUE THREAD

**Issue by katubug** [capnkirok/animania#270]
I was hoping that by keeping them separated I could prevent them from breeding unless I wanted them to, to keep the population under control. But apparently that doesn't make a difference, and the eggs hatch so fast that I can barely keep up with them!

I'd love it if it was easier to "opt out" of breeding.

**Comment by Tschipp** [comment]
We will rework AI soon, some changes to breeding will be made

**Comment by katubug** [comment]
Awesome, glad to hear it! Right now it's a little frustrating to be flooded with chickens and milk cows (especially the cows...god forbid you try to cull the herd by killing one of the bulls...). I love the mod overall though, thank you for all the work you're putting in on it!

**Comment by capnkirok** [comment]
- Yeah, the code uses a 'Proximity' check for breeding/hatching, which is 5-8 blocks, depending on the species. You'll have to set them further apart right now to keep this from happening. 
- The bulls should be easier to 'cull' now (made a change a few updates ago that makes them slower and weaker)
- @Tschipp is correct, we are reworking this. Will leave this open.

**Comment by katubug** [comment]
Not sure if I should make a new issue for this - are animals (in this case, cows) intended to breed even when not fed? I have been off the server for a day or two doing IRL stuff and my servermates are complaining about the cows overflowing their pens. Even though no one has been there to feed them, they're breeding constantly as long as the chunks are loaded. I'm assuming this probably included in your AI breeding tweaks, but I thought I'd mention it just in case. :)

Thank you for all your hard work!

**Comment by capnkirok** [comment]
@katubug let me know how you like the 1.3 updates, there are now several ways to control breeding.
