### ISSUE TITLE
[Question] What's with the CraftStudio requirement?

### ISSUE THREAD

**Issue by darthvader45** [capnkirok/animania#271]
Just noticed that Animania now requires CraftStudio.  Why?  Does it have something needed for mob animations, etc.?

**Comment by Tschipp** [comment]
Yes. The 1.11.2 version will from now on need the CraftStudio api. We currently only use it for Hamster Wheels, but Peacocks and much more will follow.

**Comment by babyvamp123** [comment]
The real question is how do you use craftstudio does it  just go in your mods folder with everything else or is there more to it?

**Comment by capnkirok** [comment]
It acts like a mod, so it just goes into the mods folder :)

**Comment by darthvader45** [comment]
Ok, that's good.  Peacocks for the tail feathers opening and closing, right?

**Comment by capnkirok** [comment]
Yes, also that (when it is ready), and for a lot more animals and objects in the future.
