### ISSUE TITLE
translation to korean

### ISSUE THREAD

**Issue by SkyBluer** [capnkirok/animania#273]
[ko_KR.zip](https://github.com/capnkirok/animania/files/1145656/ko_KR.zip)

it's done. I checked it twice, so probably there's no error i think..

**Comment by Tschipp** [comment]
Cool, can you open a PR?

**Comment by SkyBluer** [comment]
i wonder do it well..  anyway i did it.

**Comment by capnkirok** [comment]
Thank you!

**Comment by capnkirok** [comment]
Closing this as it's already in the build.
