### ISSUE TITLE
(1.11.2) Cow AI stops working with Steam Engines Mod installed

### ISSUE THREAD

**Issue by bloodystump** [capnkirok/animania#274]
Your cows don't move, eat, drink ,swim or react to being attacked when Steam Engines Mod (https://minecraft.curseforge.com/projects/steam-engines-mod) is installed. I haven't checked all the animals but your pigs and chickens work fine with it.

I ran a 1.11.2 profile with just Animania, Craft Studio API and Steam Engine Mod to test this.
I don't know if the issue lies with Steam Engines Mod or Animania but i thought i'd let you know.

**Comment by captcookie** [comment]
this happens in my modpack too. cows make grumpy noises but do not move or interact and stay hungry and thirsty.

**Comment by capnkirok** [comment]
Very strange. Will take a look.

**Comment by bloodystump** [comment]
The Steam Engines Mod dev has fixed this on their end. Cows are cowing great now with both mods installed.

**Comment by bloodystump** [comment]
Reopening as i don't know if captcookie's issue was resolved.

**Comment by capnkirok** [comment]
@captcookie let me know what your modpack is, so I can see if there's a conflict....
