### ISSUE TITLE
[Question] How to Change Back to Individual Meats?

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#277]
I was wondering how I could change back to the individual meats rather than use the prime meats? I know it's in the config, but I don't know what to change...

**Comment by capnkirok** [comment]
Hey @RaliaTheWolf 

In the config, under the 'drops' category, set the value 'Enable Animal Drops from Config' to False.

**Comment by RaliaTheWolf** [comment]
Oh alright! Thanks!

**Comment by capnkirok** [comment]
Also needs to be fixed in 1.11.2

**Comment by capnkirok** [comment]
Ok, fixed this in 1.11.2

In 1.11.2, the title of the field in the config is CustomMobDrops... set that to false.
