### ISSUE TITLE
Custom NPCs Trading Eggs

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#278]
I set up a little trading system in a village I found with Custom NPCs. I was trying to sell peacock eggs to a NPC, but it took my brown chicken eggs instead. It then took my white chicken eggs and then my peacock eggs. I'm not sure if this is intentional or not, but it's kinda handy so I don't need to set up four different trades for the eggs!

**Comment by Tschipp** [comment]
Interesting! My guess is that customnpc's uses oredictionary values for trades. All the eggs share the same oredict value.

**Comment by RaliaTheWolf** [comment]
Oh that makes sense. Thanks for giving an explanation!

**Comment by capnkirok** [comment]
Yep, this is behaving correctly. OreDictionary is a good thing :)
