### ISSUE TITLE
Current Worlds

### ISSUE THREAD

**Issue by jprocket45** [capnkirok/animania#28]
This is a major issue for anybody adding this mod to a current map if alot of world is explored no pigs or cows will spawn at all i have explored my server map on a single player ( thankfully ) and there are only Wolves,Rabbits and sheep that has been seen there is no sign of anything like Pigs,Cows or anything else from the mod actually. I am not even seeing them in new chunks at the moment will report back if I end up finding them...

Animania 1.0.0 Release
Forge 2239

**Comment by jprocket45** [comment]
update after going a couple thousand blocks out I have found some, ( new chunks ) so basically from what im seeing is any chunks that where loaded before adding this mod 1. removes the vanilla animals 2. does not spawn any animals from the mod. more testing but this is by far what im seeing so far.

**Comment by capnkirok** [comment]
This one is terrible. I will try to get an update out in the next two days. Sadly, I didn't test spawning in existing worlds. I made a wrong assumption about how worlds loaded again. Bad Cow.

So, to recap, for an existing world:
- Old chunks don't spawn any Animania animals
- Old chunks also don't spawn the vanilla animals that were there (should only affect cows, pigs, chickens)
- New chunks work

I know how to fix this, but want to find the best solution. In the meantime, would avoid using it in existing worlds unless you've just started out.

**Comment by Thyriel** [comment]
Hmm this is strange. I am using 1.0 animania on a server i'm working on the map since months. As i'm using journey map too i can for sure say that there is not a single chunk that hasn't been loaded before (limited world border) but i have animania animals running around everywhere.

Maybe you're using another mod that changes spawning ? (e.g. something that adds mobs or changes mob behavior)

**Comment by jprocket45** [comment]
id say its a bug unless RTG changes things but from my understanding it does not..... on this note Ive seen a couple people say this but this caught my eye for some reason and I thought the person saying it on curse was wrong then I started testing more and well indeed it tends to be a issue.... I am using RTG but I highly doubt that would cause the issue since its allowing them in new chunks though I am not a coder..capn said they thought it was a bug due to assumption on worlds loaded I am not blaming capnkirok either ill try to look into this more myself as well.

**Comment by jprocket45** [comment]
update....... after pregen of a regular world with no mods besides JEI Waila journeymap installed I pregened the world then added the mod same issues Thyriel must be having some vodoo magic happening from what i can see.

**Comment by capnkirok** [comment]
Hey guys, really appreciate the research efforts here! I'm going to mess around with a couple of different options. I want the animals to spawn in families anyway (and not in gender cohorts), so will try to solve two issues at once.

**Comment by jprocket45** [comment]
I love the idea of them spawning in families as well hopefully it all gets worked out very soon can't wait to add this!! 👍

**Comment by brblostmycrayons** [comment]
hi! the person who hosts the server i play on said he enabled vanilla mob spawning in the configs since we discovered that none of the mod animals were spawning in our world but they didn't show up naturally either or with spawn egg (it'd make the sound when they 'spawn' but they would never appear). i don't mind no vanilla farm animals but i think he was trying to enable them since the new ones weren't spawning either and he hoped that'd fix it until something can be figured out. just wanted to confirm that they don't spawn in previously generated worlds! 

really looking forward to a fix to see the new animals, though! hopefully soon! and super excited for the future additions, especially foxes and chinchillas ^^!

**Comment by Greylocke** [comment]
Just to add another quirk to this -- I added Animania to my existing world, then I removed Animania, and all the previous farm animals were back exactly where they were pre-Animania. As if they had always been there.

**Comment by capnkirok** [comment]
I was just going to test that, so very helpful. Glad your world didn't get messed up permanently. I'm pretty close to a solution, hopefully roll out a new build in the next day or so.

**Comment by Thyriel** [comment]
Does this solution mean you do not use the vanilla minecraft spawning mechanics and wrote your own ?
If yes please be carefull, i have seen too much mob-adding mods that totally gimped their spawn mechanics (like ignoring light levels, ignoring server gamerules, spawning in insane numbers, not working in custombiomes, etc.) Seemed to me that writing own spawn mechanics is a very complicated thing with a lot of side-effects

**Comment by Thyriel** [comment]
@Greylocke: I think that is normal modding behavior. At least it is the same when you add a mod, place blocks from it, remove the mod and later add the mod again. While that blocks will be air after removing the mod, they will be back when you add it again.

**Comment by jprocket45** [comment]
im gonna assume if you are coding spawning mechanics different your partner  that works at mojang could get some insight on how to code it differently since she works there haha  :) or I could be totally wrong I feel though this mod is going to be really good I new there would be bugs but this one as we have said is crazy still hoping to see a fix and release soon! Thanks for all the hard work and dedication your putting into this mod!

**Comment by capnkirok** [comment]
Rest easy, people. I am not re-doing spawning mechanics, just changing the events used to activate them.

For you modding nerds out there, do not use OnEntityJoinWorld to handle your spawning/spawn blocking. It will result in this thread XD.

Instead use WorldEvent.PotentialSpawns to handle spawns before they happen.

**Comment by Greylocke** [comment]
lessons were learned.
Thanks for your work on this!

**Comment by jprocket45** [comment]
Greylocke is correct any update on this? I am just curious I can wait with no problem on a update was just more curious than anything lol

**Comment by capnkirok** [comment]
Update coming in about 4 hours. Hold on to your... uh... cows.

**Comment by jprocket45** [comment]
👍

**Comment by capnkirok** [comment]
Just a heads up. To make it playable, a temporary solution is going to be to replace any spawned vanilla animal with its Animania equivalent, so pigs = Yorkshire Pig, cows = Friesian Cows, chickens = Leghorns. If they are in an appropriate biome, other animal breeds may spawn. Random gender/age will be assigned. This will work for vanilla spawn eggs too.  But to get all of them, players will have to venture to new chunks to find other breeds (for now). At least you will be able to use the mod :)

Long term solution (after conferring with the modding illuminati) is to create a tracking system that tracks chunks that have already been 'animania spawned' and trigger new spawning if not on the list. This is not a quick bit of code, so be patient. I think it's worth it.

**Comment by jprocket45** [comment]
like I said Im patient that will work for now I know its a work in progress it just wasn't really easily playable but sounds like it will be playable after the update :)

**Comment by Greylocke** [comment]
so essentially, you'd be retrogen'g like a mod that adds ores. kewl!

**Comment by capnkirok** [comment]
correct! fun!

**Comment by capnkirok** [comment]
Ok, the temporary fix is up. Let me know how it goes. Leaving this open for now.

**Comment by jprocket45** [comment]
ok so this seems to be working pretty well Id like to say from what I can if others feel the same I think it maybe time to close this :P

**Comment by Greylocke** [comment]
in a preAnimania world, I created pens for 4 each of adult vanilla cow, pig, chicken. I then shutdown the world, added Animania and restarted the world. When I logged in, there was a horrible animal love orgy noise and hearts were swarming like mosquitos in August.

When it was all done, I had 1 male, 1 female cow, and three calves (5 in all), 2 pigs and 1 piglet (3 pigs total), and 3 chicken with one chick (4 chickens total). So I actually lost one pig in the conversion, but it might have gotten pushed into a wall and suffocated. But overall I'd say this now works.

**Comment by Thyriel** [comment]
Definitly working ;) But may a bit too much spawning now. We had on a small skyblock island within half an hour like 10 chickens, 5 cows and 5 pigs. In vanilla animal spawning on a pretty small grass area takes a very long time compared to that

**Comment by capnkirok** [comment]
Lol! Yes, I think I introduced a nasty bug. So sorry. Looking into it now...

**Comment by capnkirok** [comment]
Yeah, it looks like this is affecting pre-existing worlds. Effectively, what's happening is that vanilla retro mobs are continuing to try to re-spawn after server restart, and then get converted into Animania mobs... effectively doubling every time. Fix coming shortly :/

**Comment by capnkirok** [comment]
Ok 1.0.1a is now up. I guess this is a new feature in 1.10.2 where every potential spawn is now cached on the server... ok, let's try this again: version 1.0.1a

**Comment by jprocket45** [comment]
I am getting crashes all over now on update :(       here is one       http://pastebin.com/97grckk4

**Comment by jprocket45** [comment]
im not sure if its just me but loading up my server with the new 1.0.1a update seems like I am getting waaaaaay to many together in a group its lagging my server with how many there are is anybody else noticing this?

**Comment by capnkirok** [comment]
Hey jprocket45. I thought this was fixed in 1.0.1a, so wondering what is happening. I may have to rethink what we've done here (again), and do more scenario testing on servers.

**Comment by jprocket45** [comment]
I still feel this has to deal with a preexisting world with chunks loaded.... on that note I would be glad to offer up my server to show you what I am talking about in any way possibly id love to help you get this mod as sturdy as can be!! up to you just a offer the 1.0.1a when i install it causes major lag and when im loading it takes a bit to load the world and its realy really laggy I will be testing some more in just a few, just so you know its not a small server I am just a 5 cores and 5 gigs of Ram and im only using half RAM and hardly any CPU and this is all going on.

**Comment by capnkirok** [comment]
Thanks jprocket45. Ok, good. Well, I did suspect that they extra chickens were from 1.0.1... glad the lag is gone, but the skipping ticks is not good. Can you share with me your modlist? Screenshot is fine.

**Comment by capnkirok** [comment]
jprocket45 some Questions

- What is your FPS? 
- Do you only have skipping ticks when regenning vanilla areas?... or is it everywhere (does it continue after several minutes)
- Follow me on Twitter and then we can chat there. Maybe I can come on your server and check it out. Thanks for the offer!

**Comment by jprocket45** [comment]
first off mod pack ive been running this on a server for awhile with no issues :)     https://minecraft.curseforge.com/projects/buildtime

**Comment by jprocket45** [comment]
alright 2nd lets get these questions answered  lol           FPS runs 60 most of time maybe 56 once in awhile      the ticks I honestly don't notice when playing on the server maybe once in a great while but the server has 5 gigs of ram and 5 cores im using on the processor all in all should be really good for just about anything. The server shows the ticks happening constant though, also I am following you on twitter jprocket45  is the name haha and hey if you feel it will help you out in any way you are welcome to use my server or join im. here is my latest console logs so far                                        12:24:43  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 2377ms behind, skipping 47 tick(s)
12:25:17  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 2332ms behind, skipping 46 tick(s)
12:25:35  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 3159ms behind, skipping 63 tick(s)
12:26:05  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 2505ms behind, skipping 50 tick(s)
12:26:21  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 3630ms behind, skipping 72 tick(s)

**Comment by Greylocke** [comment]
I'm on 1.0.1a, but not noticing extra large groups spawning. Also not seeing respawn triggering on server startup. I AM seeing strange "overloaded" messages that shouldn't be there because this is a very light pack, but I'm not ready to point fingers at Animania yet.

I have a small pack that is still in the WIP mode, so I'm available to do some specific-situation testing if it will help

**Comment by capnkirok** [comment]
So far I've done some experiments with the Animania code base. I do see the overloaded events in dev (with multiple mods installed). However, I still see them even if I comment out various spawn events, AI, or even the entire set of Animania mob entities. There's really not much else to the code. This could mean nothing at all, but I will keep poking around.

**Comment by Thyriel** [comment]
A modlist could help determine the overload problem. At least i'm not having it with 50+ mods and animania but i know there's a couple popular 1.10 mods that have issues with that (e.g. agricraft and TAN)

**Comment by jprocket45** [comment]
another update sorry to keep updating but feel it needs to be done lol after playing on the server played on server last night with 1.0.1 just a couple lag spikes nothing bad at all did the swap to 1.0.1a today for people to play on I am getting ghost blocks all over I may remove the mod all together just to see if this all goes away but I know 1.0.1a should be better but in my case at least it seems to be making it worse. I could be wrong that it is this mod all together but I had none of this happening before adding this and doing like 2 updates on other mods in my pack, 1.0.1 when you log in things are fine as well 1.0.1a when you log in the chunks in front of me take a bit to load... just reporting my findings tonight.

**Comment by jprocket45** [comment]
1.0.1a this maybe is the issue... I am going to remove the mod and install is back now. they keep breeding
![image](https://cloud.githubusercontent.com/assets/11837257/23588108/773a06f0-0186-11e7-8455-b3d99fb50511.png)

**Comment by capnkirok** [comment]
have you tried setting the gestation timer to 24000?

**Comment by jprocket45** [comment]
I have not I will though now I also removed the mod and installed it as of now there is no                              ( server overload ) messages it appears I may of still been suffering from the 1.0.1 possibly?? ill report possibly tomorrow on this since it will be tried out more tonight.

**Comment by jprocket45** [comment]
alright so things are looking good insept for once in a great while a tick but I can live with it hopefully next update even improves things more :)  I removed mod started server stopped server put mod back in that smoothed things over then set config gestation to 24000, this can be closed I will file something again if need be unless someone else is still having this issue thanks for all the hard work!!

**Comment by capnkirok** [comment]
Thanks so much JP for all the extra help and effort. Much appreciated!
