### ISSUE TITLE
Question / Suggestion re: Truffle Drops

### ISSUE THREAD

**Issue by scotty9090** [capnkirok/animania#280]
Is there a way to disable (or limit the frequency of) pigs digging up truffles?  I'd prefer to just be able to turn this off entirely but I don't see an option for it in the config (only changing their custom drop).  If not, then I'd like to offer that as a suggestion for an enhancement.

This is on the 1.10.2 version.

**Comment by Tschipp** [comment]
Yeah, we could make a config for it.

**Comment by scotty9090** [comment]
Thank you - I'm getting a lot of truffle drops!

**Comment by Tschipp** [comment]
We changed some plans: The truffles will now only drop if the pig is leashed to a Player. This should prevent you overflowing with truffles :D
