### ISSUE TITLE
Suggestion: Dominance for Male Animals 

### ISSUE THREAD

**Issue by CrazyBeanie** [capnkirok/animania#282]
Is there a possibility that you can get all the male creatures a dominance mechanic like:

- Roosters have spurs, will lower their heads, jump at each other, and try lower each others health until one runs away. This claims the winner, head of the flock.

- Peacocks have also have spurs, but will circle each other until one jump at the other and lower each others health until one runs away. This claims the winner, head of the flock.

- Pigs will fight by push each other and biting until one backs off - (i don't raise pigs so if someone knows how pigs fight for dominance plz put in a comment)

- Cows will ram and push each other around until one gets pushed over or just backs off. This claims the winner, head of the herd.

- Horses will rear up and nip at each other not really hurting each other, but will sometimes kick at each other until one backs off.  This claims the winner, head of the herd.

- Sheep and Goats (When they get added) will ram each other with their horns, they can hurt each other if they ram each other in the sides or legs, they will continue until one backs off.  This claims the winner, head of the herd.

**Comment by capnkirok** [comment]
We are going to try something out for Sheep and Goats. If it works, we can add similar to other animals. Thanks for the suggestions!

**Comment by CrazyBeanie** [comment]
You're Welcome!

**Comment by capnkirok** [comment]
Hey @CrazyBeanie this is on our suggestions list now. In an effort to clean up this git, I'm going to remove it so git only shows bugs.

**Comment by BryanBoru** [comment]
@CrazyBeanie  I've seen some other mods have a dedicated Entry for suggestions only to keep their pages streamlined, Also helps as others can see what's been suggested to not get multiplications of the same ideas.
