### ISSUE TITLE
Cow Names

### ISSUE THREAD

**Issue by Kniverix** [capnkirok/animania#283]
I noticed that two breeds of cows are called the Friesian & the Holstein. I just wanted to put to attention that those are horse breeds, not cow breeds.

**Comment by CrazyBeanie** [comment]
Well actually it is the name of both cow and horse breeds if you look it up

**Comment by capnkirok** [comment]
You beat me too it!

Actually, there are even Friesian Chickens!
>
>
Technically, though, the Cow breed is known as the Holstein-Friesian Breed.
They are called Holsteins in America and Friesians in the UK / Europe.

**Comment by CrazyBeanie** [comment]
Lol Sorry!!!

**Comment by capnkirok** [comment]
[](url)
