### ISSUE TITLE
Unable to make cheese [1.2.2]

### ISSUE THREAD

**Issue by Kyrislian** [capnkirok/animania#284]
Just updated! :D 

Came across a bug: the cheese molds turned into purple and black blocks, and won't make cheese anymore. When new molds are made, they retain the normal image but won't make cheese either. The new molds also randomly turn back into the purple/black block and will then stack with the existing purple/black block.

**Comment by Tschipp** [comment]
Oh noes :O

**Comment by capnkirok** [comment]
Looking into it...

**Comment by Tschipp** [comment]
@Kyrislian I tried recreating this, I really can't. Could you maybe provide a world with the blocks (and items) that are errored?

**Comment by Kyrislian** [comment]
@Tschipp I would just need to zip up the world folder and link the file here yes? *sheepish* I've not done this before so just wanted the clarification.

**Comment by Tschipp** [comment]
Yes, exactly

**Comment by Kyrislian** [comment]
Hopefully this works! [Download](https://drive.google.com/file/d/0Bxd_c_t4JGSBMkhFVmtOTkMwdUU/view?usp=sharing)

**Comment by Tschipp** [comment]
Thanks for the world, but I need some more Information. Did the mold **items** get the missing texture or the  **placed block** Molds? What do you mean they won't make cheese anymore? Can you not insert milk in the placed molds? How exactly did you get these errored item molds? They are just the mold item, with a damage value of 19. I have no clue how you got that in survival mode.

**Comment by Tschipp** [comment]
Update: I think I understand now: Before the Placeable Cheese Update, molds could have a damage value of max 100. Their damage was increased every time you **crafted** with them. My guess is that the errored mold was from before the update and was already damaged before the update. Am I correct?
In any case, just placing the errored molds on the ground and breaking them should fix your issue.

**Comment by Kyrislian** [comment]
Ah! The textures came back so yep! Placing them on the ground and breaking them worked :D And ah! I didn't realize there was a new method of making cheese now. Thank you!

**Comment by capnkirok** [comment]
Yay @Kyrislian yay @Tschipp
