### ISSUE TITLE
Truffle Soup Crash

### ISSUE THREAD

**Issue by Emraldilian** [capnkirok/animania#285]
Whenever I attempt to eat Truffle soup my game will crash. I log back in, the soup and bowl are gone, my hunger is unchanged but I have the regen.

This was my first Animania food so I tried others to be sure and the soup is the only offender.

**Comment by capnkirok** [comment]
This is a conflict with Apple Core. I made a workaround in a previous version, but now it's back again. Going to contact the author.

**Comment by capnkirok** [comment]
Tagged here https://github.com/squeek502/AppleCore/issues/97

**Comment by capnkirok** [comment]
Ok, this is fixed in the next release, thanks to tip from squeek502 (AppleCore dev). Thanks for the report!
