### ISSUE TITLE
Dreadthorne Killing Baby Animals

### ISSUE THREAD

**Issue by ToAsgaard** [capnkirok/animania#287]
For Animania 1.10:   I know that this was posted about in the past and was closed, however the problem still persists so going to post on it.  The dreadthorne from botania kills baby animals when it should only kill adults.  This only happens with Animania animals and I tested this only running botania and animania (+baubles since botania requires it) and the issue is still there.  I tested animania versions since the fix for age tracking was first implemented up until most recent version and also testing botania versions from most recent down the last 20 updates just to make sure something through there wasnt causing the issue.  The dreadthorne doesn't kill baby sheep, only animania spawned animals and this includes cows, chickens, pigs, peacocks.  Didnt test the others, but each that I did test was killed.  Only blocks I placed in my test world were dreadthorne and creative pool and then spawned in animals near the dreadthorne.  It also happens when the animals are spawned outside the dreadthorne's range and move/are pushed into it's range.

**Comment by capnkirok** [comment]
Weird. We assumed if we set "IsChild" to true, then it would take care of this. Let me look at the Botania code and maybe ping Vazkii.

**Comment by ToAsgaard** [comment]
Yeah, I tested multiple combinations of Botania and Animania versions to
see if they linked up somewhere but no dice.  However I didnt test another
mod that differentiates child animals from adults such as dark utils to see
if it worked alongside animania's settings to see if it only was something
with botania's readings.  I can test that if you want rq, but I do know
that it registers differently than vanilla's baby animals since those
aren't being killed by the dreadthorne.

**Comment by capnkirok** [comment]
No worries, we can test it.

**Comment by capnkirok** [comment]
Yeah, just looked at the code: 
`@Override
	public Predicate<Entity> getSelector() {
		return var1 -> var1 instanceof EntityAnimal && ((EntityAnimal) var1).getGrowingAge() == 0;
	}`

It's looking at GrowingAge and not if it's a Child or not.

**Comment by capnkirok** [comment]
https://github.com/Vazkii/Botania/issues/2319

**Comment by ToAsgaard** [comment]
That is odd that he's using that when a simple yes/no option is right there
:p

**Comment by capnkirok** [comment]
Ok, this should work in next release.

**Comment by ToAsgaard** [comment]
Woot, thank you for the very fast response time and for sorting that out.
Really appreciate it and great work on the mod in general btw.  One of my
favorites for adding a much needed flair and realistic approach to animals
with mc so keep it up!

**Comment by capnkirok** [comment]
This was fixed in Botania as well, which is already released, so I'm closing it here.
