### ISSUE TITLE
Mooshroom Cows are still Vanilla

### ISSUE THREAD

**Issue by SamGunGraven** [capnkirok/animania#288]
A completeness thing. Seems to me that there should be an Animania version of the Mooshroom Cow that turns into an Animania cattle when sheared and can leverage the superior AI, breeding, etc... that you guys offer.

**Comment by Tschipp** [comment]
So, you're saying that shearing a mooshroom creates the vanilla cow? @capnkirok I thought we removed those?

**Comment by capnkirok** [comment]
Ooohhh... yeah, no, they're still in the game. Pinging Razz :)

**Comment by charlesbevans** [comment]
Are you planning on removing mooshrooms? If so can you leave in a config. I found a wonderful mooshroom island, but it was so empty and sad with no mooshrooms.

**Comment by Tschipp** [comment]
Mooshrooms are not gonna be removed until we replace them with our own

**Comment by capnkirok** [comment]
Ok, Mooshrooms are in 1.4.4 update. Enjoy!
