### ISSUE TITLE
Names are pointing to the texture file paths?

### ISSUE THREAD

**Issue by SamGunGraven** [capnkirok/animania#289]
I'm using in-control to control passive mob spawns and names of Animania animals are the same as their file path to the texture png - makes for some really messy configuration files.

**Comment by capnkirok** [comment]
Yeah, pretty dumb. I didn't really understand the new ResourceLocation requirement when I first updated the entities to 1.11.2. If we change it now, people will lose their existing animals, which would be bad. Not sure there anything I can do without causing lots of pain.

We can fix this in 1.12, and in any new creatures going forward in 1.11. 

PC
