### ISSUE TITLE
Compatibility with Hatchery/Chickens/Harvestcraft/Harvest Festival

### ISSUE THREAD

**Issue by InkDragon** [capnkirok/animania#29]
I'd love to see compatibility for [hatchery](https://minecraft.curseforge.com/projects/hatchery) added.
As it is currently while you can capture chickens with the hatchery net, chickens will not go into nest boxes(chickens disappear). 

For [Chickens](https://minecraft.curseforge.com/projects/chickens), this ties in with the [Breeding Genetics](https://github.com/capnkirok/animania/issues/7) issue, as chickens adds the stats/genetics component.

Requesting that harvestcraft crops be useable as food for pigs(most crops), and seeds be useable for chicken feed. Would also be handy if the meat provided in this mod was oredictionaried to work with Harvestcraft recipes.

For Harvest Festival, would love if the eggs/cheese/meats could be sold like HF items(ie there is an ingame selling mechanic unique to HF).

**Comment by BrisingrAerowing** [comment]
I created a crafttweaker script to add the items from this mod to the ore dictionary. It is available [here](https://gist.github.com/BrisingrAerowing/85cb2f251a316a48f3fa9ccbefb23e78)

**Comment by InkDragon** [comment]
that'll work for now, but it should definetly be implemented by the mod itself

**Comment by BrisingrAerowing** [comment]
Yes, it should.

**Comment by capnkirok** [comment]
Thanks for the input guys. I'll see what I can do about compats and will defnitely take care of oredictionary.

**Comment by capnkirok** [comment]
Update:
- OreDictionary is updated for meats.

Question:
- Anything I can do for eggs or cheese? I put the brown egg in OreDictionary...

**Comment by InkDragon** [comment]
yep, might wanna look over here at the [harvestcraft](https://github.com/MatrexsVigil/harvestcraft/blob/1.11.2/src/main/java/com/pam/harvestcraft/item/GeneralOreRegistry.java) stuff to double check, but...
eggs would be under listAllegg
cheese under foodCheese and possibly listAllCheese
Milk under listAllmilk
If you are looking to accept more foods for pigs since they would eat pretty much anything maybe put listAllveggie as an acceptable food source.
same with listAllseed for anything you want to be able to feed any seeds too or in the recipe for the hamster food. 

I believe the meat is all covered by the script by @BrisingrAerowing

**Comment by capnkirok** [comment]
Perfect.. this really helps! I was looking all over for the OreDictionary general list for foods. Didn't think about checking the source!

**Comment by InkDragon** [comment]
np glad to be of service

**Comment by capnkirok** [comment]
- Ok, animania items are oredictionaried to match harvestcraft... 
- Also, animania recipes have been updated to use OreDictionary recipes
- Going to stick with the list of favorite foods already listed (it's a bit of work to change the AI for this to use OreDictionary... and tick intensive)
- Hamster Food recipe can now use listAllSeed


- Hatchery is going to be a bit of work, so give some time there.

**Comment by InkDragon** [comment]
Glad to see the compatibility is coming along <3
Feel free to do an update without adding the compatibility for hatchery, I'd rather see the easier to fix stuff get taken care of for players then have everyone wait to have everything done.

If you need more hatchery info the github is [here](https://github.com/GenDeathrow/Hatchery).

**Comment by GenDeathrow** [comment]
@capnkirok We may have to work together to get Hatchery to be compatible. I made it so Hatchery nests only work with EntityChicken.class. So unless you extend off the EntityChicken class to place chickens in.  We will have to throw some ideas  around.

**Comment by capnkirok** [comment]
Agree. Have had several requests. Two quick ideas:

- You could check for my classes by converting their class names to Strings (can send you class names)
- I could try to extend EntityChicken and see what breaks...

**Comment by GenDeathrow** [comment]
I could also attempt creating an interface api on my side, and send to you as well. That way you can control some aspects of hatchery, that may not work right with your mod. This weekend will be hard to get any work done, but I ill keep in touch.

If you use Curse/Twitch App https://invite.twitch.tv/AMpRToLaIEqxjYjialQtHA

**Comment by capnkirok** [comment]
An API would be outstanding :)

**Comment by GenDeathrow** [comment]
Alright I'll work on an API layout, but it may take me a week or two, have a few major projects and RL stuff. but I will keep ya updated.

**Comment by GenDeathrow** [comment]
I've started the API. Should be a very simple API to just allow you to place modded chickens into the nesting pens. and give you control over the hatchery egg/ breeding mechanics how you see fit.  As far as drops, nesting pens automatically capture drops, when you use the entity.dropitem() method. I'll inform ya when it ready.

**Comment by capnkirok** [comment]
Whoo hoo! Looking forward to it :)

**Comment by capnkirok** [comment]
@GenDeathrow we've found a way to extend vanilla chickens in the latest release without killing our custom AI.

**Comment by GenDeathrow** [comment]
Alright sounds great.. I have had some IRL stuff that has prevented me from getting the api done. So I'm glad this worked.

**Comment by capnkirok** [comment]
I'm closing this one now. If you see any additional problems, just post a new issue. Thanks everyone for the feedback.
