### ISSUE TITLE
Interaction with Improving Minecraft

### ISSUE THREAD

**Issue by chezpaul** [capnkirok/animania#290]
Minecraft version: 1.10.2
Animania version: animania-1.10.2-1.2.2
Improving Minecraft version: Improving Minecraft-1.12.1
Forge version: 12.18.3.2316

Mods used: appliedenergistics2-core, ivtoolkit, Micdoodlecore, NotEnoughItems, OpenComputers|Core, , ae2stuff, animania, appliedenergistics2, arsmagica2, AnimationAPI, Baubles, bdlib, bedbugs, BiblioCraft, biomebundle, BiomesOPlenty, bookshelf, Botania, bottledmilk, cfm, Chameleon, ChickenChunks, chisel, CodeChickenCore, CodeChickenLib, ccl-entityhook, cofhcore, PTRModelLib, props, eplus, endercore, EnderIO, EnderStorage, EnderZoo, energyconverters, extrautils2, FinderCompass, fluxnetworks, forestry, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, galacticraftplanets, galacticraftcore, gendustry, geographicraft, GraveStone, hammercore, Waila, immersiveengineering, imc, IC2, ironbackpacks, ironchest, JEI, jeibees, malisiscore, malisisdoors, mantle, mcmultipart, Mekanism, MekanismGenerators, MekanismTools, mercurius_updater, testdummy, Morpheus, MrTJPCoreMod, mysticalagriculture, natura, neid, notenoughwands, OpenComputers, openterraingenerator, p455w0rdslib, getalltheseeds, harvestcraft, plustic, pressure, projectred-core, projectred-integration, projectred-transmission, projectred-illumination, projectred-expansion, projectred-transportation, railcraft, reccomplex, redstonearsenal, roguelike, simplecorn, solarfluxreborn, sonarcore, special_ai, StorageDrawers, tconstruct, thermaldynamics, thermalexpansion, thermalfoundation, Translocator, unidict, wailaplugins, wanionlib, weaponcaseloot, wct, worldcontrol, worldedit, wrcbe, xtones

So, I need me some eggs. Thing is, I'm using Improving Minecraft in order to make it just a little harder and my cows and chickens are wild at first. After 2 or 3 generations, they usually become domesticated and will lay eggs. But since I've been using Animania, they don't turn into domesticated cows or chickens, the new generations become animania animals. So chickens don't lay eggs. And your cows don't give milk. You don't have sheep so the sheep become domesticated and give out wool.

Would you guys have a solution for this? Appart from not using animania? or the other mod.

Thanks

**Comment by Tschipp** [comment]
Cows do give milk, and chickens do give eggs. Chickens need nests to be able to lay eggs, and cows need to be fed and watered in order to give milk.

**Comment by Tschipp** [comment]
@chezpaul I'm gonna close this in two days, please report back if what I said solved the problem.

**Comment by chezpaul** [comment]
Yes, Nests worked... for the first week I only got Animania eggs (not minecraft ones). And then without changing anything mods wise, animania eggs, when picked up became minecraft eggs in inventory.
Weird... so now I'm fine.

**Comment by capnkirok** [comment]
Thanks for the follow up @chezpaul !
