### ISSUE TITLE
1.10.2 OTG+Animania: some mobs registered in CLASS_TO_NAME but not NAME_TO_CLASS

### ISSUE THREAD

**Issue by PG85** [capnkirok/animania#291]
Hey Purplicious_Cow,

I'm working on some code for custom mob spawning settings in OTG, trying to get Animania mobs to spawn. I noticed that for the 1.10.2 version "animania.HogYorkshire" is registered in net.minecraft.entity.EntityList.CLASS_TO_NAME, but not in net.minecraft.entity.EntityList.NAME_TO_CLASS. This seems odd because it looks like the vanilla code always adds entities to both lists at once.

Could this be something in Animania itself and is this intended behaviour, or could OTG be causing this and is it a problem? I'll implement a workaround for OTG for the time being.

Also I noticed that the cow types spawn correctly in their respective biomes, except for Angus. Mesa is spawning Friesian instead. Are Angus cows supported in 1.10.2 or are they 1.11.2 only?

Thanks!

**Comment by capnkirok** [comment]
Hey PG85!

There's nothing different about the Yorkshire Hog compared to the other pigs... is it just that animal that you have issues with? Strange?

- Angus spawns in the Jungle on 1.10.2, and it looks like Jungle, Mesa, Mushroom in 1.11.2 (I will fix this second one so that 1.10 matches 1.11)

**Comment by capnkirok** [comment]
Ok, fixed the Angus cow. Let me know about the other question above! Thx.

**Comment by darthvader45** [comment]
This version sounds awesome.  Cannot wait to see it ready to download.

**Comment by LunariusH** [comment]
So I'm using Animania to control my mobspawning, and this sound suspiciously like it might be related to a problem I'm having. I am able to control the spawning of animania mobs (though now I'm going to test all of them) by every means except one of the arguably most important.  I am unable to tell it to only spawn if under a certain number are present.

I'm using InControl to handle my mobspawning.  Is there something not registering somewhere?

**Comment by capnkirok** [comment]
@LunariusH No, I doubt this the OP is the issue, but you might be on the right track. The way Animania works is that it only spawns females naturally. Then the females have a chance to spawn a family (including mate and/or children) after they spawn the first time. I believe InControl only handles the World Gen spawn event, but you'll have to confer with McJty on that one. What are you trying to control?

**Comment by LunariusH** [comment]
Where they spawn, how many of them spawn at once, specific conditions related to their spawning behavior.  Just wanting to use one solution (InControl) than two (Animania's spawning rules +)

**Comment by capnkirok** [comment]
I would poke McJty to have InControl to expand to look at OnInitial Spawn as well, or OnEntityJoinWorldEvent.

**Comment by PG85** [comment]
Hey capnkirok, thanks for the fix and sorry for the late reply. Working on OTG for 1.11.2 and 1.12.1 atm, almost done, will update 1.10.2 after that and take another look at this and let you know.
