### ISSUE TITLE
Animals are invisible

### ISSUE THREAD

**Issue by Elizabette** [capnkirok/animania#293]
Hey!

Every time I use the egg I can hear the animals but they're invisible. Anyone know how to fix this?

Thanks!

**Comment by capnkirok** [comment]
Hi Elizabette -

What version of Animania and MC are you using? And which eggs... the vanilla eggs or the Animania eggs?

**Comment by capnkirok** [comment]
@Elizabette I'm going to close this one unless I hear back. Would recommend you update to the latest version if the problem persists.
