### ISSUE TITLE
Crash with Wild Hamster looking for a ride..

### ISSUE THREAD

**Issue by nmarshall23** [capnkirok/animania#296]
[Full Error report](https://pastebin.com/BLj70M7W) 

After a few hours of play I will get a Ticking entity Exception for a Hamster. This is the third time it's happened. Sometimes I can just reload the world with no problems. 

I have no tamed Hamsters. 

~~~
java.lang.NullPointerException: Ticking entity
    at com.animania.common.entities.rodents.EntityHamster.func_70628_a(EntityHamster.java:888)
~~~

Looks to me that he's looking for his ride:

~~~
-- Entity being ticked --
Details:
    Entity Type: animania:textures/entity/pigs/hamster_tarou.png (com.animania.common.entities.rodents.EntityHamster)
    Entity ID: 452
    Entity Name: Hamster
    Entity's Exact location: -222.26, 63.67, -109.84
    Entity's Block location: World: (-223,63,-110), Chunk: (at 1,3,2 in -14,-7; contains blocks -224,0,-112 to -209,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Entity's Momentum: -0.00, -0.21, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
~~~

**Comment by capnkirok** [comment]
Thanks for the crash log. Will take a closer look. Probably not riding, likely a conflict with another mod.

**Comment by capnkirok** [comment]
Yes! I was able to replicate. It's not a conflict. This seems to happen if the animal dies by some other means (e.g., Cactus or Sand falling on it), and caused when Custom Drops are set to null. Good catch!

**Comment by capnkirok** [comment]
Ok, this is fixed in development. You can also temporarily fix this now by adding a valid drop in the config under Drops for Hamster.
