### ISSUE TITLE
Typo: Friesian should be Frisian (cows)

### ISSUE THREAD

**Issue by AceologyGaming** [capnkirok/animania#297]
This may be fixed, I noticed it in ATM2.
Albeit a small issue, it's a little annoying :)

**Comment by CrazyBeanie** [comment]
No, the name is spelled correctly

**Comment by AceologyGaming** [comment]
Being half-Frisian myself, I know how it's spelt.

**Comment by capnkirok** [comment]
Lol :)

Could be a language issue. It's most definitely Friesian in the UK. Are you from Frisia? I can change the Dutch spelling :)

https://en.wikipedia.org/wiki/Holstein_Friesian_cattle

**Comment by AceologyGaming** [comment]
It's definitely Frisian in British English, but it appears that is for everything *except* the breeds of cows and horses, as it appears the breeds were named by Americans.

I'm half-Britsh, half-Frisian(technically half-Dutch), and the region is Friesland, the Roman-age empire  containing Friesland and pretty much the rest of the south coast of the Baltic was Frisia.

**Comment by CrazyBeanie** [comment]
I am so confuzzled (confused and puzzled)
I was not trying to say u r wrong, I was trying to say that is how u spell the name of the cow breed I am sorry

**Comment by AceologyGaming** [comment]
I believe that the British English spelling (Frisian) can also be used in the spelling of the breed, but the American spelling(Friesian) is more widely used (outside of Friesland that is, but no point translating the mod into a local dialect)

**Comment by capnkirok** [comment]
Ok, I've changed the Dutch translation to Frisian :)

**Comment by AceologyGaming** [comment]
Frisian: British English (en_gb)
Friesian: American English (en_us, default language)
