### ISSUE TITLE
Rabbit stuff

### ISSUE THREAD

**Issue by Gerbil12** [capnkirok/animania#299]
Hello, I thought that when the rabbits came to the next version, they might need some necessities, such as food and water dishes, and because rabbits need to grind their teeth, they will get hard bread that is obtained when you put in the bread oven so It will become hard bread.

**Comment by capnkirok** [comment]
Thanks for the suggestion!

**Comment by capnkirok** [comment]
Hey @Gerbil12 this is on our suggestions list now (and food bowls are high priority). In an effort to clean up this git, I'm going to remove it so git only shows bugs.
