### ISSUE TITLE
Could you add ore dictionary entries for the meats this mod adds?

### ISSUE THREAD

**Issue by BrisingrAerowing** [capnkirok/animania#30]
All raw meats use `listAllmeatraw` as an oredict entry, as well as `listAll____raw`, where the blank is the type of meat (e.g beef, chicken, pork).

The entries for cooked meats are similar, replacing the `raw` at the end with `cooked`, e.g. `listAllmeatcooked`.

In the meantime, I will add oredict entries using CraftTweaker so that the meats can be used in recipes from other mods.

**Comment by BrisingrAerowing** [comment]
If anyone is interested, the script for CraftTweaker is located [here](https://gist.github.com/BrisingrAerowing/85cb2f251a316a48f3fa9ccbefb23e78).

**Comment by capnkirok** [comment]
Will get this in the next update.

**Comment by capnkirok** [comment]
Ok, these are added and will be in the 1.0.1 update
