### ISSUE TITLE
Bull

### ISSUE THREAD

**Issue by Gerbil12** [capnkirok/animania#300]
Hello today, I learned that when I play and angry the bull and give it a dandelion, so his head goes down to the ground, but not as if he is angry but the head is not on the body but on the block.

**Comment by capnkirok** [comment]
Ah yes! You should not be able to feed an angry bull. Ha ha. That's a good one.

**Comment by capnkirok** [comment]
And nice Icon pic!

**Comment by Gerbil12** [comment]
Thank you and here's the picture.
![2017-08-17_19 47 56](https://user-images.githubusercontent.com/31073803/29425942-4b676e60-8385-11e7-80ea-ad28e2b2e390.png)

**Comment by capnkirok** [comment]
Spooky

**Comment by capnkirok** [comment]
Ok, fixed on 1.11.2
