### ISSUE TITLE
Nest

### ISSUE THREAD

**Issue by Gerbil12** [capnkirok/animania#301]
Hello, the developers just want to say that when I cheated I had a peacock in the nest and when left the nest there was feathers and eggs in the nest and when I chose them there were only eggs in the inventory but no feathers it's a mistake or One-time error.

**Comment by capnkirok** [comment]
Oh, the feathers appear when it's a peacock nest. After a peacock 'becomes interested' in a nest, only peacocks can lay eggs there. The feathers let you know that :) Not a bug.

**Comment by Gerbil12** [comment]
Haha thanks:)

**Comment by RaliaTheWolf** [comment]
You know, that would be a great alternative for getting peacock feathers so you don't have to kill them!

**Comment by capnkirok** [comment]
@RaliaTheWolf I was going to implement a way that Peacocks occasionally drop feathers... but... maybe breaking a peacock nest could drop feathers... hmmm... good suggestion!

**Comment by RaliaTheWolf** [comment]
Thank you! ^^
