### ISSUE TITLE
[Problem | Issue] Couldn't Start Minecraft Properly

### ISSUE THREAD

**Issue by FarmerB0b** [capnkirok/animania#302]
If I start my Minecraft, recommended forge installed, craftstudioapi installed.

It says : **Animania** is missing mods it depends on.
Include the following mods or remove Animania.
   **forge** 13.20.1.2386 or above
See ´fml-client-latest.log' for technical information.
-------------------------------------------------------------
I installed Forge....but why will it not work??

Please help me :)

**Comment by Tschipp** [comment]
> forge 13.20.1.2386 or above

**Comment by FarmerB0b** [comment]
Uhmmm yes I got that one, but it still says Nopeeeeeeee :(

**Comment by Tschipp** [comment]
Could you link the full client log in a pastebin?

**Comment by FarmerB0b** [comment]
Umm sure wait a sec

**Comment by FarmerB0b** [comment]
https://pastebin.com/bPVRrY9Z

**Comment by Tschipp** [comment]
> [11:48:56] [main/INFO] [FML/]: Forge Mod Loader version 13.20.0.2228 for Minecraft 1.11.2 loading
You are not using the correct version of forge

**Comment by FarmerB0b** [comment]
oh...

**Comment by FarmerB0b** [comment]
Can you please give me the Link to get that (correct) forge?

**Comment by Tschipp** [comment]
Let me ask you a question: From what site did you download forge?

**Comment by FarmerB0b** [comment]
From the official page.

**Comment by Tschipp** [comment]
https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.11.2.html

**Comment by FarmerB0b** [comment]
Thanks wait 1 sec

**Comment by FarmerB0b** [comment]
But, what installer should i get? Or Universal, where should I put it?

**Comment by Tschipp** [comment]
Is this your first time installing forge? How did you install the version that you already have? 
https://www.youtube.com/watch?v=NpZ0RbpHU7Q

**Comment by FarmerB0b** [comment]
Yes, it is my First time Installing it for myself.

And I do not know how i installed it :P

**Comment by Tschipp** [comment]
If you installed it from any website other than files.minecraftforge.net, run a virus scan.
Only download mods from these sites:
minecraftforum.com, curse.com, curseforge.com, planetminecraft.com

**Comment by FarmerB0b** [comment]
I do download mods only on Planetminecraft, curse, curseforge and minecraftforum.

**Comment by Tschipp** [comment]
good

**Comment by FarmerB0b** [comment]
Lets hope it works now.

**Comment by FarmerB0b** [comment]
it is always version 13.20.0.2228 :c

**Comment by Tschipp** [comment]
are you also choosing the correct profile in the launcher?

**Comment by FarmerB0b** [comment]
Fucking trashcrap fucking forge can suck my nuts, fucking tired of this, I JUST WANT TO PLAY WITH THE MOD ANIMANIA IS THAT TOOO FUCKING MUCH?!"??!??!! >:C
