### ISSUE TITLE
plymouth rock chick

### ISSUE THREAD

**Issue by Gerbil12** [capnkirok/animania#303]
Hello today I thought that actually in the Plymouth rocks chickens is a bug from beta that when you have chickens and turn off the game and then return the chickens to change the color.
![2017-08-18_17 44 21](https://user-images.githubusercontent.com/31073803/29466475-4b451ffa-843d-11e7-9ba0-b0fa13c52772.png)

**Comment by CrazyBeanie** [comment]
I have had the same problem but I thoughts that's what they would look like

**Comment by capnkirok** [comment]
Interesting.... well, they're not supposed to change colors... but they are supposed to have two different colors (on 1.10 only I believe).

**Comment by Tschipp** [comment]
@capnkirok yes, two colors on 1.10 and one on 1.11... I believe the guy who updated them was too lazy to include both texture variants... xD

**Comment by capnkirok** [comment]
Well, going forward, the chicks will only be speckled :) so they won't change colors.

**Comment by hron84** [comment]
I am just curious, how the chicks look like when they grow up. This purple-white texture is not as bad as purple-black is... :smiley:

**Comment by capnkirok** [comment]
It's your lucky day, because they use the purple-white texture 😃
