### ISSUE TITLE
Switching Keys to dismount a hamster

### ISSUE THREAD

**Issue by pawelik001** [capnkirok/animania#304]
It's able to change key to dismount a hamster? Because SHIFT in my opinion is bad key, and I would to change key to Page Down or something. :smile:

**Comment by capnkirok** [comment]
Thanks for the suggestion, I will take a look. We may have to change a few things because of Carry On.

**Comment by pawelik001** [comment]
Yay, thank you very much! :smiley: I can't wait! :)

**Comment by Deshiba** [comment]
This should be a keybinding thing to be honest. Let players set the key themselves trough the control menu?

**Comment by Tschipp** [comment]
How is it a bad keybinding for dismounting the hamster?

**Comment by Deshiba** [comment]
@Tschipp well, it's not necessarily bad. In this instance though, sneaking dismounts a pet. Also if other mods use the shift key for something you might want to change what it's mapped to. It'd be nice to configure the key manually trough the controls menu.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#117
