### ISSUE TITLE
Adolescence baby

### ISSUE THREAD

**Issue by Gerbil12** [capnkirok/animania#305]
Hi, I was wondering if the baby would be a pre-adult stage, so I think it would be amazing that at this age it might be known that they are women or men. So mammals could not have a baby, and birds could not bear eggs and men, could not breed, and because in your team there is a raptorfarian who has a mod, ice and fire And dragons have this similarity to age to help you, Thanks for reading and a nice day . :)

**Comment by capnkirok** [comment]
Thought about this one a while back, and meant to close it. Unfortunately, the way we have it set up, gender isn't determined until later. Because of the work involved to redo it, this is not a priority (but I like your idea).
