### ISSUE TITLE
[1.11 only] Achievements Bug?

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#306]
I was playing in the latest version of 1.11.2 and I have all of the different kinds of chickens, peafowl, cows, and pigs. I went into the achievements to marvel all of my accomplishments and it says that I don't have any animal friends... (Lol)
So out of curiosity, I spawned a cow and fed it and the little hearts appeared, but I didn't get the achievement. It says I have the hamster friend,  the draft horse friend, and the seabiscuit one, as well as the Sonic one, but none of the others, despite the fact that I have tamed every animal. Did the way you get those achievements change? 
If it helps, I'm in creative mode.

**Comment by hron84** [comment]
@RaliaTheWolf did you tried the taming in survival too? Maybe it detects taming only if you're not in creative.

**Comment by RaliaTheWolf** [comment]
You know, I haven't actually tried that... I'll do that now

**Comment by capnkirok** [comment]
Hey @RaliaTheWolf wow you are right! No achievements are firing in 1.11. We messed something up back in 1.2.2. 

Ironically everything is fine on 1.10 and on 1.12. We'll have it fixed in next release.

**Comment by RaliaTheWolf** [comment]
Okay cool! (Sorry, I never ended up testing it in survival... XD Turns out it didn't really matter much anyhow!)
