### ISSUE TITLE
Cheese Making

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#307]
Hi! Me again! ^^

I'm in creative mode in the latest version of 1.11.2 Animania and I was trying to craft some cheese. I know that you can place the cheese mold thingy, and I tried that once, but it wasn't making me any cheese and I waited for a while... I've been having a lot of problems with this world actually, including the achievements stuff I made a post about, so maybe the world is just being weird... I don't know though. 

While I'm on the topic though, some of the other weird things are my chicks not growing up (I spawned them and they grew a little bit and then just stopped), cows weren't breeding (they had food and water troughs), and roosters not turning eggs into chicks. If you'd like me to, I can check all of that in a different world and see if that makes a difference.

**Comment by capnkirok** [comment]
Might want to check on a different world. The mod is functioning fine for me. You can always tweak the config settings to speed things up for testing. Thanks for the help!

**Comment by RaliaTheWolf** [comment]
I will test them in a different world then! I'll let you know how that goes.

**Comment by RaliaTheWolf** [comment]
I've tried feeding different animals for achievements and that still isn't working... Just the ones I could get before.
I also am trying to make cheese and that doesn't appear to be working either.
I got a chick to hatch though! Only one though, the rest of the eggs haven't hatched.
I think I'm going to try downloading a fresh, new mod file and see if that fixes anything, unless you don't want me to for some reason.

Also, a quick question that will probably help me: Can I change stuff in the config while I'm in game? I haven't tried to before for fear of messing stuff up, so I thought I'd just ask instead.

**Comment by capnkirok** [comment]
Thanks for checking Ralia! Can you let me know what version of MC you are on and what version of Animania (I assume the latest and 1.11.2)....

I will check on achievements... we did change some stuff, so could be issues there.

Yes, some stuff can be changed in game. Don't worry about breaking anything, either it works or you have to restart to see it work.

PC

**Comment by RaliaTheWolf** [comment]
No problem! Happy to help!

I am on version 1.11.2 (I believe it is the latest version of Forge for 1.11.2, but I can double check) and I am playing Animania 1.11.2-1.2.2. 

Okay! Thanks for letting me know!

**Comment by capnkirok** [comment]
Ok, since the Achievements thing is listed under #306 I'm going to close this one. Thanks for double checking everything, extremely helpful.
