### ISSUE TITLE
MrCrayfish Furniture Mod Animania Recipes

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#308]
Hello everyone! I come bearing gifts! ^^
I made up two recipes to use with the CFM's oven and Animania's Prime Beef and Prime Pork! I will probably make an omelet one (once I figure out the name for it; probably animania:omelet, right?) and once you can add recipes for the grill! For now though, here's one for roast prime beef and roast prime pork! You can use the following link to find out how to make your own recipes and how to add them into the config!
http://mrcrayfishs-furniture-mod.wikia.com/wiki/Configuration

Now here's the stuff you paste into the config:

type=oven,name=Cooked Prime Beef,input-item=animania:raw_prime_beef,output-item=animania:cooked_prime_beef

type=oven,name=Cooked Prime Pork,input-item=animania:raw_prime_pork,output-item=animania:cooked_prime_pork

Enjoy~!

**Comment by capnkirok** [comment]
Hey Ralia -

This is great stuff! I'm going to put this on the Forum, ok, since this is an issue board.

PC

**Comment by RaliaTheWolf** [comment]
Oh sure thing! Sorry I would've put it there myself but I don't have an account there XD
