### ISSUE TITLE
Question - Breed-specific meats no longer in the mod?

### ISSUE THREAD

**Issue by darthvader45** [capnkirok/animania#309]
Just wondering, have the other specific meats like Angus beef been removed from the mod entirely?  I cannot find a config option for it.

**Comment by capnkirok** [comment]
Hey @darthvader45 they're still there. But you have to change the drop config to get them.

There's a setting for enable Custom Drops which is by default set to True. If you set it to False, it goes back to the original drops and ignores any custom drops set in the config.

**Comment by darthvader45** [comment]
Thanks, man.
