### ISSUE TITLE
[Suggestion] Additional Animals

### ISSUE THREAD

**Issue by InkDragon** [capnkirok/animania#31]
I'd like to suggest the addition of the following animals

Poultry
- Chickens: Silkie(Good for Brooding), Ayam Cemani(Rare, All black Meat & Feathers)
- Ducks: Pekin, Rouen, Cayuga, Saxony
- Geese or Swans
- Javan Green Peafowl
- Turkey: Wild/Normal, Broad Breasted White, Bronze, Bourbon Red, Black
- Ostrich or Emu, Rideable?
- Pigeons, Farmed for Meat & Eggs: Grey(Rock Dove), Albino, Melanistic, Brown, Piebald
- Guinea fowl
- Penguins
- Pheasant

Reptiles
- Corn Snake: Normal, Amelanistic, Lavender, Caramel, Sunrise
- Ball Python: Normal, Albino, Piebald, Axanthic, Bamboo
- Alligator (farmed for meat and hide)
- Turtles/Tortoises
- Anoles

Mammals 
- Mice, can be feed to snakes: normal(grey), white, black
- Rats, can be feed to snakes: Brown, Black, White
- Alpacas, provides fleece, rideable, 1.10 alternative to llamas?
- Boar
- Bison
- Bighorn Sheep

Others
- Fish, with a simple breeding system to make them farmable and a viable food source
- Crickets, can be used to feed for birds and some reptiles
- Frogs

edited to add optional color morphs for some animals, and add a few more animals.

**Comment by Guinaro** [comment]
Goats would also be a nice addition: for meat, wool (angora), milk (and cheese).

**Comment by capnkirok** [comment]
Goats are already on the list :)

**Comment by capnkirok** [comment]
Just FYI, I'm closing this suggestion, as I've got them in a separate area, so I can keep the issue board clean. Thanks again for the suggestion!
