### ISSUE TITLE
[1.10.2] Pigs searching for water crashes game?

### ISSUE THREAD

**Issue by SonOfDiablo** [capnkirok/animania#310]
I have multiple times had my game crash and I found this in my crashlog, which I think is related to Animania, but I'm not 100% sure.

Seems like something with pigs trying to find water crashes the game..

https://pastebin.com/GPwYuVe7

**Comment by capnkirok** [comment]
Thanks for posting the crash, always helpful. Ok this is a weird one. It's actually crashing when Forge is trying to retrieve the current Biome, which shouldn't happen. But it sometimes does if you've got a custom terrain generator. I can put in some workarounds, but I would report the bug to OTG (or one of your other worldgen mods) and ask how this could be happening from an Entity.

PC

**Comment by capnkirok** [comment]
Also related to #427 

This could be an 'initialization' thing where Biomes aren't fully initialized before the AI kicks in and starts checking for them.

**Comment by capnkirok** [comment]
Ok, got it. This is an issue with OTG. I know they are looking at it, but it basically comes down to the fact that these Biome generators are not supporting BiomeDictionary. I know they were working on a solution, but not sure where it stands. I'm closing this as there is nothing I can do. Would recommend you reach out to those devs.

You can read more about how they solved the issue in TerrainControl (another WorldGen mod).

https://github.com/MCTCP/TerrainControl/issues/500
