### ISSUE TITLE
SERVER Spamming Log [1.11.2] ANIMANIA 1.2.2

### ISSUE THREAD

**Issue by HalestormXV** [capnkirok/animania#311]
So I am running a 1.11.2 server on Forge xx--2393. This message is quite literally spamming the logs:
https://pastebin.com/qMewPgYS

Now it is referencing animania specifically hence why I am posting here, but I can' tell if it has to do with the animania mod or if this is a remnant bug from elsewhere.

Thank link above is only some of the log. It continues on quite a bit.

**Comment by capnkirok** [comment]
This is sadly a Minecraft error. It looks like they are still working on it. Seems to happen when a new entity gets a UUID that matches an existing UUID.

https://bugs.mojang.com/browse/MC-95649?jql=text%20~%20%22keeping%20entity%22

**Comment by capnkirok** [comment]
We think this is fixed in the 1.3 release as we are treating Entities and UUIDs differently. I'll leave it open for now. Please let us know!

**Comment by capnkirok** [comment]
Closing this as we haven't heard back, and believe the changes we made in 1.3 fixed this regardless.

**Comment by HalestormXV** [comment]
Sorry, I haven't responded because e-mail decided to mark this as Spam and didn't realize a response was made. Appologies. As it stands now, with this update I have not seen the error spamming the log. But if it crops back up I will re-open.
