### ISSUE TITLE
[Request] New Feature

### ISSUE THREAD

**Issue by Preminenc3** [capnkirok/animania#312]
First, amazing mod keep up the great work, and my request is animals automatically repopulate and die off like in the Harder Farming mod.

**Comment by darthvader45** [comment]
The first part is already in, as I've seen animals auto-breed when ready and in a stable (no pun intended) relationship.  Dying off can happen if starvation is on, but maybe an aging system so the oldest die off first would work.

**Comment by capnkirok** [comment]
Starvation can lead to death, if enabled in the config, as @darthvader45 says, but I think we also need an aging mechanic too. Thanks both.

**Comment by darthvader45** [comment]
No problem.  Old cows, pigs, etc. should be unable to breed (i.e. after a certain age).

**Comment by Deshiba** [comment]
Isn't this exactly the same as #198 ?

**Comment by capnkirok** [comment]
Yes @Deshiba closing this one
