### ISSUE TITLE
Animania and Forestry Server crash 1.11.2

### ISSUE THREAD

**Issue by SybilGlendevon** [capnkirok/animania#313]
Just FYI had an interesting crash related to both Animania and Forestry.

<script src="https://gist.github.com/SybilGlendevon/84cbf10100fdc3255d42c4e2d3331e3c.js"></script>

**Comment by hron84** [comment]
@SybilGlendevon FYI: GitHub issues do not support embedding gists into them, but they happily accept simple links. In your example: https://gist.github.com/SybilGlendevon/84cbf10100fdc3255d42c4e2d3331e3c

**Comment by Tschipp** [comment]
This might have been resolved during the current optimization of the code. Checking it out later.

**Comment by capnkirok** [comment]
I don't know why Base class would be trying to cast EntityAnimal against Forestry's Butterfly though, that's just weird.

**Comment by Tschipp** [comment]
LoadedEntityList... maybe a missing check somewhere

**Comment by hron84** [comment]
Butterflies as far as I know are passive mobs, maybe they should be animals too (even if they're really just bugs :smile:).

**Comment by capnkirok** [comment]
Should be fixed in the 1.3 update
