### ISSUE TITLE
Add replace vanilla horse option in config

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/animania#315]
realisticmc73309
Default is False

**Comment by hron84** [comment]
Draft Horses can have as different properties as vanilla ones can? I mean speed, health, jump height, etc. 
Also IIRC there is a mod that can manipulate horse stats by special food.

**Comment by capnkirok** [comment]
Currently, no, planned yes.

**Comment by capnkirok** [comment]
This is fixed in the 1.3.6 release
