### ISSUE TITLE
common issues with furnace cooking

### ISSUE THREAD

**Issue by touhouzun** [capnkirok/animania#316]
I just want to complain one thing.If I cook chicken eggs in furnaces,Lots of food's and Animania's cooking
recipes give two results.(Two cooked eggs,only one recipe survive.)Also happens when you cook rotten flesh for food,only given leathers.In the whole modding environment,furnace recipes aren't as flexible as crafting-table recipes.Should I use minetweaker and crafttweaker?

**Comment by touhouzun** [comment]
sorry,the "environment" should be "community"

**Comment by touhouzun** [comment]
If there's nobody here,I just use crafttweaker myself.However it's annoying when editing .zs files.

**Comment by capnkirok** [comment]
Hey touhouzoun. Sorry, I don't understand how we can help other than removing the recipe to make an omelet, or creating an alternate egg Recipe like egg + salt or something. I wish there was a FurnaceDictionary.

**Comment by Tschipp** [comment]
Yeah, I suggest you use minetweaker

**Comment by touhouzun** [comment]
Thanks a lot,I just use minetweaker to change egg-cooking-into-omelet recipe to something myself.However,egg+salt(ore dictionary)=omelet somehow sounds good.

**Comment by touhouzun** [comment]
Ah lots of food's egg-cooking loses and animania wins.Yeah.
