### ISSUE TITLE
Various Animals Causing Tick Loops

### ISSUE THREAD

**Issue by jelaw21** [capnkirok/animania#319]
There seemed to be an issue with animania in a void world and animals not de-spawning in the void. But here is the crash report. I have had it happen draft horses. Something about Entities Vehicle showing an error.  I also had the same error in another dimension.

[crash-2017-09-14_10.22.13-server.txt](https://github.com/capnkirok/animania/files/1303384/crash-2017-09-14_10.22.13-server.txt)

**Comment by capnkirok** [comment]
Hmmm... this version is pretty old. Can you update to 1.3.5, and see how this works? (out soon)

**Comment by capnkirok** [comment]
Hey @jelaw21 I'm going to close this one unless I hear back. Haven't seen this one in awhile, so assuming updating fixes your issue. LMK :)

**Comment by jelaw21** [comment]
Yeah. Thats cool.

**Comment by capnkirok** [comment]
Thanks @jelaw21 Let me know if the issue comes back!
