### ISSUE TITLE
How to make roosters stop attacking hedgehogs?

### ISSUE THREAD

**Issue by PurpleHel** [capnkirok/animania#320]
Minecraft 1.10.2, animania 1.2.2, FTB Infinity lite modpack, with some additions.

The Plymoth Red roosters keep attacking and killing the hedgehogs. I ended up killing all the roosters to stop it.

I'd really strongly prefer to be able to disable all animania animals from attacking other animania animals, or any other mobs that don't attack them first, for that matter.

**Comment by Tschipp** [comment]
The roosters attack the hedgehogs because they steal the eggs from nests. We could make it so that the hedgehog flees more quickly and can get away from the roosters

**Comment by capnkirok** [comment]
Or, I can add something to the config.

**Comment by LunariusH** [comment]
I love that you coded in this behavior. <3

**Comment by RaliaTheWolf** [comment]
I kinda wish that if the hedgehogs (and ferrets for that matter) are tamed, the roosters won't attack them. Unless they still steal eggs, even when tamed... Then by all means they have the right to get 'em. XD

**Comment by PurpleHel** [comment]
@capnkirok That'd be great, thanks! I'd be cool with the egg stealing also being disabled, wouldn't want the poor chickens getting robbed with no recourse :D

Maybe make it the 'befriends' option, all the animania animals stop hurting/upsetting each other :)

**Comment by capnkirok** [comment]
Ok, since it looks like I have to rewrite the 'Attack' code to make the suggestion work, for now, I'm making hedgehogs avoid Roosters. @PurpleHel I like the 'befriends' option, going to leave this open as a reminder to implement.

**Comment by Hootling** [comment]
Just somewhat unnecessarily chiming in that an "animal friends" option in the config, where none of the animals attack each other, would be fantastic.

There is so much cuteness, I hate to see them fight.  :)

**Comment by capnkirok** [comment]
Hey, this was added into 1.4.4, in case you didn't see it. There's a new config under Game Rules. Thanks for the suggestion!

**Comment by PurpleHel** [comment]
Excellent!
