### ISSUE TITLE
flood log 'keeping entity'

### ISSUE THREAD

**Issue by darknat** [capnkirok/animania#323]
Hello

Mods version : animania-1.10.2-1.2.2
Forge : forge-1.10.2-12.18.3.2422

I have a problem in my log, and i can't resolv this : 

`[15:36:12] [Server thread/WARN]: Keeping entity animania.HenLeghorn that already exists with UUID f2006664-e443-4d65-a668-841a152f203a`

each second on my server, this message. And i try to delete and launch my maps, and restore animania, it's the same thing. It's possible that bug make lag on my server ?

Thank you,

**Comment by capnkirok** [comment]
Related to #311

**Comment by capnkirok** [comment]
This should be fixed in 1.3 release.
