### ISSUE TITLE
Rodents

### ISSUE THREAD

**Issue by Gerbil12** [capnkirok/animania#324]
good day to think of adding guinea pigs and other rodents like a gerbil or another rodent. Thanks, have a nice day.

**Comment by Gerbil12** [comment]
examples of rodents.
mouse.
jerboa.
rat.
guinea pig.
guinea pig skinny.
squirrel.
chipmunk.
gerbil.
other hamsters.
chinchilla.
capybara.
thanks. :)

**Comment by capnkirok** [comment]
We have more rodents coming in ... what is it... 1.5 release.

Guinea pig, mouse, rat on the list. Thanks!

**Comment by capnkirok** [comment]
Gonna close this one THANKS for the add'l suggestions.!
