### ISSUE TITLE
A suggestion, and an issue

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#325]
1. Add a config option to turn off wild breeding of animals, so that runaway breeding does not cause lag.

2. The saturation value on roast prime beef is absurd. 
![screenshot 2017-09-17 21 28 20](https://user-images.githubusercontent.com/5614902/30526836-4ada5534-9bef-11e7-95de-1d7b627a4a43.png)

**Comment by Tschipp** [comment]
Whoops. Clearly the saturation value was misinterpreted.

**Comment by capnkirok** [comment]
Ok, the saturation bug is fixed. This has been in there since the beginning. It's sad I didn't understand how saturation worked until today.

**Comment by capnkirok** [comment]
Are you seeing runaway breeding? I mean if you set your gestation timer to 500, yes this will happen. But as a default?

**Comment by Sunconure11** [comment]
Mainly with rabbits, I see reproduction as soon as possible. Granted, they're rabbits.

**Comment by capnkirok** [comment]
The rabbits are on the same timer as other animals. I think they're just more of them. I'm going to sit on this one a little while and leave it open for now.

**Comment by Sunconure11** [comment]
Truffle soup has a saturation value of 200.

**Comment by capnkirok** [comment]
Yup. That recipe was not part of the automated system. Nice catch. Will come in a hotfix later today.

**Comment by capnkirok** [comment]
@Sunconure11 let me know if the spawning nerfs I just put in (1.3.2) solved this problem. I don't think the issue was breeding, but a high spawn limit over time.

**Comment by capnkirok** [comment]
I have multiple reports of overspawning being solved, so closing this for both issues listed.
