### ISSUE TITLE
Crashing on the server

### ISSUE THREAD

**Issue by djdado16** [capnkirok/animania#327]
Here, crash report ....previous version is working okay...but this new release nope

https://pastebin.com/BM8fWLfe

**Comment by capnkirok** [comment]
Looks like it's having problems with a function from MathHelper. Not good, since the function is used in multiple places. Will look at it later. Thanks for the report.

**Comment by djdado16** [comment]
Thanks, looking forward for patch :)

**Comment by capnkirok** [comment]
Yup, that function only works on client. Don't know how it got through testing on my server. Will patch tonight.

**Comment by darknat** [comment]
i have same problem 👍 

> `Description: Ticking entity
> 
> java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.func_154353_e(D)I
> 	at com.animania.entities.pigs.ai.EntityAIFollowParentPigs.func_75250_a(EntityAIFollowParentPigs.java:49)
> 	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
> 	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
> 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
> 	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
> 	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
> 	at com.animania.entities.pigs.EntityAnimaniaPig.func_70636_d(EntityAnimaniaPig.java:519)
> 	at com.animania.entities.pigs.EntityPigletBase.func_70636_d(EntityPigletBase.java:253)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
> 	at net.minecraft.world.World.func_72866_a(World.java:1964)
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
> 	at net.minecraft.world.World.func_72870_g(World.java:1934)
> 	at net.minecraft.world.World.func_72939_s(World.java:1750)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Thread.java:745)`

**Comment by capnkirok** [comment]
Yeah, uploading a fix now.
