### ISSUE TITLE
Suggestions for the next updates!

### ISSUE THREAD

**Issue by epicslayer999** [capnkirok/animania#328]
This is a simple list of stuff that I think would be great on Animania; ranging from A.I to enhancements, this list will be edited depending on my play-throughs in Animania.

- [ ] Breeding dominance. Animals such as cows, goats, and sheep should have the males spar with their horns to see who gets to breed. Given Animania's system of 2 animals being mates, this would happen if for example, 2 bulls want to breed with a fertile cow. The loser temporarily loses their breeding A.I. Chances of winning should be a 50-50.

- [x] Draft horses should reach all the way to the ground. The heads of the horses are somewhat levitating whenever they eat. I believe this is also a bug with goats and maybe sheep, where their heads don't reach the ground while they eat. It's OK if it can't be fixed.

- [ ] Animals such as pigs and rabbits should be able to give birth in litters; ranging from 2-5, I guess. Maybe rabbits can only give birth to 1-3, since we all know how much they love to breed.

- [ ] Hay bales should probably work as a food source as well, since they're made of wheat, which nearly everything in the mod eats.

- [x] (I don't know the eating mechanism for goats.) Goats should be able to be hand fed stuff like strings and stick. (Remember, I don't know how goats eat this, I may be wrong.)

- [ ] Ferrets are attacked by roosters. However, roosters should probably chase away the ferrets, and the ferrets could probably flee from them as well. Roosters could also return to the nesting location.

- [ ] Small chance that when something attacks a hedgehog the attacker is slightly hurt back. (Hedgehogs are covered in those quills and spikes, its gotta hurt at some point.)

- [ ] Another suggestion of simply improving the way it looks similarly to the horses, rams and bucks (goat bucks) shouldn't have their heads phase through each other whenever they spar. And just like the horses, if this can't be fixed, then it's OK.

That's it! Those are what I believe would be enhancements that would fit in Animania pretty well! Once more, I'll edit these depending on my experience throughout playing the mod.

**Comment by capnkirok** [comment]
Thanks for the suggestions. On 1.11+ and 1.12+, you can set whatever you want the goats to eat. 

I've added sticks and string to the default (that was missing, thanks), but since you've already created a config file, you'll have to do it manually (or delete your config after you download the update).

**Comment by epicslayer999** [comment]
No problem! I'll make sure to delete the config and have 1.3.1 create a new one.

**Comment by lsi5974** [comment]
In RL a wild ferret will actually kill and eat the chickens.  Ferrets, like cats, are obligate carnivores. They cannot survive without meat in their diet.

Another suggestion for the list is manure, either make the bigger animals defecate and use it for fertilizer or get some compatibility for the mod pig manure.  I personally would rather see this added to the mod just to make it more complete.

**Comment by capnkirok** [comment]
Hey @epicslayer999 these are on our suggestions list now. In an effort to clean up this git, I'm going to remove this so git only shows bugs. Thanks for the suggestions!
