### ISSUE TITLE
Bugs N' Suggesstions

### ISSUE THREAD

**Issue by xiinos** [capnkirok/animania#33]
**Bugs**
>> When you use a water bucket to fill a trough or directly feed an animal, the empty bucket can no longer be filled. [Creative Only]

>> Hamster Whisperer Achievement seems to be broken.

>> Friesian calves have a pink spot on the side of their butts!

**Suggestions + Ideas**
>> Add ability to place down Pumpkin, Melon, and Beetroot seeds?

_I'm going to list some breeds that I remember from my Animal Science classes, I don't expect to see all of them added in, but definitely check them out as some are pretty cool looking! I'd suggest some breeds for planned animals but I'm going to wait until they're released._

>> Possible Cows:  Jersey, Brown Swiss, Ayrshire, Shorthorn, Brahman, and Highland.
>> Possible Chickens: Silkie, Sussex, Ancona, and Pekin.

**Comment by capnkirok** [comment]
- Fixed Hamster Whisperer Achievement

**Comment by xiinos** [comment]
I never noticed the empty bucket in creative thing until now haha

**Comment by capnkirok** [comment]
FYI, I noted the breeds down for later...
