### ISSUE TITLE
Animania Crashes Game

### ISSUE THREAD

**Issue by Popplia** [capnkirok/animania#331]
My game repeatedly crashes at the loading screen.
This is what Minecraft told me as to why:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Animania (animania)

This was the new 1.11.2 version uploaded a few hours ago (for me)

I unfortunately have to remove Animania ;( Please fix this bug soon!
I hope I helped by reporting this bug!

**Comment by Tschipp** [comment]
Have you installed the craftstudio api?

**Comment by capnkirok** [comment]
Link here: https://mods.curse.com/mc-mods/minecraft/268704-craftstudio-api#t1:other-downloads

**Comment by capnkirok** [comment]
Sounds like you fixed this, since you are playing the game now :), so closing.
