### ISSUE TITLE
Water Trough seems to be not working correctly

### ISSUE THREAD

**Issue by D3nnis3n** [capnkirok/animania#332]
Hello,
i tried out your mod for the first time.

I filled a trough with water and as soon as an animal Comes near, the trough is depleting really fast - but the animal is still thirsty. Okay, i hooked up an ultimate tank of mekanism full of 112 Buckets of water with a pipe. As soon as an animal that is thirsty Comes nearby the through is depleting - and it's pulling all 112 buckets of water until its empty, but the animal is still thirsty.

Is there a bug or are animals really supposed to drink 112 Buckets of water and still not being satisfied? :D

**Comment by Tschipp** [comment]
Which version are you using? If you're using 1.3.1 for 1.10 you need to update to 1.3.1a

**Comment by D3nnis3n** [comment]
Hey, i'm using 1.3.1 for 1.12.1.

Am 19.09.2017 06:54 schrieb "Tschipp" <notifications@github.com>:

**Comment by capnkirok** [comment]
I'll take a look @Tschipp

**Comment by cursinorock** [comment]
Same here
Forge: 1.11.2-forge1.11.2-13.20.1.2476
Animania: animania-1.11.2-1.3.1

**Comment by capnkirok** [comment]
Yup, looks like Sheep, Goats, and Rabbits were insatiable. We will patch this tonight.
