### ISSUE TITLE
Hamsters, Ferrets, and Frog Ideas 

### ISSUE THREAD

**Issue by Popplia** [capnkirok/animania#333]
I've been searching for some good hamster mods for a while now, and this one is AMAZING!
I have a few suggestions, since these hamsters seem domesticated but free roam?

- Hamster Cages! ( Four Glass Panes + Sticks + Cobblestone = Hamster Cage ) (Wheat + Sticks = Bedding ) When you're going adventuring, or simply leaving your lil' buddy alone for a bit, just plop him/her into their cage.

- Hamster Cage Accessories! ( Water Bottle + Right-Clicking on cage = Adding water bottle to cage ) You can change the water every so often when it looks low, ( Wooden Bowl + Seeds or Hamster Food Mix = Food Bowl ) You also need to feed your new pet, and keep them happy! ( Wooden Bowl + Sticks = Hamster Wheel ) They need plenty of exercise, even if you take them out in their hamster ball/ free roam.

-  Ferret Cages / Enclosures ( Four Glass Panes + Sticks + Cobblestone = Ferret Cage ) Keeping your ferret in their enclosure/cage can be beneficial to your other animals and your ferret, should they not be able to control their egg-stealing urges. 

-  Ferret Beds & Toys ( Any Color Carpet + Same Color Wool Blocks = Ferret Bed ) They can cuddle together, play together! You can hand feed them, or let them run amok and find their own food. ( 2 Wood Planks in Horizontal Direction = Ferret Chewing Block )

- Frog Enclosures ( 4 Glass Panes + Sticks + Cobblestone = Frog Enclosure ) Fill it partially with water and place Stone Blocks into it to create some landings to sunbathe on. Place some Sheared Leaves in to add a touch of greenery! Add some Glowstone for a sunlight. 

I really put some thought into what would be something important that realistic animals would have, and VOILA!

I hope you take some of my ideas into account, and maybe even like them :)

Thank you! And please don't feel obliged to put these into the mod, I know making these kinds of things take a while, so thank you for all your hard work!

**Comment by capnkirok** [comment]
Thank you for the suggestions Popplia!

- We actually have a Water bottle made, it's just not enabled in the game.
- There are already Hamster Balls and a Hamster Wheel... they are great, check them out.
- Did you know that tamed animals (ferrets, hamsters, or hedgehogs) can ride on your shoulder? Just sneak + right-click.
- Agree the ferrets could have some more fun stuff to play with
- I like the 'Terrarium' idea for the frogs :)

**Comment by capnkirok** [comment]
Hey @Popplia this is on our suggestions list now. In an effort to clean up this git, I'm going to remove it so git only shows bugs.
