### ISSUE TITLE
1.10.2-1.3.1 too many animals

### ISSUE THREAD

**Issue by dskw** [capnkirok/animania#336]
Since updating to 1.3.1 yesterday all active chunks get spammed with animals.
I have already tuned down the spawn settings a lot but it looks like all animals are spawned with 100% chance, quickly reaching the individual limit per chunk.

I'm playing the Homestead modpack from ATLauncher and just replaced animania with the latest version:
https://www.atlauncher.com/pack/Homestead

Killing the animals does not help since they just respawn a while later.

```
[...]
spawn {
    I:"Number of potential Chicken families per chunk"=1
    I:"Number of potential Cow families per chunk"=1
    I:"Number of potential Goat families per chunk"=1
    I:"Number of potential Horse families per chunk"=1
    I:"Number of potential Pig families per chunk"=1
    I:"Number of potential Rabbit families per chunk"=1
    I:"Number of potential Sheep families per chunk"=1
    B:"Spawn Animania Amphibians in world"=false
    B:"Spawn Animania Chickens in world"=true
    B:"Spawn Animania Cows in world"=true
    B:"Spawn Animania Goats in world"=false
    B:"Spawn Animania Horses in world"=true
    B:"Spawn Animania Peacocks in world"=true
    B:"Spawn Animania Pigs in world"=true
    B:"Spawn Animania Rabbits in world"=false
    B:"Spawn Animania Rodents in world"=false
    B:"Spawn Animania Sheep in world"=true
    I:"Spawn limit for Amphibians in loaded chunks"=0
    I:"Spawn limit for Chickens in loaded chunks"=2
    I:"Spawn limit for Cows in loaded chunks"=4
    I:"Spawn limit for Ferrets in loaded chunks"=0
    I:"Spawn limit for Goats in loaded chunks"=0
    I:"Spawn limit for Hamsters in loaded chunks"=0
    I:"Spawn limit for Hedgehogs in loaded chunks"=0
    I:"Spawn limit for Horses in loaded chunks"=2
    I:"Spawn limit for Peacocks in loaded chunks"=2
    I:"Spawn limit for Pigs in loaded chunks"=2
    I:"Spawn limit for Rabbits in loaded chunks"=3
    I:"Spawn limit for Sheep in loaded chunks"=4
    I:"Spawn probability Chickens"=16
    I:"Spawn probability Cows"=12
    I:"Spawn probability Ferrets"=10
    I:"Spawn probability Frogs"=10
    I:"Spawn probability Goats"=10
    I:"Spawn probability Hamsters"=12
    I:"Spawn probability Hedgehogs"=10
    I:"Spawn probability Horses"=12
    I:"Spawn probability Peacocks"=20
    I:"Spawn probability Pigs"=12
    I:"Spawn probability Rabbits"=11
    I:"Spawn probability Sheep"=12
    I:"Spawn probability Toads"=10
}
```

**Comment by dskw** [comment]
Tried to make a screenshot to demonstrate the problem

![2017-09-19_19 52 37](https://user-images.githubusercontent.com/5196016/30607114-3acb3394-9d74-11e7-8093-134a806c5ca5.png)

**Comment by capnkirok** [comment]
Thanks! Will find a way to tone it down...

**Comment by twoworlds** [comment]
Had this issue on my 1.12.1 server, too. We had 25 different sheep spawning in a  4 by 2 house, causing them to glitch through the walls.

**Comment by CharCharthemonkey** [comment]
@capnkirok this is exactly the same issue (minus the glitching through houses) that i listed in my issue deal too

**Comment by capnkirok** [comment]
Ok, just did some testing here on a server. Here's what I found:

- The default spawn limits are too high (I will change this)
- However, the spawn limits seem to be working, and I was able to control the population

Question, are you updating the config on the server? That is the one that matters.

![image](https://user-images.githubusercontent.com/9628379/30616495-af355e4e-9d92-11e7-8db7-0d0552edf81d.png)

**Comment by capnkirok** [comment]
![2017-09-19_23 29 30](https://user-images.githubusercontent.com/9628379/30616532-cc68796a-9d92-11e7-857e-4d98c90fa60e.png)

**Comment by capnkirok** [comment]
I will update the default spawn limits... but also make sure you delete or reset your config after updating.

**Comment by dskw** [comment]
Hey thanks for looking into it!

Before reporting the issue I made sure to remove the old config and let the mod create a new one, then restarted the server again and the result was nearly 10 of each animal kind per chunk, more or less killing my server :/

So I changed the spawn settings to what you see there, restarted and even went away to let the mobs despawn but they soon reappeared as see
![2017-09-19_23 49 03](https://user-images.githubusercontent.com/5196016/30617172-246f57a8-9d95-11e7-9341-fdd8e00d14d7.png)
n in my screenshot.

I've attached a debug shot in case it helps. Btw: is that behaviour normal? The animal cluster I mean :D Guess this is dues to the puddle being the only water around.

**Comment by capnkirok** [comment]
Yeah, you might be on to something with that puddle cluster... but the default config is way too high, which explains the issue. You have 173 entities, which is way to high. You'll need to delete your config again after the update (version 1.3.2, should have it in about an hour-ish).

**Comment by dskw** [comment]
Perfect, I'll try it out tomorrow (1am over here) and let you know if it helped! Thanks a lot

**Comment by dskw** [comment]
Final note: Animals now spawn with realistic numbers (ususally ~ E: 13 / 82)
Thanks again for the fix!
