### ISSUE TITLE
Can't milk my cows

### ISSUE THREAD

**Issue by RunaGem** [capnkirok/animania#337]
I am playing on 1.11.2 and have just updated to Animania 1.11.2-1.3.1. Before the update I was able to milk cows just fine, but now that i've updated I can no longer get any milk from them. They are fed, and watered, and are also by a food and water source just in case my hand feeding them wasn't enough anymore, but I still can't get any milk.

Is this a bug or is there new requirements i'm not meeting for my cow friends to be happy?

**Comment by Tschipp** [comment]
Cows require to have a calf to give milk. We suggest you install TOP or Waila to see this additional information

**Comment by RunaGem** [comment]
OHHHH! Okay that's fun and exciting. makes perfect sense too. Thank you! I have WAILA but it didn't mention the Calf. How long after birthing can they produce milk?

**Comment by capnkirok** [comment]
Almost immediately after giving birth they can be milked :), and birthing takes just under 1 MC day.

When the COW is Milkable, WAIlA will tell you (you have to SNEAK while looking at the COW).
