### ISSUE TITLE
Draft Horse Ideas

### ISSUE THREAD

**Issue by epicslayer999** [capnkirok/animania#338]
So, after doing some research, I found out that draft horses are horses specifically to do slow heavy work, such as pulling carts, for example. Draft horses in Animania are, at the moment, just better cheaper vanilla horses that breed on their own instead of needing golden apples and only require the craftable riding crop to simply RIDE them. So, here are some suggestions on things draft horses can do:

- [ ] Pull wagons. (already planned I believe)

- [ ] Help out plowing fields.

- [ ] Other types of things like this thing called "logging".

Here is a source for logging and that.

https://en.wikipedia.org/wiki/Draft_horse

Don't feel obliged to do this, draft horses are already good, these are just some ideas.

**Comment by capnkirok** [comment]
Ooh, I hadn't heard of logging before. We actually have a plow/till model made, and a couple of wagons in progress. I've noted this down, thanks! Keep an eye out for the next major release.

**Comment by epicslayer999** [comment]
Thanks! Can't wait to see draft horses come into use! :D
