### ISSUE TITLE
Vanilla Horse Rework

### ISSUE THREAD

**Issue by epicslayer999** [capnkirok/animania#339]
Animania reworked just about all farmable wild animals except for regular horses. Draft horses are a different type of horse, mostly made for slow heavy work. Minecraft's regular horses appear to resemble the regular horse people directly ride in. Animania's draft horses could be unique enough to be an entity of their own, but an Animania-style regular horse with stallions, mares and foals would be cool!

Don't feel forced to do this, it's just a fun idea.

**Comment by capnkirok** [comment]
We do have other horses planned, and a lot left to do with the Draft Horses. The horses that are in MC now are pretty well done imo (they were originally made by an outside modder, btw). In a future update, we're going to provide a way to replace vanilla as well and will continue to grow the current stable (pun intended). But just so you know, it is on the list :)

**Comment by epicslayer999** [comment]
Awesome! Also, I'd recommend they keep the vanilla skins, people like those (such as myself).
