### ISSUE TITLE
problem with milk/meats & vanilla recipes! 

### ISSUE THREAD

**Issue by brblostmycrayons** [capnkirok/animania#34]
hi, love! i adore this mod so much, but  i've encountered something that makes things a little difficult! 
since animania replaces vanilla cows, pigs, and chickens and also gives specific milk and meats from the different breeds it complicates recipes between vanilla and other mods! 

a lot of recipes include milk but the cows in the mod give milk _(friesian)_ and milk _(holstein)_ which means, for example, i can't make cake! or many other recipes from, i think, pam's harvestcraft. i noticed there is at least one mod that has included your different kinds of meats into their recipes but it blocks any vanilla and other mod recipes from being made. mega sad face! 

i don't know how to fiddle with mods and see if there's a way to make it compatible but i think the easiest way, and perhaps may i make as a suggestion, remove the different kinds of milk and meats across breeds? i think it's diverse enough considering for meat there's already beef, pork, and chicken! so if possible i'd suggest making all the mod animals drop normal vanilla materials - so all the cows just produce milk and beef plainly and whatnot. that way we can have all our food recipes!

i know this mod is pretty new and i love it so much, so i hope this helps a lot. new materials being added to drops is totally fine, but i suggest keeping vanilla drops as well so as to not bar vanilla and other mod recipes! thank you so much for all your hard work and i really look forward to what is surely to come! more diversity in mc when it comes to animals is always appreciated.

oh! if you decide to take up my suggestion don't forget to look at the recipes added by your mod! the recipe for slop will have to be edited to take vanilla milk along with the vanillia carrot and potato. ^^
and cheese!

**Comment by capnkirok** [comment]
Thank you for the feedback! Yes, we're going to add a config option to drop just vanilla items. We're also putting our items in OreDictionary so that other mods can use them.

Finally, you can use vanilla milk to make slop. It just doesn't show in JEI... try it out.

Thanks again!

**Comment by capnkirok** [comment]
Fixed in Dev, will be added in 1.0.1 coming shortly.
