### ISSUE TITLE
umm idk if this is really an issue but after updating to 1.3.2 animania in 1.12.1

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#340]
![2017-09-19_22 54 06](https://user-images.githubusercontent.com/30783285/30654784-9c6f0d34-9df4-11e7-923f-cc08b326e1cd.png)
that showed up in chat for the "update"

**Comment by epicslayer999** [comment]
Yeah, that seems to happen.

**Comment by CharCharthemonkey** [comment]
but im on the 1.3.2 version and its telling me to "update" to 1.3.1 lol so umm guessing minor bug

**Comment by capnkirok** [comment]
Yeah, that's a bug. Sorry. You can turn off the message if you want in the
config.

**Comment by CharCharthemonkey** [comment]
noted and ty @capnkirok

**Comment by CharCharthemonkey** [comment]
forgot to ask if it will be fixed possibly?

**Comment by capnkirok** [comment]
What version are you running? 1.10 -> 1.12?

On Wed, Sep 20, 2017 at 6:20 PM, CharCharthemonkey <notifications@github.com

**Comment by CharCharthemonkey** [comment]
im running 1.12.1 atm also ran into an issue with goats too

**Comment by CharCharthemonkey** [comment]
the issue with goats is trying to give them water in a trough causes massive FPS lag when using something to auto import water

**Comment by CharCharthemonkey** [comment]
found out my goat issue is #344 also

**Comment by capnkirok** [comment]
Hey guys, this should be fixed. At least I am not seeing it with version 1.3.2. Can you pls verify?

**Comment by capnkirok** [comment]
Ok, to be clear, the update notification issue should be closed. Working on the drinking, but that is tracked elsewhere, so closing this.
