### ISSUE TITLE
Can't make cheese

### ISSUE THREAD

**Issue by Syferia** [capnkirok/animania#341]
I can't make cheese in any inventory, and when I have a pet hamster sitting, it teleports to me

**Comment by Tschipp** [comment]
Cheese is made by placing milk in the cheese mold and waiting. (Holstein, Friesian, Goat and Sheep). Unfortunately the forum post is currently quite outdated, we’re working on that

**Comment by capnkirok** [comment]
Hi @Syferia what version of Animania and what version of Forge are you on?

**Comment by capnkirok** [comment]
In 1.10, you need to combine a bucket of animania milk with a cheese mold in a crafting table
In 1.11 and 1.12, you need to place a cheese mold on the ground and pour the milk into it, where it ages until it is ready.

**Comment by capnkirok** [comment]
Closing this, as Cheese Making is working fine on all versions
