### ISSUE TITLE
Peafowl not eating growing seeds?

### ISSUE THREAD

**Issue by PurpleHel** [capnkirok/animania#342]
So I have my peafowl in an enclosure, with a 2x2 square pond surrounded by growing wheat. They keep getting weakness. Can they not eat growing seeds? (In the attached screenshot, I put seeds on the ground for them.

If they can't, if I set up a dispenser to throw seeds out, will they eat those? Or do the seeds have to be right clicked onto the ground for the peafowl to eat the seeds?
Thanks!

http://imgur.com/gallery/ODK2S

**Comment by Tschipp** [comment]
Dispensers can place the seeds. Just put down a dispenser facing upward and put it on a clock.

**Comment by capnkirok** [comment]
But they should be eating seeds. Will take a look. Thank you for the report
(and the screenshot)

**Comment by capnkirok** [comment]
Hey @PurpleHel I checked on all Animania 1.3.2 versions (1.10 - 1.12) and the Peafowl are all eating correctly. Keep in mind they don't immediately rush to eat when they get hungry, the AI has a more natural cycle. 

Are they moving around, or do they seem stuck in one place to you? And are you on 1.3.2? Thanks for your help!

**Comment by PurpleHel** [comment]
I am on 1.3.2, I updated before posting. I swear I know to include version when reporting stuff, I'm just beyond brain fried this week. (Spent my weekend driving from DC to Chicago and back to rescue a suddenly homeless cos of breakup friend. It does not make for a good worky brain.)

They are walking around their enclosure, which is about 5x12, but don't seem to be touching the wheat I planted for them. If I don't manually place seeds on the ground rather than plant them, or have a dispenser placing seeds, the peafowl get weakness. There's also no indication that they are ever touching the planted wheat.

I am understanding correctly, right? They are supposed to be eating *planted* wheat? And shouldn't be going so long between meals as to get weakness?

**Comment by Tschipp** [comment]
They don’t eat planted wheat. Just seeds on the ground.

**Comment by capnkirok** [comment]
You can just right click grass while holding seeds and it will automatically scatter them on the ground. See if that makes a difference..?

**Comment by PurpleHel** [comment]
Ok, I was misunderstanding then!

**Comment by capnkirok** [comment]
Ok, glad it worked out! Closing this :)
