### ISSUE TITLE
Animania 1.3.2 on MC 1.12.1 server - Sheep always thirsty

### ISSUE THREAD

**Issue by twoworlds** [capnkirok/animania#343]
Hi,

with the 1.3.2 update the spawn rates seem to be fine. But I found another problem. If i feed water in troughs to sheep, they drink but are always thirsty. If i feed them water from a bucket, they a well fed.

It seems, that sheep can't drink from natural water or from troughs. So i have seen many sheep gathering in lakes but always show "thirsty". 

https://imgur.com/a/omUcI

They go to the trough and consume water but are always thirsty

**Comment by capnkirok** [comment]
Was pretty sure we fixed this in 1.3.2, but I will check it out. Thanks for reporting.

**Comment by twoworlds** [comment]
Here is what I did:

I downloaded 1.3.2 again, deleted the mod and the config on my server and client. I restarted the server and checked, that the config file was created. 

I put two sheep in a closed surrounding and checked one hour later. You can see the result in the first picture:
https://imgur.com/a/zEpzb
(Don't look at the pink futura blocks, this is my daughters build ;)

When I move around I finde many sheep inside pools or ponds (see picture 2+3) Strangely they are all thirsty. 

Until now I haven't seen a cow and only a few pigs, so this problem seems to be with sheep only ?

One thing I saw, that the animals are often glitching through solid blocks (see picture 4).

Thanks for your hard work !!!

**Comment by epicslayer999** [comment]
#344

**Comment by capnkirok** [comment]
Will be fixed tonight.
