### ISSUE TITLE
I know the problem with sheep drinking!

### ISSUE THREAD

**Issue by epicslayer999** [capnkirok/animania#344]
I did F3+B to show the hitboxes, and I realized; the hitboxes of the sheep are too big, and they detect the water before they are actually within range. So, the hitboxes are too big and don't seem to let them the part of the sheep that lets it drink water get into the troughs/lakes.

**Comment by capnkirok** [comment]
You may be right @epicslayer999 thanks for the diligence. Checking...

**Comment by CharCharthemonkey** [comment]
weirdly i saw the same thing with rabbits where the hitbox would show b4 they were near water so they didnt drink/eat anything like the goats idk if it helps or hinders things (tho with rabbits they dont cause massive FPS loss like the goats do when they try to eat or drink)

**Comment by capnkirok** [comment]
Well, this was not the problem, but I did solve it :)

Patch coming tonight with a bunch of water fixes.

**Comment by epicslayer999** [comment]
Awesome! Hope this helped in some way.

**Comment by capnkirok** [comment]
It definitely did. I ended up doing a full test of the code as a result and found the issue.
