### ISSUE TITLE
minor issue with animal names in 1.3.2 

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#345]
![2017-09-21_12 18 09](https://user-images.githubusercontent.com/30783285/30712547-00fbce8a-9ed2-11e7-89c1-30d763052b12.png)
idk if this actually counts as an issue but figured its atleast worth mentioning

**Comment by capnkirok** [comment]
Yeah, this one is fixed in Dev, saw it two days ago on Darkosto's stream.

**Comment by CharCharthemonkey** [comment]
ty bunches
