### ISSUE TITLE
not as much an issue as a question

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#346]
for animania is it possible to make the chickens the same as the vanilla ones or no? i ask cause a recipe from another mod needs a chicken in a lasso for a ring but it requires a vanilla chicken and was wondering if that was either an animania thing or XU2 thing for it but figured id ask plz and ty for any info on this

**Comment by capnkirok** [comment]
Animania chickens extend the vanilla versions. So, I would check with the other mod author, as they can easily use ours.

Alternatively, you can also change the Animania config to not replace the Vanilla chickens, but that looks really weird imo. Recommend you reach out to the other author.

**Comment by Tschipp** [comment]
Alternatively, you can edit the recipe with Minetweaker to use our chickens.
