### ISSUE TITLE
Is it possible to get vanilla milk anymore?

### ISSUE THREAD

**Issue by epicslayer999** [capnkirok/animania#347]
Just a question, is it even possible to get vanilla milk anymore? I just want to know, since without counting enabling vanilla mobs in the config (which I don't want to do) milking cows gives you "Holstein Milk" and "Friesian Milk" and that.

**Comment by capnkirok** [comment]
You can place Holstein Milk into the crafting table and get Vanilla Milk. All the milks are in OreDictionary so they should work in all other recipes regardless.

**Comment by epicslayer999** [comment]
Thanks for the info.
