### ISSUE TITLE
Snowing

### ISSUE THREAD

**Issue by bob0bob** [capnkirok/animania#348]
When it snows,   a snow block appear over the trough.  Its funny looking because the snow appears in the next block so there is a gap between the trough and the snow.   

Water in trough doesn't freeze when all the water in the biome is frozen from frigid water????  Maybe a thought for future.

**Comment by capnkirok** [comment]
Ok, part 1 is fixed in the 1.3.6 release.

**Comment by capnkirok** [comment]
Looks like this was only an issue on 1.12, they changed the snow layer conditionals...
