### ISSUE TITLE
[Suggestion] RF generated by hamsters!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [capnkirok/animania#35]
This mod needs a funny machine, a RF generating machine powered by hamsters. Each hamster breed gives a different RF value and can only be powered by so long (they die or something...)

**Comment by Thyriel** [comment]
Lol somehow i love that idea ;)

**Comment by capnkirok** [comment]
Ha ha ha! I love it. Let me strategize with Razz :)

**Comment by InkDragon** [comment]
Ooo rather then die can they just stop until they are feed and are happy again?
that way it works into the already existing happiness mechanic

**Comment by capnkirok** [comment]
Guys.... this is going to happen...

**Comment by InkDragon** [comment]
this is beautiful ;.=.; can not wait to see tiny hamsters running on treadmills or in wheels waiting to generate RF to power my tiny farm

**Comment by Guinaro** [comment]
Really love the idea, this will the first "machine" you would need to build to start up your RF utilities, everything will be gated behind this Hamster RF Production machine.
Also make those machines produces more RF at night, as they are nocturnal animals after all.

**Comment by MokahTGS** [comment]
Yes, this needs to be a thing.  I want a grand hamster wheel powered reactor.
