### ISSUE TITLE
[1.3.2/MC 1.12] Too much Frogs/Toads 

### ISSUE THREAD

**Issue by hron84** [capnkirok/animania#350]
In my current custom pack and seed, I living in a Plains biome, next to a Roofed Forest, close to a Savannah and a Desert too. I can see a ton, literally a ton of Toads next to every lake/river, however I cannot see Hamsters, Ferrets or Hedgehogs. Also, it seems like there is no other natural enemy for Toads so they spawn up to some limits, but this limit seems affects all other animals too. 

I also played with Sprout, which has Animania 1.2.1 where I could see these animals to spawn. Is this something that Sprout tweaked, or is there any way to decrease Toad spawning to not overrun other small animals?

**Comment by capnkirok** [comment]
Hey hron84! 

- You can adjust the spawn settings in the in-game config. Decrease the spawn limit and lower the probability they spawn. This could in fact be a conflict with another mod or Sprout.
- Hens and Roosters will happily gobble up your extra toads. You can use our other mod, Carry On, to carry a few over there for a nice meal
- Hedgehogs spawn only in Forests, Hamsters in Deserts or sandy areas, and Ferrets in Savannas. You can adjust spawn rates of all animals in the config.

Out of curiosity, how many Toads are you seeing? And what is your limit set to?

**Comment by hron84** [comment]
I've all settings, defaults.  In the in-game config, I cannot see Frogs/Toads limit, so I assume it's between 40-60.
![2017-09-23_17 20 36](https://user-images.githubusercontent.com/88636/30774495-9e8ca478-a083-11e7-8dd1-27b73df064b0.png)

I'm just curious: would it be possible to make Hedgehogs spawn in Roofed forest too? Technically, they are more close to Forest than Swamp.

**Comment by capnkirok** [comment]
Oh my god, that is way too high. You have the old settings from 1.3 launch. I recommend you delete your config file and restart the game. That should fix it!

SpawnLimitAmphibians is what you are looking for and it should be somewhere around 15 I think, but you'll see what the new default is after you restart :)

**Comment by hron84** [comment]
Ohh, I see. Yeah, I upgraded your mod step-by-step as i get update notification in my chat, but did not reset configs.

**Comment by hron84** [comment]
@capnkirok could you also provide a proper tooltip to this limit? "Amphibians" is not the word that's easy to understand for a non-english speaker. Like: "Limits spawning for ambient creatures like frogs or toads"

**Comment by capnkirok** [comment]
Hey, we found an additional problem with Frogs and Toads causing extra spawning. Something to do with them being Ambient creatures increase the rate. We've changed their type and put in tighter controls.

Will be in tonights update.

**Comment by hron84** [comment]
@capnkirok i will definitelly look into the 1.3.4 update, because after limiting amphibians to 12 i still got a ton of frogs/toads preventing to spawn any other mob. I had to disable them completely.

**Comment by capnkirok** [comment]
@hron84 The 1.3.4 update is better, but now I have a de-spawning problem. May want to wait until 1.3.5.

**Comment by hron84** [comment]
@capnkirok I had no chance yesterday to update, but it seems like it's ok. Then I wait for 1.3.5.
Btw, should I worry about my shiny new albino hedgehog?

**Comment by capnkirok** [comment]
Well, you can always give everything you want to keep a name just to be sure.
