### ISSUE TITLE
[SUGGESTION] Support for modded shears, and dyeable goats and sheep

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#351]
1. Would it be possible to bring back the ability to dye sheep from vanilla, and apply it to angora goats too? Considering how you are trying to be a bit realistic though, dyed sheep and goats should not carry their color onto offspring.

2. Would it be possible to add support for shears from other mods? Roots, ceramics, thermal expansion, and botania come to mind.

**Comment by capnkirok** [comment]
1. Yes, in progress
2. Yes

**Comment by epicslayer999** [comment]
What? Roots shears work just fine for me.

**Comment by capnkirok** [comment]
#2 will be in next release. Basically, if it's an instance of ItemShears then it will work. I assume all of these extend/modify the vanilla version (or they wouldn't work).

**Comment by capnkirok** [comment]
I'm going to close this one. Dyable sheep is on the feature list for 1.4.

**Comment by LunariusH** [comment]
Such a shame, I was hoping you'd add a dyeing tub instead. ;)
