### ISSUE TITLE
carving knives remains when repaired in the crafting bench

### ISSUE THREAD

**Issue by Deing-Young** [capnkirok/animania#352]
Nothing big, but when I tried to repair a damaged carving knife (the knife you use to slice meat, 1.10.2, animania 1.3.3) by placing two damaged carving knives in the carfting bench, not only do I get a fully repaired one, but the two damaged knives used in the recipe does not disappear, instead their durability go down by one, and I could pull out another repaired carving knife. Thus if I only craft two of these knives, I can get loads of them without having to consume any other iron.  
As a Chinese who only signed up on Github today, please excuse me if I made any mistakes here or there. And I do hope that you could fix this bug.

**Comment by capnkirok** [comment]
Ahh thanks for the head up! I understood your message perfectly.

D

**Comment by Deing-Young** [comment]
Great!

**Comment by capnkirok** [comment]
I'm disabling repair in the crafting table, but you can still use the Anvil.
