### ISSUE TITLE
Breeding, Disappearing, Bulls Aggro, Range

### ISSUE THREAD

**Issue by bob0bob** [capnkirok/animania#354]
I have many issues.  I'm new to this mod.
I've created a fence pen to keep cows in and the fence doesn't keep cows in.  They can easily get out of the fence.
Second,  They breed like rabbits.  I mean.   I started with 4 cows and 4 days later,  I have 30+ cows.  So many that they are now popping out of the fence.   Is there a way in the config to reduce how much they breed.  
Third,  Are Bulls even when the pen is empty suppose to be get out of the fence area when you hit them?
Fourth,  Bulls can hit you about 3 - 4 blocks away.   I find the bulls the most powerful mob in minecraft.   I've even tried standing on a stack of dirt 3 high to kill the bull with an arrow and it still killed me from the ground.
fitfh,  is a bull suppose to never give up on the chase?  I find a bull will never quick until you are killed.
sixth,   I've even been killed from inside a home through a wall from a bull outside of a house.
seventh,   I've had a trough just disappear.  DOn't know if that is your fault or not.  I came back from a save and the trough in the pig pen was gone.

How about changing breed to be affected by the size of their pin.   There ends up so many cows in the pen that there is no room to move.
Also,  maybe this is random.  Not sure.  But the number of bulls are about 60% of the new births on my game.  Don't know if this is that random.

Sorry for putting so many issues into one item.

**Comment by Tschipp** [comment]
What version are you using?

**Comment by capnkirok** [comment]
1. This is a hitbox issue. If there are too many packed into one place, they will bounce each other out. I need to work on this. This also happens when the game is reloaded from save (it places them differently).

2. Sounds like you might have an old config file, because they shouldn't breed that much in such a short period any more. Would recommend you delete your config file and restart your world, you may lose a few cows in the process.

3/4. Sound similar. I haven't seen this problem before.

5. They give up on the chase, but you have to sprint and create separation. How old is the version you are using, because I slowed them down sometime in version 1.2

6. This distance they hit should have reduced, but I can test.

7. Don't know about this one.

Changing size may happen later when we add more genetics. It's just random that 60% are bulls. It's straight 50/50 in the code.

**Comment by bob0bob** [comment]
version 1.3.3

First version I've every used.

I am 100% positive a bull can kill you while in a house.  It can hit you through walls.  Don't know if it is walls or glass windows.  but there is no check between me and the bull to see if there is a object that prevents the hit.

**Comment by bob0bob** [comment]
![2017-09-26_20 43 46](https://user-images.githubusercontent.com/30982580/30892010-e227c01c-a2fb-11e7-9515-70433e76fe0e.png)

Here is the screen shot of my version

**Comment by bob0bob** [comment]
Here is my config file.  It should be default config.  I've not altered it at all.

# Configuration file

general {

    gamerules {
        # Allow eggs to be thrown
        B:allowEggThrowing=false

        # Allow random mobs to spawn on Animania animals
        B:allowMobRiding=true

        # Allow dispensers to place seeds
        B:allowSeedDispenserPlacement=true

        # Allow the trough to be automated with hoppers/pipes
        B:allowTroughAutomation=true

        # Animals do not have to eat or drink
        B:ambianceMode=false

        # Animals starve to death when not fed and watered
        B:animalsStarve=false

        # Ticks that a Cheese takes to mature
        I:cheeseMaturityTime=24000

        # Enable recipes to exchange special meats for vanilla
        B:enableVanillaMeatRecipes=false

        # Multiplier for reducing fall damage when animals are leashed
        D:fallDamageReduceMultiplier=0.44999998807907104

        # Foods give bonus effects
        B:foodsGiveBonusEffects=true

        # Capacity of RF that the Hamster Wheel has
        I:hamsterWheelCapacity=200000

        # RF/tick that the Hamster wheel generates while in use
        I:hamsterWheelRFGeneration=20

        # Ticks that the hamster stays in the wheel before it needs more food
        I:hamsterWheelUseTime=900

        # Remove vanilla Chickens
        B:replaceVanillaChickens=true

        # Remove vanilla Cows
        B:replaceVanillaCows=true

        # Remove vanilla Pigs
        B:replaceVanillaPigs=true

        # Remove vanilla Rabbits
        B:replaceVanillaRabbits=true

        # Remove vanilla Sheep
        B:replaceVanillaSheep=true

        # Shift-Right-Click for Seed Placement
        B:shiftSeedPlacement=false

        # Show mod update notification at startup
        B:showModUpdateNotification=true

        # Show male parts (modesty flag)
        B:showParts=true

        # Show particles when animals are unhappy
        B:showUnhappyParticles=true

        # Food Items that can be placed in the trough
        S:troughFood <
            minecraft:wheat
            simplecorn:corncob
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
            harvestcraft:cornitem
            minecraft:apple
            minecraft:carrot
            minecraft:beetroot
            minecraft:potato
            minecraft:poisonous_potato
         >

        # Water blocks removed after large animals drink
        B:waterRemovedAfterDrinking=true
    }

    drops {
        # Set Custom Chicken Drop (if enabled)
        S:chickenDrop=animania:raw_prime_chicken

        # Allow Animania Chickens to drop Eggs
        B:chickensDropEggs=false

        # Allow Animania Chickens to drop Feathers
        B:chickensDropFeathers=true

        # Set Custom Cow Drop (if enabled)
        S:cowDrop=animania:raw_prime_beef

        # Enable Animal Drops from Config
        B:customMobDrops=true

        # Set Custom Dart Frog Drop
        S:dartFrogDrop=

        # Set Custom Ferret Drop (if enabled)
        S:ferretDrop=

        # Set Custom Frog Drop
        S:frogDrop=animania:raw_frog_legs

        # Set Custom Goat Drop
        S:goatDrop=animania:raw_chevon

        # Set Custom Hamster Drop (if enabled)
        S:hamsterDrop=animania:hamster_food

        # Set Custom Hedgehog Drop (if enabled)
        S:hedgehogDrop=

        # Set Custom Horse Drop (if enabled)
        S:horseDrop=minecraft:leather

        # Enable Animals Drop their custom meat types
        B:oldMeatDrops=false

        # Set Custom Blue Peacock Drop (if enabled)
        S:peacockBlueDrop=animania:blue_peacock_feather

        # Set Custom Charcoal Peacock Drop (if enabled)
        S:peacockCharcoalDrop=animania:charcoal_peacock_feather

        # Set Custom Opal Peacock Drop (if enabled)
        S:peacockOpalDrop=animania:opal_peacock_feather

        # Set Custom Peach Peacock Drop (if enabled)
        S:peacockPeachDrop=animania:peach_peacock_feather

        # Set Custom Purple Peacock Drop (if enabled)
        S:peacockPurpleDrop=animania:purple_peacock_feather

        # Set Custom Taupe Peacock Drop (if enabled)
        S:peacockTaupeDrop=animania:taupe_peacock_feather

        # Set Custom White Peacock Drop (if enabled)
        S:peacockWhiteDrop=animania:white_peacock_feather

        # Set Custom Pig Drop (if enabled)
        S:pigDrop=animania:raw_prime_pork

        # Set Custom Rabbit Drop
        S:rabbitDrop=animania:raw_prime_rabbit

        # Set Custom Sheep Drop
        S:sheepDrop=animania:raw_prime_mutton

        # Set Custom Toad Drop
        S:toadDrop=
    }

    spawn {
        # Number of potential Chicken families per chunk
        I:numberChickenFamilies=1

        # Number of potential Cow families per chunk
        I:numberCowFamilies=1

        # Number of potential Goat families per chunk
        I:numberGoatFamilies=1

        # Number of potential Horse families per chunk
        I:numberHorseFamilies=1

        # Number of potential Pig families per chunk
        I:numberPigFamilies=1

        # Number of potential Rabbit families per chunk
        I:numberRabbitFamilies=1

        # Number of potential Sheep families per chunk
        I:numberSheepFamilies=2

        # Spawn Animania Amphibians in world
        B:spawnAnimaniaAmphibians=true

        # Spawn Animania Chickens in world
        B:spawnAnimaniaChickens=true

        # Spawn Animania Cows in world
        B:spawnAnimaniaCows=true

        # Spawn Animania Goats in world
        B:spawnAnimaniaGoats=true

        # Spawn Animania Horses in world
        B:spawnAnimaniaHorses=true

        # Spawn Animania Peacocks in world
        B:spawnAnimaniaPeacocks=true

        # Spawn Animania Pigs in world
        B:spawnAnimaniaPigs=true

        # Spawn Animania Rabbits in world
        B:spawnAnimaniaRabbits=true

        # Spawn Animania Rodents in world
        B:spawnAnimaniaRodents=true

        # Spawn Animania Sheep in world
        B:spawnAnimaniaSheep=true

        # Spawn limit for Amphibians in loaded chunks
        I:spawnLimitAmphibians=12

        # Spawn limit for Chickens in loaded chunks
        I:spawnLimitChickens=12

        # Spawn limit for Cows in loaded chunks
        I:spawnLimitCows=12

        # Spawn limit for Ferrets in loaded chunks
        I:spawnLimitFerrets=12

        # Spawn limit for Goats in loaded chunks
        I:spawnLimitGoats=12

        # Spawn limit for Hamsters in loaded chunks
        I:spawnLimitHamsters=12

        # Spawn limit for Hedgehogs in loaded chunks
        I:spawnLimitHedgehogs=12

        # Spawn limit for Horses in loaded chunks
        I:spawnLimitHorses=12

        # Spawn limit for Peacocks in loaded chunks
        I:spawnLimitPeacocks=12

        # Spawn limit for Pigs in loaded chunks
        I:spawnLimitPigs=12

        # Spawn limit for Rabbits in loaded chunks
        I:spawnLimitRabbits=12

        # Spawn limit for Sheep in loaded chunks
        I:spawnLimitSheep=16

        # Spawn probability Amphibians
        I:spawnProbabilityAmphibians=8

        # Spawn probability Cows
        I:spawnProbabilityCows=10

        # Spawn probability Ferrets
        I:spawnProbabilityFerrets=8

        # Spawn probability Goats
        I:spawnProbabilityGoats=6

        # Spawn probability Hamsters
        I:spawnProbabilityHamsters=8

        # Spawn probability Hedgehogs
        I:spawnProbabilityHedgehogs=8

        # Spawn probability Hens
        I:spawnProbabilityHens=10

        # Spawn probability Horses
        I:spawnProbabilityHorses=10

        # Spawn probability Peacocks
        I:spawnProbabilityPeacocks=8

        # Spawn probability Rabbits
        I:spawnProbabilityRabbits=6

        # Spawn probability Sheep
        I:spawnProbabilitySheep=8

        # Spawn probability Pigs
        I:spawnProbabilitySows=10
    }

    careandfeeding {
        # Ticks before next incremental growth
        I:childGrowthTick=200

        # Food Items that cows can eat
        S:cowFood <
            minecraft:wheat
            simplecorn:corncob
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
            harvestcraft:cornitem
         >

        # Egg hatch chance (1/x)
        I:eggHatchChance=2

        # Ticks between dropping feathers
        I:featherTimer=12000

        # Ticks between feedings
        I:feedTimer=12000

        # Ticks between birthings
        I:gestationTimer=20000

        # Food Items that goats can eat
        S:goatFood <
            minecraft:wheat
            minecraft:string
            minecraft:stick
            simplecorn:corncob
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
            harvestcraft:cornitem
         >

        # Food Items that horses can eat
        S:horseFood <
            minecraft:wheat
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
            minecraft:apple
            minecraft:carrot
         >

        # Ticks between laying eggs
        I:laidTimer=2000

        # Food Items that pigs can eat
        S:pigFood <
            minecraft:carrot
            minecraft:beetroot
            minecraft:potato
            minecraft:poisonous_potato
            minecraft:bread
         >

        # Ticks between playing
        I:playTimer=4000

        # Food Items that rabbits can eat
        S:rabbitFood <
            minecraft:wheat
            minecraft:carrot
            minecraft:beetroot
            minecraft:apple
         >

        # Maximum uses of the salt lick
        I:saltLickMaxUses=200

        # Ticks between using Salt Lick
        I:saltLickTick=8000

        # Food Items that sheep can eat
        S:sheepFood <
            minecraft:wheat
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
         >

        # Ticks between animals taking starvation damage
        I:starvationTimer=400

        # Ticks between drinking water
        I:waterTimer=8000

        # Ticks before wool regrowth after shearing
        I:woolRegrowthTimer=8000
    }

    foodvalues {
        # Food Value Overrides
        S:foodValueOverrides <
         >
    }

}

**Comment by bob0bob** [comment]
mc 1.12.1

**Comment by Sunconure11** [comment]
This happens with goats and sheep sometimes though. I've also noticed large disappearances of goats and what not if enough are bred.

**Comment by capnkirok** [comment]
- The 'disappearance' was addressed in 1.3.5+. However, if you are upgrading from anything below that, name all the animals you want to keep (any name will do). After upgrading to 1.3.5+, the animals will no longer disappear.

- Overbreeding/spawning also addressed in 1.3.5

- Various bull issues are fixed in 1.3.6

- The fences not holding larger animals in is still a problem. I'm going to create a separate issue since this one is so off topic

**Comment by Sunconure11** [comment]
I'm not sure if this is connected, but I've noticed troughs disappear.

**Comment by capnkirok** [comment]
@Sunconure11 You necro'd a thread with a marginally related topic! No cake for you.

So.... troughs... talk to me... version... repro steps... any other clues?

**Comment by Sunconure11** [comment]
Version is latest on 1.11.2, but it's been happening for a few versions. No clue how to recreate it, it is very random. I do have forge set to remove erroring entities, and I have added more items to be allowed in the trough.

**Comment by bob0bob** [comment]
With 1.3.5, everything appears to be working again. I deleted the config.  I;ve not tested hitting the bull to see if he can still hit you through solid walls, but breading. chasing all seems to be working fine now.
