### ISSUE TITLE
Suggestion: Squirrels

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#355]
I'd like to suggest squirrels as ambient creatures, these would really spruce up the forests. There's some variety to be had as well.
- [Gray Squirrels](https://www.google.nl/search?q=gray+squirrels&source=lnms&tbm=isch)
- [Red Squirrels](https://www.google.nl/search?q=red+squirrels&source=lnms&tbm=isch)
- [Flying Squirrels](https://www.google.nl/search?q=flying+squirrels&source=lnms&tbm=isch)
- [Chipmunks](https://www.google.nl/search?q=chipmunk&source=lnms&tbm=isch)

**Comment by capnkirok** [comment]
Yes, squirrels are coming. Thanks for the links/breed suggestions.

**Comment by Deshiba** [comment]
@capnkirok cool!

**Comment by capnkirok** [comment]
Hey @Deshiba this is on our todo list. In an effort to clean up this git, I'm going to remove it from git for now, so git only shows bugs.
