### ISSUE TITLE
Hamster Wheel exceeds internal RF limit

### ISSUE THREAD

**Issue by BakermanLP** [capnkirok/animania#357]
Hello,

we tried the hamster wheel. And after some time, the hamster wheel exceeds the 200k rf limit.

Tested Version was animania-1.11.2-1.2.2

Can you fix that?

Thanks for reading

Michael (aka BakermanLP)

**Comment by Tschipp** [comment]
Oops.

**Comment by epicslayer999** [comment]
Umm.. This is Animania 1.2.2? Animania 1.3.3 is the latest version @BakermanLP , try updating to that.

**Comment by Tschipp** [comment]
It actually is in latest and has been in since we implemented the wheel
