### ISSUE TITLE
question also #341

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#358]
on the cheese thing can it be automated or is it only manual? odd question yes but was wondering cause if it could be automated then sweet but if not then would it be possible for a future idea?

**Comment by capnkirok** [comment]
Asking @Tschipp

**Comment by capnkirok** [comment]
Asking @Tschipp

**Comment by CharCharthemonkey** [comment]
thank you and i figured its better to ask 1st b4 trying and breaking something badly lol

**Comment by Tschipp** [comment]
yes
