### ISSUE TITLE
[SUGGESTION] Better milkable sheep plus milkable horses

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#360]
In many cultures, both sheep and horses are reared for milk. Would it be possible to add varieties of both that are reared for milk?

Horse breed for milk: Bashkir
Horse milk products: Kumis (Horse milk booze), horse milk cheese (this is a thing).

Sheep breeds for milk: Lacaune, Icelandic, Clun Forest, East Friesian, Chios, Sarda, Awassi, Zwartbles
Sheep milk products: Feta cheese, Roquefort cheese, Pecorino sardo cheese, yogurt

**Comment by epicslayer999** [comment]
Yes for horses, but based on my personal experience, ewes can already be milked after they've given birth. Also, making cheese is already a feature, although it's a generic "cheese". Yogurt does sound interesting though! Can't wait to see what the devs say.

**Comment by capnkirok** [comment]
Ewes can give milk now, but they need to have given birth first. Haven't thought about Horse Milk, interesting.

**Comment by capnkirok** [comment]
Hey @Sunconure11 I've add this to our suggestions list. In an effort to clean up this git, however, I'm going to remove it from git for now, so git only shows bugs. Thanks for the suggestion!
