### ISSUE TITLE
Genetics and Breeding

### ISSUE THREAD

**Issue by LunariusH** [capnkirok/animania#361]
I would love to see a system implemented where:
You start with wild Aurochs, Water Buffalo, Yaks, and other bovine relatives and have to capture these 'unrefined' breeds.  Each would have a mild benefit to one resource they produce, but none of them would produce very well.

By interbreeding these you could generate the other breeds, but that's just the start.  Once you have a breed available you can start improving your herd by interbreeding with animals with superior traits.

milkProduction: (How quickly the cow produces a unit of milk)
milkVolume: (Maximum units of milk a cow can hold)
meatProduction: (How quickly a cow bulks up)
meatVolume: (Maximum units of meat a cow can produce)
hideVolumePerStage: (How many units of rawhide a cow drops when butchered * growth stage)
boneVolumePerStage: (How many units of bone a cow drops when butchered * growth stage)
GrowthRate: (How quickly a cow grows through the stages)
Appetite: (How often a cow eats, a valuable consideration when compared to production+volume)

Every time you breed there would be a random modifier applied to these values, causing them to either increase or (occasionally) decrease per breeding.

Extend this system to all other livestock.

**Comment by CharCharthemonkey** [comment]
so basically agricraft for animals?

**Comment by LunariusH** [comment]
That's a pretty clean way to put it, yes. ;)

**Comment by Wolfixsp** [comment]
sounds great to me hope they add that

**Comment by capnkirok** [comment]
There's also speed, size, strength, health ... this stuff is actually on the original spec for Animania, but.... it's WIP. Tagging @Tschipp food for thought

**Comment by Tschipp** [comment]
While I myself as a fan of advanced genetics and stuff, I don't think it would fit with the main mod well, because of its simplicity. I've thought about making an addon for Animania though, that adds exactly these things - for the users that want to have more advanced breeding.

**Comment by RaliaTheWolf** [comment]
An addon could be nice! You could call it something like Animania+ and add some more advanced features like genetics with coloring and breed mixing and such?

**Comment by Wolfixsp** [comment]
Yup and maybe add mutations that help in animal stats, you know health meat quality, etc and maybe even color mutations for maybe sheeps or all animals like ark breeding mechanics

**Comment by capnkirok** [comment]
Hey @Tschipp , I'm going to close this one, and suggest you consider making that add on :)
