### ISSUE TITLE
[Suggestion] Pheasants (with special feature)

### ISSUE THREAD

**Issue by LunariusH** [capnkirok/animania#363]
I would love to see pheasants introduced, with one special feature.  They're attracted to tall grass and will be invisible and invulnerable when located within it.  Want to hunt/catch pheasant? FLUSH'EM'OUT!

**Comment by NavyT** [comment]
I love this idea!

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#119
