### ISSUE TITLE
[Suggestion] Disable mob griefing for the new farm animals

### ISSUE THREAD

**Issue by NeonSunset** [capnkirok/animania#364]
When you use the cheat /mobgriefing false, it prevents the vanilla animals from "removing" layers of grass when they eat, so you don't have bald patches everywhere; they still eat (i.e. sheep regrow their wool), but it leaves no visual damage in the world.

I would love for this to be an available option in the .cfg for Animania, as I get aggravated seeing so many dirt patches all over the place. Thank you.

**Comment by Tschipp** [comment]
@capnkirok did we not add this ages ago?

**Comment by NeonSunset** [comment]
There's the ambiance mode config which disables the need to eat or drink, but I'm not seeing anything that refers to the land griefing issue.

**Comment by capnkirok** [comment]
I added it for water, can add it for grass, too.

**Comment by NeonSunset** [comment]
Thanks very much; I really appreciate it. :-)

**Comment by capnkirok** [comment]
Going into tonight's update in the config.

**Comment by NeonSunset** [comment]
Awesome; thanks again for this; I'll go ahead and close this thread. ;-)
