### ISSUE TITLE
[Suggestion/Bug?] Bull's Combat Range and Group Aggro

### ISSUE THREAD

**Issue by Sandriell** [capnkirok/animania#365]
I am playing with the latest version, 1.10.2-1.3.3, and bulls are very frustrating to deal with when it comes to combat.

First the possible bugs. Currently when I aggro a bull sometimes (but not always) all the other nearby bulls also aggro on me as well. Distance doesn't seem to factor in too much either as I have had ones standing next to me ignore me as I kill another bull and sometimes they don't. I am positive that I am not simply accidentally hitting them too because I have taken a bull out of the pen and into another one entirely and killed it there- yet the others still aggro sometimes. Is this intended behavior?

Secondly, bulls seem to stay aggro'd forever?

And finally the suggestion. The attack range of bulls seems to be exceedingly high, least the same as mine if not a touch more? This makes it hard and just frustrating to kill them because they will hit me, and throw me back before I ever get close enough to hit them. I have taken to leading them to a separate pen to kill them, but even then as I edge closer to the fence to get in range, sometimes they hit me before i'm close enough. And with the mass-aggro issue mentioned above this is even more difficult.

**Comment by Mac15001900** [comment]
I just had both of these issues as well. Aggro seems to only affect bulls of the same breed, and the attack range seems to be around 2.5 blocks and ignores any, even solid, block in-between. Tried giving them a lot of wheat to appease them and waiting for a lot, neither of which helped. 
Are there any solutions other than killing all of them and spawning new ones?

**Comment by capnkirok** [comment]
Well, i could reduce the range and change how aggro works, which is what I'm going to do. But in the meantime, recommend you put your bulls farther away.

**Comment by capnkirok** [comment]
Ok, this will be fixed in the next release. Yay!

**Comment by Sandriell** [comment]
Thank you. I die from bulls more than everything else combined!
