### ISSUE TITLE
can't place cheese mold on ground (Animania1.3.3)

### ISSUE THREAD

**Issue by nuindil** [capnkirok/animania#367]
I am playing modpack The Simple Life 2 v.1.3.5 (which has Animania v.1.3.3 and Minecraft v.1.10.2) on a server. We are unable to place Cheese Mold on the ground. When you right click the ground with it nothing happens. Any help to address this would be greatly appreciated as the cheese mold is the only way to make cheese in this modpack. Thanks!

**Comment by capnkirok** [comment]
In 1.10 version, you don't place the mold on the ground. Just put the mold and your bucket of milk into a crafting table.

**Comment by nuindil** [comment]
Ok great thanks!
