### ISSUE TITLE
Holy COWS!!!

### ISSUE THREAD

**Issue by jelaw21** [capnkirok/animania#368]
I think either the Cows are happy all the time and don't need food and water to reproduce, or the spawn rate on Cows is greatly increased.

animania-1.10.2-1.3.3
Forge 2422 
![20171001_132315](https://user-images.githubusercontent.com/21100827/31057752-c6b44b94-a6b5-11e7-82a6-00e47a20f3e7.jpg)
![20171001_132419](https://user-images.githubusercontent.com/21100827/31057754-c9b1a5b2-a6b5-11e7-947e-1cdc07ec71f5.jpg)

**Comment by capnkirok** [comment]
did you delete the config before you started the new version?

**Comment by jelaw21** [comment]
I did. The option to not feed and water animals is set to false.

**Comment by capnkirok** [comment]
But the spawn limit for cows is 15?

**Comment by capnkirok** [comment]
Can you cut/paste your config?

**Comment by jelaw21** [comment]
I actually nerfed it and set it to 6.

**Comment by jelaw21** [comment]
# Configuration file

"care and feeding" {
    I:"Egg hatch chance (1/x)"=2
    I:"Max uses of the Salt Lick"=200
    I:"Ticks before next incremental growth"=200
    I:"Ticks before wool regrowth after shearing"=8000
    I:"Ticks between birthings"=20000
    I:"Ticks between drinking water"=8000
    I:"Ticks between dropping feathers"=12000
    I:"Ticks between feedings"=20000
    I:"Ticks between laying eggs"=2000
    I:"Ticks between playing"=4000
    I:"Ticks between using Salt Lick"=8000
}


drops {
    B:"Animals Drop their individual meat types"=true
    B:"Enable Animal Drops from Config"=false
    S:"Set Custom Blue Peacock Drop (if
enabled)"=animania:blue_peacock_feather
    S:"Set Custom Charcoal Peacock Drop (if
enabled)"=animania:charcoal_peacock_feather
    S:"Set Custom Chicken Drop (if enabled)"=animania:raw_prime_chicken
    S:"Set Custom Cow Drop (if enabled)"=animania:raw_prime_beef
    S:"Set Custom Dart Frog Drop (if enabled)"=
    S:"Set Custom Ferret Drop (if enabled)"=
    S:"Set Custom Frog Drop (if enabled)"=animania:raw_frog_legs
    S:"Set Custom Goat Drop (if enabled)"=animania:raw_prime_chevon
    S:"Set Custom Hamster Drop (if enabled)"=animania:hamster_food
    S:"Set Custom Hedgehog Drop (if enabled)"=
    S:"Set Custom Horse Drop (if enabled)"=
    S:"Set Custom Opal Peacock Drop (if
enabled)"=animania:opal_peacock_feather
    S:"Set Custom Peach Peacock Drop (if
enabled)"=animania:peach_peacock_feather
    S:"Set Custom Pig Drop (if enabled)"=animania:raw_prime_pork
    S:"Set Custom Purple Peacock Drop (if
enabled)"=animania:purple_peacock_feather
    S:"Set Custom Rabbit Drop (if enabled)"=animania:raw_prime_rabbit
    S:"Set Custom Sheep Drop (if enabled)"=animania:raw_prime_mutton
    S:"Set Custom Taupe Peacock Drop (if
enabled)"=animania:taupe_peacock_feather
    S:"Set Custom Toad Drop (if enabled)"=
    S:"Set Custom White Peacock Drop (if
enabled)"=animania:white_peacock_feather
}


entities {
    I:"Albino Hedgehog Male Entity ID"=550
    I:"Angus Bull Entity ID"=507
    I:"Angus Calf Entity ID"=508
    I:"Angus Cow Entity ID"=506
    I:"Charcoal Peachick Entity ID"=588
    I:"Charcoal Peacock Entity ID"=586
    I:"Charcoal Peafowl Entity ID"=587
    I:"Dart Frog Entity ID"=801
    I:"Draft Horse Foal Entity ID"=703
    I:"Draft Horse Mare Entity ID"=701
    I:"Draft Horse Stallion Entity ID"=702
    I:"Duroc Hog Entity ID"=613
    I:"Duroc Piglet Entity ID"=614
    I:"Duroc Sow Entity ID"=612
    I:"Friesian Bull Entity ID"=504
    I:"Friesian Calf Entity ID"=505
    I:"Friesian Cow Entity ID"=503
    I:"Frog Entity ID"=800
    I:"Grey Ferret Male Entity ID"=523
    I:"Hampshire Hog Entity ID"=616
    I:"Hampshire Piglet Entity ID"=617
    I:"Hampshire Sow Entity ID"=615
    I:"Hamster Male Entity ID"=520
    I:"Hedgehog Male Entity ID"=529
    I:"Hereford Bull Entity ID"=513
    I:"Hereford Calf Entity ID"=514
    I:"Hereford Cow Entity ID"=512
    I:"Holstein Bull Entity ID"=501
    I:"Holstein Calf Entity ID"=502
    I:"Holstein Cow Entity ID"=500
    I:"India Blue Peachick Entity ID"=582
    I:"India Blue Peacock Entity ID"=580
    I:"India Blue Peafowl Entity ID"=581
    I:"Large Black Hog Entity ID"=607
    I:"Large Black Piglet Entity ID"=608
    I:"Large Black Sow Entity ID"=606
    I:"Large White Hog Entity ID"=610
    I:"Large White Piglet Entity ID"=611
    I:"Large White Sow Entity ID"=609
    I:"Leghorn Chick Entity ID"=535
    I:"Leghorn Entity ID"=534
    I:"Leghorn Hen Entity ID"=533
    I:"Longhorn Bull Entity ID"=510
    I:"Longhorn Calf Entity ID"=511
    I:"Longhorn Cow Entity ID"=509
    I:"Old Spot Hog Entity ID"=604
    I:"Old Spot Piglet Entity ID"=605
    I:"Old Spot Sow Entity ID"=603
    I:"Opal Peachick Entity ID"=591
    I:"Opal Peacock Entity ID"=589
    I:"Opal Peafowl Entity ID"=590
    I:"Orpington Chick Entity ID"=538
    I:"Orpington Entity ID"=537
    I:"Orpington Hen Entity ID"=536
    I:"Peach Peachick Entity ID"=594
    I:"Peach Peacock Entity ID"=592
    I:"Peach Peafowl Entity ID"=593
    I:"Plymouth Rock Chick Entity ID"=532
    I:"Plymouth Rock Hen Entity ID"=530
    I:"Plymouth Rock Rooster Entity ID"=531
    I:"Purple Peachick Entity ID"=597
    I:"Purple Peacock Entity ID"=595
    I:"Purple Peafowl Entity ID"=596
    I:"Rhode Island Red Chick Entity ID"=544
    I:"Rhode Island Red Entity ID"=543
    I:"Rhode Island Red Hen Entity ID"=542
    I:"Taupe Peachick Entity ID"=579
    I:"Taupe Peacock Entity ID"=598
    I:"Taupe Peafowl Entity ID"=599
    I:"Toad Entity ID"=802
    I:"White Ferret Male Entity ID"=526
    I:"White Peachick Entity ID"=585
    I:"White Peacock Entity ID"=583
    I:"White Peafowl Entity ID"=584
    I:"Wyandotte Chick Entity ID"=541
    I:"Wyandotte Entity ID"=540
    I:"Wyandotte Hen Entity ID"=539
    I:"Yorkshire Hog Entity ID"=601
    I:"Yorkshire Piglet Entity ID"=602
    I:"Yorkshire Sow Entity ID"=600
}


"game rules" {
    B:"Allow Animania Chickens to drop Eggs"=false
    B:"Allow Animania Chickens to drop Feathers"=true
    B:"Allow dispensers to place seeds"=true
    B:"Allow eggs to be thrown"=false
    B:"Allow random mobs to ride Animania animals"=true
    B:"Animals do not need to eat or drink"=false
    B:"Enable recipes to exchange special meats for vanilla"=false
    B:"Foods give bonus effects"=true
    B:"Remove vanilla Chickens"=true
    B:"Remove vanilla Cows"=true
    B:"Remove vanilla Pigs"=true
    B:"Remove vanilla Rabbits"=true
    B:"Remove vanilla Sheep"=true
    B:"Shift-Right-Click for Seed Placement"=false
    B:"Show male parts (modesty flag)"=true
    B:"Show mod update notification at startup"=true
    B:"Show particles when animals are unhappy"=true
    B:"Water blocks removed after large animal drinks"=false
}


spawn {
    I:"Number of potential Chicken families per chunk"=1
    I:"Number of potential Cow families per chunk"=1
    I:"Number of potential Goat families per chunk"=1
    I:"Number of potential Horse families per chunk"=1
    I:"Number of potential Pig families per chunk"=1
    I:"Number of potential Rabbit families per chunk"=1
    I:"Number of potential Sheep families per chunk"=1
    B:"Spawn Animania Amphibians in world"=true
    B:"Spawn Animania Chickens in world"=true
    B:"Spawn Animania Cows in world"=true
    B:"Spawn Animania Goats in world"=true
    B:"Spawn Animania Horses in world"=true
    B:"Spawn Animania Peacocks in world"=true
    B:"Spawn Animania Pigs in world"=true
    B:"Spawn Animania Rabbits in world"=true
    B:"Spawn Animania Rodents in world"=true
    B:"Spawn Animania Sheep in world"=true
    I:"Spawn limit for Amphibians in loaded chunks"=6
    I:"Spawn limit for Chickens in loaded chunks"=6
    I:"Spawn limit for Cows in loaded chunks"=6
    I:"Spawn limit for Ferrets in loaded chunks"=6
    I:"Spawn limit for Goats in loaded chunks"=6
    I:"Spawn limit for Hamsters in loaded chunks"=6
    I:"Spawn limit for Hedgehogs in loaded chunks"=6
    I:"Spawn limit for Horses in loaded chunks"=6
    I:"Spawn limit for Peacocks in loaded chunks"=6
    I:"Spawn limit for Pigs in loaded chunks"=6
    I:"Spawn limit for Rabbits in loaded chunks"=6
    I:"Spawn limit for Sheep in loaded chunks"=6
    I:"Spawn probability Chickens"=10
    I:"Spawn probability Cows"=10
    I:"Spawn probability Ferrets"=8
    I:"Spawn probability Frogs"=8
    I:"Spawn probability Goats"=6
    I:"Spawn probability Hamsters"=8
    I:"Spawn probability Hedgehogs"=8
    I:"Spawn probability Horses"=10
    I:"Spawn probability Peacocks"=12
    I:"Spawn probability Pigs"=10
    I:"Spawn probability Rabbits"=6
    I:"Spawn probability Sheep"=8
    I:"Spawn probability Toads"=8
}

**Comment by capnkirok** [comment]
Thanks for posting. Yeah that should be fine... wow! Does it seem like they are having lots of babies, or does it seem like cows are just appearing?

You could also lower spawn probability to 6 also for now. 

Any way to share modlist?

**Comment by jelaw21** [comment]
I think its babies ....

**Comment by jelaw21** [comment]
Not the best list, but here it is ...
[modlist.txt](https://github.com/capnkirok/animania/files/1348603/modlist.txt)

**Comment by Sunconure11** [comment]
I've encountered this with both cows and rabbits, as well. It happened on 1.11.2, and I noticed my cows had been rapidly multiplying, even though settings to require them to eat were on.

**Comment by capnkirok** [comment]
Thanks guys. You have no idea how much testing I have done on this, so super surprised to see this again. 

I will have to take a deeper look again this upcoming weekend.

**Comment by scotty9090** [comment]
Same thing here with Cows in a prior game, and now pigs.  The latest game is a fresh install that I added onto a brand new pack installation so my configs should be completely vanilla, except I changed Animals Don't need Food or Water to true.  I think this is what triggered the problem for me since it seemed okay until I did this - so I'm guessing babies.

**Comment by PurpleHel** [comment]
/kill @e[type=animania:bull_WHATEVER (angus, fresian, etc)]
so to kill all the angus bulls its /kill @e[type=animania:bull_angus]
or cow_angus
or calf_angus

If you want to know other type names, you can type /summon and then hit tab and it will show you all the options. or /summon animania: and then hit tab to only see animania entity types.

I had cows and pigs go crazy spawning or breeding as well.

**Comment by capnkirok** [comment]
Thanks guys. Super disappointed that this is still happening AND I can't reproduce 🙁.

I am contemplating creating a kill switch on the entity itself at the initial spawn (so suicide, basically). Treats the symptom at least until I can find out what's going wrong. Technically, the animals should not be allowed workd spawn (or give birth) if they exceed the limits....

**Comment by capnkirok** [comment]
Ok, after much testing, I was able to reproduce. It is definitely a bug. I will be rolling out a fix tonight, thanks for the feedback everyone!

**Comment by scotty9090** [comment]
@PurpleHel - Thank you very much for the help, those are useful commands to know.

@capnkirok - Thank you for the upcoming fix and just in general.  This mod is so great and just keeps getting better.
