### ISSUE TITLE
Heifers (Cows) should also defend themselves

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#369]
in animania 1.12.1 for a config is it possible to have it so male cows attack if either they or a female cow get attacked? (just an odd question)

**Comment by LunariusH** [comment]
I support this plan, especially if the other cows have the option to either stampede in a random direction (together) and cause damage if they trample you, or will just flee from the aggressor.

**Comment by CharCharthemonkey** [comment]
bbut @LunariusH i mean say u got a few cows around say 4 males and 4 females and maybe 2 kids but u attack a female then the 4 males would come over and basically rip u a new one for attacking the female if that makes sense

**Comment by LunariusH** [comment]
@CharCharthemonkey I believe we understand each other perfectly.

**Comment by CharCharthemonkey** [comment]
@LunariusH the females ive dealt with deal much more harm then the males do but yea tho i hope atleast a config for this might be considered lol

**Comment by capnkirok** [comment]
Yeah, I need to build in some defense mechanisms. I know heifers and other female animals can be just as if not more dangerous.

**Comment by capnkirok** [comment]
This one is going in 1.4.2... they don't do as much damage as bulls.
