### ISSUE TITLE
[Suggestion] Random spawn eggs

### ISSUE THREAD

**Issue by Thyriel** [capnkirok/animania#37]
Would it be too much asking if you could add spawn eggs that do not spawn a specific race but rather spawn a random one ?
For example "Random Pig" can spawn any of the pig races ?
Or even a "Random generic spawn" egg that can spawn any animal from the mod ?

Background: I am using your mod in a modpack that plays like skyblock (but underground) so i had to integrate a way to obtain the animals. Which i did through sieving with ExNihilo (i know sounds strange but i did not had a better idea). But as there are so much different animals it's a pretty huge list that i have to configure manually (and keep up to date if you add more animals later). Having some generic spawn eggs would be of great help with that :)

**Comment by capnkirok** [comment]
Hey, check out the way vanilla eggs work now with the mod installed (pig, cow, or chicken). Let me know if this is what you were thinking.  Version 1.0.1

**Comment by Thyriel** [comment]
Oh thats nice didn't notice that :)
Tested it but it's not exactly what i was thinking of. The vanilla eggs always spawn the same kind (Yorkshire Sow, Friesian Cow, Leghorn Hen). Would be cool if they would spawn a random kind (and maybe add one "vanilla" like egg for random spawn of Ferrets, Hamsters or Peacocks)

**Comment by capnkirok** [comment]
Yes, I can do this. It's actually rather simple. Thanks for the suggestion.

**Comment by capnkirok** [comment]
Ok, this will be in 1.0.3
