### ISSUE TITLE
Question about mod compatibility

### ISSUE THREAD

**Issue by PlainVanillaMC** [capnkirok/animania#370]
Since comments aren't open on the CurseForge download page, I was wondering if this mod recognizes and accepts mud and/or various types of crops from mods that create them?

**Comment by capnkirok** [comment]
Comments are open on the Curse page, but not the project page. But hey.

If you are talking about the mud block, right now, the pig can only work with Animania mud. What mods do you know of that create mud (besides BOP) that we should look into?

**Comment by Ash70** [comment]
Earthworks also has a mudblock. I usually setup my own oredict and conversion recipes with crafttweaker.

**Comment by capnkirok** [comment]
Thanks. We can add compatibility so that the pigs can roll in this mud too. I assume that is what you are looking for?

**Comment by 13illy** [comment]
Biomes o plenty and the between land both have mud blocks.

**Comment by capnkirok** [comment]
Well, this will be in the next update. I thought this would be easy.. but it was not. Oh, well, it's a nice touch.
