### ISSUE TITLE
[1.10.2-1.3.3]Shearing Brown Suffolk Ewes gives wool with incorrect metadata

### ISSUE THREAD

**Issue by thephoenixlodge** [capnkirok/animania#371]
As per title, Shearing a brown Suffolk Ewes gives a wool block with a meta of 6, which results in it having a broken texture in the inventory. Based on there being 7 special wool types I suspect you were originally going to have them on 1 block id using metadata, and this appears to just be an oversight with forgetting to remove the metadata part of the wool id from shearing.
This is specific to Ewes, and to Shearing. Both shearing Rams, and killing Ewes and Rams results in the correct meta 0 wool.

**Comment by capnkirok** [comment]
Thx, fixed in next release.
