### ISSUE TITLE
Log Spam "*that already exists with UUID *" - Same as #311 but with more Info as well

### ISSUE THREAD

**Issue by HalestormXV** [capnkirok/animania#372]
Issue with log spamming warnings is still occuring as of version 1.11.2-1.3.3

https://pastebin.com/3dsPJXep

This is the same as #311 - I don't know how to re-open that issue.

To add to this. Here is a crash that I just happened to see happen. It is a Watching server crash which as we know usually mean a thread took to long beyond the config time to execute. 

https://pastebin.com/frc3D9Vh

I can't say for certain if it is related to the log spam but it happened right after the log spam and no one is on the server. And in that crashlog it references a few mods, animania being one but also seems to hone in on EntityLiving. I can't be certain if it is directly related or not but hopefully it can be helpful.

**Comment by capnkirok** [comment]
Thanks for the follow up and the log. Disappointed it's still happening for you, but I'll continue to work on it.

**Comment by capnkirok** [comment]
- I'm sorry to say this, but it looks like you've been caught in a Minecraft Bugs:
https://bugs.mojang.com/browse/MC-95649
https://bugs.mojang.com/browse/MC-22147

Is there a way you can kill these entities, or create a new world? The problem hasn't been reported elsewhere, so hoping you can.

- The second issue looks like an error where your server can't find the file to save to, which could be the reason that you are getting the spam in the first place, as it is trying to save entity information to the disk

Don't know what I can do to help. Any way you can update to 1.12?

**Comment by HalestormXV** [comment]
No, can't generate a new world as it is a pretty solid SMP server, and no can't update to 1.12 since most mods in that server haven't been updated yet. But I am aware of the Minecraft bug so what I will have to try and do is generate a list of the duplicates and execute the kill command on the UUID and hope they don't duplicate again. Alright, thanks for the response. I'll mark this as closed.
