### ISSUE TITLE
Questions About Mod Compatability

### ISSUE THREAD

**Issue by vasillisa** [capnkirok/animania#373]
Hi. I play on 1.10.2 and I'd really like to add this mod but I have a few questions. You said it is compatible with Hatchery, how does that affect the egg-laying and breeding for the chickens? Are there different types of chicken or is it better to just use the Animania mod?
With the new meats and food stuffs, does it conflict with Pam's Harvestcraft?
Also, does this mod have any conflicts with Mo'Creatures mod?
Thanks!

**Comment by capnkirok** [comment]
This is actually in the Forum Post...

- Definitely compatible with Pam's Harvestcraft
- The Hens work with Hatchery... you can also decide to keep vanilla chickens too if you really want to (it's in the config).
- No conflicts with Mo'Creatures have been reported, but I haven't built any special compats in like I did for the above two.
