### ISSUE TITLE
Too many animals, wild animals breeding?

### ISSUE THREAD

**Issue by Nakkuchan** [capnkirok/animania#374]
Hi! I have recently created a server with animania on it, and I found that animals spawn like crazy. I attach a couple screenshots where you can see the number of entities. 
![2017-10-05_21 26 05](https://user-images.githubusercontent.com/32543871/31248517-504fa982-aa14-11e7-9d98-85375b71c25a.png)
![2017-10-05_21 24 42](https://user-images.githubusercontent.com/32543871/31248518-50521c9e-aa14-11e7-878a-26e148955c9f.png)

Sometimes they breed by their own. I had to fence the crops but they still breed and spawn out of control. I deleted and let the game create the config file again, and the version of the mod is: animania-1.10.2-1.3.3

Any idea? Thank you!

Here is the config file, just in case:

spawn {
    I:"Number of potential Chicken families per chunk"=1
    I:"Number of potential Cow families per chunk"=1
    I:"Number of potential Goat families per chunk"=1
    I:"Number of potential Horse families per chunk"=1
    I:"Number of potential Pig families per chunk"=1
    I:"Number of potential Rabbit families per chunk"=1
    I:"Number of potential Sheep families per chunk"=1
    B:"Spawn Animania Amphibians in world"=true
    B:"Spawn Animania Chickens in world"=true
    B:"Spawn Animania Cows in world"=true
    B:"Spawn Animania Goats in world"=true
    B:"Spawn Animania Horses in world"=true
    B:"Spawn Animania Peacocks in world"=true
    B:"Spawn Animania Pigs in world"=true
    B:"Spawn Animania Rabbits in world"=true
    B:"Spawn Animania Rodents in world"=true
    B:"Spawn Animania Sheep in world"=true
    I:"Spawn limit for Amphibians in loaded chunks"=12
    I:"Spawn limit for Chickens in loaded chunks"=12
    I:"Spawn limit for Cows in loaded chunks"=12
    I:"Spawn limit for Ferrets in loaded chunks"=12
    I:"Spawn limit for Goats in loaded chunks"=12
    I:"Spawn limit for Hamsters in loaded chunks"=12
    I:"Spawn limit for Hedgehogs in loaded chunks"=12
    I:"Spawn limit for Horses in loaded chunks"=12
    I:"Spawn limit for Peacocks in loaded chunks"=12
    I:"Spawn limit for Pigs in loaded chunks"=12
    I:"Spawn limit for Rabbits in loaded chunks"=12
    I:"Spawn limit for Sheep in loaded chunks"=12
    I:"Spawn probability Chickens"=10
    I:"Spawn probability Cows"=10
    I:"Spawn probability Ferrets"=8
    I:"Spawn probability Frogs"=8
    I:"Spawn probability Goats"=6
    I:"Spawn probability Hamsters"=8
    I:"Spawn probability Hedgehogs"=8
    I:"Spawn probability Horses"=10
    I:"Spawn probability Peacocks"=12
    I:"Spawn probability Pigs"=10
    I:"Spawn probability Rabbits"=6
    I:"Spawn probability Sheep"=8
    I:"Spawn probability Toads"=8
}

Is the spawn limit too high? This is what I get by defalut.

**Comment by capnkirok** [comment]
Rekated to #368

**Comment by Nakkuchan** [comment]
Sorry if I missed the answer, but I read that thread and didn't find an answer. Is 6 the proper spawn limit to solve the problem? Sorry if I misunderstood.

**Comment by capnkirok** [comment]
So, your config settings look fine. The numbers aren't ridiculously high (100 total entities), but they are too high for what

**Comment by capnkirok** [comment]
... sorry doing this from mobile. You can lower your limits, yes, but I also need to put in a fix.

Question: what animals are most out of control? cows? any species look to be more out of control than others? all help appreciated!

**Comment by LenaAlcie** [comment]
Cows and goats breed more often than chickens. 
There is no way to make them don't breed by themselves? We don't need the life finding ways xD

**Comment by Nakkuchan** [comment]
I lowered the spawn limit to 5 and also lowered the spawn probability substracting 2 to all the numbers by default. I don't know if this solves anything tho.

If I kill all the entities around me, they slowly start to appear, and when some time has past all the place is conquered by nature. Also, they spawn in groups almost always, with babies.

**Comment by capnkirok** [comment]
Thanks both, very helpful. 

@Nakkuchan, it will help, but I will have a patch out tomorrow late.

@LenaAlcie good idea... nature abhors a vacuum (or in this case, available spawn space it seems)

**Comment by Nakkuchan** [comment]
This is a screenshot with the nerfed config. Still a problem. Just in case it helps :) And cause its funny...

![2017-10-05_22 38 57](https://user-images.githubusercontent.com/32543871/31251949-e77459a6-aa1f-11e7-9cc6-5d7c91db9fab.png)

**Comment by Ash70** [comment]
If this is related and you need more info/cases: I recently started a new world (1.12.2) and the area had 5 sheep in it to begin with (it was a large-ish island) 4 MC-days later the whole island was overpopulated with sheep. I kept slaughtering them, but they came back (at one point I thought I had killed them all only to have them reappear later). It was so bad it must have reached the mob-cap since I had no hostiles spawn at night at all. In the end I decided it was best to move out myself, lol.

**Comment by Nakkuchan** [comment]
Also, while playing I observed the animals eating the grass all around

**Comment by capnkirok** [comment]
@Nakkuchan yes, the eating of grass is normal

**Comment by capnkirok** [comment]
Hey everyone. Can confirm this is an issue on a server. It is not the result of any additional mods. And it has to do with Spawning (not out of control birth rates). I will have an update tonight. THANK YOU ALL FOR THE INPUT!
