### ISSUE TITLE
[SUGGESTION] Crafttweaker support for the aging mold

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#375]
Would it be possible to add Crafttweaker support for the aging mold? The input could be a fluid, and the output could be a solid block, or something similar to represent things like items (salt)

**Comment by lolorz13** [comment]
I agree, this would be useful for manipulating the salt output as well, 16 salt seems a bit excessive (1 bucket of water gets 16 salt, 8 salt = 1 salt lick which is almost a full block)

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#120
