### ISSUE TITLE
[SUGGESTION] Disable animal sparring

### ISSUE THREAD

**Issue by elalejo07** [capnkirok/animania#376]
It would be good to have a config option to disable bucks and rams sparring. They are driving me crazy with all that running all the time.
Thanks for this great mod!!!

**Comment by capnkirok** [comment]
I've put a longer delay between sparring sessions (about 4x as long) as a starter.

**Comment by capnkirok** [comment]
Hey, this one is in the 1.4.4 build. Forgot to mention it. It's a config option under gamerules "animalsCanAttackOthers"
