### ISSUE TITLE
[1.12.2] Horse has no TOP Overlay and is unhittable (hitbox issue)

### ISSUE THREAD

**Issue by D3nnis3n** [capnkirok/animania#379]
Hello,
i do not know exactly if these nice animals are from your mod or from vanilla, but as i got no other animal adding mods i presume they are.

In the screenshot you can see that despite me having installed TOP i can not see a Overlay for this mob and i can't hit it. i just hit through it. It's invincible as it wouldn't be there :O 

https://ibb.co/eEdjBG

And yes, i do get TOP Overlays for all your other Mobs and all vanilla mobs depsite these horses there and can kill and hit them.

If this mob is not from you, well, ignore it. But i'm really wondering how this comes, then oO

**Comment by capnkirok** [comment]
- What version of Animania are you running (e.g., 1.3.4?)
- This is a 'ghost' entity, only alive on the client. You can restart and it will disappear.
- Any idea how it got into your world? (did you find it, was it born there, did it come from another mod)

**Comment by D3nnis3n** [comment]
Hello,
okay - i have no idea what a ghost entitiy is or how it is created, but i never spotted some before updating to 1.3.4 which is my Animania Version, my forge is 2509.

It got spawned there. I just walked around alone on the Server, got there and it was there. So i presume it has spawned there. However this is possible.

**Comment by capnkirok** [comment]
If you spawn a horse from one of our Spawn Eggs... does it also do this? (Draft Horse)

**Comment by D3nnis3n** [comment]
No, it works fine then.

**Comment by D3nnis3n** [comment]
Just walked around a bit. Every horse in the world is a ghost Entity. There is not a single horse that is real. That's spooky. Halloween easteregg? :D

**Comment by D3nnis3n** [comment]
Stop. I found one horse that is real. I could not find a ghost Entity that is not a horse but something else.

**Comment by D3nnis3n** [comment]
HAH! I think i found something out that helps you. After i saw one does indeed eat grass and the block changes i found out that the hitbox of These animals is incredibly small.

If i Point on there front feet i CAN see the tooltip. And if i hit there, i CAN hit them. But only on the front feet. Anywhere else, i just hit through.

Also, those Mobs are considered "foals":

https://ibb.co/iLTWQb

**Comment by capnkirok** [comment]
Oh, goodness. Ok, these aren't ghost entities. The hitbox is just too small. Ok, I can fix this. Thanks for the follow up.

**Comment by D3nnis3n** [comment]
Look here how a foal Looks when it is spawned: 

Then i can hit anywhere and it does indeed get a tooltip. It seems like it got a wrong texture.

https://ibb.co/fCOsWG

**Comment by capnkirok** [comment]
That texture is correct, the colors are random.

**Comment by D3nnis3n** [comment]
Well the foal that seemed like a ghost Entity is as big as a real horse, isn’t it? If you compare with the working foal?

Gesendet von Mail für Windows 10

Von: Purplicious_Cow
Gesendet: Montag, 9. Oktober 2017 00:45
An: capnkirok/animania
Cc: D3nnis3n; Assign
Betreff: Re: [capnkirok/animania] [1.12.2] Horse has no TOP Overlay and isunhittable (hitbox issue) (#379)

That texture is correct, the colors are random.

**Comment by D3nnis3n** [comment]
This issue also applies to "Friesan Lamb" You can hit that one only on the bottom feet.
If it stands in front of a block you will se the block TOP Overlay and hit the block instead of the animal.
IF you want, i can do another screenshot, but i didn't as the issue seems clear and i just saw it when Walking by.

**Comment by twoworlds** [comment]
I encountered a similar problem. "Child" mobs seem to be untouchable. I can't feed them nor hit them. I thought this might be intentional, but if they grow up, they can be fed and killed.

**Comment by twoworlds** [comment]
And also very strange, I have only vanilla horses on my server, i have never seen these "Draft Horses" anywhere in my world

**Comment by Gepett0** [comment]
Seen a similar problem woth calfs. You have to hit the front legs/hooves to kill them, hard to hit in survival with this nasty runners.

**Comment by capnkirok** [comment]
Hitboxes have all been enlarged for baby animals in next release.
