### ISSUE TITLE
[1.12.*] Mod Compat Request: Vampirism

### ISSUE THREAD

**Issue by Alaberti** [capnkirok/animania#380]
Would it be possible to enable animania creatures to be "biteable" by vampires via the vampirism mod? It's kind of a weird thing to ask, but we have a modpack with both these mods and because animania replaces all vanilla passive creatures, the people who became vampires now no longer can "drink blood" from livestock and are all basically starving to death.

I don't know if this helps, but there's an api around somewhere? https://github.com/TeamLapen/Vampirism/tree/1.12/src/api/java/de/teamlapen/vampirism/api

Please and thank you

**Comment by capnkirok** [comment]
Hmmm... most of the animals in the game extend the minecraft vanilla counterparts (e.g., Cows, Horses, Sheep and Goats, Rabbits... do those not work with Vampirism? If not, I might suggest your reach out to that author to check for 'instance of' instead of the exact class.

**Comment by Alaberti** [comment]
Figured it out - vampirism dev has some instructions for how to add entities from other mods, all's well.
