### ISSUE TITLE
[All Versions] Disappearing animals on Animania 1.3.4

### ISSUE THREAD

**Issue by xVizorg** [capnkirok/animania#382]
Hello, I just want to say that after an update to Animania 1.3.4 (from 1.3) animals on my server (created for 2 person) are disappearing randomly. First time my 2 cows vanished, then after client restart they appear again. Second time these animals vanished again (cows and pigs). I just went aprox. 100 blocks from them. They are appearing and disappearing randomly - for example - 2 pigs, next time 4 cows, 3 pigs. I was trying to delete config files on server/in my client  or reloading Animania mod by deleting and downloading one more time but the effect is still the same. On version 1.3 it wasn't happening but i got colosal lag (avg. tick 150 ms with 2 person), then i tried to update and it's better, but not perfect (still avg. tick 60-70 ms). I got good computer, with 4-8 GB of ram for server and we are playing both (2 slots).
Thanks for created such a good mod, i hope you will fix it !

**Comment by capnkirok** [comment]
Thanks for the report. Will investigate further. Glad the performance has improved.

**Comment by capnkirok** [comment]
Yup, this is confirmed. 

Temporary solution: give them a Custom Name, they will stay, regardless of limits.

**Comment by Gepett0** [comment]
Tried to build a new enclosure on the place my vanished rabbits were.
Encountered a weird issue:
Can't place blocks on some places, they just flash and don't stay placed.
Pushing them with pistons has decreased the area from 5*5 to 2*3, any blocks pushed into this area will stay, but if I break them and try to place by hand gives a flashing again.

So maybe the rabbits try to troll me from ghostworld, meaning they are still there on server, but not on client?

**Comment by capnkirok** [comment]
@Gepett0 interesting.... there may be something to this... when I changed a few settings recently, the animals I thought were de-spawned suddenly appeared again. Will include this in my test scenarios.

**Comment by xVizorg** [comment]
@Gepett0 in my opinion these animals are still on server, but they are disappearing in client. In my case these cows and pigs are still in a farm - they sometimes appear, to vanish again in a moment. 
@capnkirok how can I give them custom name ?

**Comment by capnkirok** [comment]
Put a Nametag into the Anvil, give it a name. Right click on animal with Nametag
Nametag recipe = string + gold nugget

**Comment by Sunconure11** [comment]
I had this happen with my angora goats when I was breeding them for wool to survive (TaN). I'd come back, and half of them would be gone.

**Comment by D3nnis3n** [comment]
I can confirm this rabbit not there but there issue. I got Points on my map where i can't drive with my car of ultimate car mod, as its supposed to shut engines off when hitting a mob. Instead of doing this, it just hangs on the block an invisibile creature might be. Also, you cant place any blocks on exactly this square. And: those invisible Mobs do not seem to move.

**Comment by ExperiSkittles** [comment]
This is casually now happening with Sheep and chickens, for me it's naturally  fixable by restarting the game or simply leaving the chunk but I can't do that every time I need a egg, it also stops them from breeding or laying in a nest when they reappear in the chunk. ( That might be a different issue entirely but you know why not include it while Im here. )

**Comment by capnkirok** [comment]
- Disappearing animals will be fixed tonght
- The 'invisible' blocking will be fixed also tonight (they will be removed automatically)
