### ISSUE TITLE
Rabbits don't drop meat

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#383]
Current config settings, just in case it's relevant:

https://www.dropbox.com/s/w13ojh78yhqhlkp/animania.cfg?dl=0

**Comment by capnkirok** [comment]
Thx. Re: cows, not breeding, but spawning (many other threads ongoing).

**Comment by capnkirok** [comment]
Hey there. The rabbit drops are working as intended. There are certain rabbits that I set to not drop meat (e.g., Dutch, Lop)... but I think this is just confusing.

In the 1.3.5 update, even the 'pet' breeds will drop vanilla meats.

**Comment by capnkirok** [comment]
Also, your config settings look fine. If you kill off the cows, do they come back? And just checking you are on 1.3.4?

**Comment by Sunconure11** [comment]
I'm on 1.3.4. I haven't tried killing them off 100%, but they breed out of control, even when I've killed the bulls, as they will breed with their children once they turn into bulls.

**Comment by capnkirok** [comment]
Ewwww

**Comment by Sunconure11** [comment]
I bred one friesian and one holstein together, and got a massive herd that won't stop breeding.

**Comment by capnkirok** [comment]
and you are on 1.11.2, correct?

**Comment by Sunconure11** [comment]
Yes.

**Comment by capnkirok** [comment]
Ok, check out 1.3.5 (out shortly). I am 99% sure everything can be controlled.

Also, just checking... make sure you replace your config on both the server and client after downloading 1.3.5
