### ISSUE TITLE
[1.11/ 1.12] Support request for WAWLA, HWYLA, Waila Harvestability

### ISSUE THREAD

**Issue by SilverWolfII** [capnkirok/animania#384]
When looking at the animal (any) with waila, I noticed that the growth or mating timer doesn't run. It's stuck in 0:00 or 19:59. Is this normal? What more info do you need?

Love the mod, sorry for bad english.

**Comment by Sunconure11** [comment]
I can confirm this happening on 1.11.2 as well.

**Comment by capnkirok** [comment]
Thanks for the report. Looking at it now.

**Comment by capnkirok** [comment]
Wait... WAILA is not available for 1.12.x, looking at 1.11.x

Also, there isn't an Animal Growth / Mating timer. There is only a Time until Birth / Hatching or Wool Regrowth timer....

**Comment by Sandriell** [comment]
Also happens on 1.10.2 with The One Probe. There is definitely a timer. Might be something built into Walia/TOP to support vanilla animals?

**Comment by capnkirok** [comment]
@Sandriell I didn't build in any support for TOP in 1.10 yet, so you are probably right, as many of these animals extend vanilla.

Screenshot probably the best way to show me

**Comment by Gepett0** [comment]
Copy from my other post:
<<Using HWYLA 1.8.20-B35_1.12, WAWLA 1.12.2-2.5.245 and WailaHarvestability 1.12-1.1.12.>>
So maybe OP meant HWYLA instead?!?
Rabbits: showing permanent "breedable" for me
Chickens: showing "Breeding Cooldown 0:00" independently from there real status
- Chicken + rooster in a small enclosure with a nest - BCD 0:00
- fed them - BCD 0:00
- chick lays an egg - BCD 0:00
 - the newborn hatches - parents both BCD 0:00 - chick "Growing CD 19:59"
Sheeps: no status shown on adults
Cows: no status shown on adults
Any babies: showing "Growing Cooldown 19:59" until they are adults
Got no other domesticated animals so no information there

**Comment by capnkirok** [comment]
Thanks @Gepett0 ! 

Yes, these mod extenders are not supported, just WAILA and TOP.

But... I know what the growing CD issue is. In 1.3.4, I tried using mc's GrowingAge for something else, which is probably why it gets stuck. Had no idea these mod extenderss were using it. Animania animals have their own internal timer. At any rate, I've stopped using it in 1.3.5.

So, really, this is not an Issue, but a compat request for support of these mod extenders.

**Comment by PurpleHel** [comment]
Another voice saying please add compatibility with WAILA alternatives when you can. :)

**Comment by capnkirok** [comment]
Thanks @PurpleHel .. noted!

**Comment by capnkirok** [comment]
Ok HWYLA is in for 1.12, and TOP for 1.10... long overdue.
WAILA Harvestability doesn't seem to have an API, but it extends WAILA/HWYLA so it should work

**Comment by SilverWolfII** [comment]
Thank you for your hard work! This will help a lot!

**Comment by PurpleHel** [comment]
Woot!
