### ISSUE TITLE
Hitboxes still a bit too small

### ISSUE THREAD

**Issue by D3nnis3n** [capnkirok/animania#385]
I find the hitboxes still a bit too small after the 1.3.5 update. E.g. the friesan calf you can not Point to the head to see the tooltip or to feed (or kill) it. But, well, yeah, it's the head you feed, isn't it?

**Comment by capnkirok** [comment]
Yes, you are right. It looks MC shrinks the hitboxes of any animals that extend vanilla (like the cows). Others are ok. Will be in next release.
