### ISSUE TITLE
Animals desappeared

### ISSUE THREAD

**Issue by dave75vgnut** [capnkirok/animania#386]
After i updated from Animania 1.3.3 to 1.3.5 most if not all my captive animals disappeared, so i went bck to 1.3.3 and they reappeared.

**Comment by capnkirok** [comment]
Hey @dave75vgnut ... sounds like your spawn limits might be set too low. Would recommend you update your config. And also... give your animals names... that will ensure they don't disappear. Then try the update again. Let me know how it goes!

**Comment by capnkirok** [comment]
To get an easy nametag, combine a gold nugget and string (Animania recipe)

**Comment by capnkirok** [comment]
Ok @dave75vgnut I'm closing this one. See my notes above... Name the animals you want to keep. After the upgrade to 1.3.5+, you won't see this problem again.
