### ISSUE TITLE
Invisible Animals seem to still be there

### ISSUE THREAD

**Issue by D3nnis3n** [capnkirok/animania#387]
Hey, you fixed that Problem with the invisible animals in the last patch. It seems like they are still there. I can now even better see that, as my car mod now is configured to damage animals when driving over and whewnever i drive over one of the spots i had thought there would be such an animal, i see damage numbers appearing. unfortunatley i can drive over them ten thousand times, they don't disappear and i still can't place blocks there.

**Comment by capnkirok** [comment]
Well, that's disappointing. I haven't seen any problems here, and no further reports of issues. Very bizarre. I'm wondering if this is animania. Maybe you can help me with the following:
- Can you try a test with just Animania and your car mod in a new world? 
- What is this car mod by the way?
- Have you tried using a command to apply the 'glow' affect? Maybe that will tell you what animals you have... 
- I think you said you are on a client / server? Did you delete the config on both client and server?There might be an EntityID mismatch...

**Comment by D3nnis3n** [comment]
Hello,
1. I’ll test that in the Course of the week. At the Moment i’m working on a world Generation and that Needs my complete Attention, unfortunatley. It’s also hard to say if it occurs only with both mods, as if i remove all the other mods the places where the „invisible Mobs“ were would no longer be there – they’re all modded blocks.
2. The Car mod is called „Ultimate Cars“
3. I don’t exactly know how this works, but i might can find out on the Wiki.
4. No, Config had only been deleted on the Server. I’ll try to remove it on the Client, too.

Von: Purplicious_Cow
Gesendet: Donnerstag, 12. Oktober 2017 19:17
An: capnkirok/animania
Cc: D3nnis3n; Author
Betreff: Re: [capnkirok/animania] Invisible Animals seem to still be there(#387)

Well, that's disappointing. I haven't seen any problems here, and no further reports of issues. Very bizarre. I'm wondering if this is animania. Maybe you can help me with the following:
• Can you try a test with just Animania and your car mod in a new world?
• What is this car mod by the way?
• Have you tried using a command to apply the 'glow' affect? Maybe that will tell you what animals you have...
• I think you said you are on a client / server? Did you delete the config on both client and server?There might be an EntityID mismatch...

**Comment by capnkirok** [comment]
I installed both Ultimate Car and Animania and didn't see any issues, but maybe I'm missing something. Let me know what you find out.

**Comment by D3nnis3n** [comment]
Well, i cannot reproduce this on a new world with or without the other mods installed.
But i can reproduce this using the Server-World on my Client without any other mods. On the spaces where „invisible animals“ were, they’re still there. Dunno, maybe they’ll eventually die some time.

Gesendet von Mail für Windows 10

Von: Purplicious_Cow
Gesendet: Freitag, 13. Oktober 2017 18:58
An: capnkirok/animania
Cc: D3nnis3n; Assign
Betreff: Re: [capnkirok/animania] Invisible Animals seem to still be there(#387)

I installed both Ultimate Car and Animania and didn't see any issues, but maybe I'm missing something. Let me know what you find out.

**Comment by capnkirok** [comment]
Ok, @D3nnis3n well, I'm not entirely sure what happened to your world. I wonder if there's another way to find out what these things are and killing them? 

At any rate, I'm closing this now. Let me know if you find out any more info :)
