### ISSUE TITLE
[Question/Suggestion/Possible bug] Chicken Jockey weirdness.

### ISSUE THREAD

**Issue by 63502** [capnkirok/animania#39]
It seems to me that whenever a chicken jockey spawns, the vanilla chicken gets replaced with a Leghorn chicken, the baby zombie gets dismounted, and then the baby zombie despawns, leaving the chicken. Animania appears to disrupt both the chicken jockey's natural behavior, and the automatic despawning of the chicken that serves as the mount. Over an extended period of time, this leads to a buildup of random leghorn chickens in caves and occasionally in the nether.

Would it be possible to add compatibility to animania chickens so that they can properly behave and despawn as chicken jockey mounts? A couple other ideas would be to add a special type of "zombified" or otherwise unusable chicken that acts specifically as a chicken jockey's mount, or to just disable chicken jockeys entirely.

**Comment by capnkirok** [comment]
Yes, let me see what's going on here.

**Comment by capnkirok** [comment]
I think this is a combination of two things... the 1.0.1 release... which was doubling vanilla spawns... and incorrectly implemented Jockey behavior. I've already fixed the first part in 1.0.1a (I think). I'm going to work on the second part...

**Comment by 63502** [comment]
Ok, good to know that things are going relatively smoothly. :)

**Comment by capnkirok** [comment]
Still looking at this one. Have an idea.
