### ISSUE TITLE
Animal pairs don't breed more than once?

### ISSUE THREAD

**Issue by Wildiful** [capnkirok/animania#390]
This has happened with my sheep and my horses. I have 4 sheep, two were the parents and  one was the offspring and one is a new unrelated sheep. My ram and ewe had only one lamb who is still with them who is now grown, I also have a male and female horse who had a foal who is also grown. Problem is I expected them to breed again once their offspring was grown so I could eventually produce a faster more higher jumping horse but they don't seem to breed more than once in their lifetime. It's weird, they are also always happy and never starving or thirsty so I always take care of them, I was going to have long lists of parents and their offspring but I can't really do this if they only have one baby. I looked in the config and I didn't see any toggle for how often animals breed? any idea why this happens? cheers

**Comment by capnkirok** [comment]
What version are you on (1.10 - 1.12)?

**Comment by moesaur** [comment]
Not exactly sure if this is related, but I guess it's worth sharing. 
I was having a similar issue, except it was with Cows. They'd breed once and then never again. JEI would show on the tooltip that the cow is "pregnant" but it wouldn't show the amount of ticks remaining. I thought my save file was glitched so a switched to a new world seed and the same happened again.

Eventually I decided to increase the "Spawn limit for Cows in loaded chunks" from already-modified 80 to 120 and when I logged in again all the pregnant cows had their offspring spawned. 
Funny thing is that I only had 8 cows in the pen. Had no extra chunks loaded with no world anchors whatsoever and my pen covered 2~3 chunks max. 
Tried flying around in spectator to see if I had some cows stuck in the neighborhood but found nothing. Maybe they are invisible? 

Also using Animania 1.3.5 except I'm on minecraft 1.11.2

**Comment by capnkirok** [comment]
@moesaur thank you for all the detail and the extra testing. All of that is supposed to happen except of course the limits should be correct. I really hope they are not invisible. 

@Wildiful , see what happens if you increase spawn limits... I will check some stuff on my end.

Thanks both!

**Comment by lebanni** [comment]
I have the same issue with Animania 1.3.5 and MC 1.10.2.

**Comment by Wildiful** [comment]
Thank you for your suggestion Moesaur! I modified my config to allow 70 of each animals to be in every chunk, so far nothing out of the ordinary has happened with there being more baby animals but it'll probably occur soon. crossing my fingers

**Comment by capnkirok** [comment]
Thanks for the additional testing guys! Let me know what you find.

**Comment by moesaur** [comment]
@capnkirok I tried reproducing it and seems like my issue wasn't really related. Bumping the spawn limit fixed the cows. 
Here's what I got:
-started a  new flat world with the config file attached bellow (changed ticks and pop. cap only)
-butchered all entities with /kill 
-spawned in two friesian sheep, they mated 
![2017-10-17_23 09 11](https://user-images.githubusercontent.com/32858147/31696985-84429492-b393-11e7-88c9-5163b0ac287d.png)
-decided to name them (cliche names :P ) so it wouldn't get confusing 
![2017-10-17_23 13 54](https://user-images.githubusercontent.com/32858147/31697028-c09540c0-b393-11e7-9b72-3db75f38f3ae.png)
![2017-10-17_23 13 57](https://user-images.githubusercontent.com/32858147/31697031-c8ff98fa-b393-11e7-8fde-b0861952c1ab.png)
-however Adam and Eve would not breed again (Eve wouldn't even show as "pregnant") 
-decided relogging. To my surprise, their relationships was gone for a brief moment and Adam soon after was mated with Offspring 
![2017-10-17_23 22 17](https://user-images.githubusercontent.com/32858147/31697108-3e99c7e8-b394-11e7-99ba-0b1cb284222b.png)
-they had a kid (another female) and the same behavior repeated, they'd not breed again
-relogged. Adam was now paired with the new (unnamed) female 
![2017-10-17_23 27 08](https://user-images.githubusercontent.com/32858147/31697133-6b8b8dea-b394-11e7-907f-5276f33a6806.png)

Here's the config and mods I'm currently running: https://pastebin.com/vfBFbEdf
Hope it helps!

**Comment by capnkirok** [comment]
FYI, there's a specific bug with the sheep in 1.3.5, just found it and working on it.

**Comment by capnkirok** [comment]
This will be fixed in next release (1.3.6). It was a combination of issues, from a bug in Sheep, to the finding mate algorithm in other animals.
