### ISSUE TITLE
[SUGGESTION] Milk should be drinkable, like in vanilla, and clear potion effects

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#395]

**Comment by Tschipp** [comment]
Not possible, because we use forge universal buckets. We will add milk bottles in the next release though

**Comment by capnkirok** [comment]
@Tschipp sounds like you are volunteering for that one :)

**Comment by capnkirok** [comment]
Ok, guess not. We'll I'll get it in 1.3.7

**Comment by capnkirok** [comment]
We have a texture.... next update... :/

**Comment by Tschipp** [comment]
lol "Next release" he said

**Comment by capnkirok** [comment]
Man, I hate audit trails.

**Comment by capnkirok** [comment]
Ok, this really is in the next release. Cuz it's in now :)

**Comment by capnkirok** [comment]
FYI: On 1.10, you can drink the bucket of milk... so only put the milk bottles in 1.11 and 1.12.
