### ISSUE TITLE
Named vanilla mobs cause Animania mobs to spawn

### ISSUE THREAD

**Issue by SSyl** [capnkirok/animania#396]
If you have custom named vanilla mobs in an existing world and add Animania to it, with the option to replace Vanilla mobs enabled, it won't remove the vanilla mobs but it will still add new Animania mobs to it.

It seems to do this on every server restart as well, so if you have a few named vanilla cows, chickens, pigs, or sheep it'll start adding up.

You can also replicate this if you do /summon minecraft:cow ~ ~ ~ {CustomName:"Cow"}. It'll summon both a cow named "Cow" and also a new unnamed Animania animal.

Edit: As a side note, anyway this could be fixed by simply not summoning new Animania animals on named mobs? That way the few people on my server who just want their couple vanilla animals can keep them, but the rest of the server only has Animania animals with no new vanilla ones spawning.

**Comment by capnkirok** [comment]
Ooh that's a good one.

**Comment by capnkirok** [comment]
Ok, this will be fixed in 1.3.6. Thanks for reporting!
