### ISSUE TITLE
cheese mold not working as intended.

### ISSUE THREAD

**Issue by mattrix444** [capnkirok/animania#398]
### Expected Behavior
cheese mold having any recipes accompanying it.

### Actual Behavior
i can make the mold but the cheese mold does not have any uses and doesnt do anything when placed with milk in the crafting table.
also non of the cheeses have recipes (not sure if this is intentional or not )

### Version of Minecraft, version of Animania, Single Player or Server
Animania-1.10.2-1.3.5 single player

**Comment by capnkirok** [comment]
Only milk from certain Animania Cows (Holstein or Friesian), Sheep, or Goats work for making cheese. Vanilla milk does not make cheese.

[![Screenshot from Gyazo](https://gyazo.com/3c7ed1401cfdd30930c64aa51b11134b/raw)](https://gyazo.com/3c7ed1401cfdd30930c64aa51b11134b)

**Comment by mattrix444** [comment]
ah ok brill thanks :)

**Comment by Idioxic** [comment]
When doing this at the crafting table I don't get cheese, whether that be with a regular milk bucket or with a Friesian milk bucket. (also my milk buckets look more rounded when filled with animania milk)

**Comment by capnkirok** [comment]
Hey @Idioxic this is for 1.10, in 1.11 and 1.12 you place the cheese mold on the ground and pour the bucket into it.

**Comment by Idioxic** [comment]
Oh my gosh, thank you. This mod needs a FAQ forum , there's so much stuff! XD

**Comment by capnkirok** [comment]
Well, there's a pretty detailed forum post: https://minecraft.curseforge.com/projects/animania

Also, working on a Wiki... and maybe an in-game guide... at any rate... YES, lots of stuff
