### ISSUE TITLE
Cows, Pigs, Chickens double after every respawn

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/animania#40]
Due to the new spawning rules, cows, pigs, chickens are multiplying after every respawn event, in version 1.0.1. This is because Minecraft is now caching spawn events.

**Comment by Thyriel** [comment]
I don't think the problem is only restarts.
This is what our skyblock map looked like today after we left yesterday with 6 cows:
http://imgur.com/a/9GiLH

Server did not restart but there is a chunkloader running

**Comment by capnkirok** [comment]
Ok, will look into it. Are you guys using 1.0.1a?

**Comment by Thyriel** [comment]
1.0.1 - think i wait for the next release to update ;)
Maybe implement any "breeding maximum" mechanic ? Like when there are already x cows within an area they stop breeding ? (configurable)

**Comment by capnkirok** [comment]
Yes, was thinking exactly that. Well, as long as you are not using a world that once had vanilla animals in it, you should be fine with 1.0.1, otherwise be prepared to 'cull' everytime a re-spawn occurs.

**Comment by capnkirok** [comment]
Ok, have fixed the gestation period, after each birth, and baseline. I did not implement a cap, but the default is now 1 child per 1 MC day, provided the female is happy and the male is within a small radius.

**Comment by Thyriel** [comment]
I tested around a bit with the "care and feeding" settings in 1.0.1a to better balance them on a server with chunkloaders. However, it seems to me that some of these settings don't work like they should:

Settings used:

    I:"Egg hatch chance (1/x)"=4
    I:"Ticks before growth"=6000
    I:"Ticks between birthings"=72000
    I:"Ticks between drinking water"=4000
    I:"Ticks between feedings"=4000
    I:"Ticks between laying eggs"=24000
    I:"Ticks between playing"=12000

Chickens:
As far as i understand it, those settings should mean that a chicken can lay an egg every 20mins, and that egg has a 1:4 chance of generating a new chicken. Not sure how many growth stages there are (as it seems the 6000 ticks before growth is per growth stage) but as far as i've seen it takes a long time now to grow up.
All in all, starting with 2 chickens and a rooster, they should not be able to double themself faster then once per hour but i still had countless chickens the next morning (RL).
Next problem i noticed, chickens don't seem to eat the seeds laying on the ground. They never get used up so they stay happy forever.

Cows:
Here the opposite is happening. I didn't managed to get more then 1 calf on a whole RL day but the settings should allow one calf per hour. Interestingly the Waila tooltip says "breedable" on them, but they don't breed. (No unhappy animation, they have water and food)

**Comment by capnkirok** [comment]
Yeah, they don't all work the way you think they do. So, I think I'll have to make these more explicit. Good feedback.

24000 ticks actually is about 24 minutes, or one full MC day.

'Egg hatch chance' actually means... if the nest block has an egg in it, and the timer ticks, and there's a Rooster close enough.. the egg has a 1/4 chance of hatching... the other 3/4 times, it resets the timer. I keep this at 1/2 by default.

The 'Ticks before growth' is how many ticks before the tiniest increase in size, not full growth. You are correct that they are growth stages. 6000 is a very long time. The default is 150 ticks, which enables full growth in about 1 mc day. At 6000, it's going to take 40 mc days for full growth.

Having countless chickens the next day doesn't sound right... but I will take a closer look at this one.

The chickens have a 1/3 chance of destroying the seed block. They eat and become happy, but don't always destroy the block. I might change this back, and just keep them saturated longer.

The Waila tooltip refers to vanilla cows, has nothing to do with Animania. Although, ironically, Prof. Mobius (Razz's husband) did help out a bit with some of the pathing issues :)

**Comment by Thyriel** [comment]
> The chickens have a 1/3 chance of destroying the seed block. They eat and become happy, but don't always destroy the block. I might change this back, and just keep them saturated longer.

As far as i've noticed they either never destroy the seed block or never eat. I droped 3-4 seeds into their cake 2 days ago and they still lay on the ground. There where hundreds of chickens in there since then.

**Comment by capnkirok** [comment]
Fixed in 1.0.2 (all of the above, double spawns, growth ticks/labelling, seeds blocks always destroyed.)
