### ISSUE TITLE
Babies dissapear once they reach their max size

### ISSUE THREAD

**Issue by Wolfixsp** [capnkirok/animania#404]
### Expected Behavior
Babies turning into Adults

### Actual Behavior

Babies growing until being max sized and then dissapearing
### Version of Minecraft, version of Animania, Single Player or Server

Single player, Minecraft 1.12.2 with animania 1.3.5 the last version

**Comment by capnkirok** [comment]
Which animal? I have a feeling this is spawn limit related (you are at your spawn limit). May want to try increasing your limit in the config, or taking the animal to a new chunk area.

**Comment by capnkirok** [comment]
Also, if you have TheOneProbe installed, you can see the Pregnancy Timer... if it just says Pregnant over the female... but it is not ticking down, then it's definitely the Spawn Limit.

**Comment by Wolfixsp** [comment]
Actually i have seen that in cows, where the claf born but they get big and then they dissapear, in chicks they take a time to hacth but they grow and piglets dont even give birth, also i put a wild piglet and it seems that it scapes from the fence so maybe the are giving birth but scaping, ill see.                                              
Also i would like to now how to change thet spawn limit please
Hope u have a good day, Wolfixsp

**Comment by Wolfixsp** [comment]
also ill be cheking the new version and tell you if its fixed :D

**Comment by Wolfixsp** [comment]
I have seen one chick dissapearing but the others are growing

**Comment by Wolfixsp** [comment]
was spawn config, fixed! thx a lot now i have my farm full of babies

**Comment by capnkirok** [comment]
He he :)
