### ISSUE TITLE
[1.10.2; 1.3.5] Hoppers cannot pull from nests

### ISSUE THREAD

**Issue by Sandriell** [capnkirok/animania#405]
I am unable to get eggs to be pulled from nests using hoppers.

### Expected Behavior

Hooper being able to pull eggs from nests

### Actual Behavior

Nothing happens; eggs stay in the nest.

### Steps to Reproduce

Place, chest, place hopper, place nest on top.

### Version of Minecraft, version of Animania, Single Player or Server

1.10.2, 1.3.5, Server

**Comment by capnkirok** [comment]
Yeah, 1.3.5 is not automated. Old trough, old nest, no hamster wheel...

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#124
