### ISSUE TITLE
1.12.2 cow has wierd blue cloud above it

### ISSUE THREAD

**Issue by captcookie** [capnkirok/animania#408]
[https://media.discordapp.net/attachments/374323167872679946/374362717424713728/2017-10-29_19.59.17.png?width=848&height=450](url)

[https://cdn.discordapp.com/attachments/374323167872679946/374362735833645058/2017-10-29_19.59.29.png](url)

The screen gets darker. The jei is missing recipes. In the distance as the cow moves, a blue shadow at the top of screen moves as the cow moves.

**Comment by captcookie** [comment]
When I remove the mod everything is normal and the recipes are in tack.

**Comment by capnkirok** [comment]
There might be something wrong with the one you downloaded. I would delete that version and re-download from Curse. Let me know if that does it.

**Comment by capnkirok** [comment]
Hey @captcookie I am assuming everything is ok and am going to close this one.
