### ISSUE TITLE
[1.10.2]after updating to 1.3.6, animals disappeared.

### ISSUE THREAD

**Issue by sharlin073** [capnkirok/animania#409]
### Actual Behavior
Hereford cows disappeared. I am not sure about other animals, but it seems like I can not find other animals around, also.

### Steps to Reproduce
update animania.

I play minecraft with Pam's harvestcraft, Tough as nails, realistic world generation, Quark.
I didn't updated any other mods today. since now it was okey.

### Version of Minecraft, version of Animania, Single Player or Server
1.10.2 / 1.3.6 Single Player

### Screenshots encouraged
they are not invisible, they are just gone...

**Comment by capnkirok** [comment]
What version were you on before the upgrade? 1.3.5 ? Or earlier?

**Comment by sharlin073** [comment]
it was 1.3.5 :)

**Comment by capnkirok** [comment]
Well, that's disappointing. I will do some testing tonight. As you suspect, this should not happen.

**Comment by PeakXing** [comment]
mee to
mc ver 1.12.2
forge ver 14.23.0.2503
mod ver 1.3.6.1

**Comment by Xeon2003** [comment]
We have the same issue, except that only Chicken disappear.
Animania 1.3.6.1 / MC 1.11.2 Server

**Comment by capnkirok** [comment]
Thanks @Xeon2003 ... I have another case of Chickens disappearing as well. I am wondering if this is caused by extending vanilla animals (which can disappear).

**Comment by capnkirok** [comment]
Ok, I've done a few hours of testing on SP... it doesn't appear to be happening in a new world. I'm going to test upgrades now.

**Comment by capnkirok** [comment]
Guys, I did tons of testing on this. I'm not seeing ANY animals disappear on server or client in new worlds, or when upgrading from 1.3.5. I hope it's not a conflict causing this. 

Can anyone report animals disappearing on a fresh world after 1.3.7?

**Comment by capnkirok** [comment]
This was a bug on 1.10 and 1.11.

**Comment by sharlin073** [comment]
Thanks!
