### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by Alrawn** [capnkirok/animania#41]
This happens every time I try to load an established world after adding Animania to my private pack. Strange thing is, I can create a new world just fine using the same mods.
Any ideas?
[crashlog](http://pastebin.com/kQD3MLm4)

**Comment by capnkirok** [comment]
Hmmm... the crash line in question is checking to see if the block near the pig has a valid registry name. I can try to put error trapping around it, but this should not be crashing here.

**Comment by Alrawn** [comment]
Seems to be a pig-specific issue. I managed to get into my world after deleting the ticking pig via MCedit and disabling pig spawns. all other animals seem to spawn just fine. I tried re-enabling pig spawns and it worked for a while (I saw pigs spawn) until another ticking pig spawned and crashed the game.

**Comment by capnkirok** [comment]
I had another problem with the Yorkshire Sow early in development. No other pigs had issues, just that one. I think I'll have to go line by line to see what's happening. Thanks.

**Comment by capnkirok** [comment]
Ok, I've put in error trapping for this. It means that one of your mods has a block that has a null registry name... at any rate, should fix the issue when it goes live.

**Comment by capnkirok** [comment]
Closed in 1.0.2
