### ISSUE TITLE
[1.12.2] Crash with Server

### ISSUE THREAD

**Issue by twoworlds** [capnkirok/animania#410]
When entering my world after updating to animania 1.3.6 I get this error:

https://pastebin.com/jhvVzSAj

Server: MC 1.12.2
Forge: 14.23.0.2517
Animania: 1.3.6

**Comment by capnkirok** [comment]
Ah, looks like an issue with the new 'rain fills troughs' feature. Thanks for the report.

**Comment by ArMoReDfUrY** [comment]
just had the same on my SSP world. i'd post the crash but it reads exactly like Twoworlds Report.
thanks for the awesome mod :) looking forward to its future.

**Comment by capnkirok** [comment]
Hey guys, was there anything in your troughs when this happened?

**Comment by twoworlds** [comment]
Yes, at least there was water in the troughs, as I am using an automated refilling system with the Xnet mod from McJty and so the water troughs are always full.

**Comment by capnkirok** [comment]
Never mind. That's exactly the problem. If there's any kind of 'dry' food in the trough when its raining (on a server)... there's a crash. 

Ok, fixed in dev and patching shortly.

**Comment by capnkirok** [comment]
Ok, it's up now. Version 1.3.6.1.

Thanks again!

https://minecraft.curseforge.com/projects/animania/files/2496016
