### ISSUE TITLE
Performance issues after latest update.

### ISSUE THREAD

**Issue by Krhymez** [capnkirok/animania#412]
The latest version of the mod is the "lag killer" but it is causing very low tps on servers.

After running a command to kill all the animania mobs, the tps went back up to 20. Before killing them, tps was 7.

**Comment by kurtu5** [comment]
I am working with Krhymez doing testing of this latest version for his pack Primal.   https://minecraft.curseforge.com/projects/primal
 

He recently updated the pack to 1.0.10(animania-1.12.2-1.3.6.jar) from 1.0.9(animania-1.12.2-1.3.5.jar) and we restarted our server and immediately saw low tps.

I ran /cofh killall animania and reported to him the improvement to 20 tps.  I then spawned in a bunch of new animania mobs and performance went down to 16 or so.  Right now I am waiting for them to get hungry to see if it worsens.

We are discussing this on our discord if you want realtime communication with us.   https://discord.gg/YGtcVhJ

**Comment by capnkirok** [comment]
Unfortunately, I am at work. Can you get a VisualVM snapshot of the CPU? That will let me know what threads/classes are causing the issue.

I've already confirmed with two other pack devs that performance increased, and I see it here as well, so a bit confused. I really just added a conditional in the pathing code that cuts down on the loops... it shouldn't be getting worse.

For testing, you can always change the feeding and watering timers to lower (I usually put them at say 1000).

**Comment by capnkirok** [comment]
I am back later in the afternoon (in about 4 hours, will check in on Discord then)

**Comment by capnkirok** [comment]
![2017-10-31_11 40 21](https://user-images.githubusercontent.com/9628379/32219996-5d8b189a-be30-11e7-9173-4acd2ac3394d.png)

**Comment by kurtu5** [comment]
We are rolling back to a snapshot right after the update to get you better information.  BTW what are you using to show tps like that?   Here is a list of mod changes from out .9 to .10 pack.   "--->" show the version number changes.

AdHooks-1.12.1-3.1.1.0-build.0034.jar
animania-1.12.2-1.3.5.jar    --->  1.3.6
antiqueatlas-1.12-4.4.4.jar
AppleCore-mc1.12.2-2.2.2.jar
astralsorcery-1.12.2-1.7.jar    --->  1.7.2
BetterAdvancements-1.12.2-0.0.3.15.jar
BetterQuesting-2.5.236.jar
betterwithengineering-1.2.jar
BetterWithMods-1.12-2.0.14.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
binnie-mods-1.12.2-2.4.0.82.jar   ---->  .83
BirdsNests1.12.2-2.0.0.jar
blockcraftery-0.1.3.jar
Bookshelf-1.12.2-2.2.468.jar
Ceramics-1.12-1.3.3b.jar
Chameleon-1.12-4.1.3.jar
ChestTransporter-1.12-2.8.7.jar
Chisel-MC1.12-0.0.14.18.jar
chiselsandbits-14.9.jar
ClientTweaks_1.12-3.1.2.jar
CodeChickenLib-1.12-3.1.3.313-universal.jar
CoFHCore-1.12-4.3.6.14-universal.jar
CoFHWorld-1.12-1.0.1.8-universal.jar
CookingForBlockheads_1.12.1-6.3.6.jar
coroutil-1.12.1-1.1.22.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CraftTweaker2-1.12-4.0.8.jar    ---->   .9
CTM-MC1.12-0.2.3.9.jar
ctmortar-1.12.2-1.0.2-1-g1210615.jar
Currency-1.12.0-1.2.6.jar
DarkUtils-1.12.2-1.7.176.jar
davincisvessels-1.12-6.337-full.jar
DynamicSurroundings-1.12.2-3.4.7.2.jar
ediblebugs-MC1.12.0_EB1.5.7.2443.jar
elulib-0.1.7.jar
felling-1.2.3.jar
foamfix-0.8.0-1.12-law.jar
foamflower-1.12.2-1.0.0.0-beta1.jar
forestry_1.12.2-5.6.0.201.jar
ForgeCraft-1.3.25.jar
ForgeEndertech-1.12.1-4.2.0.0-build.0034.jar
FTBLib-4.2.2.jar                            ---> .3
FTBUtilities-4.2.1.jar                      ---> .2
furniture-4.1.5-1.12.jar
HardcoreDarkness-MC1.12-1.9.jar
Harvest-1.12-1.2.6-18.jar
ImmersiveEngineering-0.12-74.jar
ImmersiveEngineering-0.12-74-core.jar
immersivepetroleum-1.12-1.1.3.jar
ImmersiveRailroading-0.3.4.jar             ---> .5
immersivetech-1.12-1.3.4.jar
InventoryTweaks-1.63.jar
IronBackpacks-1.12.2-3.0.0.jar
ironchest-1.12.2-7.0.34.820.jar
jei_1.12.2-4.8.0.105.jar
jeibees-0.9.0.5-mc1.12.2.jar
JustAFewFish-1.7_for_1.12.jar
LootTableTweaker-1.12.2-1.1.13.jar
malisiscore-1.12.2-6.1.7.jar
malisisdoors-1.12.2-7.1.1.jar
MCA-1.12.x-5.3.1-universal.jar
MCMultiPart-2.3.3.jar
modnametooltip_1.12.2-1.10.0.jar
modtweaker-4.0.4.jar
movingworld-1.12-6.342-full.jar
MTLib-3.0.1.jar
multistorage-1.12.0-1.4.4.jar
NetherPortalFix_1.12.1-5.3.13.jar         REMOVED
NotEnoughIDs-1.5.4.2.jar
OpenGlider-1.12.1-1.1.0.jar
Pam's ClaySpawn 1.12a.jar
Plants-2.1.0.jar
platforms-1.12.0-1.4.1.jar
PrimalCore-1.12.2-0.5.20.jar
questbook-3.0.0-1.12.jar
RadixCore-1.12.x-2.2.1-universal.jar
RebornCore-1.12.2-3.4.8.138-universal.jar    ---> 9.143
RedstoneFlux-1.12-2.0.1.2-universal.jar
RefinedRelocation_1.12.1-4.1.12.jar
roots-2-0.103.jar
roughTweaks0.2.3-1.12.jar
rustic-0.4.3.jar
SeedDrop-1.1.0-1.12.jar
shetiphiancore-1.12.0-3.5.4.jar
SimpleSponge-1.12-3.5.jar
SoundFilters-0.10_for_1.12.jar
SpartanShields-1.12-1.3a.jar
SpartanWeaponry-1.12-beta-1.1.jar
spikemod-1.12-2.1.0.jar
StandardExpansion-2.4.134.jar
StevesCarts-1.12.2-2.4.10.49.jar
stg-1.12-1.2.1.jar
StorageDrawers-1.12.1-5.3.3.jar
StorageDrawersExtras-1.12-3.1.0.jar
TechReborn-1.12.2-2.7.9.301-universal.jar     ---> 10.327 
theoneprobe-1.12-1.4.18.jar
ThermalDynamics-1.12-2.3.6.13-universal.jar
ThermalFoundation-1.12-2.3.6.16-universal.jar
thutcore-5.11.6.jar                             ---> .7
thuttech-6.0.6.1.jar                          ----> 0.7
tombstone-1.3.9-1.12.jar
topaddons-1.12.2-1.1.2.jar
ToughAsNails-1.12-3.0.0.64-universal.jar
twilightforest-1.12.2-3.3.202-universal.jar
vending-1.12.2-3.0.0.0.jar
YABBA-1.0.9.jar                               ---> .10
zombieawareness-1.12.1-1.11.10.jar

**Comment by Krhymez** [comment]
I will close this.

The issue seems to be more about the loaded chunks than the animania mobs that are in them.  The mobs just increase the issue. So after killing all, it appeared they were the cause but they were not.  I am still not sure what caused this after the update... possibly Forge. 

The pack is also in 1.12.2 while that screenshot you posted is in 1.12.  Not sure if Forge on both versions is identical.

**Comment by capnkirok** [comment]
Thanks guys. I will update my server to 1.12.2 and test again also. 

@kurtu5 I uses Nallar's Tick Profiler: https://minecraft.curseforge.com/projects/tickprofiler

What are you guys using?

**Comment by kurtu5** [comment]
cofh tps

**Comment by kurtu5** [comment]
BTW we tried running VisualVM but our box doesn't have any Xdrivers so we cant X11 forward to a local display so we gave up on that.

**Comment by kurtu5** [comment]
https://www.dropbox.com/s/b7wrcvdilx6kvd1/application-1510050000839.apps?dl=0
