### ISSUE TITLE
Is there a way to set the settings on a Server with multiple players?

### ISSUE THREAD

**Issue by Shareina** [capnkirok/animania#413]
After testing this on singleplayer, myself and my family fell in love. We were hoping to apply it to our family server, but we ran into a few lag problems due to the higher entity count.

We are aware there is a way to do this on singleplayer, but we have not found a way to do this on the server.

If this is not a possibility, I would like to post this as a suggestion.

We are using Forge/Minecraft 1.10.2.

Thanks!

EDIT: My dad found the config files, I am so sorry about that!

**Comment by capnkirok** [comment]
Glad you fixed it, hope you enjoy! The latest version on 1.10 has solved some of the lag issues... but there have some reports of people losing their animals... so... would upgrade when you want to start a new world :)
