### ISSUE TITLE
[SUGGESTION] Allow animals from this mod to eat modded flowers and grass

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#417]
Biomes O' Plenty has a bunch of examples of this, for instance.

**Comment by NavyT** [comment]
Maybe even plants from (Plants) mod
https://minecraft.curseforge.com/projects/plants

**Comment by capnkirok** [comment]
Yes, I've wanted to do this for sometime.

**Comment by capnkirok** [comment]
Biomes o' Plenty uses a custom class with no reference to vanilla except 'IShearable'. Would prefer to do this without an API, but will let you know.

**Comment by capnkirok** [comment]
Well, I can extend it to use BlockCrops... which most mods use... just not BOP. I can ping glitchfiend.
