### ISSUE TITLE
(Bug) Sheeps breeding work and don't/Chunk bug?

### ISSUE THREAD

**Issue by NavyT** [capnkirok/animania#419]
Most of my sheep or half of them have a bug where there pregnant ticks are 100 and go down. But instead of giving birth, it repeats back at 100. It takes a while for them to ACTUALLY give birth. As it seems the coding is waiting for the other sheep to have theirs. Also, sometimes when i don't nametag a momma sheeps baby. It'll disappear when i leave the chunk.

(Edit) The sheep after a few birthings have the 100 sec bug. Even if others haven't had their first birth. When it happens like this to one. It **won't** fix it self.

They are all also fully fed with water and food.

**Comment by Wolfixsp** [comment]
i think is spawn config maybe, go to config folder in ur .minecraft folder and edit animania config with wordpad, by changing max sheep families per chunk and max sheeps per chunk

**Comment by Wolfixsp** [comment]
i had that problem with cows but config file fixed it

**Comment by NavyT** [comment]
Thanks!

**Comment by capnkirok** [comment]
Yeah, I think I need to add something to TOP or WAILA that says "At Spawn Limit" or something.
