### ISSUE TITLE
clay buckets/ceramics compatibility

### ISSUE THREAD

**Issue by InkDragon** [capnkirok/animania#42]
requesting compatibility to collect milk in clay buckets added by either the [clay bucket](https://github.com/abecderic/clay-bucket) mod or [ceramics](https://github.com/KnightMiner/Ceramics) mod. also requesting the ability to put water into troughs with clay buckets.

let me know if I should instead contact the mod authors for support on their instead. <3

**Comment by capnkirok** [comment]
- I can do #1 if it's vanilla milk, but special milks (holstein, friesian) need special buckets
- #2 i can do on my own

**Comment by InkDragon** [comment]
>  can do clay milk buckets if it's vanilla milk (and the item exists in clay bucket mod), but special milks (holstein, friesian) need special buckets
this is fine <3 also gives an alternative way to collect vanilla milk

**Comment by WesCook** [comment]
You might also consider using the Forge Universal Bucket feature for the custom milks.  Then the bucket texture will respond appropriately to texture packs, and mods like Ceramics will generate buckets for special milks as well (though right click functionality would still need to be implemented manually).

**Comment by capnkirok** [comment]
Yes, this is probably the best solution. Means I need to make Slop a liquid, which would help with automation.

**Comment by capnkirok** [comment]
Hey, this is added to the next release of 1.11.2

**Comment by WesCook** [comment]
Awesome.  :)

Just out of curiosity, have new features started becoming 1.11-exclusive or is this an exception?

**Comment by capnkirok** [comment]
There are a few that won't be in 1.10 yet. We do plan on bringing the missing features to 1.10 in a future release.
