### ISSUE TITLE
Pigs dont come out of the mud and start starving because that

### ISSUE THREAD

**Issue by Wolfixsp** [capnkirok/animania#420]
### Expected Behavior

To pigs to come out of mud to swim, drink and eat
### Actual Behavior

Pigs stay in mud a lot and start to be sad cause starving and thirsty
### Steps to Reproduce

idk if it's a suggestion to pigs to have a timero to come out of mud and have a cooldown or they do and theres a glitch
### Version of Minecraft, version of Animania, Single Player or Server
minecraft 1.12.2 animania 1.3.6 single player

**Comment by capnkirok** [comment]
You can change the mud timer in the config so they go there less often... say 24000 ticks or so instead of what it is by default

**Comment by Wolfixsp** [comment]
Is it in config file? I'll check that thx
