### ISSUE TITLE
Game crashes due to rain fulling troughts

### ISSUE THREAD

**Issue by Wolfixsp** [capnkirok/animania#421]
my game crashes when it rains, says that theres a block with excess of ticks
and that block is the trought

**Comment by capnkirok** [comment]
What version are you on? Why did you not answer the questions in the template?

**Comment by capnkirok** [comment]
I see from a previous posting that you are using 1.3.6... 1.3.6.1 fixed this bug, so you need to update.

![image](https://user-images.githubusercontent.com/9628379/32413289-da01a722-c20e-11e7-9ea2-f7f40f17944c.png)

https://minecraft.curseforge.com/projects/animania/files/2496016

**Comment by Wolfixsp** [comment]
Yeah thx it was 1.3.6 now it works with the new update
