### ISSUE TITLE
(Suggestion/idea) sheepherders

### ISSUE THREAD

**Issue by NavyT** [capnkirok/animania#422]
There's a staff that the sheep follow. If its in your hand they will follow it. You could place it down and they will stay near the stick.

**Comment by Wolfixsp** [comment]
Omg i was thinking about the same idea, I agree totally!

**Comment by Deshiba** [comment]
Maybe guarded by the sheepdogs from suggestion #228

**Comment by capnkirok** [comment]
Great idea !

**Comment by Wolfixsp** [comment]
Tras sheepdogs to protect the sheeps from wild wolves cause they are always trying to kill my sheeps

**Comment by capnkirok** [comment]
Hey, I've add this to our to do list. In an effort to clean up this git, however, I'm going to remove it from git for now, so git only shows bugs. Thanks for the suggestion!
