### ISSUE TITLE
Ambiance Mode

### ISSUE THREAD

**Issue by ashly138** [capnkirok/animania#423]
Is it normal with Ambiance Mode that the One Probe still displays that animals are hungry and so on?

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2 & Latest Mod Version for it and SP

**Comment by capnkirok** [comment]
Well, I guess I could hide that information. Thanks for the suggestion.

**Comment by capnkirok** [comment]
Ok, this will be in 1.4
