### ISSUE TITLE
Performance issues with animania on servers. 

### ISSUE THREAD

**Issue by kiwifrogg** [capnkirok/animania#424]
### Expected Behavior
Normal Tps with a few players online.

### Actual Behavior
Tps drop on server when only 2 players online(or more), often as low as 7, when killing off only the animania mobs the tps does return to 20. Screenshots are not as bad as usual, the zip has visual vm output before and after, a class called dethwatch showed up as different between the 2 files. 

### Steps to Reproduce
Server with 2 or more ppl online, with differing animania mobs.

### Version of Minecraft, version of Animania, Single Player or Server
Server 1.12.2,  forge-1.12.2-14.23.0.2532-universal, Animania-1.12.2-1.3.6.1

### Screenshots encouraged
![2017-11-09_21 06 05](https://user-images.githubusercontent.com/15997082/32595990-b0cf5dd2-c596-11e7-911a-bc484f95bc5d.png)
![2017-11-09_21 06 54](https://user-images.githubusercontent.com/15997082/32595993-b2e50c48-c596-11e7-8f01-3e3d601bb378.png)

[tpsdrop.zip](https://github.com/capnkirok/animania/files/1456916/tpsdrop.zip)

**Comment by capnkirok** [comment]
Thanks for the detail and the VM report. Two questions:
- Is performance fine with only one player? (this could be significant)
- Can you post your modlist? I'm wondering if there's a conflict somewhere.

**Comment by kiwifrogg** [comment]
its the primal pack by krymez its a carry on from the issue we closed last time,
AdHooks-1.12.1-3.1.1.0-build.0034.jar
animania-1.12.2-1.3.5.jar ---> 1.3.6
antiqueatlas-1.12-4.4.4.jar
AppleCore-mc1.12.2-2.2.2.jar
astralsorcery-1.12.2-1.7.jar ---> 1.7.2
BetterAdvancements-1.12.2-0.0.3.15.jar
BetterQuesting-2.5.236.jar
betterwithengineering-1.2.jar
BetterWithMods-1.12-2.0.14.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
binnie-mods-1.12.2-2.4.0.82.jar ----> .83
BirdsNests1.12.2-2.0.0.jar
blockcraftery-0.1.3.jar
Bookshelf-1.12.2-2.2.468.jar
Ceramics-1.12-1.3.3b.jar
Chameleon-1.12-4.1.3.jar
ChestTransporter-1.12-2.8.7.jar
Chisel-MC1.12-0.0.14.18.jar
chiselsandbits-14.9.jar
ClientTweaks_1.12-3.1.2.jar
CodeChickenLib-1.12-3.1.3.313-universal.jar
CoFHCore-1.12-4.3.6.14-universal.jar
CoFHWorld-1.12-1.0.1.8-universal.jar
CookingForBlockheads_1.12.1-6.3.6.jar
coroutil-1.12.1-1.1.22.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CraftTweaker2-1.12-4.0.8.jar ----> .9
CTM-MC1.12-0.2.3.9.jar
ctmortar-1.12.2-1.0.2-1-g1210615.jar
Currency-1.12.0-1.2.6.jar
DarkUtils-1.12.2-1.7.176.jar
davincisvessels-1.12-6.337-full.jar
DynamicSurroundings-1.12.2-3.4.7.2.jar
ediblebugs-MC1.12.0_EB1.5.7.2443.jar
elulib-0.1.7.jar
felling-1.2.3.jar
foamfix-0.8.0-1.12-law.jar
foamflower-1.12.2-1.0.0.0-beta1.jar
forestry_1.12.2-5.6.0.201.jar
ForgeCraft-1.3.25.jar
ForgeEndertech-1.12.1-4.2.0.0-build.0034.jar
FTBLib-4.2.2.jar ---> .3
FTBUtilities-4.2.1.jar ---> .2
furniture-4.1.5-1.12.jar
HardcoreDarkness-MC1.12-1.9.jar
Harvest-1.12-1.2.6-18.jar
ImmersiveEngineering-0.12-74.jar
ImmersiveEngineering-0.12-74-core.jar
immersivepetroleum-1.12-1.1.3.jar
ImmersiveRailroading-0.3.4.jar ---> .5
immersivetech-1.12-1.3.4.jar
InventoryTweaks-1.63.jar
IronBackpacks-1.12.2-3.0.0.jar
ironchest-1.12.2-7.0.34.820.jar
jei_1.12.2-4.8.0.105.jar
jeibees-0.9.0.5-mc1.12.2.jar
JustAFewFish-1.7_for_1.12.jar
LootTableTweaker-1.12.2-1.1.13.jar
malisiscore-1.12.2-6.1.7.jar
malisisdoors-1.12.2-7.1.1.jar
MCA-1.12.x-5.3.1-universal.jar
MCMultiPart-2.3.3.jar
modnametooltip_1.12.2-1.10.0.jar
modtweaker-4.0.4.jar
movingworld-1.12-6.342-full.jar
MTLib-3.0.1.jar
multistorage-1.12.0-1.4.4.jar
NetherPortalFix_1.12.1-5.3.13.jar REMOVED
NotEnoughIDs-1.5.4.2.jar
OpenGlider-1.12.1-1.1.0.jar
Pam's ClaySpawn 1.12a.jar
Plants-2.1.0.jar
platforms-1.12.0-1.4.1.jar
PrimalCore-1.12.2-0.5.20.jar
questbook-3.0.0-1.12.jar
RadixCore-1.12.x-2.2.1-universal.jar
RebornCore-1.12.2-3.4.8.138-universal.jar ---> 9.143
RedstoneFlux-1.12-2.0.1.2-universal.jar
RefinedRelocation_1.12.1-4.1.12.jar
roots-2-0.103.jar
roughTweaks0.2.3-1.12.jar
rustic-0.4.3.jar
SeedDrop-1.1.0-1.12.jar
shetiphiancore-1.12.0-3.5.4.jar
SimpleSponge-1.12-3.5.jar
SoundFilters-0.10_for_1.12.jar
SpartanShields-1.12-1.3a.jar
SpartanWeaponry-1.12-beta-1.1.jar
spikemod-1.12-2.1.0.jar
StandardExpansion-2.4.134.jar
StevesCarts-1.12.2-2.4.10.49.jar
stg-1.12-1.2.1.jar
StorageDrawers-1.12.1-5.3.3.jar
StorageDrawersExtras-1.12-3.1.0.jar
TechReborn-1.12.2-2.7.9.301-universal.jar ---> 10.327
theoneprobe-1.12-1.4.18.jar
ThermalDynamics-1.12-2.3.6.13-universal.jar
ThermalFoundation-1.12-2.3.6.16-universal.jar
thutcore-5.11.6.jar ---> .7
thuttech-6.0.6.1.jar ----> 0.7
tombstone-1.3.9-1.12.jar
topaddons-1.12.2-1.1.2.jar
ToughAsNails-1.12-3.0.0.64-universal.jar
twilightforest-1.12.2-3.3.202-universal.jar
vending-1.12.2-3.0.0.0.jar
YABBA-1.0.9.jar ---> .10
zombieawareness-1.12.1-1.11.10.jar

**Comment by kiwifrogg** [comment]
Oh and yes the issue only happened once 2 people are loading more than 1 space.  So like 2 basses 1000 blocks apart. When those players visit each other at one base the tps usually returns to normal. We also did a mobs kill no change, then a MCA(villager) kill and no change, it is only when we kill the animania mobs that the tps returns. I'm not sure if it's a particular animal causing it.

**Comment by capnkirok** [comment]
Thanks so much for the VM snapshot and the detail. Looks like it's still over-indexing with animals and pathfinding (cows in particular). Is there anything unusual you saw with the cows? Like, are there many of them... or are they underground, or trapped somewhere where they see water or food but can't get near it. Would help with replicating the bug here.
![image](https://user-images.githubusercontent.com/9628379/32662157-d4c381b2-c629-11e7-8215-5fde8ed25edb.png)

**Comment by kiwifrogg** [comment]
We've closed that world because we started an official pack server, however there were not huge number of cow spawns, there was a spot on top of my base where a single cow would always get stuck, it spawned in there.  I'll keep an eye on things on this new world and see if something similar occurs.

**Comment by capnkirok** [comment]
I've added some new checks in the latest version. I believe the AI was getting pegged in a continuous loop when an animal didn't find what it needed. I've added a 'release valve' and buffer between checks. Hopefully this fixes the problem. Look for release 1.4, coming out late tonight and let me know how it goes.

**Comment by capnkirok** [comment]
@kiwifrogg ok the 1.4 update is live. Crossing my fingers. https://minecraft.curseforge.com/projects/animania

**Comment by kiwifrogg** [comment]
Sweet as, Thanks heaps I'll let you know :) looking forward to these carts too

**Comment by capnkirok** [comment]
Ok, fresh build up on Curse Forge. I did extensive testing using VisualVM... I really think we got it this time. Am closing, but feel free to comment again if you have issues.

**Comment by kurtu5** [comment]
kiwi and I will let you know if issues arise again.  Thanks for being an awesome mod maker.

**Comment by hunter688** [comment]
Looks like 1.4.1 fixes this issue, thanks a lot!

**Comment by capnkirok** [comment]
Oh this is great news!

**Comment by Sandriell** [comment]
Have you stopped supporting 1.10.2?

**Comment by capnkirok** [comment]
@Sandriell no we still support it. As a matter of fact, I have an update coming today which includes the carts and a bunch of other features.
