### ISSUE TITLE
Rabbits unable to drink from trough

### ISSUE THREAD

**Issue by Rambonata** [capnkirok/animania#425]
### Expected Behavior
Rabbits satisfy their thirst and hunger by using troughs.

### Actual Behavior
Rabbits ignore filled troughs as a water source.
They however, do eat from a trough.

### Steps to Reproduce
Rabbit in pen with only trough as water source.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft version: 1.12.2, Animania version: 1.3.6.1, Single Player.

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/29131003/32693809-d3dcdce6-c6fe-11e7-9bda-f051a40405c2.png)
I had it sit there for a while, The Cottontail in the picture was also thirsty.

**Comment by capnkirok** [comment]
Yeah, none of the 'rodents'... ferrets, hamsters, hedgehogs, rabbits can drink from troughs. Marking this a suggestion.

**Comment by Rambonata** [comment]
Sorry for technically wasting your time.
