### ISSUE TITLE
Carving knife only works with full durability

### ISSUE THREAD

**Issue by cowardlyDog** [capnkirok/animania#426]
### Expected Behavior
Carving knife should work as long as it has durability left.

### Actual Behavior
It doesn't it just works with full durability.

### Steps to Reproduce
Use a used carving knife with any cheese or prime meat (only tried goat cheese and I think some goat prime meat, but I suppose it happens with any).

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania-1.12.2-1.3.6.1
Single Player

### Screenshots encouraged

**Comment by capnkirok** [comment]
Hmm... I have no problems with this, and am sure would have gotten reports from others if it wasn't working. Do you have any other recipe modifying mods installed?

![image](https://user-images.githubusercontent.com/9628379/32704277-9b6742f2-c802-11e7-89f6-e66cbbc66ebe.png)

Only Cow and Pig roasts can be further carved (before cooking).

Have you tried re-starting? Sometimes the recipes don't work the first load I've noticed...

**Comment by Tschipp** [comment]
Yep I've also tested this, works fine for me

**Comment by cowardlyDog** [comment]
Yeah I tought it could be just me, the only mod I have of that kind is crafttweaker don't know why happened but I already solved it with crafttweaker. And it did also happen after restarting.

Here's the script in case someone else has this issue: https://pastebin.com/diWr9fq3

**Comment by capnkirok** [comment]
Thanks for posting the script!

**Comment by ALongStringOfNumbers** [comment]
Depending on the Forge version you were using, https://github.com/MinecraftForge/MinecraftForge/issues/4516
could be be related

**Comment by Nerezza** [comment]
Just wanted to note that I encountered this issue and also believe it to be caused by forge, as it also affected another mod unrelated to animania.

**Comment by capnkirok** [comment]
It is caused by the current version of forge, yes, @ALongStringOfNumbers is correct. Lex is working on it.

**Comment by LexManos** [comment]
Please test on Forge 2552+ I believe I have fixed this if you use the normal Shapeless/Ingredients. 
See my comment: https://github.com/MinecraftForge/MinecraftForge/issues/4516#issuecomment-346478694

**Comment by capnkirok** [comment]
It works. Thanks @LexManos !
