### ISSUE TITLE
Animals do not eat/drink on their own, can only be handfed

### ISSUE THREAD

**Issue by cowardlyDog** [capnkirok/animania#428]
### Expected Behavior
Chickens should drink if they're thirsty and have a trough filled with water nearby, should eat if there's seeds on the ground and shouldn't be looking for a nest when they're sitting in one.

### Actual Behavior
They are always thirsty, hungry and looking for a nest

### Steps to Reproduce
Have chickens close to water, food and a nest and wait.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.4
Single Player

### Screenshots encouraged
![2017-11-14_00 52 27](https://user-images.githubusercontent.com/30737871/32767101-81f0e816-c8d7-11e7-800e-8c264708eabc.png)
![2017-11-14_00 52 50](https://user-images.githubusercontent.com/30737871/32767113-89e507dc-c8d7-11e7-9e52-a825039ef139.png)
![2017-11-14_00 55 26](https://user-images.githubusercontent.com/30737871/32767119-8ef93446-c8d7-11e7-8be2-25b78c8abce7.png)
![2017-11-14_00 55 30](https://user-images.githubusercontent.com/30737871/32767122-91da1770-c8d7-11e7-9bfe-d3947b89d35c.png)

I hope it isn't just me this time, I fed the chickens manually that's why they're not hungry in the screenshots, but they weren't eating. Another issue I found is that pigs are always bored as shown in these screenshots:

![2017-11-14_00 54 05](https://user-images.githubusercontent.com/30737871/32767264-33c7a6d8-c8d8-11e7-8215-d46dcc4d4cfb.png)
![2017-11-14_00 53 00](https://user-images.githubusercontent.com/30737871/32767266-33d6c186-c8d8-11e7-9db3-8807e3253bf3.png)
![2017-11-14_00 53 04](https://user-images.githubusercontent.com/30737871/32767267-33e5d180-c8d8-11e7-8dff-25ec0743fc6f.png)
![2017-11-14_00 53 09](https://user-images.githubusercontent.com/30737871/32767268-33f47fc8-c8d8-11e7-9b2a-b7627d6b148c.png)

**Comment by SSyl** [comment]
I'm having the same issue. Updated to 1.4 from 1.3.6.1 on MC 1.12.2.

Chickens don't eat or drink and they're always looking for a nest, but never sit in one/lay eggs. You can hand feed them, but that's it.

I also noticed that hedgehogs don't eat, dig up food, or drink water.

**Comment by capnkirok** [comment]
Yep, looks like I messed something up. Will have to do a hot fix. On the plus side... it has reduced lag ha ha ha.

**Comment by capnkirok** [comment]
Ok, I will push this fix tonight. For now, all you can do is handfeed (or go Ambiance mode)

**Comment by capnkirok** [comment]
Ok, this is fixed. Pushing shortly.
