### ISSUE TITLE
Make Less Blocks connect to fences

### ISSUE THREAD

**Issue by FelixRilling** [capnkirok/animania#430]
### Expected Behavior
Blocks like nests or placed seeds don't connect to fences

### Actual Behavior
Blocks like nests or placed seeds connect to fences

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.4, Single Player

### Screenshots encouraged
https://how-about-th.at/64cc83.png

**Comment by Tschipp** [comment]
Agree, looks weird. I'll take care of it.
