### ISSUE TITLE
Horses dont need saddles to ride

### ISSUE THREAD

**Issue by Krhymez** [capnkirok/animania#431]
Not a huge deal, but i find it odd that i can just ride any horse in the wild. No saddle, no taming. Any plans to add a taming feature?

**Comment by capnkirok** [comment]
Yeah, we have saddles designed, I just haven't gotten them in yet. I agree, it's too easy :).

**Comment by capnkirok** [comment]
Meant to close this awhile ago. Saddles are in 1.11 and 1.12 now.
