### ISSUE TITLE
Will bears be added in future updates?

### ISSUE THREAD

**Issue by ChrissPz** [capnkirok/animania#432]
It would look great on Animania mod, grizzly bears, Kodiak Bears, panda bears, etc, variability of bears in their respective biomes.

Obviously those would not be domesticated even though koalas are added.

I mean bears as I wouldn't know if they're out of reach of Animania.

**Comment by Deshiba** [comment]
Ambiance mobs like the polar bear seems reasonable.

**Comment by Narwhal8** [comment]
maybe some kind of plar bear variation

**Comment by capnkirok** [comment]
Guys, I've added this to the suggestions list. Going to close it here so the git only has bugs. Thanks for the suggestions!
