### ISSUE TITLE
suggestion for carts in animaina

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#433]
if possible plz add the ability to use modded storages in the carts plz? something like iron chests mod or quantum storages or black hole storages from industrial forgoing or drawers or storage crates from actually additions if possible pretty plz?

**Comment by capnkirok** [comment]
Thanks for posting. So, to do this, I would have to store the 'blockType' on the Cart entity, as well as all the meta data and contents. It's possible (like Carry On), but not straightforward.

**Comment by CharCharthemonkey** [comment]
all i ask is pretty plz consider? lol since vanilla chests only give max 54 slots lol pretty plz and ty

**Comment by Deshiba** [comment]
For now you could put 1 ender chest and 53 shulker boxes in there and fill the ender chest with 27 shulker boxes aswell. This gives you 80 shulker boxes with 27 inventory slots which gives you 2160 slots to store stuff in.

Seems like plenty of space for any project you would undertake really.

**Comment by CharCharthemonkey** [comment]
well if i knew how to get the shulkers beginning game maybe lol also if the carts werent buggy lol (no offence to animania team) lol

**Comment by capnkirok** [comment]
Ummm..... what bugs @CharCharthemonkey ? It would be nice if you posted those instead of just feature enhancements :)

**Comment by CharCharthemonkey** [comment]
sry @capnkirok will post them tho not 100% sure if they are bugs

**Comment by capnkirok** [comment]
Hey @CharCharthemonkey I talked with @Tschipp about this one, and allowing other chest types would be super difficult and probably buggy, as we'd essentially have to make our own 'portable' versions of these chests just to make them work. So, gonna have to say no to this one (hope you see why). I like @Deshiba 's solution
