### ISSUE TITLE
Chickens disappearing from pen in 1.4.1

### ISSUE THREAD

**Issue by Nerezza** [capnkirok/animania#434]
I updated to the latest Animania this morning before setting up my first ever goat pen and chicken pen. The goats are doing fine, the chickens not so fine.

I brought home with me (via leads) a Wyandotte hen and a Wyandotte rooster. I set up a couple nests, fed them a bit, and got me a couple chicks real quick. Well, I did some things just a chunk over (literally) and came back to find the chicks missing... I made sure there wasn't any way to hop out of the pen (there wasn't), fed them again, then did more things.

I got more chicks, slept for the night, heard the rooster crow in the morning, went to feed them a little more, did some things just in the next chunk, and returned to find my rooster gone without a trace.

I haven't been able to reproduce this reliably, but I've searched around and never run into the missing chickens so I know for a fact that they just flat disappeared from the game. I wish I could give you more to work with, but this is all I've got :/

Edit:

I just loaded the save to find my chicken pen filled with bones and feathers instead of chickens. I had maybe 7 or 8 hens when I'd saved and quit, but now that's all that's left of them.

The goats are still doing fine though. One of them managed to glitch out the fence while the game was still loading, but otherwise I haven't had any issue with my goats.

**Comment by capnkirok** [comment]
Thanks for the report. I have heard of other strange things happening with fences, and I've heard this also affects vanilla animals. I am thinking about a way to prevent 'damage' from glitching into fences.

**Comment by capnkirok** [comment]
May be connected to #409

**Comment by Nerezza** [comment]
The goats don't seem to be having trouble with fences so I'm not sure. It may just be that since the chickens and roosters have such low health, it takes significantly less glitchiness to kill them off.

Anyway a couple extra details I do remember is that when my 7 or 8 hens died on load-in, all their drops were right against the fence line on the inside. It may be that being on the edge of a fence block is dangerous to animals somehow.

**Comment by Nerezza** [comment]
Another little update. One of my goats died when I loaded a game, and once against the animal was right up against a vanilla fence judging by the placement of dropped items.

The problem is DEFINITELY related to animals standing on the same block as fences, since they allow for a little extra 'wiggle room' at their edges, and it seems like the issue might be related to #403 since my fences are doing a poor job of holding the goats in anyway.

**Comment by capnkirok** [comment]
Ok, the fence problem still exists, but animals were legit disappearing due to a bug. A really dumb one. Let's see how this update treats you and keep this open for a bit. I have an idea to make new fences (maybe).

**Comment by Nerezza** [comment]
I'll be unable to test this myself for a week (thanksgiving out of town), but next week when I can I'll keep an eye on my animals while playing.

**Comment by capnkirok** [comment]
Hey @Nerezza I just discovered another source of disappearing animals, which had to do with spawning (strangely). At any rate, this is fixed in the next release (1.4.4)
