### ISSUE TITLE
Animania milk not in the ore dictionary

### ISSUE THREAD

**Issue by Nerezza** [capnkirok/animania#435]
Although the player can craft buckets of Animania milk by itself to produce Minecraft milk buckets, it would be handy if they could be registered into the ore dictionary to save trouble, particularly with using Pam's Harvestcraft alongside it. That is, if there isn't a technical issue preventing this.

The relevant dictionary is: listAllmilk

**Comment by capnkirok** [comment]
There is an issue with this as only milk from Animania cows should be used to make Animania Cheese(s). If I add this to OreDictionary, then it throws off game balance. Thoughts?

**Comment by Nerezza** [comment]
I'm not familiar with the mechanics of the ore dictionary in regards to fluid, so I can't give thoughts on implementation.

As for balance though, I definitely agree that Animania cheese should be produced only from its respective milks. If it's not possible to preserve that when the milks are added to the ore dictionary under listAllmilk, then perhaps an issue should be opened at Forge's github?

**Comment by capnkirok** [comment]
Tested and you are correct. The following have been added to OreDictionary in 1.4.2

`OreDictionary.registerOre("listAllmilk", milkHolstein);
OreDictionary.registerOre("listAllmilk", milkFriesian);
OreDictionary.registerOre("listAllmilk", milkGoat);
OreDictionary.registerOre("listAllmilk", milkSheep);`

**Comment by Tschipp** [comment]
I faintly remember some issue... I'm sure I tried this but I'm not sure what the issue was. Make sure that it actually only registered oredict for milk, not for all buckets.
