### ISSUE TITLE
Troughs don't like being right next to salt licks 1.4.1

### ISSUE THREAD

**Issue by Nerezza** [capnkirok/animania#436]
I put a trough down right next to a salt lick, to where the two blocks were touching, then filled the trough with water. Just under 5 seconds later I crashed to the launcher, here's the report: https://pastebin.com/7biYUdgg

My understanding is that the trough really hates the salt lick and when I made contact between the two the world imploded.

Unrelated: When I milk my goats the bucket will often instantly pour milk out into the world. Since two fluids can't occupy the same space, the rapidly flowing milk instantly destroys the pond in my goat pen which is why I've added a water trough in the first place. Is goat milk supposed to pour out of the bucket into the world like that, or do you think I'm dealing with a mod conflict somewhere?

**Comment by Nerezza** [comment]
I had to delete the salt lick in MCEdit to load the world again, it just crashed on load otherwise.

**Comment by capnkirok** [comment]
Ewww, that's not good.

**Comment by SSyl** [comment]
Same thing happening here. I had to use MCEdit to delete the problem salt lick.

What's odd is that the salt lick was there for a while before it starting producing errors.

**Comment by capnkirok** [comment]
We made an update to the trough recently, might be the source.
