### ISSUE TITLE
carts in animania 1.4.1 

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#437]
### Expected Behavior
work as advertized

### Actual Behavior
glitchy and doesnt work well when pulling via player or horse 

### Steps to Reproduce
craft a cart place a vanilla small chest in it right click/shift right click and it doesnt hook up

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 minecraft 1.4.1 animania and single player

**Comment by CharCharthemonkey** [comment]
oh and links to #433 as well

**Comment by capnkirok** [comment]
- I don't know what 'glitchy' means, or doesn't work well. Does it become disconnected?
- What happens when you click the cart with the chest... what happens... nothing?

**Comment by CharCharthemonkey** [comment]
sry for being vague but right clocking the cart does nothing right clicking with a chest places the chest shift right clicking accesses chest and trying to connect the cart to a player or horse works for maybe 5 blocks b4 it disconnects and the cart will not go up blocks as ud expect with stuff on wheels and even trying to use either a vanilla horse or animania horse to pull the cart still gets disconnected after a few blocks and wont go up blocks either

**Comment by capnkirok** [comment]
Hey thanks for the feedback. This is very helpful.

- Ok, right click is definitely working. Is your hand empty? Are you close enough and on the same level as the cart (not above or below)? _That is the way it currently works (but I could make it easier)_
- Cart will get disconnected if it somehow gets blocked, so if you run into an entity or into a solid block (like a low tree), it can hold and disconnect the cart. _This one I think is the most annoying to players, as you really have to be careful where you are pulling the cart. I could also make this more forgiving._

**Comment by CharCharthemonkey** [comment]
did further testing and found out the cart disconnects when walking by an animal/hostle/passive entity found out the going up and down blocks thing was my derp cause of the disconnect thing

**Comment by capnkirok** [comment]
- I've added a change in the next update that it won't disconnect if it runs into an entity (but will still disconnect if you run into a solid block). I think this is a good change.

**Comment by CharCharthemonkey** [comment]
thank you and imo it shouldnt disconnect when walking near an entity but yea the solid block i could see doing it hehe
