### ISSUE TITLE
[Suggestion]Sheep genders & species 

### ISSUE THREAD

**Issue by TitusArmillius** [capnkirok/animania#44]
I'm sure this is planned; but just to confirm, will you be adding rams, different sheep species, etc?

Also, as a side suggestion, perhaps add goats as well along with the sheep in a future update.

**Comment by capnkirok** [comment]
Yes, both sheep and goats are coming :)

**Comment by MokahTGS** [comment]
The universe requires you to add both Fainting and Pygmy Goats to the game.

**Comment by capnkirok** [comment]
They are on the list already :)

**Comment by OreCruncher** [comment]
OK - can't wait for the Fainting ones.  I have this vision of breeding a herd of 'em and setting off TnT nearby to watch them drop.
