### ISSUE TITLE
All mobs disabled after removing animania mod

### ISSUE THREAD

**Issue by mahilo3550** [capnkirok/animania#441]
### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.3.6.1, SP

Decided to remove the Animania mod from my world and ever since then, no mobs will spawn, all existing mobs disappeared and spawn eggs no longer work. Already typed /gamerule doMobSpawning true.

**Comment by capnkirok** [comment]
Well, existing Animania mobs would of course disappear after you removed the Animania mod. There's no reasons why other mobs or spawn eggs would disappear, the Animania code is completely gone from the game (the way you describe it). Have you tried completely exiting from Minecraft and going back in?

**Comment by CharCharthemonkey** [comment]
actually the animals not spawning is from another mod called extra utilities 2 so just downgrade that to 1.6.5 and it should fix ure issues @mahilo3550

**Comment by capnkirok** [comment]
@mahilo3550 any luck with your world? Going to close this one in the next couple of days.. let me know what you found out.

**Comment by Sandriell** [comment]
@CharCharthemonkey That was fixed in 1.6.7

**Comment by capnkirok** [comment]
Ok closing this one. Let me know if you figured it out.
