### ISSUE TITLE
Rabbit

### ISSUE THREAD

**Issue by Gerbil12** [capnkirok/animania#447]
Hi, I can ask if it can be made for a rabbit burrow in which rabbits can hide from the crowd. And I also noticed that the rabbits panic near the zombies and other monsters.

**Comment by Krhymez** [comment]
Do you have any other mods enabled?

I noticed some weird AI when using "Better with mods" but i disabled the "Hunting module". May have been my imagination.. but it seemed the animals were very skidish when that was enabled.

**Comment by capnkirok** [comment]
@Gerbil12 you are right, they are set to panic around Mobs and Wolves (like Rabbits would, of course, they are quite skittish creatures). I like the idea of a burrow... but putting this under suggestions.

**Comment by capnkirok** [comment]
Hey, I've add this to our to do list. In an effort to clean up this git, however, I'm going to remove it from git for now, so git only shows bugs. Thanks for the suggestion!
