### ISSUE TITLE
Feature request- Meat drop amount config

### ISSUE THREAD

**Issue by Krhymez** [capnkirok/animania#448]
Currently in the pack i am making i have the timers all set to 4x default, due to the fact that my days are 4x as long.

I may be overlooking it, but it would be cool if there was a multiplier to change the amount of meat dropped from an animal.  Making the animals drop more meat because of the longer growth and birthing times.

In turn this could make players need smaller farms.  if they can get more meat from fewer animals.

**Comment by Narwhal8** [comment]
I also think this whould be useful. Im making a "Modpack"(Something for me just to play around on) and i have breeding disabled so having the animals you find be worth more whould be nice.

**Comment by capnkirok** [comment]
Yeah, I agree. I also need to add support for the 'second' drops...e.g., Wool, Feathers..

**Comment by Krhymez** [comment]
Also the ability to change meat food values. It is odd that "Prime beef" is higher then meals on my pack.

**Comment by capnkirok** [comment]
Alright, secondary drops are going into the next update.

**Comment by capnkirok** [comment]
And @Krhymez the feature to change the food values is already in the config. You can override any of the values... format is something like 
`animania:angus_steak(3,15)`
