### ISSUE TITLE
[Feature Request] Support for Metamorph mod

### ISSUE THREAD

**Issue by NovaViper** [capnkirok/animania#449]
I wish there was automatic support for the [Metamorph mod](https://minecraft.curseforge.com/projects/metamorph), which lets you turn into mobs. I already added in (manually) support for the chickens and pigs, but it's really hard for the Hedgehogs, Ferrets, and frogs since each has different movement speeds and the frogs have different abilities.

Here's are the ones I already added: https://hastebin.com/bumubepiye.scala

**Comment by CharCharthemonkey** [comment]
umm there should be support from animania to metamorph since it should count the animals as vanilla for morphs from wat ive seen

**Comment by NovaViper** [comment]
Strangely there isn't. I also still see the vanilla mobs in the menu despite they replace the vanilla mobs. The abilities nor health are added (like the animania pigs have different levels of health and the animania chickens can glide)

**Comment by CharCharthemonkey** [comment]
weird then hopefully they add it

**Comment by capnkirok** [comment]
Hey @NovaViper -

Between multiple mods and a FT job, I don't have to write JSON for metamorph :) But you are off to a good start. I'm going to tweet this one out to see if there's anyone who can help.

Instructions are here for people who want to help:
https://github.com/mchorse/metamorph/wiki/Configuring-Morphs

**Comment by aionys** [comment]
Give me a list of each animal with it's health and speed, and I can get a full file going pretty quickly.

As it is, the only way I'm aware of to get the health and speed even remotely easily is from the NBT tags. Metamorph does let you see the NBT tag for an entity, but only one at a time, making the process very arduous.

If anyone knows of a way to export the NBT tags of all registered entities en masse, it would be hugely easy from that point. Unfortunately none of my Googling has borne fruit.

**Comment by aionys** [comment]
The good news is, only the animals that have abilities need to be put into the morphs.json file. The mod actually handles getting the regular values perfectly fine, such as health and speed.

The bad news is, it doesn't have a clue about which animals have special abilities like flying, climbing, etc.

@capnkirok Would you agree with the following?

Abilities:
> climb – allows players to climb like a spider. This ability also prevents fall damage.

ferrets

> fly – allows players to fly in survival.

peafowl

> glide – makes players fly slowly toward the ground. Also prevents fall damage while gliding. If you sneak, you'll fall as usual.

chickens, peafowl

> jumping – makes player hopping.

rabbit, chinchilla, frog, dart frog, toad

> prevent_fall – prevents fall damage.

chicken, peafowl, rabbitt, chinchilla, frog, dart frog, toad

> swim – makes player very mobile in the water. Also inflicts damage on player when he's on air.

frog, dart frog, toad

Actions:
> jump – jumps 3 blocks high in the air.

chinchilla, rabbit, frog, dart frog, toad

Attacks:
> poison – applies poison potion effect on the attacked target.

dart frog

**Comment by aionys** [comment]
Here's the morphs.json I made:

https://pastebin.com/QdapQW6d

**Comment by NovaViper** [comment]
That's a good set of abilities for the animals :D

**Comment by capnkirok** [comment]
@aionys this is great, thanks for putting your thoughts together and for the JSON :+1:

**Comment by capnkirok** [comment]
I talked with MCHorsey (creator of Metamorph mod). Right now there are no plans to automate community created configs, so just going to add this as a separate download on the Forums. Thanks again!

**Comment by aionys** [comment]
No worries. I'll update to have swim for the amphibians if he ever fixes that. I put in an issue on the github for it. Maybe gets some +'s over there?

https://github.com/mchorse/metamorph/issues/89

**Comment by aionys** [comment]
Also, interesting side note: morphing into the dart frog inflicts you with poison. That's not fun. :)

**Comment by capnkirok** [comment]
@aionys yes, interesting. Well, the way the dart frog works... if a player comes in contact with it, the player is poisoned. I'm guessing the way metamorph works... it's using the morph like a skin. I could disable this if Metamorph is installed or something... not sure how else to know if you've morphed into a Dart Frog.

**Comment by Deshiba** [comment]
@capnkirok The cave spiders apply poison when they attack someone. Is it possible to apply the same thing to the Dart Frog but have their attack do 0 damage?

**Comment by aionys** [comment]
Check the UUID of the entity, if it matches the UUID of the player, disable the poison?

**Comment by capnkirok** [comment]
@aionys might work, can try. @Deshiba frogs don't attack, they are just poisonous if you touch them (just like IRL).

**Comment by aionys** [comment]
Cool beans. Let me know when it's up and I'll test it.

**Comment by mchorse** [comment]
> MCHorsey

It's McHorse (why does everyone mess up spelling my name? 😂). 

> The cave spiders apply poison when they attack someone. Is it possible to apply the same thing to the Dart Frog but have their attack do 0 damage?

There is `"attack": ""` property which allows to assign one attack ability (basically applies on some entity which player has attacked). There is no much actions at the moment, although, you might use `"poison"` attack ability. 🤔

**Comment by capnkirok** [comment]
Fixed!
@mchorse apologies to you and the entire horse family

**Comment by aionys** [comment]
McHorse just released an update to MetaMorph that makes it so the swim ability doesn't cause damage anymore, now, instead, water breathing causes suffocation when in air, which makes it so the little froggies can finally frolic in the water like they should.

And so, as promised, the updated morphs.json:
https://pastebin.com/4u7GSr2C

**Comment by capnkirok** [comment]
Woo-hoo :)

**Comment by mchorse** [comment]
Ah, crap, completely forgot about this issue 🙁 

I should've implemented/added Animania's JSON to the code base... I guess in the next update. I'll write it down in my ToDo list.

**Comment by mchorse** [comment]
@capnkirok how about this feature: you put the Metamorph configuration `morphs.json` into mod's `src/main/resources/assets/animania/` repository, and upon (re)loading of configuration, I'll read it from the resource pack system.
