### ISSUE TITLE
Birth spawn position

### ISSUE THREAD

**Issue by Thyriel** [capnkirok/animania#45]
Can it be that the block a new animal is spawned (due to birth) is not the same block then the mother is at ? I have noticed that it happens sometimes that new childs are running around outside the fenced area

**Comment by capnkirok** [comment]
I saw this comment from someone else. Well, I had the calves/piglets spawning at x +.5, y + .2, z + .5 relative to their mothers. I've changed it to the exact same perceived location. I'll so some testing and see if this fixes it.

**Comment by capnkirok** [comment]
Yes, this seems to have fixed it. Will roll out this week on 1.0.2

**Comment by Thyriel** [comment]
Still doesn't seem to work. Installed 1.0.2, deleted config file, killed all animals and respawned them. The next morning the animals where still mixed despite a 2 block high fence seperates them: http://imgur.com/a/WrxNa

**Comment by capnkirok** [comment]
Ooh I bet this is because of the other nearby male... not the spawn.

**Comment by capnkirok** [comment]
It may be that your mates are from different breeds, but they are still close enough in your pens that continued breeding is working. This is my suspicion.

I've shortened the required distance, but you might want to try separating the cows pens > 10 blocks and see if birthing still happens (after installing 1.0.3).

**Comment by capnkirok** [comment]
Let me know how this one looks in 1.0.3+

**Comment by Thyriel** [comment]
I fear that will take a while as my servers currently running a 1.7 modpack ;)

**Comment by capnkirok** [comment]
:)
