### ISSUE TITLE
[1.12.2] Blue/Black screen when looking at any Animia animal with a lead on it in Survival Mode

### ISSUE THREAD

**Issue by NovaViper** [capnkirok/animania#451]
### Expected Behavior
No blue/black screen, just normal view of the animal

### Actual Behavior
Whenever when I'm in survival and staring at an Animania animal with lead, the game display suddenly disappears, showing only the sky color.

### Steps to Reproduce
- Get an Animania Animal
- Put a lead on the animal
- Get into survival mode
- Look at the animal

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, Single Player

### Screenshots encouraged
In Creative Mode: 
![creative](https://user-images.githubusercontent.com/7191115/33104989-a98b8ac4-cef0-11e7-8573-db25d5198cef.png)

In Survival Mode: 
![survival](https://user-images.githubusercontent.com/7191115/33104975-9a2e7cda-cef0-11e7-8fb2-f2008da6f702.png)

**Comment by capnkirok** [comment]
That is very strange. I am not seeing this in my environment. Does it only happen with Animania animals?

**Comment by NovaViper** [comment]
Strangely.. it does occur with vanilla mobs aswell

**Comment by NovaViper** [comment]
Ah HA! I have discovered the source! Appearently, this mod wasn't the issue at all; it was the shaders (Sildur's Enhanced Default [redone] v1.0.1)

**Comment by NovaViper** [comment]
Ooooh, even more a curious issue. There _is_ a mod that is causing this issue with the Shaders. The mod, RPGHud has a certain setting (Entity Inspect) where I can see the entity's status and such like OneProbe and WAILA. Turning off this setting solves the issue

**Comment by capnkirok** [comment]
Thanks for the follow-up and info @NovaViper
