### ISSUE TITLE
1.12.1 knife only working once

### ISSUE THREAD

**Issue by Narwhal8** [capnkirok/animania#452]
### Expected Behavior

For the knife to work until running out of durability and when combining knives to turn 2 into 1

### Actual Behavior

The knife not working after losing 1 durability and the knives duping when trying to combine knives by taking neither of the knives

### Steps to Reproduce

Get a prime porkchop(how i found it) and craft with the same kinfe more then 1 time

### Version of Minecraft, version of Animania, Single Player or Server

1.12.1, Version of animania 1.4.2 1.4.1 just tested with only 1 knife use and 1.3.6 is tested to have both issues

**Comment by Narwhal8** [comment]
Correction. I am on 1.12.2 and Versions 1.4.1 and 1.3.2 Are having this issue

**Comment by capnkirok** [comment]
It's a problem with Forge. Lex says it should be fixed in the latest version... what version are you on?

**Comment by Narwhal8** [comment]
That fixed it. Thank you
