### ISSUE TITLE
Could you provide iChun with yout NBT tags for his mod Morph

### ISSUE THREAD

**Issue by Preminenc3** [capnkirok/animania#453]
[Link to Post](https://github.com/iChun/Morph/issues/893#issuecomment-346492470)

**Comment by capnkirok** [comment]
Yes, will do. Just chatted with him.

**Comment by Preminenc3** [comment]
Thank you so much

**Comment by capnkirok** [comment]
@Preminenc3 I just tested the latest version of Morph to look for gaps but all the animals seemed to work (except for 'babies'). Have you tried it (1.12.2)?

**Comment by capnkirok** [comment]
Ahhh.... ichun showed me. Ok, I need to remove a few tags for him. Still working on it.

**Comment by capnkirok** [comment]
Ok these are in and working. Will be in the next release of Animania.
