### ISSUE TITLE
cows not being milkable when they spawn into the world

### ISSUE THREAD

**Issue by Narwhal8** [capnkirok/animania#455]
### Expected Behavior

Cows being milkable when they spawn into the world in the wild
### Actual Behavior

cows not being milkable when the world loads
### Steps to Reproduce

Use hunger overhaul (Latest version) To change delay in milking and try to milk a wild cow
### Version of Minecraft, version of Animania, Single Player or Server

1.4.2 animania. Forge 2552 1.12.2 minecraft

**Comment by Tschipp** [comment]
Cows need to give birth before they can be milked. Can you try that?

**Comment by Narwhal8** [comment]
can i disable that? i have a modpack that disables breeding to prevent farming

**Comment by capnkirok** [comment]
I'll have to add a config, it's the simplest way.

**Comment by Narwhal8** [comment]
That whould be helpful. Thanks!

**Comment by capnkirok** [comment]
Ok, this is added in 1.5
