### ISSUE TITLE
convert animania meat to vanilla meat recipes not working.

### ISSUE THREAD

**Issue by ArMoReDfUrY** [capnkirok/animania#456]
### Expected Behavior

        # Enable recipes to exchange special meats for vanilla
        B:enableVanillaMeatRecipes=true

### Actual Behavior

no vanilla meat recipes are shown in jei and don't seem to be craftable 

### Steps to Reproduce

**1**-enable recipes in config, launch game, kill 30-40 pigs(no vanilla meats dropped? overview suggests they should be?)
**2**-try to find recipe by using JEI "u" keybind on raw_prime_pork to see item use (no vanilla meat crafts visible)
**3**-use JEI "R" keybind on vanilla meats to find recipes to craft vanilla meats (no recipes availible)  
repeated steps using each "raw" meat and also bacon,steaks... 

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft - 1.12.2 
Forge -1.12.2-14.23.0.2552 
Animania - 1.12.2 - 1.4.2

### Screenshots encouraged
none sorry, shouldn't need them though.

Thanks for the awesome mod, looking forward to the next release.

**Comment by Narwhal8** [comment]
have you tried just crafting?

**Comment by ArMoReDfUrY** [comment]
sorry. forgot to add that.
yes i have tried just crafting and there is no output.
just about to bump to the current forge build 2554, i will test all the vanilla conversions again and post my results.
need a few hours to finish the RL stuff then i can test.

**Comment by capnkirok** [comment]
I think I'll make these work this way by default.

**Comment by capnkirok** [comment]
Ok, this will just be default going forward, no need to enable in the config.
