### ISSUE TITLE
[1.12.2] When the Carving Knife looses durability, I can no longer craft bacon or anything

### ISSUE THREAD

**Issue by NovaViper** [capnkirok/animania#457]
### Expected Behavior
Still be able to use the carving knife to cut cheeses and meats

### Actual Behavior
Once the knife is used once, I can no longer craft bacon or anything else that can be modified by the knife

### Steps to Reproduce

1. Get a new knife
2. Use it once on any Animania item (such as Prime Pork)
3. Use the same knife on any Animania item

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.4.2 ,Single Player

### Screenshots encouraged
![2017-11-24_09 40 06](https://user-images.githubusercontent.com/7191115/33216922-81cf4a2c-d0fb-11e7-9ade-292f27102b4f.png)

**Comment by capnkirok** [comment]
You are using a bugged version of Forge, should be fixed in the latest version.

**Comment by capnkirok** [comment]
Meaning you should download the latest version of Forge :)

**Comment by NovaViper** [comment]
Thanks! I was using 14.23.0.2550, updating to 14.23.0.2552 fixed the bug
