### ISSUE TITLE
[SUGGESTION] Mundane livestock should not spawn in mushroom islands

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#458]
Instead, why not rework mooshrooms to fit the animania cattle in a future update?

Maybe more fungi-variants for various other livestock as well...

**Comment by capnkirok** [comment]
Hey @Sunconure11 !

Yeah, this has been suggested. #288

**Comment by capnkirok** [comment]
Just checked, I only have the Angus cow spawning there currently. What animals did you see there?

**Comment by Sunconure11** [comment]
Yeah, I saw Angus there at the moment.

**Comment by capnkirok** [comment]
Ok, I've removed Angus from spawning in Mushroom. Not sure why I put them there in the first place.

**Comment by Sunconure11** [comment]
Hmm... I'm trying to come up with ideas for other mushroom-based livestock, but I can't think of much.

Mooshroom Variants:

Portabella
Fly Agaric

Mushroom Goat (I'm sure there's a better name you could come up with this):

Morel
Lion's Mane

Maitake (Sheep's Head Mushroom, in this case, a sheep found there):

Maitake
Puffball

Hen of the Woods (Chicken):

Fried Chicken Mushroom
Chicken of the Woods

Toadstool (Frog):

Toadstool

Turkey Tail (Peacock):

Turkey Tail

**Comment by capnkirok** [comment]
@Sunconure11  ha ha ha ha I love it :)
