### ISSUE TITLE
Throwing seeds breaking other mods

### ISSUE THREAD

**Issue by Thyriel** [capnkirok/animania#46]
Could you change it so that seeds on the ground are generated in a different way then just throwing seeds ?
E.g. shift+rightclick or so

Seems your current way of handling them is breaking other mods that require seeds to be thrown like Botania

**Comment by capnkirok** [comment]
Yeah, I am not digging the current way of throwing so much either. I'm not sure how do this without making a new seed item, but will look into it.

**Comment by Thyriel** [comment]
How about just adding a simple recipe for chickenfood that is then thrown on the ground ? E.g. Seed+Seed = Chickenfood

**Comment by capnkirok** [comment]
Yes, this is exactly what we'll do.

**Comment by Thyriel** [comment]
Didn't made it into 1.0.2 ? :(

**Comment by capnkirok** [comment]
Almost. I pulled it out at the last minute as the event solution caused issues on left click, which I need more time to solve. Next update, for sure.

**Comment by Tschipp** [comment]
I'm guessing by event solution you refer to what I proposed for the seeds? What excactly isn't working?

**Comment by capnkirok** [comment]
So, right click works great. The block is placed, and it avoids farmland. Perfect.

Left click is weird. In Creative, it breaks the block under it then places the block over the hole it created. It also acts similarly in Survival with one click destroy blocks. I just need to find a way to disable left click working, and then it will go in. If you have any ideas, feel free to share.

**Comment by Tschipp** [comment]
Don't listen to the entire PlayerInteractEvent. Only listen to PlayerInteractEvent.RightClickBlock. That subevent only fires when a block is right clicked.

**Comment by capnkirok** [comment]
Cheers!

**Comment by capnkirok** [comment]
Didn't use your code, have something a bit different already working, borrowed the fakeplayer check and the swingArm... :) will go in this weekend.

**Comment by Tschipp** [comment]
I think you could also leave out the FakePlayer check, if you want machines like the Autonomous Activator to be able to place the seeds.
