### ISSUE TITLE
cheese put down and crash

### ISSUE THREAD

**Issue by hiritsuki** [capnkirok/animania#460]
### Expected Behavior
crash

### Actual Behavior
put down anywhere cheese and get crash

### Steps to Reproduce
that's all

### Version of Minecraft, version of Animania, Single Player or Server
animania-1.12.2-1.4.2.jar

**Comment by capnkirok** [comment]
Sorry, there's no issue with Cheese in 1.12.2, 1.4.2. Probably a conflict with another mod.

You'll need to link your crash report (cut/paste into pastebin.com)?

[![Screenshot from Gyazo](https://gyazo.com/4cb7fc7d8d46e3788fdf5bf8809b758d/raw)](https://gyazo.com/4cb7fc7d8d46e3788fdf5bf8809b758d)

**Comment by hiritsuki** [comment]
https://pastebin.com/Tkafqrew

sorry it's here

**Comment by capnkirok** [comment]
![image](https://user-images.githubusercontent.com/9628379/33242912-3032a276-d2dc-11e7-809f-8fd878bf41a2.png)

You should contact the HWYLA author, TehNut, github here: https://github.com/TehNut/HWYLA/issues

**Comment by capnkirok** [comment]
I tagged TehNut. We go back like two weeks now.

**Comment by hiritsuki** [comment]
thank you
I don't know why the crash problem happen, just know the cheese put and crash.

**Comment by TehNut** [comment]
@hiritsuki Could you run `/dumphandlers` in-game? It'll print a file to your instance directory.

**Comment by capnkirok** [comment]
This will be fixed in the next release. Was a problem on the animania side after all. Thanks @TehNut

**Comment by TehNut** [comment]
![](http://img1.ak.crunchyroll.com/i/spire4/1a775e970748bf5bc26698d5397b43fb1454381846_large.png)
