### ISSUE TITLE
Duplicating eggs with the mod Carry On

### ISSUE THREAD

**Issue by Ubermensch1999** [capnkirok/animania#461]
When you pick up an eggs nest with an egg in it while holding an incomplete stack of eggs, you gain an egg to that incomplete stack... without using the egg from the nest, after putting the nest back down you can start to repeat the process and split the egg stacks to virtually get infinite eggs.... if you wanted

**Comment by capnkirok** [comment]
Oh, that's not good. I assume this is on 1.12? @Tschipp wanna take a peek?

**Comment by Tschipp** [comment]
Assume this is 1.10, as I rewrote nests for 1.11 and 1.12 and CarryOn supports the new ItemStackHandlers

**Comment by capnkirok** [comment]
Dang. Ok, will add it to the list. @Ubermensch1999 this is an Animania issue.

**Comment by Ubermensch1999** [comment]
sorry for the late reply, but this is happening on 1.12.2, with the latest version of animania and forge, aswell as carryon and craftstudio

**Comment by Narwhal8** [comment]
Im not part of the staff but forge 2491 is buggy with animania. Update to forge 2552 for compatibility

**Comment by capnkirok** [comment]
Ok, this is fixed in the next release.

**Comment by Tschipp** [comment]
oopsie, yeah there should probably a check for shift clicking in processinteract
