### ISSUE TITLE
posting this for a friend

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#463]
### Expected Behavior
to work as normal

### Actual Behavior
doesnt work exactly

### Steps to Reproduce
using carry on and animania not exactly a bug report but seem using the animania cart with carry on conflicts cause of carry on using shift right click to pick up stuff and having to use shift right click to place entites and chests in the cart causes conflicts

### Version of Minecraft, version of Animania, Single Player or Server
unknown as its a friend having the issue named @darkphan

**Comment by Tschipp** [comment]
We will add the carts to the blacklist in the next CarryOn release. For now you can just add it yourself.

**Comment by capnkirok** [comment]
I love my shift-right-clicks. What can I say.

**Comment by Narwhal8** [comment]
Make sure your on forge 2552

**Comment by capnkirok** [comment]
I"m closing this as it's listed on Carry On side.
