### ISSUE TITLE
BlockHamsterWheel

### ISSUE THREAD

**Issue by georgio3333** [capnkirok/animania#465]
### Expected Behavior
i don't know

### Actual Behavior
https://pastebin.com/zAPp13bN

### Steps to Reproduce
when i right clic on hamster wheel

### Version of Minecraft, version of Animania, Single Player or Server
minecraft : 1.10.2
LWJGL : 2.9.1
Forge : 12.18.3.2511
Animania  :  1.4.2

### Screenshots encouraged
http://hpics.li/7984175

**Comment by capnkirok** [comment]
Yeah, looks like it's crashing if you haven't put a hamster in yet, and then right click. It should do nothing.

So, the way it's supposed to work... put a tamed Hamster on your shoulder, then right-click on the wheel. The Hamster will run in the wheel and generate energy.

**Comment by capnkirok** [comment]
Ok, this is fixed in the next release. To avoid this, don't right click on the hamster wheel unless you've got a well fed / tamed hamster nearby.
