### ISSUE TITLE
Water Buckets not filling up Trout or Cheese Mold? 1.12.2

### ISSUE THREAD

**Issue by Wolvesrfun** [capnkirok/animania#468]
(Sorry if this has already been posted!)
### Expected Behavior
Trouts and Cheese Molds should fill up with water when right-clicked with a bucket of water.

### Actual Behavior
Water is placed on the block above Trout/Cheese Mold. Doesn't fill up.

### Steps to Reproduce

1. Obtain Bucket of Water

2. Obtain Trout and/or Cheese Mold

3. Attempt to fill block with water by right-clicking with bucket

4. Fail miserably

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.4.2, Single Player

### Screenshots encouraged
BETTER THAN SCREENSHOT! I made a video.

https://youtu.be/mReykF1NBYo

**Comment by capnkirok** [comment]
Uhh.... I just tested.
[![Screenshot from Gyazo](https://gyazo.com/125f75c5e100f986f5a3a590ba4f7175/raw)](https://gyazo.com/125f75c5e100f986f5a3a590ba4f7175)


What's weird to me is that you seem to be holding the normal vanilla water bucket, but we have enabled the Forge Filled bucket (see mine). So, there must be a conflict. Are there any mods in your environment that modify buckets?

**Comment by Wolvesrfun** [comment]
I just have these mods (besides Animania/CraftStudio API):

LabyMod
Just Enough Items
Packing Tape
Xray
Chisels and Bits
Bibliocraft

Pretty sure none of these modify buckets, but I guess I could be wrong?

**Comment by capnkirok** [comment]
Just as a test.. try it without Chisels and Bits and also Bibliocraft... let me know if you get the same result... thanks for the help :)

**Comment by Wolvesrfun** [comment]
I tested in a different world. It's still not working for me, even without Bibliocraft and C&B.

**Comment by capnkirok** [comment]
Ok, two more things to try, if you are up for it.

- Try it with only Animania and CraftStudio.
- Let me know what version of Forge you are using

Thanks!

**Comment by Wolvesrfun** [comment]
I think the problem might stem from LabyMod, since all the other mods seem to allow the bucket to work. Weird, but since I don't know code, I can't say anything.

My forge version is: 1.12.2-14.23.1.2555

**Comment by capnkirok** [comment]
Yeah, that version is fine. Is there a way to contact the author of LabyMod? There's nothing special about the item itself... I think it's a conflict between LabyMod and Forge actually.

**Comment by capnkirok** [comment]
Ok, I just posted to their support on twitter... who knows what we'll find out...https://twitter.com/Purplicious_Cow/status/937799451560890369

**Comment by Wolvesrfun** [comment]
Yeah, I don't really know how to contact the author, but I'm glad they have a twitter. If it's a problem with forge, maybe my forge version is wrong?

**Comment by capnkirok** [comment]
I haven't heard back from LabyMod people either. I can't do anything about this one unfortunately. Maybe you can try on the support forums? This one is out of my hands.. :(
