### ISSUE TITLE
[1.10.2] Animania-1.4.2 -- Chickens lay Loony Tunes-proportion amount of eggs.

### ISSUE THREAD

**Issue by Ayasu** [capnkirok/animania#469]
### Expected Behavior
Chicken laying 1-3 eggs and there be a wait time, I guess?

### Actual Behavior
Tested with 2 different breeds of chicken, each chicken laid nearly 200 eggs in one go. 

Breeds tested -- Rhode Island Red, Leghorn

### Steps to Reproduce
Chicken + nest = every eggs ever

### Version of Minecraft, version of Animania, Single Player or Server
Multiplayer, all other information in subject

**Comment by capnkirok** [comment]
Ha ha Loony Tunes :)

Yeah, I saw this when I was testing, and it's already fixed in 1.4.3. Thanks for the note.
