### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by Eniam** [capnkirok/animania#47]
Similar to #41 (I don't post many glitches, so apologies if it's exactly the same but seemed different to me)
My crash log http://pastebin.com/TF0j3803

Like #41 it's the Yorkshire pig causing it, but specifically seems to be searching for a mud block.
It doesn't crash for me, but when my wife logs on (of whom is on a mainland with many animals) we both crash.

**Comment by capnkirok** [comment]
Yes, this will be fixed in 1.0.2... it's essentially the same error. Thanks for the report!

**Comment by Eniam** [comment]
Apologies, I wasn't sure. Thanks for the quick reply! ^_^

**Comment by capnkirok** [comment]
No need for an apology, I would have forgotten to check the AI script without your help! Thanks!

**Comment by capnkirok** [comment]
Closed in 1.0.2
