### ISSUE TITLE
Crash when placing seeds on snow

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#470]
### Expected Behavior

Seeds should replace snow

### Actual Behavior

https://pastebin.com/40RLZmqe

### Steps to Reproduce

1. Place seeds on snow for a bit
2. ???
3. https://pastebin.com/40RLZmqe

### Version of Minecraft, version of Animania, Single Player or Server

Forge 2559 for 1.12.2, minecraft 1.12.2, animania 1.4.2, server but the log blames the client

**Comment by capnkirok** [comment]
Oooh, that's a WAILA (HWYLA) crash. Doesn't like something about the blockstate. I just added compatibility for this in 1.12, so why it hasn't shown before.

**Comment by capnkirok** [comment]
Ok, this is fixed in next release. Was able to repro finally and found a fix. Has to do with somehow seeds failing to replace the snow (like an incomplete block placement), and then WAILA being caught with bad data. I've added error trapping so it won't crash if it happens again.
