### ISSUE TITLE
Animals Forever Terrified

### ISSUE THREAD

**Issue by Patchlamb** [capnkirok/animania#471]
### Expected Behavior

Animals get over their fear like normal minecraft mobs after being hit or seeing others animals be hit

### Actual Behavior

Animals remain forever scared after being hit or hitting an animal close to them. They run everywhere wildly. Sometimes roping them with a lead then taking the lead calms them down- it did for my goats and sheep but not for my cows.

### Steps to Reproduce

Hit an animal.

### Version of Minecraft, version of Animania, Single Player or Server

1.12.2, 1.12.2, single player. 

### Screenshots encouraged

You know what it looks like when an animal is scared so I don't think a screenshot is needed tbh

**Comment by capnkirok** [comment]
Hey @Patchlamb I am not experiencing this issue. The are frightened for a long time (like 2 minutes I believe?), but it will go away eventually (just like real animals). You can also leave the area and come back (or logout/login) and they will calm down.

**Comment by capnkirok** [comment]
Verified, this is working as intended. I felt that the vanilla implementation of animal fear was unrealistic, which is why they stay frightened for longer. However, as mentioned, it will wear off eventually.
