### ISSUE TITLE
[1.12.2] Missing ore dict names

### ISSUE THREAD

**Issue by JonasCiss** [capnkirok/animania#473]
It is unpossible to use the diffrent wool version of Animania for recipes that uses the ore dict "wool".
That could be changed.

**Comment by Deshiba** [comment]
This was an old issue supposedly fixed in 1.3.4 #353
There was one mention of stuff not working in 1.3.5 #388 but that was possibly an issue on the side of another mod.

Can you post the version of Animania, Craftstudio and forge you are using?

**Comment by Deshiba** [comment]
Also, the name was changed from "wool" to "blockWool" in order to match the oreDict [naming conventions](https://mcforge.readthedocs.io/en/latest/utilities/oredictionary/#oredictionary-name-convention)

**Comment by JonasCiss** [comment]
animania-1.12.2-1.4.2
CraftStudio-1.0.0.93-mc1.12-alpha
1.12.2 - 14.23.1.2562

**Comment by capnkirok** [comment]
Hey @JonasCiss what recipes use "wool" as the oreDict name? Mods should be using "blockWool". Possible to reach out to those authors?

**Comment by JonasCiss** [comment]
I will try.

**Comment by capnkirok** [comment]
Closing this one. Other mods should follow the OreDict naming conventions.
