### ISSUE TITLE
Support for Chickens Mod

### ISSUE THREAD

**Issue by Preminenc3** [capnkirok/animania#476]
I was wondering if you would make support for Chickens, More Chickens, and Roost mods.

**Comment by Deshiba** [comment]
Uhm, you posted an issue on this before. You might want to defer to the answer given in #454 if your question is still as below.
> If possible could you change their models so they match the Animania mods models and have them use Animania nests? 

Otherwise please rephrase your query or suggest another way to possibly add support.

**Comment by capnkirok** [comment]
@Preminenc3 going to close this one in a couple of days unless I hear back. I can't make another mod use our models. We have already made animania chickens extend vanilla, so these mods should be able to use Animania chickens. Not sure what else we can do from our side....
