### ISSUE TITLE
(Suggestion)two little suggestions

### ISSUE THREAD

**Issue by touhouzun** [capnkirok/animania#477]
Maybe these two are both impossible_(:з)∠)_
1.Make making salt&cheese in 1.10 the same as in 1.11/1.12
It's not a must-be-done,but pouring waterbucket into vanilla crafting table to make salt seems unscientific.Same as cheese.
2.Compress curseforge wiki and cut&paste into github.
The curseforge page is a bit too long_(:з)∠)_

**Comment by capnkirok** [comment]
Well, part 1, this is actually the way cheese is made. I mean I left out the curds and the rennet etc., but essentially the same. As for salt... yeah, this one's a bit of a stretch, but not in a rush to change it (yet).

Part 2, definitely agree. We have a new wiki that needs content added.

**Comment by capnkirok** [comment]
I'm going to close this though as the second is a suggestion and it is being worked on. Technically for the Salt Lick, we could make another mold... or just call the Cheese Mold a 'Mold'.

**Comment by touhouzun** [comment]
Emmmm...I mean:Cheese should be made in molds(milk in molds,not milk in craftingtable);Salt should be made by evaporating/heating water(water in molds,not water in craftingtable).
It's ok not to update cheese&salt making in 1.10 the same as in 1.11/1.12
For salt,have you ever heard of tofucraft and saltymod?Salt-making is not your duty,I just mean their salt-making methods are better.
Please remain this issue closed,thanks a lot.
