### ISSUE TITLE
Goat belly texture

### ISSUE THREAD

**Issue by BlueWither** [capnkirok/animania#478]
### Actual Behavior
The texture of the goat's belly is reversed.
### Version of Minecraft, version of Animania, Single Player or Server
Minecraft1.12.2
Animania1.4.3
Single Player
### Screenshots encouraged
![Goat1](https://i.imgur.com/yiZsg1r.png)
![Goat2](https://i.imgur.com/WFoKOVY.png)

**Comment by capnkirok** [comment]
Thanks. Probably means all of the goats are wrong.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#133
