### ISSUE TITLE
Carving knife is disposable

### ISSUE THREAD

**Issue by shursik** [capnkirok/animania#479]

**Comment by capnkirok** [comment]
Not sure what you mean.... it can't be repaired?

**Comment by shursik** [comment]
It can't be used anymore if it had damage.

**Comment by shursik** [comment]
It work only for one piece and only if it new. After one use it had damage and don't work anymore.

**Comment by capnkirok** [comment]
You need to update to the latest version of Forge. There is a bug in the version you are using with recipes involving "wildcards" like the Carving Knife.

1.12.2 - 14.23.1.2555
