### ISSUE TITLE
Animals don't render from spawn egg.

### ISSUE THREAD

**Issue by theDaleighChronicle** [capnkirok/animania#48]
I'm not sure if there is a conflict with other mods I have, but this is the only animal-related mod I'm using in my personal modpack. Though I hear the animal sounds, I don't see the animals, even when I spawn them from eggs. They are all invisible. Help?

**Comment by capnkirok** [comment]
Very strange. Can you link me to your modpack?

**Comment by theDaleighChronicle** [comment]
Sorry, just need to update now. I took a closer look at the configs and adjusted them a bit. I've got it working now. Thanks!
