### ISSUE TITLE
Horses don't move

### ISSUE THREAD

**Issue by NeonWolfie** [capnkirok/animania#480]
Okay, so whenever I spawn a horse or it generates it moves about 3 blocks and then just stands still.I don't think their frozen because they can still turn and their eyes blink, but the don't move forward or backwards or sideways.

Is there a setting I need to change or am I doing something wrong, because all the other animals move it's only the horses that do this.It's on version 1.4.2 and 1.4.3 and it's Minecraft version 1.11.2

**Comment by capnkirok** [comment]
Weird. Well, they move for me. Have you tried holding wheat in your hand to see if they come to you? Because they do for me.

Also, they do not 'wander' if they are attached to a Cart or Wagon...

**Comment by NeonWolfie** [comment]
@capnkirok They're not attached to carts, but I'll try holding wheat.

**Comment by touhouzun** [comment]
@NeonWolfie Hmmmm....does it seems that:male draft horses can jump but cannot move,female draft horses can move but cannot jump?If you're referring these problems,I suggest to disable animania's draft horses and use vanilla's instead.

**Comment by NeonWolfie** [comment]
@touhouzun Neither of them move, but the male horses sometimes jump when I move up blocks, but sometimes they get stuck until I press the jump key.

**Comment by capnkirok** [comment]
Hey guys. There's nothing wrong with the Animania horses. Both males and females jump and move fine. Have you fed and watered them? They don't ride well unless they are well fed.

[![Example of Horse Riding in 1.11](https://gyazo.com/29129707be1f3c5c918fc88237ce033d/raw)](https://gyazo.com/29129707be1f3c5c918fc88237ce033d)

**Comment by capnkirok** [comment]
Hey guys. I'm closing this one in a few days, as I'm not able to replicate. Both Male and Females Horses move correctly, jump just fine in 1.11.2, you'll have to give me more context.
