### ISSUE TITLE
My chickens are not eating

### ISSUE THREAD

**Issue by SheroxGG** [capnkirok/animania#482]
### Expected Behavior
Breeding and getting a lot of chickens

### Actual Behavior
they dont eat, I have to feed them

### Version of Minecraft, version of Animania, Single Player or Server
Server 1.4.2 1.11.2

### Screenshots encouraged
![2017-12-16_13 15 43](https://user-images.githubusercontent.com/34599826/34070284-ad1d598e-e263-11e7-86fb-4ca333b30934.png)

**Comment by capnkirok** [comment]
You need to place the seeds on the ground, not plant them. To do this, just hold seeds in your hand and right click on the ground.

[![Screenshot from Gyazo](https://gyazo.com/8ce21e60ffaf2e180db20dbd579c1cba/raw)](https://gyazo.com/8ce21e60ffaf2e180db20dbd579c1cba)

**Comment by SheroxGG** [comment]
Hello thanks for the help. Also my cows are not eating and they have food, like the chickens, the wheat is jus decorative. My cows have something similar to the chickents but they dont have nests.

**Comment by capnkirok** [comment]
Cows only eat when they are hungry. Have you installed either The One Probe or HWYLA? That will give you additional info on what's happening with your animals.

**Comment by SheroxGG** [comment]
THANKS!! You really helped me. Have you thought of creating a discord server so we can create a community with a lot of people helping each other?

**Comment by capnkirok** [comment]
There is one 👍 

Go to: https://discord.gg/xyXrVBa
