### ISSUE TITLE
dark sheep drop wrong wool  (chisel mod.)

### ISSUE THREAD

**Issue by 13illy** [capnkirok/animania#483]
### Expected Behavior
Get usable wool from black sheep (only tested with Friesian ewe)

### Actual Behavior
you get black chisel wool from black and brown sheep (friends say they got different types of wool as well but could not get this myself.)

### Steps to Reproduce
instal chisel and sheer multiple black and brown Friesian ewes (unsure if this effects other sheep)

### Version of Minecraft, version of Animania, Single Player or Server
1.10.2
1.4.3
single player and server.

### Screenshots encouraged
![2017-12-17_23 16 04](https://user-images.githubusercontent.com/32988918/34084918-542e7402-e380-11e7-9c00-8a122a2ecc51.png)

**Comment by capnkirok** [comment]
Thanks! Fixed in next release :)
