### ISSUE TITLE
Thirsty, Hungry all the time

### ISSUE THREAD

**Issue by LunaKenn** [capnkirok/animania#484]
### Expected Behavior
![mods](https://user-images.githubusercontent.com/34673924/34145855-f2b18ad0-e4eb-11e7-84c6-e45dac31c897.jpg)

When I feed them either water or their respective foods it should change their status to well fed.

### Actual Behavior
It never changes, even if I feed them 100 times... It won't change T.T

### Steps to Reproduce
Just feed them by hand, or by recipient... (Also, I should probably mention that I have the mod in Spanish... however, I wouldn't mind having this mod in English (Just the mod))

### Version of Minecraft, version of Animania, Single Player or Server
1.11.2, 1.4.3 (I believe), Single Player

### Screenshots encouraged
![2017-12-19_18 37 19](https://user-images.githubusercontent.com/34673924/34145823-bee8d15e-e4eb-11e7-9013-180cf1b9d801.png)

![2017-12-19_18 37 21](https://user-images.githubusercontent.com/34673924/34145826-c1bf6956-e4eb-11e7-9c87-20b9bdd92963.png)

![2017-12-19_18 37 19](https://user-images.githubusercontent.com/34673924/34145823-bee8d15e-e4eb-11e7-9013-180cf1b9d801.png)

![2017-12-19_18 37 21](https://user-images.githubusercontent.com/34673924/34145826-c1bf6956-e4eb-11e7-9c87-20b9bdd92963.png)

**Comment by capnkirok** [comment]
Thanks, I will take a look!

**Comment by capnkirok** [comment]
Looks like you are using HWYLA for 1.11.2, a fork of WAILA. I think this could be the issue. Have you tried this with WAILA instead? I will test HWYLA now.

**Comment by capnkirok** [comment]
Also, do you see this during your start up sequence on the console?

```
[12:02:51] [Client thread/INFO] [Waila]: Receiving registration request from [ animania ] for method com.animania.compat.waila.WailaCompat.registerWaila
[12:02:51] [Client thread/INFO] [FML]: Injecting itemstacks
[12:02:51] [Client thread/INFO] [FML]: Itemstack injection complete
[12:02:51] [Client thread/INFO]: [STDOUT]: TrueTypeFont loaded: java.awt.Font[family=Minecraftia,name=Minecraftia Regular,style=plain,size=14] - AntiAlias = true
[12:02:51] [Client thread/INFO] [Waila]: [Agriculture] Agriculture mod not found.
[12:02:51] [Client thread/INFO] [Waila]: Trying to reflect com.animania.compat.waila.WailaCompat registerWaila
[12:02:51] [Client thread/INFO] [Waila]: Success in registering animania
```

**Comment by capnkirok** [comment]
Hey @LunaKenn I just finally tested this and HWYLA is definitely not working, while WAILA is. This is particularly strange since HWYLA is just a fork of WAILA. Would recommend you try WAILA for 1.11.2 (make sure you download CompatLayer).

I will report this to the HWYLA author.

**Comment by MauveCloud** [comment]
I noticed this a few days ago in 1.10.2 with Hwyla-1.8.17-B31_1.10.2, but switched to TOP instead (and decided I like it better).  Waila hasn't been released for 1.12 (and due to the existence of Hwyla, idk whether the original Waila author is even planning to make a 1.12 version)

**Comment by capnkirok** [comment]
I'm working with TehNut on this (HWYLA author). It is taking a backseat to some other issues, but we'll get to it.

**Comment by LunaKenn** [comment]
OMG I am so sorry, couldn´t log into my account xD

I have been following though, and I really appreciate your work :) Thanks, I will use WAILA for now, and what is that CompatLayer? Didn´t even know it existed xD

**Comment by capnkirok** [comment]
@LunaKenn CompatLayer is a super handy mod that McJty put together that allowed some 1.10 mods to also run on 1.11. It's required if you want to use WAILA in 1.11.2

**Comment by capnkirok** [comment]
Ok, thanks to @TehNut, this one is fixed in next release.
