### ISSUE TITLE
Throwing eggs (vanilla or brown) will produce adult chickens

### ISSUE THREAD

**Issue by WesCook** [capnkirok/animania#49]
Throwing an egg in Animania can produce adult Animania chickens.  This is true of both vanilla eggs, and brown mod-added eggs.

I presume this is due to the mechanic that Animania replaces vanilla mobs, where the game would spawn a vanilla chick and it's replaced.

Proposed changes:

1. Thrown eggs should yield baby Animania chickens instead, or...
2. This mechanic should be disabled entirely, as it makes chicken breeding/growth too easy.

Personally I'd opt for Option 2, as being able to spawn chickens negates the rooster mechanic entirely.

You could also consider a config, if you think there's a reason modpack authors may want to keep this mechanic.

**Comment by capnkirok** [comment]
I will see if can get Option 2 to work. Thanks for feedback.

**Comment by capnkirok** [comment]
Well, I've figured out a way to disable Egg Throwing altogether. Might stick with this as a backup (with an option in the Config to re-enable)

**Comment by WesCook** [comment]
The only casualty I can think of is Better With Mods, which uses egg throwing as a method to get raw eggs.  Eggs that don't hatch into chickens become an item drop instead.

I can add a recipe via CraftTweaker to bridge the gap, so it shouldn't be an issue for me.

But yeah, a config is probably a good idea in that case.

**Comment by capnkirok** [comment]
Ok, here's where I ended up. 

1) By default, Egg Throwing is now disabled.
2) Via config, you can re-enable, but... it won't throw if you are within 1-2 blocks of any animal (ferret, hedgehog) that eats eggs.

Will be in next release (1.0.3)
