### ISSUE TITLE
[1.12.2 - 1.4.3] Milk bottle not filling food bar, drinking a stack of milk bottles drinks them all

### ISSUE THREAD

**Issue by Luke616** [capnkirok/animania#494]
### Expected Behavior
Milk bottles refill hunger and saturation
Drinking a stack of milk will drink one bottle at a time

### Actual Behavior
Milk bottles refill nothing
Drinking a stack drinks all the milk at once and turns the stack into a single empty bottle

### Steps to Reproduce
Become hungry and drink a milk bottle

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.4.3
Single Player

**Comment by capnkirok** [comment]
They should refill partial hunger and saturation (not all), will check. 
Drinking a full stack is definitely a bug.

**Comment by capnkirok** [comment]
Yup, these were both bugs. Thanks for the post! Both will be fixed in next release.
