### ISSUE TITLE
Ice and Fire Issue

### ISSUE THREAD

**Issue by Aaron082001** [capnkirok/animania#499]
Hi i know raptorfarian is one of the author of this mod and raptorfarian also is the author of ice and fire...Now this is my problem before i download animania the dragon in ice and fire mod can eat an animal like chicken,sheep etc. it have an animation on it.The dragon bite on the animal then shake it then the animal will die instantly.But when i download the animania the dragon still do the eating animation but the animal will not die instanly like before.After the dragon it eat it will just drop eat and the animal did not lose any health...plss fix this

sry for bad english

**Comment by capnkirok** [comment]
The author of fire and ice is working on this one. Can only be done on his side.
