### ISSUE TITLE
Pig and Cow Pathing needs (serious) improvement

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/animania#5]

**Comment by ruyanve** [comment]
I was just about to report this :)
Loving it so far!

**Comment by MrAmericanMike** [comment]
I guess this goes here also, had same issues with the pigs, once I punched them and push them into water they back to normal.-

****
Well, not sure if a bug, or if they just taking a break or something, but I have in my world some pigs that don't move at all, they just standing and some particles come from them time to time.

![image](https://cloud.githubusercontent.com/assets/8037559/23235692/41886708-f935-11e6-8ce2-9e82d7ab3d7c.png)
![image](https://cloud.githubusercontent.com/assets/8037559/23235719/5576c570-f935-11e6-8faa-448a92dd4af3.png)

PS: I believe they were trying to drink some water, I pushed them and after that they swim a little bit and started moving again

This last one not close to water, so not sure.

![image](https://cloud.githubusercontent.com/assets/8037559/23235845/c220c04a-f935-11e6-8057-64d95e07adbe.png)

Also took him to water, he drink some and alive again ;)

**Comment by capnkirok** [comment]
Thanks for the screenshots. Yeah, I'm completely redoing all pathing for Pigs.

**Comment by capnkirok** [comment]
There are a couple of issues here. Pathing & AI. Both will be much better in 1.0. But still need more work on pathing.

**Comment by capnkirok** [comment]
OK, made some  more improvements to pathing for Cows and Pigs. This appears to be a problem for any entity that's wider / longer than 1 block (using default mc pathing)
