### ISSUE TITLE
render issue with refined storage and animania

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#500]
### Expected Behavior

work as intended
### Actual Behavior

crashes the client
### Steps to Reproduce
tried to make an auto craft recipe with refined storage for cheese wedges and it crashed my client

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 minecraft 1.4.3 animaina single player

**Comment by capnkirok** [comment]
Can you post your crash log, please.

**Comment by CharCharthemonkey** [comment]
[crash-2018-01-06_21.14.02-client.txt](https://github.com/capnkirok/animania/files/1609954/crash-2018-01-06_21.14.02-client.txt)
as requested

**Comment by CharCharthemonkey** [comment]
[crash-2018-01-07_11.10.44-client.txt](https://github.com/capnkirok/animania/files/1609991/crash-2018-01-07_11.10.44-client.txt)
this was after disableing the mod to remove all RS connections then re adding it and it still crashed cause of the cheese mold and cheese knife

**Comment by capnkirok** [comment]
Hey @CharCharthemonkey can you post this one to Refined Storage? There's nothing wrong with our recipe..

**Comment by CharCharthemonkey** [comment]
will do thank you for checking

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#137
