### ISSUE TITLE
Mob Spawning problem

### ISSUE THREAD

**Issue by NoahTheGreat02** [capnkirok/animania#501]
When I am playing all of the animani mobs spawn and so do the vanilla hostile mobs but I have had no non hostile mobs spawn (sheep, pigs, cows, chickens etc) HELP!

**Comment by CharCharthemonkey** [comment]
that seems like a config derp noah check if u have it set to allow vanilla animals or disable them to allow the animania ones if possible

**Comment by capnkirok** [comment]
@NoahTheGreat02 CharChar is correct. There is a setting in the config file "Replace vanilla [insert animal here]". By default these are set to true. Set them to false to spawn Vanilla animals.
