### ISSUE TITLE
Rabbit Doe Chinchilla / Nigerian Kid Goat Ticking Entity Crash

### ISSUE THREAD

**Issue by ElvenChaos** [capnkirok/animania#502]
I'm getting an occasional crash due to ticking entity of animania mobs concerning pathing.
Crash log (most recent): https://pastebin.com/vVeE8zu4

In this case, it was a doe_chinchilla, though I also have older logs with other animals:
Crash log (older, other changes present): https://pastebin.com/mzyJ5HqM

I have been creating new world instances to test changes and issues in my pack, and while minding my business these crashes happen seemingly randomly.

Animania: 1.12.2-1.4.3
Forge: 2584

EDIT: Rejoining the same world as the ticking entity quickly, but not immediately, caused the same crash.

EDIT 2: Just created a new world and instantly got the crash. However, this time it wasn't from an animania mob but a roots mob, so a different mod entirely may be the issue and not animania. Here is the crash log for reference, I'll leave the issue open for now in case you have any insight into the issue:
https://pastebin.com/UdmbpeYa

EDIT 3: Is this related? https://bugs.mojang.com/browse/MC-117839 Could the issue be caused from a poor tick rate, making "too many movement commands" easier to achieve?

**Comment by capnkirok** [comment]
Looks related to #503

**Comment by reiyooki** [comment]
It appears specifically related to this line: net.minecraft.pathfinding.WalkNodeProcessor.func_186332_a(WalkNodeProcessor.java:192)

The mojang bug post does appear related, if you scroll down you can see its' "caused by" line pointing to the same place.

**Comment by capnkirok** [comment]
@reiyooki yes, I believe you are correct. This is also related to #490 

I need to redo my pathing algorithm again.

**Comment by capnkirok** [comment]
Pathing algorithm and entity update frequency are changed in 1.4.4.
