### ISSUE TITLE
[1.12] [1.4.3] Ticking Entity NPE

### ISSUE THREAD

**Issue by reiyooki** [capnkirok/animania#503]
### Expected Behavior
Animania animal pathing normally

### Actual Behavior
Game lock

### Steps to Reproduce
Unsure what's causing the issue, I've encountered it 3 times while simply flying around a test world in creative, each time with a different animal being listed as the ticking entity. All instances appear to point to net.minecraft.pathfinding.WalkNodeProcessor

### Version of Minecraft, version of Animania, Single Player or Server
Single Player
Minecraft 1.12.2
Animania 1.4.3

### Crash Log
[crash-2018-01-10_22.24.15-server.txt](https://github.com/capnkirok/animania/files/1621784/crash-2018-01-10_22.24.15-server.txt)

**Comment by Sluggasaurus** [comment]
Disabling Rodent spawns seems to have fixed this error for me

**Comment by capnkirok** [comment]
The only I changed is the update frequency of Entities, which seems like the culprit. In the 1.4.4 release, I've changed this back. Assuming this is fixed.
