### ISSUE TITLE
Hungry Animals Compatibility?

### ISSUE THREAD

**Issue by Aaron082001** [capnkirok/animania#504]
Is this mod and Hungry animal mod is compatible because hungry animals mod change the behaviour of the vanilla animals

**Comment by Deshiba** [comment]
Hey, did you try it out yourself? 

If it doesn't work you could request support. However if there is no issue at the moment then this message becomes obsolete.

**Comment by capnkirok** [comment]
Someone has made an integration mod for it:
https://github.com/utoc123/hungryanimals-animania_integration

Still in progress but soon... keep an eye on it
