### ISSUE TITLE
Covered Wagon does not remember rotation

### ISSUE THREAD

**Issue by grugsy** [capnkirok/animania#505]
### Expected Behavior
remains facing direction it was left in

### Actual Behavior
turns itself to random diagonal position when left alone for a time/sleep in normal bed

https://www.modlister.com/user/grugsy

**Comment by capnkirok** [comment]
Ah yes, rotation. Are you by chance on a server?

**Comment by grugsy** [comment]
nope

**Comment by grugsy** [comment]
I even tried blocking the tug pole/yoke but found out quickly that it has no collision...lol

**Comment by capnkirok** [comment]
Yeah, Minecraft entities are just giant blocks. No subtlety there.
