### ISSUE TITLE
Lang files correction

### ISSUE THREAD

**Issue by Foxgreat** [capnkirok/animania#506]
Correct text in all .lang files in 104 raw

item.animania_cooked_chevon.name.Roast Chevon
to
item.animania_cooked_chevon.name=Roast Chevon

TY

**Comment by Foxgreat** [comment]
Sorry if i too rude. I'm new on git world and have less experiense in discussion with foreigns)

I will take merge request TY =D

**Comment by capnkirok** [comment]
Hey guys. I'm going to close this one. Since it's only one line, I already fixed it :)

We do need an update on BG & DK, though :)

**Comment by Deshiba** [comment]
@capnkirok On closer inspection it appears that pretty much all the LANG files need a pass over. A lot has changed in 11 months:

 	no_NO.lang 	Add files via upload 	11 months ago
	pt_BR.lang 	Add files via upload 	11 months ago
	pt_PT.lang 	Add files via upload 	11 months ago

**Comment by Deshiba** [comment]
@capnkirok Could you point me to the .Lang file that is used as the base for all Lang files?

**Comment by capnkirok** [comment]
This one: https://github.com/capnkirok/animania/blob/master/en_US.lang

**Comment by Deshiba** [comment]
@capnkirok I assume that some stuff got removed? The zh_CH.lang contains the following.

item.animania_wheel.name=转轮
item.animania_salt.name=盐

These are not present in the en_US.lang

**Comment by capnkirok** [comment]
@Deshiba yup, was not updated. Try again :)

**Comment by Deshiba** [comment]
@capnkirok Sorry to be a bother...

fluid.slop=
fluid.milk_holstein=
fluid.milk_friesian=
fluid.milk_goat=
fluid.milk_sheep=

Seems to be gone from the en_US.lang file

**Comment by capnkirok** [comment]
sorry, i copied from 1.10. Try again...
