### ISSUE TITLE
Friesian Bulls clogging skeleton XP farm

### ISSUE THREAD

**Issue by Kavrrin** [capnkirok/animania#507]
### Expected Behavior
for animals to not spawn at y46 and especially not in pitch black water covered rooms

### Actual Behavior
friesian bulls somehow spawning in and clogging up the water lift thats transporting the skeletons upwards to drop for an easy kill

### Steps to Reproduce
make skeleton spawner. wait about 5 to 10 minutes

### Version of Minecraft, version of Animania, Single Player or Server
using the Curse Magiculture modpack (packs version being 0.1.2.4) on a singleplayer world, minecraft version being 1.12.2, animania version being 1.4.2

### Screenshots encouraged
![2018-01-13_23 49 13](https://user-images.githubusercontent.com/35414606/34912983-f1457086-f8bd-11e7-8aac-9a78537e7c78.png)
minimap in top right showing y46

im super confused and very concerned. why are these bulls spawning underground??? do they think they can eat the stone or something???? ive played animania in other packs but ive never took the chance to make an xp farm so this is my first sighting of this... bug i guess. i put in a glowstone block to see better when cleaning them out but before that they were spawning in a pitch black, 1x2 tunnel. im not sure if it's the pack itself or not and if so, im sorry for bringing it up here.

**Comment by Kavrrin** [comment]
note: theyre not spawning in the room with the spawner at all. theyre spawning specifically in the tunnel leading to the water lift, and sometimes in the lift itself

**Comment by capnkirok** [comment]
There's a feature in Animania that spawns Friesian bulls with mounted skeletons. I believe that is what is happening here. You can turn this off in the config... "AllowMobRiding = false"

**Comment by capnkirok** [comment]
I will also change this so that they don't spawn underground, but the above should fix your issue for now.

**Comment by capnkirok** [comment]
Ok, mob riders won't spawn < 60 blocks. Fixed in next release.
