### ISSUE TITLE
Hamster wheel not working (unable to place hamster in it)

### ISSUE THREAD

**Issue by Byrdo** [capnkirok/animania#508]
### Expected Behavior
After taming a hamster and shift-right clicking it onto my shoulder, I should be able to place it into a hamster wheel by right clicking. 

### Actual Behavior
I'm able to mount the hamster on my shoulder, but when I attempt to right-click the hamster wheel, nothing happens. The block outline that typically encases a block when you hover over it doesn't appear over any block while having the hamster on my shoulder. 

### Steps to Reproduce
Place hamster wheel somewhere
Get a hamster
Tame the hamster
Shift-right click hamster onto shoulder
Attempt to right-click hamster onto wheel

### Version of Minecraft, version of Animania, Single Player or Server
1.10.2, Animania version 1.4.3, Single Player and Server

**Comment by capnkirok** [comment]
It's different in 1.10. Just tame it and make sure it's sitting nearby the wheel. Then right click on the wheel.
