### ISSUE TITLE
Suggestion: Camels

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#510]
In arid climates [Camels](https://en.wikipedia.org/wiki/Camel) and [Dromedary](https://en.wikipedia.org/wiki/Dromedary) are domesticated as Draft Animals and Farm animals. 

They are used in caravans much like the Alpaca Vanilla MC added, they also pull carts and can be ridden. 
As farm animals they can be milked and are butchered for meat.

It would be nice to have a little more content in the desert.

**Comment by capnkirok** [comment]
Hey @Deshiba these are on the list :)

**Comment by Deshiba** [comment]
@capnkirok these weer allready submitted? If so, sorry die missing it.

**Comment by Deshiba** [comment]
@capnkirok these weer allready submitted? If so, sorry die missing it.

**Comment by capnkirok** [comment]
No, they were on our original list... just never shared it :) Keep your ideas coming!
