### ISSUE TITLE
Own Custom Drops not working

### ISSUE THREAD

**Issue by Glutzahn** [capnkirok/animania#512]
### Expected Behavior
Having Minecraft Coal plus Prime Pork Chop droped

### Actual Behavior
nothing droped (except for the pigs that drop default porkchop)

### Steps to Reproduce
add a custom drop in the mod config menu
I wanted to add tallow from the quark mod to pig drops, since that didn't work I removed all mods except animania, then I made a new world and reverted the drop setting to default. Everything worked.
Then I tried to add Mincraft:Coal as a test drop, result all pig that should drop prime prokchop droped nothing as they did with quark:tallow when quark was still in.
I tried sepreating the drops with ";" "," "." "; " ", " ". " nothing worked at all

### Version of Minecraft, version of Animania, Single Player or Server
MC: 1.12.2, Animania: 1.4.3 for 1.12.2, Single Player

**Comment by capnkirok** [comment]
Hey @Glutzahn ... they work but... they only work for one drop, and only with the 'exotic' pigs (so, not Yorkshires or Large Whites). Format is "minecraft:apple" or any mod.

In the next update, you will be able to modify the initial and second drops of any animal.

Related to: #448

**Comment by Glutzahn** [comment]
so that means they can only drop either the prime meat or the drop I want?
Ok thanks for the answer ^^
I'm looking forward to the next update. 
Thy for your amazing work^^

**Comment by capnkirok** [comment]
Yup, until this weekend :)
