### ISSUE TITLE
Hamsters lose name after using Hamster Wheel

### ISSUE THREAD

**Issue by SSyl** [capnkirok/animania#513]
### Expected Behavior
When a hamster is finished running in a hamster wheel, it should retain its name.

### Actual Behavior
When a hamster is finished running in a hamster wheel, it loses its name and also some other entity data. For example, I named a hamster "Mr Hamster" and made him invulnerable (via commands). After putting him in a hamster wheel, he no longer had his name and was vulnerable again.

### Steps to Reproduce
1. Tame a hamster.
2. Put a custom nametag on the hamster.
3. Put it in a hamster wheel.
4. When it comes out, it'll no longer have its name.

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2 Forge 14.23.1.2590
Animania 1.4.3
Both SP and server

### Screenshots encouraged

![2018-01-18_13 50 46](https://user-images.githubusercontent.com/6855315/35118575-c88fbb7c-fc57-11e7-9968-613e299aac1a.png)

![2018-01-18_13 50 59](https://user-images.githubusercontent.com/6855315/35118585-cd82d25e-fc57-11e7-97b1-755b98b68f4e.png)

![2018-01-18_13 51 45](https://user-images.githubusercontent.com/6855315/35118598-d83e11d6-fc57-11e7-8e11-8310236d6ecb.png)

**Comment by capnkirok** [comment]
Cheers. Yes, this is an issue on 1.11 and 1.12.

**Comment by capnkirok** [comment]
Poor Reggie!

**Comment by Tschipp** [comment]
Fixed! https://i.gyazo.com/6a8bc78a652f6e3e172dee77a97981df.gif
