### ISSUE TITLE
Cant take animania off of server

### ISSUE THREAD

**Issue by goodgollyitsmol** [capnkirok/animania#515]
Whenever my friend tries to take the mod off of the server, we arent able to restart it up. the config is saying there are still mobs on the server even though we have done /kill @e and it says theres nothing left to kill. any help?

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 server
![screen_shot_2018-01-18_at_20 00 18](https://user-images.githubusercontent.com/35578408/35119078-d95c48b2-fc61-11e7-842b-5c92f950d489.png)

**Comment by capnkirok** [comment]
Hmm... never seen this one before, but it appears to be harmless. These are just notifications, not a crash. Is there a rash error anywhere? And they are notifications of a registry entry, not of an actual living mob.

http://www.minecraftforum.net/forums/support/server-support/2835437-forge-why-do-i-get-found-a-missing-id-from-the

**Comment by goodgollyitsmol** [comment]
its not crashing, just not starting after we take the mod off

**Comment by capnkirok** [comment]
Is there a note on the server asking you to proceed?

**Comment by capnkirok** [comment]
Hey @goodgollyitsmol per the above note.. you should be able to respond to question on the server and it will allow you to continue.
