### ISSUE TITLE
[1.12.2] [1.4.3] Ticking Entity Error - Client Crash Only

### ISSUE THREAD

**Issue by Sluggasaurus** [capnkirok/animania#516]
### Expected Behavior
Rodents and horses to spawn properly and not conflict

### Actual Behavior
They cause conflicts with other mods when they try to spawn.
It's only crashing the client however, not the server itself. 
Disabling Rodent and Horses from spawning in the conflict fixes the issue.
(also this seems like a similar issue to #503 and #502 )

### Steps to Reproduce
Install animania and ice and fire

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft version 1.12.2
Animania 1.4.3
Server

### Screenshots encouraged
No screenshots, but I have a crash report. It seems that it is a conflict with ice and fire, but it also happens with animania's hamsters, hedgehogs, and horses, and this client-side crash ONLY happens if rodent and horse spawning is enabled in the server's config
https://paste.ee/p/FttT7

**Comment by capnkirok** [comment]
Can you post this to the ice and fire github? The crash is on the ice and fire side. And Animania does not use Byte in any of its NBT data. You can cross reference it hear, so that Alex and I can dialog.

Thanks!

**Comment by Sluggasaurus** [comment]
Thank you for clearing that up! However I was also experiencing crashes with hedgehogs, hamsters and horses specifically, with it referencing them in the crash log. Would that still be caused by ice and fire?
(also I have no idea how to cross reference, I am so sorry, I am very new to actually using github)

**Comment by capnkirok** [comment]
You can just post on his github, and then add the link back here in your text: https://github.com/capnkirok/animania/issues/516

**Comment by Sluggasaurus** [comment]
You are completely amazing! Thank you so much!
 I have spent three days trying to root out the problem with these crashes, not really glad it's ice and fire, but I'm glad I finally know whats causing it.
And I will do that right away, I already posed about Hippogryphs from his mod causing some problems, hopefully this can help them fix something.

**Comment by Alex-the-666** [comment]
@capnkirok yes this issue is completely on my side and has nothing to do with animania. should be closed

**Comment by capnkirok** [comment]
Thx :)
