### ISSUE TITLE
minior dupe

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#517]
### Expected Behavior
the mod to disable vanilla chickens

### Actual Behavior

vanilla chickens still spawn when a baby zombie or baby pigman spawn with one and picking up the chicken in say a mob imprisonment tool or some type of net or lasso will allow u to dupe chickens
### Steps to Reproduce
find a baby zombie riding a chicken or baby pigman on one kill it and net the chicken the place down and infinite chickens 

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 minecraft 1.4.3 animania in single player

**Comment by capnkirok** [comment]
Hey @CharCharthemonkey ... what mod are you using to imprison or lasso (so I can test).

**Comment by CharCharthemonkey** [comment]
the golden lasso from XU2 the imprisonment tool from industrial forgoing and the one in cyclic and all 3 dupe

**Comment by CharCharthemonkey** [comment]
i did find out version 1.4.4 indirectly fixes the dupe cause it actually removes the vanilla chickens from spawning totally tho still very weird hiccup tho

**Comment by capnkirok** [comment]
Yes! That is what I hoped to hear :)

Closing...
