### ISSUE TITLE
[suggestion] make pigs spin around in mud less

### ISSUE THREAD

**Issue by Zygus42** [capnkirok/animania#52]
If pigs spun that fast in mud, they could be used as an RF power source.  Should be slow and lazy, and would feel a lot more realistic.

**Comment by capnkirok** [comment]
yeah, not sure what is causing the spinning... even if I make them super slow, they still whip around.

**Comment by Tschipp** [comment]
It's because you rotate the model, and they are really just spinning around their bodies. A custom AI task might fix this, by preventing the lookAround task

**Comment by capnkirok** [comment]
I removed all the AI tasks from the pigs, and they STILL rotate around. I think it might be buried somewhere in the MC code. Going to keep working on it.

**Comment by capnkirok** [comment]
Think I figured this out. Going to try to add it in 1.4.3.

**Comment by capnkirok** [comment]
Ok, it's much better. Still turns a bit... but that's because of the WanderAI. Going to leave it like this for now.
