### ISSUE TITLE
Mooshroom Calves Not Shearable

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#521]
I'm not entirely sure if it was intentional or not, but the Mooshroom calves can't be sheared to turn into Friesian calves.
I'm using Animania version 1.4.4 for Minecraft 1.11.2 and I'm in single player, if that helps.

**Comment by capnkirok** [comment]
Yeah, I thought the calves should not be shearable... just like sheep ...

**Comment by RaliaTheWolf** [comment]
Ah, okay! That makes sense... Just thought I'd ask just in case it wasn't intentional!

**Comment by capnkirok** [comment]
👍
