### ISSUE TITLE
[Suggestion] Add config option to disable "Edible Anytime" on foods

### ISSUE THREAD

**Issue by SSyl** [capnkirok/animania#522]
It would be nice if there was a config option to disable the "Edible Anytime" on foods.

The reason being that it unbalances other mods, such as [Nutrition](https://github.com/WesCook/Nutrition), which depend on you only being able to eat when hungry. In Nutrition's case, you're able to cook up a few Animania omelettes and cheese to quickly max out your dairy and protein meters.

**Comment by capnkirok** [comment]
Oh I had no idea. I always found it annoying if you wanted to eat something for its other benefits (like strength or speed etc), but you have to wait until you were hungry.

Yes, can add a config :)

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#138
