### ISSUE TITLE
Error in 1.4.4. config

### ISSUE THREAD

**Issue by BryanBoru** [capnkirok/animania#523]
With a fresh Config in 1.4.4. 

Line 395+ has the Animal diets.

https://i.gyazo.com/b1cc565a7917af895e3a26c308f7913a.png

they all say ``cow`` instead of the intended animal.

**Comment by Deshiba** [comment]
Probably an oversight on release. If you hadn't noticed you can tell which is which by the line under it
>S:[animal]Food

**Comment by capnkirok** [comment]
Oh god, copy paste. Yup thx.

**Comment by capnkirok** [comment]
Ok fixed for next release
