### ISSUE TITLE
[1.12.2] [1.4.4] Drinking milk from bottle causes connection to client to be interrupted

### ISSUE THREAD

**Issue by JonoColwell** [capnkirok/animania#524]
### Expected Behavior
Drink milk, cure potion effect

### Actual Behavior
drink milk, cure potion effect, returned to server select by way of internal server error

### Steps to Reproduce
Drink bottled milk

### Version of Minecraft, version of Animania, Single Player or Server
MC: 1.12.2
Animania: 1.4.4
Server - Consistent for all players

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/8704304/35272985-104ba732-008b-11e8-909b-a60853acf0bc.png)

**Comment by capnkirok** [comment]
Bleh, I didn't test this on servers. Serves me right. Do you happen to have a crash log, just in case I can't repro?

**Comment by capnkirok** [comment]
Yeah, I can't reproduce this. I'm going to guess you are using AppleCore? Let me know.

**Comment by capnkirok** [comment]
Ok, if you are seeing a crash, it's likely a conflict with another mod, but I can't help you without a modlist or a crash log. So... I'm going to close this unless I hear back :)

**Comment by drakray** [comment]
Got this in single player game https://pastebin.com/sJk4X3Nk

**Comment by capnkirok** [comment]
Yeah, AppleCore. It doesn't like it if you access FoodStats before it does. Let me see if I can do anything on my side before bothering that author.

**Comment by capnkirok** [comment]
Ok, this is fixed in the next release. AppleCore doesn't like it if you reduce stack size to zero before applying food stats (unlike vanilla mc, which is fine with it).
