### ISSUE TITLE
more of a question actually 

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#526]
### Expected Behavior
probably

### Actual Behavior

idk
### Steps to Reproduce
none

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 1.4.4 but was wondering if possible for the vanilla spawn eggs instead of them just poofing would it be possible to have them give a random animal instead?

**Comment by Tschipp** [comment]
What?

**Comment by capnkirok** [comment]
@Tschipp with my new spawn fix, the vanilla eggs no longer work.

**Comment by Tschipp** [comment]
Ah, didn't know

**Comment by CharCharthemonkey** [comment]
yea and instead of them fizzeling out was wondering if possible to have them give a radom chance to spawn any of the animania animals based on spawn egg if thats possible?

**Comment by capnkirok** [comment]
Maybe, it would be an enhancement though (and called it as such).

**Comment by CharCharthemonkey** [comment]
noted and wasnt sure which tag would fit lol and ty

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#139
