### ISSUE TITLE
Spawn limit config

### ISSUE THREAD

**Issue by Zadnicaff** [capnkirok/animania#529]
After updating to 1.12.2-1.4.4 and generating a new config file, I've noticed that options for setting spawn limits for each animal are now gone. I don't know if this change was intentional of if it's just a bug, but it would be great to be able to limit natural spawn again.
 (It would also be super great if it didn't affect manual breeding).

**Comment by capnkirok** [comment]
You should read the release notes :) you can find them on the file in Curse (and on Twitter).

You can reduce natural spawn by lowering probabilities and reducing family size.
