### ISSUE TITLE
Rabbit Hides Don't Drop

### ISSUE THREAD

**Issue by magerooster** [capnkirok/animania#533]
### Expected Behavior
Rabbits to drop Rabbit Hide (one of their normal vanilla drops). Animania configs don't allow for a third item drop type, and rabbits should have three different items they can drop. (This may affect other creatures as well).

What would be super-swell is if the item drops for each creature was something like: minecraft:item1,percentchance,quantity;minecraft:item2,percentchange,quantity;etc

### Actual Behavior
Rabbits only drop the raw rabbit meat and rabbit's feet as per the config file.

### Steps to Reproduce
Kill a bunch of rabbits.

### Version of Minecraft, version of Animania, Single Player or Server
1.10.2, 1.4.4, Multiplayer

### Screenshots encouraged
(No screenshots really needed for this.)

**Comment by Tschipp** [comment]
Right, but rabbit hide has no use (in vanilla) other than create leather

**Comment by Palpiter** [comment]
other mods might use rabbit hide as a crafting ingredient though (one example which is why i'm even here would be thaumcraft 6), so please re-add rabbit hide with its vanilla droprate to your rabbit-variations.

**Comment by capnkirok** [comment]
Working in Dev. Will be in next release.
