### ISSUE TITLE
problem with reproduction

### ISSUE THREAD

**Issue by LeoB20** [capnkirok/animania#535]
Hello Good, I have a big failure with the uncontrolled reproduction of the animals (all), if you want to know what I'm talking about you can see the Vegetta777 channel in your wigetta world series, the same happened to me in the last version of the mod for which I had to download the previous one, I hope you find this solution, Thanks!

**Comment by capnkirok** [comment]
Hey Leo, this is being tracked by many at #532 , we are trying to find the issue, looks to be a conflict of some sort. Closing this, and please follow that thread.
