### ISSUE TITLE
Potential memory leak (Sponge + Animania)

### ISSUE THREAD

**Issue by Ghostlyr** [capnkirok/animania#537]
I'm not a developer, just decided to go deeper into to investigate the problem.

### Expected Behavior
Full-length long game with allocated 1.5 GB RAM.

### Actual Behavior
Unable to play in the game for more than 40 minutes nearby a chunks with large amount of mod mobs. The gaming client starts hanging due to a lack of memory, reaching 100% used RAM. I tried to find out the source of problems by profiling and found the following strange things:
- The extreme memory consumption is caused by fast filling HEAP space.
- Memory starts to fill with garbage objects from rendering models classes. (which seems strange to me, occupying more than primitive classes objects)
- The work of the garbage collector becomes unstable and takes a long time.

(screenshots below)

Tried to run my modpack excluding Animania and did not observe any problems on the same map for a long time.

For these reasons, I came to the conclusion that the problem is caused by a Animania modification.
I repeat that I have no education in programming and excuse me dummy for the technical illiteracy. I will try to provide additional information if someone explains what needs to be done in simple words to me.

### Steps to Reproduce
Launch modpack with animania and load world with 200 and more nearby mobs from this mod.

### Version of Minecraft, version of Animania, Single Player or Server
1,12,2 forge 14.23.1.2607
Animania 1.4.4
Remote spongeforge-1.12.2-2586-7.1.0-BETA-2859 server

**Environment:** Win 10 x64, 8 GB RAM, available RAM capacity during problems - 1+GB,  Java 8 161 x64.

**Other mods (all updated to actual versions):**
ivtoolkit, baubles, codechickenlib, craftstudioapi, cxlibrary, ichunutil, mantle, biomesoplenty, animania, bibliocraft, ctm, chisel, crafttweaker, ctgui, jei, crafttweakerjei, foamflower, cfm, hats, inventorytweaks, ironchest, morefurnaces, plants2, reccomplex, bspkrscore, treecapitator, vending, controlling, waila, mousetweaks, nei, torohealthmod, optifine, betterfps

### Screenshots encouraged

**Profiling with Animania & Optifine & BetterFPS and other mods**

![screenshot](https://user-images.githubusercontent.com/8511068/35590939-89d1d4d0-0632-11e8-86f4-04750c66a995.png)
![screenshot](https://user-images.githubusercontent.com/8511068/35590941-89f8b488-0632-11e8-8faf-d67c5e6e94bd.png)

**Profiling on this modpack w/o Optifine & BetterFPS**
![screenshot](https://user-images.githubusercontent.com/8511068/35593366-ecacb686-0639-11e8-9f9f-8d847d270788.png)
![screenshot](https://user-images.githubusercontent.com/8511068/35593158-597b548a-0639-11e8-8acf-53b5892af3f6.png)

**This modpack w/o Animania & CraftStudio API**
![screenshot](https://user-images.githubusercontent.com/8511068/35592896-9d480a4c-0638-11e8-9cb6-82e2170aaea1.png)
![screenshot](https://user-images.githubusercontent.com/8511068/35592898-9d912b82-0638-11e8-88f5-5f932ff0cf1d.png)

**Comment by capnkirok** [comment]
Large amount of mobs is due to a conflict between Sponge and Animnia. Listed in #532 
Will let you know when it is fixed. Until then, yes, would avoid combining Animania and Sponge

**Comment by Ghostlyr** [comment]
But this issue only affects the spawn of mobs. My problem is about memory leaks on the client side, which can be repeated without Sponge in singleplayer - simple farms and large view distance.

**Comment by capnkirok** [comment]
Maybe I don't understand what you are trying to say. You shared information based on your Sponge server, which is currently causing excessive mob spawning. Which in turn causes memory leak in the client as it can't keep up with the rendering the large and ever-expanding number of mobs... am I missing something?

**Comment by Ghostlyr** [comment]
All right. That's only the problem reproduced in a singleplayer without Sponge and no other mods with 1.5g ram. It seems to me that this is not a MC defect, since without animania modification the gaming client suffers more vanilla and mod mobs without any problems. 

In this case, I would try to allocate even more memory. but I think the result will be the same, as it is clogged up with garbage jvm heap, not application space.

**Comment by capnkirok** [comment]
Thanks for the follow-up. I don't know if there's a memory leak or not, honestly. The animania animals are much more complex than vanilla though both in terms of AI and models/animation. So, it makes sense the server would choke on fewer mobs.

Regardless, the first order of business is to reduce and control the number of spawns. Will take a look at memory while I am at it.

**Comment by Ghostlyr** [comment]
Same situation with 4.0 GB of RAM, only after 2-3 hours of the game. I can not start profiling in this mode, because have not enough memory for YourKit and other important applications.

**Memory dump analysis in Eclipse Memory Analyzer:**

![screenshot4](https://user-images.githubusercontent.com/8511068/35630142-c605ed0e-06ca-11e8-9f05-2e11363c71f8.png)
![screenshot5](https://user-images.githubusercontent.com/8511068/35630141-c5d932d2-06ca-11e8-99ae-d38f16c80a89.png)

**Comment by capnkirok** [comment]
Thanks. Interesting, this is referencing the Trough, while the other was referencing entities. How many Troughs do you have?

**Comment by Ghostlyr** [comment]
Yes, very strange.

Only these:

![2018-01-31_21 27 00](https://user-images.githubusercontent.com/8511068/35631318-c14171be-06cd-11e8-9608-3cc4b6a92d01.png)

**Comment by QAngelusQ** [comment]
@Ghostlyr Just a question because I use sponge myself. I just noticed you're using forge 2607 for your client (assuming), while using sponge server for forge 2586. Wouldn't that cause some issue? or does it not matter?

**Comment by capnkirok** [comment]
The overspawning issue with Sponge should be fixed. Going to take a closer look at the Trough. Let me know if you are still seeing a leak using 1.4.5 (I assume yet, but want to check).

**Comment by Ghostlyr** [comment]
This is only recommended Forge version, some my modifications have raised the minimum requirement.

@capnkirok, Yep, the problem is still present on 1.4.5.

**Comment by capnkirok** [comment]
Hello people on this thread. This has now been fixed, the error was in the render code. Fixed in development and available in 1.4.8 release. Thanks!

https://github.com/capnkirok/animaniamod/issues/42
