### ISSUE TITLE
pig breeding is not really working ?

### ISSUE THREAD

**Issue by Zygus42** [capnkirok/animania#54]
I'm making a new modpack, and I just spent the better part of the day testing why my pig breeding from this mod wasn't working.   I thought it might be a mod conflict, so I've been pulling mods on and off again.  After numberless experiments and only a couple of successes, I've come to the conclusion that it's the mud - pigs love it so much that they mostly stay in it, never going to the food troughs or drinking or swimming in the water hole, so they're not happy enough to breed - I think.  Can anyone confirm this ?  Or is it working ok for everyone else ?  Or am I missing something ?

**Comment by capnkirok** [comment]
Your theory could be correct. I can review this later today. In the meantime, there is an easy way to test this. Just adjust the 'play' timer in the config to something longer (like 8000) and see if breeding works. Also you can change the 'birth' timer lower... (to say 2000).

And ensure the male is in decent proximity to the female of course.

PC

**Comment by Zygus42** [comment]
That was my first thought, and I adjusted the config to:
    I:"Ticks between giving birth"=200
after that nothing bred any more, not chickens, pigs or cows.

So I figured maybe it's because they wanted to breed, but hadn't eaten or drunk, so I adjusted:
     I:"Ticks between drinking water"=100
    I:"Ticks between feedings"=100
and the pigs didn't seem to eat much at all, nor drink much, nor breed at all.

Wasn't sure what the play timer did exactly, so I didn't mess with that one.

So I guess all up, kind of confused, but think something's not as it should be :)

**Comment by capnkirok** [comment]
Yeah, that's too low for drinking water and eating, so they will never be happy. That's about 5 seconds. Recommend you set drinking and feeding and play to 4000, and birth to 500.

**Comment by capnkirok** [comment]
I just tested with the above settings and it's working fine, so if the above doesn't work, there is something else going on.

**Comment by capnkirok** [comment]
Ah, ok. I think I found the issue. After the first birth, it resets the timer to a full MC day PLUS the timer. In the meantime, see if you can get the first birth working with some new animals. I will update the code to fix the follow-up births.

**Comment by Zygus42** [comment]
Tried your settings, and yes, chickens, pigs & cows had 1 child and very quickly.
