### ISSUE TITLE
Cow Breeding Question

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#540]
### Expected Behavior
cows should breed like normal

### Actual Behavior

they just sit there eating and drinking
### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 versions 1.4.3 and 1.4.4 cows do not breed anymore and was wondering how to fix pretty plz?

**Comment by Deshiba** [comment]
For animania animals you have to make them happy in order for them to breed. In order to view the happiness of animals Waila or TOP are recommended.

If you are sure they are happy you could expand your info with screenshots.

If you want classic breeding you should turn this on in the config files.

I hope this helped you out.

**Comment by CharCharthemonkey** [comment]
they are always happy and well fed tho and still dont breed and will double check the config maybe i made a derp on my end and is y they wont breed lol

**Comment by CharCharthemonkey** [comment]
ok so with further investigating i found its mainly just the fresian cows that wont breed the holstiens do breed which i guess could be a work around but hopefully if its a bug could be fixed plz and thank you

**Comment by capnkirok** [comment]
@CharCharthemonkey what happens if you put the cow and a bull on leads so they are next to each other? They literally need be just a few blocks away or less to even notice each other.

**Comment by CharCharthemonkey** [comment]
nothing happens and they are well withing a few blocks of each other unless having them to close to other bulls/cows messes up the stuff
![2017-12-25_12 12 59](https://user-images.githubusercontent.com/30783285/35654083-e82abcb2-06b0-11e8-9ada-085b269d98a8.png)
in the picture in the bottom right is is each pen size roughly 7x7 or 9x9 ish with a 1 block gap in between each

**Comment by capnkirok** [comment]
Ok, one more check... do you have WAILA or TOP installed so you can see if they happen to be mated with someone else?

**Comment by capnkirok** [comment]
@CharCharthemonkey try the latest version with some new animals and let me know if it works.

**Comment by EerieP** [comment]
I am having the same issue running the latest version of animania (1.4.5) on my CreateMC custom modded pack.

Here are a few screenshots of the problem...

![2018-02-05_22 15 15](https://user-images.githubusercontent.com/31190884/35844533-e77d0372-0ac2-11e8-907b-08f3006ab50c.png)
![2018-02-05_22 15 25](https://user-images.githubusercontent.com/31190884/35844534-e9bb6f48-0ac2-11e8-81f0-91f139c05690.png)
![2018-02-05_22 16 39](https://user-images.githubusercontent.com/31190884/35844537-eb754ef8-0ac2-11e8-87f4-ebcb683e3a2a.png)

Manual breeding is set to false, so they should be breeding if they are fed and watered. This is not the case... As you can see, the cow is bred with the bull but there is no baby created.

**Comment by capnkirok** [comment]
Hey @CharCharthemonkey ok, so that Cow says it's mated, but it might be mated to another bull than the one that is in the Pen. If you give the bull a name, and then press 'sneak' while looking at the cow, does it reveal the name of the bull that's in the pen?

**Comment by capnkirok** [comment]
Are you on 1.11 or 1.12?

**Comment by Deshiba** [comment]
@capnkirok That's in the original post:

> Version of Minecraft, version of Animania, Single Player or Server
> 1.12.2 versions 1.4.3 and 1.4.4

**Comment by EerieP** [comment]
I am using version 1.12.2

**Comment by EerieP** [comment]
It seems that the problem was with the female cow itself. I grabbed another cow and they bred fine.

**Comment by capnkirok** [comment]
Ok, great. Yeah, I think this 'lifelong' mating thing is going to have to change.
