### ISSUE TITLE
Odd configuration values in drops

### ISSUE THREAD

**Issue by MidnightsFX** [capnkirok/animania#541]
### Expected Behavior
Unsure of impact.

### Actual Behavior
Unsure of impact.

### Steps to Reproduce
Clean config for 1.10.2 include custom drop values which are empty and potentially a typo?

`    S:"Set Custom Chicken Sheep Drop"=`

`    S:"Set Custom Chicken Toad Drop"=`

### Version of Minecraft, version of Animania, Single Player or Server
Forge 12.18.3.2511, MC 1.10.2, Single-player

**Comment by capnkirok** [comment]
It won't affect gameplay, but it sure is confusing :)

The 'Chicken' should have said 'Secondary'... I've fixed this in the development environment. Luckily neither of these animals have a secondary drop, so the blank part is ok. 

Thanks for posting!
