### ISSUE TITLE
Suggestion: show male/female indicator for baby animals

### ISSUE THREAD

**Issue by MauveCloud** [capnkirok/animania#542]
It seems like it would be useful, especially with "classic" breeding (as opposed to manual breeding) to be able to check whether a calf, lamb, chick, etc. is male or female via Waila or The One Probe.  However, a quick glance via jd-gui indicates that baby animals are currently of indeterminate sex and choose randomly which to become upon reaching adulthood, which does not seem realistic.

**Comment by Deshiba** [comment]
Similar to #305, so I guess the answer here is the same:
> "...Unfortunately, the way we have it set up, gender isn't determined until later. Because of the work involved to redo it, this is not a priority (but I like your idea)."

**Comment by MauveCloud** [comment]
😞 The description of that one is enough different that I didn't catch it when searching for an existing bug, and I'm not sure what makes this so much work - if the mod were open source, I'd try to make a pull request for it myself, but it isn't (yet).

**Comment by capnkirok** [comment]
Thanks @MauveCloud yeah, I need to clean up some of the code in our private git first. I meant to have it public in January...

**Comment by Deshiba** [comment]
@MauveCloud Source has been open for a while now. See https://github.com/capnkirok/animania.

**Comment by Deshiba** [comment]
@MauveCloud Source has been open for a while now. See https://github.com/capnkirok/animaniamod

**Comment by capnkirok** [comment]
I'm going to put this on the to do list

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#141
