### ISSUE TITLE
"Growing time" shows 1199s until adulthood

### ISSUE THREAD

**Issue by MauveCloud** [capnkirok/animania#543]
### Expected Behavior
Growing time, if shown at all, should be a countdown to adulthood (or maybe adolescence first, some animals (but possibly not all) seem to have a separate model for that).

### Actual Behavior
Growing time remains stuck at 1199s until the animal suddenly reaches adulthood, at which point it disappears from the tooltip.

### Steps to Reproduce
1. Make sure The One Probe is installed.  This might also happen with Waila/Hwyla (possibly with Wawla, I haven't checked for this with those mods)
2. Find or breed a calf, lamb, etc. and watch the tooltip.

### Version of Minecraft, version of Animania, Single Player or Server
Seen in Minecraft 1.10.2 and 1.12.2, Animania 1.4.4, Single Player peaceful.

### Screenshots encouraged
![2018-01-31_17 41 48](https://user-images.githubusercontent.com/8942955/35657238-5a212366-06b0-11e8-88c9-39c699036e77.png)

**Comment by capnkirok** [comment]
Uhhh... growing time isn't something I'm tracking on Animania animals. This is a leftover from vanilla, which I ignore. Are you by chance using WAWLA?

**Comment by MauveCloud** [comment]
Nope.  I'm using The One Probe (with TOP Addons, in case that matters - though it shouldn't, considering TOP has an option in its own config for showing this).

**Comment by capnkirok** [comment]
From today (1.12).... is this something you can turn off in AddOns?

![2018-02-05_01 18 39](https://user-images.githubusercontent.com/9628379/35784026-9a514302-0a12-11e8-87b1-328b4d5262ca.png)

**Comment by MauveCloud** [comment]
Turning it off in TOP Addons was insufficient.  Turning it off in TOP itself as well worked.  However, it is on by default in TOP by itself, so I'm confused that you're not getting it in the TOP tooltip.

**Comment by capnkirok** [comment]
@RarCs you need to turn off this feature in the TOP config to fix it.

**Comment by beanaboston** [comment]
This is happening to me too. I'll just disable that option, as it's a little annoying to just see that the whole time until it grows up.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#142
