### ISSUE TITLE
[Client Crash] java.lang.NullPointerException: Ticking entity | MC 1.10.2

### ISSUE THREAD

**Issue by OmegaDerp** [capnkirok/animania#544]
### Expected Behavior

Does not apply

### Actual Behavior

Game sometimes crashes. It's probably when rendering the animal, and it can't "find" it. I can fix it by removing the entity, but this shouldn't be the solution :(

### Steps to Reproduce

There aren't really any steps. It happens randomly. It happened with a Draft horse, and now it happened with a Merino Ram.

### Version of Minecraft, version of Animania, Single Player or Server

MC Version: 1.10.2
Ani Version: 1.4.4

### Screenshots encouraged

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  PlusTiC (plustic-5.2.1.3.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.11.2-0.7.3-Anarchy.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  Extra Alchemy ASM (extraalchemy-0.3.3.1-release.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  AppleCore (AppleCore-mc1.10.2-3.1.0.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 2/2/18 12:16 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.animania.entities.sheep.EntityAnimaniaSheep.func_70628_a(EntityAnimaniaSheep.java:566)
	at net.minecraft.entity.EntityLivingBase.func_184610_a(EntityLivingBase.java:1100)
	at net.minecraft.entity.EntityLiving.func_184610_a(EntityLiving.java:555)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1080)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:64)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:224)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.animania.entities.sheep.EntityAnimaniaSheep.func_70628_a(EntityAnimaniaSheep.java:566)
	at net.minecraft.entity.EntityLivingBase.func_184610_a(EntityLivingBase.java:1100)
	at net.minecraft.entity.EntityLiving.func_184610_a(EntityLiving.java:555)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1080)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:64)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:224)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)

-- Entity being ticked --
Details:
	Entity Type: animania.ram_merino (com.animania.entities.sheep.EntityRamMerino)
	Entity ID: 150407
	Entity Name: Merino Ram
	Entity's Exact location: -3159.02, 64.00, 5169.99
	Entity's Block location: World: (-3160,64,5169), Chunk: (at 8,4,1 in -198,323; contains blocks -3168,0,5168 to -3153,255,5183), Region: (-7,10; contains chunks -224,320 to -193,351, blocks -3584,0,5120 to -3073,255,5631)
	Entity's Momentum: -0.00, -0.08, -0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: Survival World
	All players: 1 total; [EntityPlayerMP['retracted'/350, l='Survival World', x=-3176.22, y=62.07, z=5045.15]]
	Chunk stats: ServerChunkCache: 894 Drop: 0
	Level seed: 2684796111584309777
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 391974 game time, 673568 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 134973 (now: false), thunder time: 14696 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1242306008 bytes (1184 MB) / 2977955840 bytes (2840 MB) up to 2977955840 bytes (2840 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	openmodscore{0.11.5} [OpenModsLib Core] (minecraft.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.11.0} [InfinityLib] (infinitylib-0.11.0.jar) 
	UCHIJAAAA	agricraft{2.0.0-0.11.0-a21} [AgriCraft] (agricraft-2.0.0-0.11.0-a21.jar) 
	UCHIJAAAA	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.87-mc1.10.2-beta.jar) 
	UCHIJAAAA	animania{1.4.4} [Animania] (animania-1.10.2-1.4.4.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	AppleCore{3.1.0} [AppleCore] (AppleCore-mc1.10.2-3.1.0.jar) 
	UCHIJAAAA	appleskin{1.0.9} [AppleSkin] (AppleSkin-mc1.10.2-1.0.9.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UCHIJAAAA	aquaculture{1.4.1} [Aquaculture] (Aquaculture-1.10.2-1.4.1.4.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	BetterSprinting{1.1.7} [Better Sprinting] (BetterSprinting  MC-1.10.2  v1.1.7.jar) 
	UCHIJAAAA	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	UCHIJAAAA	ctm{MC1.10.2-0.2.3.26} [CTM] (CTM-MC1.10.2-0.2.3.26.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.1.1.39} [Chisel] (Chisel-MC1.10.2-0.1.1.39.jar) 
	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.16} [Chisels & Bits] (chiselsandbits-12.16.jar) 
	UCHIJAAAA	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJAAAA	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.183} [Ender IO] (EnderIO-1.10.2-3.1.183.jar) 
	UCHIJAAAA	extraalchemy{0.3.3.1-release} [Extra Alchemy] (extraalchemy-0.3.3.1-release.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.7.3.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (FoamFix-1.11.2-0.7.3-Anarchy.jar) 
	UCHIJAAAA	forestry{5.2.17.388} [Forestry] (forestry_1.10.2-5.2.17.388.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJAAAA	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.33} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.33.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHIJAAAA	lootbags{2.5.0} [Loot Bags] (LootBags-1.10.2-2.5.0.jar) 
	UCHIJAAAA	moreoverlays{1.11} [MoreOverlays] (moreoverlays-1.11-mc1.10.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.5.9} [Mystical Agriculture] (mysticalagriculture-1.10.2-1.5.9.jar) 
	UCHIJAAAA	mysticalagradditions{1.0.4} [Mystical Agradditions] (mysticalagradditions-1.10.2-1.0.4.jar) 
	UCHIJAAAA	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.10.2-1.3.1.jar) 
	UCHIJAAAA	openmods{0.11.5} [OpenModsLib] (OpenModsLib-1.10.2-0.11.5.jar) 
	UCHIJAAAA	openblocks{1.7.5} [OpenBlocks] (OpenBlocks-1.10.2-1.7.5.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	plustic{5.2.1.3} [PlusTiC] (plustic-5.2.1.3.jar) 
	UCHIJAAAA	railcraft{10.3.1} [Railcraft] (Railcraft_1.10.2-10.3.1.jar) 
	UCHIJAAAA	stevescarts{2.2.0.86} [Steve's Carts 2] (StevesCarts-1.10.2-2.2.0.86.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.10.jar) 
	UCHIJAAAA	wanionlib{1.10.2-1.3} [WanionLib] (WanionLib-1.10.2-1.3.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	waystones{2.0.13} [Waystones] (Waystones_1.10.2-2.0.13.jar) 
	UCHIJAAAA	unidict{1.10.2-2.9b} [UniDict] (UniDict-1.10.2-2.9b.jar) 
	Loaded coremods (and transformers): 
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
PlusTiC (plustic-5.2.1.3.jar)
  landmaster.plustic.asm.Transform
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.11.2-0.7.3-Anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
Extra Alchemy ASM (extraalchemy-0.3.3.1-release.jar)
  zabi.minecraft.extraalchemy.asm.PotionTransformer
CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AppleCore (AppleCore-mc1.10.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [pre_world_render_hook:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Games/Minecraft/Instances/Survival%20Mode/mods/plustic-5.2.1.3.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Games/Minecraft/Instances/Survival%20Mode/mods/plustic-5.2.1.3.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Games/Minecraft/Instances/Survival%20Mode/mods/plustic-5.2.1.3.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Games/Minecraft/Instances/Survival%20Mode/mods/plustic-5.2.1.3.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Games/Minecraft/Instances/Survival%20Mode/mods/plustic-5.2.1.3.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Games/Minecraft/Instances/Survival%20Mode/mods/plustic-5.2.1.3.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Games/Minecraft/Instances/Survival%20Mode/mods/plustic-5.2.1.3.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Games/Minecraft/Instances/Survival%20Mode/mods/plustic-5.2.1.3.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Games/Minecraft/Instances/Survival%20Mode/mods/plustic-5.2.1.3.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RF:ON, RFItem:ON, Waila:ON, JEI:ON, THE_ONE_PROBE:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['retracted'/350, l='Survival World', x=-3176.22, y=62.07, z=5045.15]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MauveCloud** [comment]
I think I can clarify what's really going on here, at least with the sheep (I'm not sure about the draft horse).

> at com.animania.entities.sheep.EntityAnimaniaSheep.func_70628_a(EntityAnimaniaSheep.java:566)

I looked at this method and line in jd-gui.  It seems like the method deals with determining what items drop when the sheep dies.  The line in question looks like this:

> woolItem.field_77994_a = (1 + lootlevel);

However, "woolItem" will be null if the sheep has been sheared, and there is no check for that around it.  Also, to crash at that line (rather than 579 or 587), the sheep in question must have been well fed.

**Comment by capnkirok** [comment]
@OmegaDerp thank you for the report.

@MauveCloud Yup, you are correct. I thought this was one of the many DataParameter errors I was receiving, but it's just a simple exposed null. The sheep should not drop wool if sheared already.

Ok, this is fixed in dev and will be in next release.

**Comment by OmegaDerp** [comment]
@capnkirok Glad to know it is getting fixed. Really like having your mod :)
Should I close this ticket?

**Comment by capnkirok** [comment]
I like to leave it open until it's officially released. Thank you for the nice words!

**Comment by OmegaDerp** [comment]
@capnkirok Okay, good to know :) I'll be looking forward to the next update!
