### ISSUE TITLE
Config file comments are all cows

### ISSUE THREAD

**Issue by crittens** [capnkirok/animania#545]
### Expected Behavior
The wrong string is added to the config file above the list of items that mobs can eat.

One would expect "Food Items that *rabbits* can eat ..." comment above S:rabbitFood < ...

### Actual Behavior
It's all cows: "Food Items that *cows* can eat ..." for all mobs.

### Steps to Reproduce
Nothing special.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.4.4, single player

All is fine for 1.11.2, 1.4.4.

**Comment by capnkirok** [comment]
Yep, copy pasta looks like. Shouldn't affect gameplay, but definitely confusing.
