### ISSUE TITLE
Incompatability with Genetics Reborn and Animania

### ISSUE THREAD

**Issue by GeminiMarshdevil** [capnkirok/animania#547]
Incompatability with Genetics Reborn

### Expected Behavior
Cows, chickens, horses, sheep should all be registering as their respective vanilla animal when takeing genes from them using the genetics reborn scrapper

### Actual Behavior
does not do the above

### Steps to Reproduce
load up a modpack with genetics reborn and animania installed and try drawing genes from cows for being able to inject that gene into other animals

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 (suspect this works the same as on any other version)

**Comment by capnkirok** [comment]
Hi @GeminiMarshdevil 

Chickens, horses, and sheep all extend their vanilla counterparts. You'll have to ping the Genetics Reborn people. I'll leave this open, and you can cross-post.

**Comment by GeminiMarshdevil** [comment]
thanks for reply, i found a sloppy work around with simply allowing the vanilla creatures from spawning in aswell as the animania ones.  
check out my other issue report though, rather serious crash problem regarding hamsters (sad sadface hamsters )

**Comment by capnkirok** [comment]
@GeminiMarshdevil saw your other report. Looks like a conflict, as it's working fine for me. It's probably the data parameter corruption issue. But I'll need your crash log (maybe client side?), the one you posted doesn't refer to Animania.

**Comment by MauveCloud** [comment]
There is already a related issue for Genetics Reborn: https://github.com/TheUnderTaker11/GeneticsReborn/issues/38

Also, I found in the code where the data is picked out to be added to the organic matter produced by the scraper, in such a way that extending the classes for vanilla animals doesn't make much difference:
https://github.com/TheUnderTaker11/GeneticsReborn/blob/master/src/main/java/com/theundertaker11/GeneticsReborn/event/RightClickEntityEvent.java#L80-L81
