### ISSUE TITLE
Cheese mold can't be placed on ground - Homestead Modpack - Animania 1.4.3

### ISSUE THREAD

**Issue by MarikOfAces** [capnkirok/animania#548]
### Expected Behavior
Right click with cheese mold while targeting ground places cheese mold on ground

### Actual Behavior
Right clicking with cheese mold does nothing.

### Steps to Reproduce
Using the Homestead modpack on the AT launcher,
Load single player and right click on ground with a cheese mold.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.10.2, Animania 1.4.3, Singleplayer. (Using the Homestead modpack on the ATLauncher)

**Comment by capnkirok** [comment]
Cheese Mold is not placed on ground in 1.10, that's a 1.11/1.12 feature.

![image](https://user-images.githubusercontent.com/9628379/35821781-7102c1fe-0aaa-11e8-8d56-75b1cf5bf3f3.png)
