### ISSUE TITLE
Missing Animal Models w/ Valkyrien Warfare

### ISSUE THREAD

**Issue by WenXin20** [capnkirok/animania#55]
[Valkyrien Warfare v0.8.7-106 Jenkins](https://jenkins.ironhide.de/job/Valkyrien-Warfare-Revamped/changes)
Animania v1.0.2
It seems that with these two mods combined, causes Animania's animals to have missing models, and instead shows a white cube for the animals.

![2017-03-16_22 07 28](https://cloud.githubusercontent.com/assets/12000593/24027374/15a51af2-0a95-11e7-91fe-27d0a952bb91.png)

**Comment by capnkirok** [comment]
Yeah, that's weird. Can you post on their board? There's nothing strange in our render code, so would put it on them.

**Comment by WenXin20** [comment]
It seems to be fixed in the newest version (v107) of the mod.
