### ISSUE TITLE
Animania wool not directly usable in Animania recipes

### ISSUE THREAD

**Issue by MauveCloud** [capnkirok/animania#552]
### Expected Behavior
Recipes for Animania items that require wool should also accept Animania wool types (e.g. Jacob wool, Merino wool)

### Actual Behavior
Covered Wagon and Nest (which seem to be the only Animania items with recipes that require wool) accept vanilla wool according to JEI, but not Animania wool.

A number of recipes from other mods seem to require vanilla wool instead of ore dictionary "blockWool", but those aren't Animania's responsibility.  (e.g. somebody else posted an issue for Forestry: https://github.com/ForestryMC/ForestryMC/issues/1974, which is what prompted me to check what recipes _would_ take Animania wool)

### Steps to Reproduce
1. Look up usage of Animania wool in JEI, or recipes for Covered Wagon and Nest.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.4.5, Single Player.

**Comment by capnkirok** [comment]
So... the recipe works:
![image](https://user-images.githubusercontent.com/9628379/35849246-36da3544-0b21-11e8-9bc8-fda0f6a80087.png)

And it shows if you search BlockWool:
![image](https://user-images.githubusercontent.com/9628379/35849402-c44d3836-0b21-11e8-9fef-e4e0903c9e04.png)

But it doesn't seem to show when it is flipping through recipes. Would post this to JEI, but I am ok with it.

**Comment by MauveCloud** [comment]
Yes, that works.  However, I'm not certain whether it's really a bug in JEI or something weird you're doing when registering the recipe that makes JEI think you want it to only show with vanilla wool.  The nest is simple enough to craft manually, but the covered wagon (if anyone actually bothers making it - searching the CurseForge page, there doesn't seem to be documentation on what purpose it serves) is a strong candidate for using JEI's "+" button to automatically populate the crafting table.

**Comment by capnkirok** [comment]
Ha ha ha. I love the subtle digs ... "something weird you're doing" ... "if anyone bothers making it"...(not really, by the way, they are kind of insulting)

Here's the JSON. Let me know if you see something... weird...
![image](https://user-images.githubusercontent.com/9628379/35882840-c2f51e40-0b85-11e8-9ee6-659352ef19b9.png)

**Comment by MauveCloud** [comment]
With my full modlist, both the stick and leaves show me an "Accepts any" for the ore dictionary entry.  However, with only Animania, CraftStudio, and JEI, only the leaves show me that (presumably because there are no other sticks in the "stickWood" ore dictionary).  This gives me an idea for why this might be happening.  What is the timing of Animania wool being added to the "blockWool" ore dictionary?  If it happens after JEI has initialized its recipe list, that might explain why JEI doesn't show it as an option.

Sorry about the "subtle digs" 🙁 .  In hindsight, I probably could have worded that better.  My intent was not to be insulting, but rather to make sure we weren't prematurely blaming JEI for something that might turn out not to be that mod's fault.

**Comment by capnkirok** [comment]
Ooh that’s a good one. I can try to force load JEI later.

And your posts are always solid, keep them coming. I just grow weary of fixing things that should just work imo :)

**Comment by capnkirok** [comment]
Ok, turns out it doesn't matter whether it loads before or after JEI. After looking at the code, I'm convinced that it's because "blockWool" doesn't have an official entry in Forge's OreDictionary, unlike Leaves and Sticks.

**Comment by MauveCloud** [comment]
That's surprising, but I can confirm you are correct - in an instance with only Forge, JEI, and JEI Integration (to show me the ore dictionary details of items/blocks), wool is not registered in the ore dictionary.  Searching a decompiled copy of your mod, it looks like you only register "blockWool", while my 79-mod game also has wool registered as "blockWoolWhite", "blockWoolOrange", etc.  If Forge itself isn't doing that, idk which mod(s) are registering those entries.

**Comment by capnkirok** [comment]
wow.... which mod registered "blockWoolWhite"?
We can also ping Lex and ask him to add blockWool to the forge code.

**Comment by MauveCloud** [comment]
Searching my mods with WinRar, it looks like CodeChickenLib registers blockWoolWhite, etc. (though curiously not "blockWool" - I can get that from CoFHCore or AE2 as well as from Animania, though) - it matched in EnumColour.class (source here: https://github.com/TheCBProject/CodeChickenLib/blob/master/src/main/java/codechicken/lib/colour/EnumColour.java, though I'm not sure it actually does the oredict registration in that class)

**Comment by mezz** [comment]
Lex is not receptive to adding lots of stuff to the ore dictionary.
It will work fine if we just agree as mods that wool should be `blockWool` and both register and use it. 👍

**Comment by capnkirok** [comment]
Sounds like a plan @mezz

**Comment by Deshiba** [comment]
It's a pity this doesnt get standardized by forge. People new to modding might not know what the  (unspoken rule) standard is.

**Comment by capnkirok** [comment]
I'm going to close this one. But if you see this happening, please ping the respective mod authors and get them to change their recipes to include oreDictionary version of blockWool

**Comment by glindsey** [comment]
Let me just say I am _so_ happy to help standardize things across mods... it really touches that part of me that loves to organize things. If I had more free time and my Java wasn't so rusty I'd love to help with the actual coding! 😅
