### ISSUE TITLE
vanilla foods barely filling hunger

### ISSUE THREAD

**Issue by EternalShadow17** [capnkirok/animania#553]
### Expected Behavior
vanilla steak fill 8 hunger

### Actual Behavior
vanilla steak only filling 2 hunger

### Steps to Reproduce

eat
### Version of Minecraft, version of Animania, Single Player or Server
minecraft 1.12.2, animania 1.4.5, single player

**Comment by EternalShadow17** [comment]
just found out pams harvestcraft was causing this. sorry for the inconvenience

**Comment by capnkirok** [comment]
Thank goodness :) I was worried I'd broken something else...

**Comment by EternalShadow17** [comment]
Nope, just me being stupid haha
