### ISSUE TITLE
Make Through to accept fluiducts

### ISSUE THREAD

**Issue by hron84** [capnkirok/animania#554]
### Expected Behavior

When I place a fluiduct next to an empty Through, it should connect to it and I'd be able to send water to it

### Actual Behavior

Fluiduct does not connect

### Version of Minecraft, version of Animania, Single Player or Server

Minecraft: 1.10.2
Animania: 1.4.5
SSP / SMP

**Comment by capnkirok** [comment]
I doubt we'll go back and do this for 1.10 a this point (it's a lot of work)... sorry to say

**Comment by hron84** [comment]
@capnkirok so it works with later versions? In the same time, which is the best way to automate troughs? Water bucket is allowed to pick up the water, but I'm unsure to check it with a comparator... 

Currently, I use an XU mechanical user to fill it, but to not place-pickup the water constantly, it needs proper timing.

**Comment by capnkirok** [comment]
Yes, fluiducts work on 1.11 and 1.12, @Tschipp did the code there. And yes, you should be able to use a comparator on all versions.

**Comment by capnkirok** [comment]
(closing ... )
