### ISSUE TITLE
Shoulder hamster turns invisible on Minecraft relaunch

### ISSUE THREAD

**Issue by MauveCloud** [capnkirok/animania#557]
### Expected Behavior
A tamed hamster riding my shoulder should remain visible after relaunching Minecraft.

### Actual Behavior
Relaunching Minecraft causes a shoulder hamster to become invisible.  At first I thought it had been deleted (switching perspective with F5 didn't reveal it to be there), but when I went to tame another one, it popped out when I started to pick up the new one, so after a moment I figured out the original one had still been there, just invisible.  Another relaunch test revealed that I could put it down and pick it up again to make it reappear on my shoulder.

### Steps to Reproduce
1. Tame a hamster.
2. Pick it up to your shoulder.
3. Exit Minecraft.
4. Relaunch Minecraft.
5. Enter your world.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.4.5, Single Player
Confirmed to still happen with bare minimum mods (Animania, CraftStudio API, JEI)

**Comment by capnkirok** [comment]
Fixed by @Tschipp
