### ISSUE TITLE
Killing by entity type not working

### ISSUE THREAD

**Issue by notfood** [capnkirok/animania#560]
I have an overpopulation problem eating my tps and the kill command with selector isn't helping.

/kill @e[type=animania:mare_draft]

### Expected Behavior
Kill the 500 horses.

### Actual Behavior
Error in selector, unable to run it.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft Server 1.12.2
Animania 1.12.2-1.4.5

**Comment by capnkirok** [comment]
That command worked for me...

Is it giving you an error, or is it just because of all the lag?

![2018-02-13_18 56 00](https://user-images.githubusercontent.com/9628379/36165375-a69c7698-10ef-11e8-9c97-1ae0ed025d3e.png)

**Comment by notfood** [comment]
Interesting, must be Spongeforge messing with it.
