### ISSUE TITLE
[Suggestion] Peafowl drops

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#561]
Currently peafowl only drop feathers. But like most poultry they are also hunted for their meat much like Pheasants and Quails. I would suggest adding these meats, if there is a cultural stigma involved it could be handled like the horse issue #231 
https://en.wikipedia.org/wiki/Poultry#Examples

~~A second suggestion, please make the peafowl drop their fathers randomly like chickens currently do so I don't HAVE to kill them. Peafowl shed their plumage in real life too: https://animals.howstuffworks.com/birds/peacock-feathers.htm~~

**Comment by capnkirok** [comment]
Yes, agree.

**Comment by capnkirok** [comment]
This was was added in 1.5.1 Of course, you won't be able to cook them until 1.5.2, but the drops are there!
