### ISSUE TITLE
Horse Mobs crashing clients who connect to server.

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [capnkirok/animania#562]
### Expected Behavior
Not crash joining clients with ticking entity

### Actual Behavior
Crashes the client who joins SMP (Open-LAN connect or Direct Connection to dedicated servers)
`Ticking Entity
at com.animania.common.entities.horses.EntityAnimaniaHorse.getColorNumber(EntityAnimaniaHorse.java:337)
at com.animania.common.entities.horses.EntityMareBase.func_70636_d(EntityMareBase.java:509)`

`-- Entity being ticked --
Details:
	Entity Type: animania:mare_draft (com.animania.common.entities.horses.EntityMareDraftHorse)
	Entity ID: 68616
	Entity Name: Draft Horse Mare`

[Gist Log/Full Log](https://gist.github.com/Misunderstood-Wookiee/9ee2b0638551393a702604f1b8c5e5a4)

### Steps to Reproduce
I don't know sorry? This issue does not affect how I am playing the game. 
Just when players join the LAN server locally or via internet their clients crash while I start the game from SP and enable open-to-LAN and I don't crash it works for me.

I suspect this is something related with how ticking entity is ticked to the clients who join SMP
or maybe it is MoCreatures, but I doubt this. The only solution to fix this for me is to turn off the prob for an animania horse to spawn and then butcher ALL the horses around the effected area. 

If you want to have a crack to produce it even tho you failed with the hamsters, just start up a SP world throw a ton of horeses around in a chunk make sure entityremoval is turned off then join that world with another client by opening your SP world to LAN or you can just throw up a forge server, I don't think it even effects local joins because I tested this with SMP and dedicated server local hosted, for SMP I just start the world in SP and no crash, if I join my local dedicated server running the same modpack via `localhost:port` no crash!

>  it only crashes everyone else who joins over network or internet.

### Version Information & Single Player or Server
Minecraft: `1.12.2`
Forge `14.23.2.2611`
Animania: `1.4.4`
_Server/Local World_

### Screenshots encouraged
There is nothing to screenshot

**Comment by ElvenChaos** [comment]
@Misunderstood-Wookiee First, you are one version behind on animania, try updating it. After that, if horses are still crashing you, you can either set `B:spawnAnimaniaHorses=false` and delete/re-create your world, or you can possibly find what other entity-creating mod is causing the corruption of animania entities. It could be any that do so; mo creatures, ice and fire, minecolonies, or steve's carts, looking at your log.

**Comment by Misunderstood-Wookiee** [comment]
@ElvenChaos 
Okay thanks, Yea I read the other report about hamsters so it appears the only way to get rid of it for all time is too figure out which entity adding mod is the issue by installing just those and find out which is the problem and remove that or fix it.

**Comment by ElvenChaos** [comment]
Until the entity-rewrite is finished, pretty much. You can either remove the affected mob from animania, or the affecting mod from your pack.

**Comment by Misunderstood-Wookiee** [comment]
@ElvenChaos 
I read that this issue can be fixed pretty easily by wrapping the mobs in a  `try` catch and discard it rather than let it go unhandled it's not the best fix but it works according to the developer of Lycenite's mobs  the problem seems to occur when two mods attempt to use the same data names then the client gets the wrong packet and responds with something which is not for that mod and obviously the code is not what was expected in return so it crashes. 

This really a Forge issue, as mods need to be uniquely identifiable to avoid the mix up on the client end. 

Yes I was able to fix this issue, by butchering any mob which got corrupted and it can happen anytime with multiple modded mobs or tile entities.  It is possible to actually spawn the animal again and not get a corrupted one but it's a mixed bag really and it's safer to just disable the animal which is affected like you suggested until a better workaround can be made.  I don't think re-writing the entity is going to fix the problem, it might but only until another mod conflicts with new names.  

If you guys are re-writing the entities I suggest doing what Lycenite did and encapsulate the entity with a `try` and handle the error instead of it causing an exception error causing the client the crash.

I don't know much Java yet myself or I would fix this in all the entity mods I have and use my own builds I suppose somebody could write a core mod which affects all entities and which pass through Forge classes and write the try catch directly into that so every mod is fixed ???

**Comment by capnkirok** [comment]
Per other thread, trying out this 'patch solution' today.

**Comment by capnkirok** [comment]
Lycanite's Data Parameter Try/Catch Example found here:
https://github.com/Lycanite/LycanitesMobs/blob/29d85172fc2b87e3d1e3d741c11558bff8708204/src/main/java/com/lycanitesmobs/core/entity/EntityCreatureBase.java#L509

**Comment by capnkirok** [comment]
See test link at bottom of this thread:
https://github.com/capnkirok/animania/issues/550

**Comment by capnkirok** [comment]
Fixed in next release
