### ISSUE TITLE
[Suggestion] More Animal Ideas...

### ISSUE THREAD

**Issue by glindsey** [capnkirok/animania#563]
Just wanted to put a few suggestions out here for more animal types:

- Cats: Just saying this because my daughter adores them, and there doesn't seem to be any other mod out there that adds them.
- Aquatic Animals: 1.13 is due to add a ton of aquatic life to the game, but will probably also totally break just about every mod out there due to the infrastructure changes it's making. So I'm suggesting various aquatic lifeforms get added to Animania, because oceans filled with nothing but squid gets awfully boring!
- Koalas/Pandas: I only mention them because I've been playing our server lately, stumbling across Bamboo Forests and Eucalyptus trees, and thinking about how great it would be to have either of these in the game.

That's about it! Keep up the absolutely fantastic work!

**Comment by Deshiba** [comment]
Not to be rude, but your suggestions have been suggested.
* Cats are already on the upcoming features list, the list can be found on the forums or curseforge
* Aquatic animals have been discussed on #31, #123 and #179 
* Bears and koalas have been suggested in #423

**Comment by glindsey** [comment]
I’m sorry, you’re right of course. I should’ve done a search prior to my post. I’ll close this guy out.

**Comment by Deshiba** [comment]
@glindsey All thoughts are appreciated, they make the mod better. You care enough to comment, much love!
