### ISSUE TITLE
Creative tab duplicates

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#564]
### Expected Behavior
I expect resources to only be found in 1 creative tab

### Actual Behavior
Anything in a bucket is on both the "Animania Resources" and Minecrafts' "Miscelanious" tabs 

### Steps to Reproduce
Create and/or open a creative world
Open the creative tab menu

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2, Animania: 1.4.5

**Comment by capnkirok** [comment]
Yeah, this one is bc of Forge Bucket. Could hide it on Animania Resources, but I don't think that's ideal.

**Comment by capnkirok** [comment]
Going to close this one since there's nothing I can do at the moment. ForgeBucket needs some improvements imo.
