### ISSUE TITLE
Creative tab food inconsistency

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#565]
### Expected Behavior
For all foods to be in either Animania Resources or Foodstuffs 

### Actual Behavior
Regular meat and cooked meat are in the minecraft "Foodstuffs" tab. Prime meat and Cooked Prime meat are in the "Animania Resources" tab.

### Steps to Reproduce
Create and/or open a creative world
Open the creative tab menu

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2, Animania: 1.4.5

**Comment by capnkirok** [comment]
Yeah, I never know where to but these things. I like the keep the Animania stuff in one area. Could put them in both...

**Comment by Deshiba** [comment]
I'd keep them in the animania tab.

Imagine if all mods put their foods in foodstuff, between animania and pam's harvestcraft you'd be unable to find anything.

**Comment by capnkirok** [comment]
It actually should hide the 'breed' drops unless the option is ticked in the config.
