### ISSUE TITLE
Edible Truffles

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#566]
### Expected Behavior
Truffles to be edible in raw form

### Actual Behavior
Truffles can't be eaten raw

### Additional Info
Most truffle species [can be eaten raw](https://en.wikipedia.org/wiki/Truffle#Culinary_use). It would be justified to be able to eat them in the game as well.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#145
