### ISSUE TITLE
[Suggestion] Wolf/Dog and Cat/Ocelot breeds

### ISSUE THREAD

**Issue by vpontin** [capnkirok/animania#567]
Are this planned?

For reference, there was a good mod who added this back in 1.7 ([Here](https://minecraft.curseforge.com/projects/style) is its curse page).

**Comment by Deshiba** [comment]
Yes, and yes. These are both in the planned features section on curseforge and the Minecraft forum post. Working dogs and cats are incoming.

**Comment by capnkirok** [comment]
Going to close this one. Thanks for the feedback!
