### ISSUE TITLE
Playing this with the new version of Thaumcraft

### ISSUE THREAD

**Issue by madkingdiamond** [capnkirok/animania#568]
### Expected Behavior
Rabbits drop hide

### Actual Behavior
Rabbits do not drop Rabbit Hide, needed for Thaumcraft 6

### Steps to Reproduce
Made a Spawner using Woot on all types of rabbits and no hide

### Version of Minecraft, version of Animania, Single Player or Server
1.10.2 , 1.4.5, Server

### Screenshots encouraged
Not really needed

**Comment by capnkirok** [comment]
You are the second player to ask for this, so will have to add a third option via config for rabbits.

In the short term, you can:
- Enable Vanilla Rabbits
- Modify one of the drops for rabbits already (feet for instance)
- Use In Control (mod) to modify/add drops

**Comment by Tschipp** [comment]
We need to do loottables and end this once and for all

**Comment by capnkirok** [comment]
We'd have to make our own. Forge doesn't support loot tables for custom entities.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#146
