### ISSUE TITLE
Overspawning still occurs, though at a reduced rate

### ISSUE THREAD

**Issue by crittens** [capnkirok/animania#569]
### Expected Behavior
Finite goats.

### Actual Behavior
(Approximately) infinite goats. :)

### Steps to Reproduce
(1) Install a large number of mods besides Animania.
(2) Wait
(3) Count goats.

The number of mods and the amount of time to be able to detect an incipient goat-splosion makes it impossible to determine if there's some sort of inter-mod interaction going on, sorry.

I do have infernal mobs, zombie awareness, and webshooter, though those should only affect hostiles.  I also have better agriculture though, as well as tough as nails, hence the frozen pond referenced below.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.4.5, single player.

### Screenshots encouraged
Imagine a hundred goats all gathered around a frozen pond in winter. I guess they're thirsty?

Maybe it is an inter-mod issue but not a bug. All goats go to the frozen pond, fail to drink, stay and run into all the other goats. Ain't got nuthin' better ta do but get jiggy wit it then, hence lots of baby goats, who become breeding adult goats?

**Comment by crittens** [comment]
They are not all kids. Most are does (80%). Kids are 5% or so.

I killed all the angoras but that just left the 'ecological niche' open for the Nigerian dwarfs. Just had to kill them too. The Nigerians were mostly does too, again about 80%.

Will try all the other things and let you know.

**Comment by capnkirok** [comment]
Hey @crittens please check out version 1.4.7 when it is out.
