### ISSUE TITLE
[suggestion] small animal cage

### ISSUE THREAD

**Issue by Zygus42** [capnkirok/animania#57]
Would be great if there was a hand-held cage which you right clicked on small mobs (chicken, hamster, ferret) to capture them and were then able to release them again elsewhere.  I just can't see using a lead to catch hamsters and bring them back to your base !  I would make the cage out of iron bars with the same recipe as a wooden chest.

**Comment by capnkirok** [comment]
That's a great idea. Or something like it. Definitely need an easier way to port animals.

**Comment by Zygus42** [comment]
Yep, although I did find some cute hamsters a LONG way away in a jungle, and had a good old laugh at the idea of leashing them and dragging them many 1000s of blocks away :)

**Comment by Guinaro** [comment]
Can we maybe somehow implemented this with a luring system?
Like you place a cage, need to place enticing foor inside and wait to snap the trap, by yourself (holding a rope/lead) or having the trap close automatically catching the animal.

**Comment by OreCruncher** [comment]
I like the trap idea.  Player can then break the trap block to get the trap/animal in their inventory, and then they would have to place again to get the animal out.  There could be a variety of different sizes/kinds of traps to depending on the animal being trapped.  A lot of fun could be had trying to get a bear out of a large bear trap...

**Comment by 19nrussell** [comment]
This does not really deal with small animals but  possibly another way of transporting large animals in the future .Like a trailer, something that can carry large and or more quantity of animals .

**Comment by capnkirok** [comment]
Yes, I completely agree need a better way to capture and transport large animals (other than a lead)

**Comment by Tschipp** [comment]
Mhh yes but what would that be? Can't be trailers, because Minecraft doesn't have cars. I personally think leads are just fine. You shouldn't be able to put a cow inside an item and carry it around. Doesn't feel right. @capnkirok

**Comment by 19nrussell** [comment]
Maybe there is a way after other things are in to maybe see if someone has a mod like trailers and do similar to with the hamsters possibly

**Comment by OreCruncher** [comment]
Giant hamsters that can serve as a mount as well as pull carts...

**Comment by 19nrussell** [comment]
since I know I have herd about carts is there any way that maybe a cart could be used like a trailer and could be pulled by the horses  that to me seems realistic 
<3 Loving the mod and how realistic it is since I'm a farm girl.  <3

**Comment by Tschipp** [comment]
This handheld cage idea has been moved to a separate mod, [CarryOn](https://minecraft.curseforge.com/projects/carry-on)
