### ISSUE TITLE
[1.10.2] Client-side crash when seeing a hamster

### ISSUE THREAD

**Issue by ASpieler** [capnkirok/animania#571]
Anything other than a random crash upon seeing a hamster

client-side crash, as soon as a hamster comes into view

load a client with version 1.10.2-1.4.5 and look for a hamster

Minecraft 1.10.2, forge 2488, Animania 1.10.2-1.4.5

i initially thought one of my players had a corrupted copy of your mod, when she told me a hamster had crashed her,  but no, i tp'ed to her location and crashed as soon as it came into render range.

pertinent info from the stacktrace:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.animania.entities.rodents.EntityHamster.isHamsterSitting(EntityHamster.java:870)

if you think you need my mod list, say so, but this looks like an internal issue, as no other mod is going to be futzing with your hamster's sitting state

**Comment by capnkirok** [comment]
Take a look at my github, you'll see this issue listed no less than 8 times. You would be surprised, but it's not my mod. And other mods do mess with data parameters of entities. However, I can put error trapping in.

There is no way I could ever try to cast an Integer as a Boolean. The mod wouldn't compile.

See #550 for full story.

**Comment by capnkirok** [comment]
Update should be out in the next 24 hours. I will be so happy when this is not my issue anymore.

**Comment by ASpieler** [comment]
i did check the github, the closest thing i found was an issue with the 'age' parameter, with exactly the same typecast

**Comment by capnkirok** [comment]
Yeah, these are all the same.
