### ISSUE TITLE
Textures stay after mod is removed

### ISSUE THREAD

**Issue by tinymollydogg** [capnkirok/animania#572]
### Expected Behavior

The textures of the chickens, cows, and pigs should return to the default Minecraft ones.
### Actual Behavior

The textures of the Animania mod stay, even though I removed the mod from my mods folder.

### Version of Minecraft, version of Animania, Single Player or Server

Minecraft Version 1.12.2, Animania 1.12.2, Single Player
### Screenshots encouraged
![2018-02-20_10 35 31](https://user-images.githubusercontent.com/36670701/36433930-5e76670a-1623-11e8-990f-496ca295d6f7.png)

**Comment by Deshiba** [comment]
When you removed animania, did you remove craft studio too?

**Comment by wamc2017** [comment]
Isn't this one of the random animal textures from the Quark mod?

**Comment by capnkirok** [comment]
If you've removed the mod, there's no way the textures can remain. Plus that's not our model, so I know that isn't ours.

**Comment by capnkirok** [comment]
I'm closing this one, it's not ours.
