### ISSUE TITLE
[Suggestion] JourneyMap compatibility

### ISSUE THREAD

**Issue by DeymorSalk** [capnkirok/animania#573]
Animals do not appear on the map.
--------------------------------------
Os animais não aparecem no mapa.

**Comment by MauveCloud** [comment]
Are you sure about that?  I've had them appear on JourneyMap, but they get generic dots even if I set JourneyMap to use small/large icons, and that can be changed: https://journeymap.info/Custom_Mob_Icon_Sets

**Comment by Deshiba** [comment]
I Don't think there are custom Icons yet. Maybe making them and adding journeyMap support  could be a thing.

It'd also be nice to have for the wiki

**Comment by capnkirok** [comment]
Custom Journey Map icons would be nice @DeymorSalk :)

**Comment by Deshiba** [comment]
Extra info, these have been requested before in #155

**Comment by capnkirok** [comment]
Never hurts to ask again :)

**Comment by Deshiba** [comment]
Working on the icons now. Pigs are done, at this rate ETA should be 3 to 10 days

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#147
