### ISSUE TITLE
[Optimization] Potentially Add "Cooldowns" to AI behaviour

### ISSUE THREAD

**Issue by ElvenChaos** [capnkirok/animania#574]
### Description
_I'm aware you have been working on re-writing the animal code, and I don't know how it will affect the below issue, or visa versa._

If you get a large number of random Animania animals trapped in a pool of water (this happened naturally for me due to world gen around my testing grounds), the animals ALL start trying to leave the pool constantly due to their natural need for food or other AI triggers, even though they can't find a way out. This causes a huge drop in TPS. It doesn't help that thirsty animals will either go into a pool they can't escape, or spawn in a surrounding grass block inside the pit.

There should be some kind of "cooldown" or "stop, and try again in a few seconds" to these behaviors, or even just a way to only scan for changes in the surrounding terrain instead of trying to re-path constantly.

### Expected Behavior
No party animals drinking up all the TPS.

### Actual Behavior
_POOL PARTY!_

### Steps to Reproduce
Create a pool deep enough that animals can't escape. Spawn animals until they are evenly spread across the surface.

### Version of Minecraft, version of Animania, Single Player or Server
MC: 1.12.2
Animania: 1.4.5
SSP, could also affect SMP.

**Comment by capnkirok** [comment]
Ahhh.... yes. I actually put in the AI that they should try to leave the water, because for some reason, default MC AI leaves them bobbing in lakes. But, there is no timer on that.

**Comment by ElvenChaos** [comment]
Hey! Animals need to bathe every now and again too! :P

**Comment by capnkirok** [comment]
Ok, this should be much improved in the next release. Was just as I explained above.
