### ISSUE TITLE
[SUGGESTION] Replace Vanilla Horses

### ISSUE THREAD

**Issue by Kitsufoxy** [capnkirok/animania#575]
I'm not sure if this is planned, but it's at least not on the list.

I'd like to see vanilla horses replaced with improved horses that behave more like the the drafts, and are adapted to the Animania breeding systems, which I adore. I think it would be a great counterpart to the addition of Ponies and the existence of draft Horses. (maybe in addition to ponies, also do Mini Horses, just because minis are awesome and every world needs more equines).

Thank you for all your hard work on this awesome mod!

**Comment by capnkirok** [comment]
Thanks @Kitsufoxy ! Yes, it's on the list. Thank you for the suggestion. It might take a bit... but we will get there :)

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#148
