### ISSUE TITLE
Draft horses still require the crop to ride

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#576]
### Expected Behavior
For the riding crop to not be necessary in 1.4.5 and 1.4.6 as stated in 1.4.4 update announcement 

### Actual Behavior
You still need the riding crop in 1.4.5 and 1.4.6

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft version 1.12.2, Animania 1.4.5 and 1.4.6, Single Player

**Comment by capnkirok** [comment]
Yeah, you are right. Need to get those saddles in. It's listed as a feature, but I'll leave it up here :)

**Comment by capnkirok** [comment]
This is done on 1.11 and 1.12, (and currently live i 1.4.7), but 1.10 is presenting some new problems.

**Comment by capnkirok** [comment]
I'm actually closing this one. 1.10 has very few downloads so we'll be stopping update soon.
