### ISSUE TITLE
[Suggestion] Giraffes, Elephants and Alpacas

### ISSUE THREAD

**Issue by CreamyHorse** [capnkirok/animania#577]
I would like to see some new animals and there are some suggestions:

Giraffes: I would like to see giraffes been add to the mod, tameable?

Elephants: I know they are not farm animals, but I think it will be a good idea to add in the mod that players can tame and ride them, and they can help player attack monsters and enemies. 

Alpacas: Same behavior with vanilla llamas...?

**Comment by CreamyHorse** [comment]
Also Ducks and Goose?

**Comment by Deshiba** [comment]
I'm sure these have been sugested already.

**Comment by CreamyHorse** [comment]
Ok, its very interesting lol. I saw many animals such as pigs, cows, chickens even goats and sheeps has different breed and I think that is what this mod all about, Good job XD I think horses and donkeys also needs more breeds instead of just Draft horses, I would also likes to see some breeds like: 
pony
miniature donkey
hinny
zebra

**Comment by Deshiba** [comment]
Zebras and ponies are allready inc. So are donkeys

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#149
