### ISSUE TITLE
New Cow Breeds Don't Have Achievements

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#580]
I'm not sure if you just haven't gotten around to adding them yet, or maybe you forgot, but the new cow breeds don't have achievements for taming them yet.

**Comment by capnkirok** [comment]
Yeah, just forgot 😝

**Comment by RaliaTheWolf** [comment]
Ah, okay! Glad I mentioned it then! ^^

**Comment by capnkirok** [comment]
Ok, fixed. Was only an issue on 1.11. Next release :)

**Comment by RaliaTheWolf** [comment]
Awesome! ^^
