### ISSUE TITLE
[1.10.2-1.4.6]animania has a serious server mistake

### ISSUE THREAD

**Issue by MrSeven590** [capnkirok/animania#582]
### Expected Behavior
stop server
### Actual Behavior
load new map

### Steps to Reproduce
server load new map

### Version of Minecraft, version of Animania, Single Player or Server
1.10.2-1.4.6
Server

---- Minecraft Crash Report ----
Time: 18-2-24 6:13pm
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:244)
	at org.spongepowered.common.world.gen.populators.AnimalPopulator.populate(AnimalPopulator.java:51)
	at org.spongepowered.api.world.gen.Populator.populate(Populator.java:101)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:230)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3543)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:819)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:764)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3491)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Random.nextInt(Unknown Source)
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:244)
	at org.spongepowered.common.world.gen.populators.AnimalPopulator.populate(AnimalPopulator.java:51)
	at org.spongepowered.api.world.gen.Populator.populate(Populator.java:101)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:230)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3543)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:819)

-- Sponge CauseTracker --
Details:
	Cause Stack: /*********************************************************************/
/*   - Phase: GeneralGenerationPhaseState{id=WORLD_SPAWNER_SPAWNING} */
/*     Context:                                                      */
/*     - Name: CapturedBlocks                                        */
/*       Object: CapturedBlocksSupplier{Captured=0}                  */
/*     - Name: CapturedEntities                                      */
/*       Object: CapturedEntitiesSupplier{Captured=0}                */
/*     - Name: World                                                 */
/*       Object: WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld} */
/*     - Name: Source                                                */
/*       Object: WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld} */
/*   - Phase: PopulatorGenerationPhaseState{id=POPULATOR_RUNNING}    */
/*     Context:                                                      */
/*     - Name: World                                                 */
/*       Object: WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld} */
/*     - Name: PopulatorType                                         */
/*       Object: SpongePopulatorType{id=minecraft:animal, name=animal, modid=minecraft} */
/*     - Name: CapturedEntities                                      */
/*       Object: CapturedEntitiesSupplier{Captured=0}                */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}     */
/*     Context:                                                      */
/*     - Name: World                                                 */
/*       Object: WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld} */
/*     - Name: CapturedBlocks                                        */
/*       Object: CapturedBlocksSupplier{Captured=0}                  */
/*     - Name: CapturedEntities                                      */
/*       Object: CapturedEntitiesSupplier{Captured=0}                */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}     */
/*     Context:                                                      */
/*     - Name: CapturedBlocks                                        */
/*       Object: CapturedBlocksSupplier{Captured=0}                  */
/*     - Name: CapturedEntities                                      */
/*       Object: CapturedEntitiesSupplier{Captured=0}                */
/*     - Name: World                                                 */
/*       Object: WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld} */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}     */
/*     Context:                                                      */
/*     - Name: Source                                                */
/*       Object: WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld} */
/*     - Name: World                                                 */
/*       Object: WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld} */
/*     - Name: CapturedBlocks                                        */
/*       Object: CapturedBlocksSupplier{Captured=0}                  */
/*     - Name: CapturedEntities                                      */
/*       Object: CapturedEntitiesSupplier{Captured=0}                */
/*********************************************************************/

Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zhp000(MinecraftServer.java:3953)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:503)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2043018240 bytes (1948 MB) / 3039821824 bytes (2899 MB) up to 3039821824 bytes (2899 MB)
	JVM Flags: 2 total; -Xms2G -Xmx3G
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2477 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2477-universal.jar) 
	UCHIJAA	Forge{12.18.3.2477} [Minecraft Forge] (forge-1.10.2-12.18.3.2477-universal.jar) 
	UCHIJAA	spongeapi{5.2.0-SNAPSHOT-c675e80} [SpongeAPI] (minecraft.jar) 
	UCHIJAA	sponge{1.10.2-2477-5.2.0-BETA-2793} [SpongeForge] (spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar) 
	UCHIJAA	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.87-mc1.10.2-beta.jar) 
	UCHIJAA	animania{1.4.6} [Animania] (animania-1.10.2-1.4.6.jar) 
	UCHIJAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAA	AppleCore{3.1.0} [AppleCore] (AppleCore-mc1.10.2-3.1.0.jar) 
	UCHIJAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.18.jar) 
	UCHIJAA	coroutil{1.10.2-1.1.18} [CoroUtil Library] (coroutil-1.10.2-1.1.18.jar) 
	UCHIJAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.18.jar) 
	UCHIJAA	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	UCHIJAA	ichunutil{6.5.0} [iChunUtil] (iChunUtil-1.10.2-6.5.0.jar) 
	UCHIJAA	IC2{2.6.254-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.254-ex110.jar) 
	UCHIJAA	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.10.2.jar) 
	UCHIJAA	mobamputation{6.0.0} [MobAmputation] (MobAmputation-1.10.2-6.0.0.jar) 
	UCHIJAA	morefood{1.17} [More Foods] (more-foods-1.10.2-2011-1.17.jar) 
	UCHIJAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAA	SpiceOfLife{1.3.11} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.11.jar) 
	UCHIJAA	teastory{2.1.1.1} [Tea: The Story] (TeaStory 2.1.1.1 1.10.jar) 
	UCHIJAA	ToughAsNails{1.1.1.66} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.66-universal.jar) 
	UCHIJAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
	UCHIJAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAA	zombieawareness{1.10.2-1.11.8} [Zombie Awareness] (zombieawareness-1.10.2-1.11.8.jar) 
	UCHIJAA	blockaction{1.11} [BlockAction] (BlockAction-1.11-API5.x.jar) 
	UCHIJAA	catclearlag{0.8} [CatClearLag] (CatClearLag-0.8.jar) 
	UCHIJAA	deathpenalty{v1.1} [DeathPenalty] (deathpenalty-v1.1.jar) 
	UCHIJAA	economylite{2.12.0} [EconomyLite] (EconomyLite-5.0.0-2.12.0.jar) 
	UCHIJAA	foxcore{0.10.4-api5.2-222} [FoxCore] (foxcore-0.10.4-api5.2-222-server.jar) 
	UCHIJAA	foxguard{0.20.idk-api5.2-371} [FoxGuard] (foxguard-0.20.idk-api5.2-371-server.jar) 
	UCHIJAA	inspector{0.6.4} [Inspector] (Inspector-0.6.4.jar) 
	UCHIJAA	latch{0.4.6} [latch] (latch-0.4.6-s5.2.0.jar) 
	UCHIJAA	nucleus{1.1.10-LTS-COMMUNITY-S5.1} [Nucleus] (Nucleus-1.1.10-LTS-COMMUNITY-S5.1-MC1.10.2-plugin.jar) 
	UCHIJAA	payday{1.1.0} [PayDay] (PayDay-1.1.0-1.1.0.jar) 
	UCHIJAA	customcommands{1.0} [CustomCommands] (PermissionManager-2.6.0-API-5.X-6.X.jar) 
	UCHIJAA	permissionmanager{2.6.0} [PermissionManager] (PermissionManager-2.6.0-API-5.X-6.X.jar) 
	UCHIJAA	placeholderapi{4.4} [PlaceholderAPI] (PlaceholderAPI-4.4.jar) 
	UCHIJAA	pjp{0.13.6} [ProjectPortals] (projectportals-5.1.0-0.13.jar) 
	UCHIJAA	statusprotocol{0.3} [StatusProtocol] (statusprotocol-03.jar) 
	UCHIJAA	serverlistplus{3.4.8} [ServerListPlus] (ServerListPlus-3.4.8-Universal.jar) 
	UCHIJAA	spongychest{0.4.8} [SpongyChest] (SpongyChest-1.10.2-0.4.8-universal.jar) 
	UCHIJAA	tmotd{1.0} [TitleMOTD] (TitleMOTD.-.1.jar) 
	UCHIJAA	virtualchest{0.4.7} [VirtualChest] (VirtualChest-0.4.7.jar) 
	UCHIJAA	com.gmail.trentech.worldbackup{0.3.5} [World Backup] (worldbackup-4.1.0-0.3.5.jar) 
	UCHIJAA	hungeroverhaul{1.10.2-1.1.0.jenkins118} [Hunger Overhaul] (HungerOverhaul-1.10.2-1.1.0.jenkins118.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.254-ex110.jar)
  
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.66-universal.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
SpongeCoremod (spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
AppleCore (AppleCore-mc1.10.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by MrSeven590** [comment]
Oh, it's my fault,I set these numbers to 0.

**Comment by MrSeven590** [comment]
my server is normal, now 

thank you very much!

**Comment by capnkirok** [comment]
Woot :)

If you want to turn off the animania animals, do it in the game config section (e.g., set 'spawnAnimaniaHorses' to false.)
