### ISSUE TITLE
Unmovable, impervious boat-bulls

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#583]
### Expected Behavior
To be able to kill a bull or break a boat once a bull enters a boat

### Actual Behavior
The boat-bull becomes impervious to any attack, so does the bull-boat

### Steps to Reproduce
Have a bull enter a boat and try to kill the bull or break the boat

### Version of Minecraft, version of Animania, Single Player or Server
This is on the community server razzle hosts
Minecraft:1.12
Animania:1.4.6
Craftstudio:1.0.0
Biomes 'o Plenty: 7.0.01

I also did a single-player test with just animania, the same thing happens
With chickens, peafowl, pigs and frogs (I stopped testing here)  you can break the boat but not harm the animal

Draft horses will not even enter boats.

### Screenshots encouraged
![2018-02-24_13 03 47](https://user-images.githubusercontent.com/10565800/36630260-c5447eb6-1963-11e8-9caa-f23b567c4af5.png)

**Comment by capnkirok** [comment]
Bwa-ha-ha-haha

Amazing. I love this game. 

(on a more serious note, this is probably a hitbox issue)

**Comment by Deshiba** [comment]
Yes, You can actually break the boat if you swim under it. 
Still all animals can't be hurt when they are in a boat.

**Comment by capnkirok** [comment]
So... you can attach a lead to remove the Bull from the Boat. I actually did this so you could add/remove them from Horse Carts. So..... not broken. I think I'm going to leave this as is, so people can carry their animals over water.
