### ISSUE TITLE
[1.12.2 Server Only] Can't cut cheese (or meat)

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#584]
### Expected Behavior
To be able to cut a cheese wheel with a carving knife

### Actual Behavior
After the first cheese wheel the knife becomes unusable

### Steps to Reproduce
Open the game, get cheese, cut it with a knife

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft version: 1.12.2
Animania version: 1.4.6
Crafstudio version: 1.0.0
Decocraft version: 2.5.4
JEI version: 4.8.5.147
Hwyala version: 1.8.23

### Screenshots encouraged
![2018-02-24_20 41 52](https://user-images.githubusercontent.com/10565800/36634376-d6ba1878-19a3-11e8-9ea5-be7566462590.png)

**Comment by capnkirok** [comment]
yeah, this is a bug, but only with the player inventory crafting. works fine with the table.

**Comment by capnkirok** [comment]
If knife has any damage, recipe no longer works (on servers)

**Comment by Deshiba** [comment]
Yep, sorry if it wasn't clear. The first cut works fine.
* "After the first cheese wheel the knife becomes unusable'

**Comment by capnkirok** [comment]
An update to forge broke the 'wildcard' functionality. Finally, an explanation as to why this suddenly broke. Thanks to @Tschipp for finding and for fixing :)
