### ISSUE TITLE
[Bug] Visual glitch with hamsterballed hamster and enchanted items

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#585]
### Expected Behavior
No visual glitches

### Actual Behavior
Visual glitch with enchanted tool when a hamster balled hamster is on the shoulder and the item is equiped.

### Steps to Reproduce
Get an enchanted tool
Get a hamster
Get your hamster in a hamster-ball
Carry the hamster on your shoulder
Equip the enchanted tool

### Version of Minecraft, version of Animania, Single Player or Server
This is on the community server.
Minecraft version: 1.12.2
Animania version: 1.4.6
Crafstudio version: 1.0.0
Decocraft version: 2.5.4
JEI version: 4.8.5.147
Hwyala version: 1.8.23

### Screenshots encouraged
![2018-02-25_10 01 30](https://user-images.githubusercontent.com/10565800/36639723-389e2bd2-1a13-11e8-99a4-06cae9019e30.png)

**Comment by capnkirok** [comment]
Yeah, I need to change a few things with the Hamster Ball. One is that you shouldn't be able to put it on your shoulder at all (which would solve this problem).

**Comment by Deshiba** [comment]
Shift+right click should be used to have the hamster exit the ball. As you stated that would solve this issue

**Comment by Deshiba** [comment]
The glitch happens with just the hamster as well, no ball gives the same effect on enchanted items.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#150
