### ISSUE TITLE
Draft Horses aren't eating from troughs

### ISSUE THREAD

**Issue by JPZF** [capnkirok/animania#586]
Hello, my draft horses can't be ridden because they're hungry and they won't eat from the  trough, I tried to feed them by right-clicking with the food they eat but nothing happens, but I can give them water by right-clicking with a bucket with water, am I doing something wrong? what should I do? I'm tired of waiting for them to eat grass.  Help!

**Comment by capnkirok** [comment]
Yes, this could be a bug. Can you tell me which version of Animania and MC are you using? Can you send me an overhead screenshot of your setup?

**Comment by Deshiba** [comment]
Right now you stil need a riding crop to ride draft horses at all. Are you holding one when you try to mount?

**Comment by capnkirok** [comment]
I'm seeing issues on the latest version of 1.10, but 1.11 and 1.12 are working as intended. Going to see  I can retro fit.

**Comment by capnkirok** [comment]
Ok, I've fixed eating by hand (was a problem on all three versions, due to the change I made to the crop being required). Also, on 1.10, I've updated the AI to match 1.12. In other words, this is fixed in the next version.
