### ISSUE TITLE
Hamsters disappear on server after placing on shoulder

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/animania#588]
### Expected Behavior
Hamsters always stay visible to everyone on server

### Actual Behavior
After placing Hamster on shoulder, others cannot see them (on server)

### Steps to Reproduce
On server environment, place hamster on shoulder, then place back on ground. Other players will not be able to see Hamster.

### Version of Minecraft, version of Animania, Single Player or Server
1.12 observed, on Animania server

**Comment by Deshiba** [comment]
A relog gets them back, seems like a visual glitch.

**Comment by Tschipp** [comment]
Yeah if someone carrying a hamster is already doing that before the player gets rendered by other players, the hamster doesn't show up (Also happens when switching dimensions)
