### ISSUE TITLE
[1.12] Salt creation not working on Server

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/animania#589]
### Expected Behavior
Can pour water into Cheese Mold to make salt

### Actual Behavior
Nothing happens

### Steps to Reproduce
Go on server, pour bucket of water into cheese mold

**Comment by Deshiba** [comment]
I'd like to note that this worked fine for me 5 days ago. This changed after you looked into our spawning/breeding issues

**Comment by capnkirok** [comment]
Interesting....

**Comment by capnkirok** [comment]
Yeah, it's the config on the server. Will make a new one for Razz.
