### ISSUE TITLE
A Few Problems With Rodents

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#590]
So I was playing in the latest version of Animania for 1.11.2 in singleplayer and I found a few bugs...

-Hamster's cheeks don't puff up when fed

-Hedgehogs don't have a sitting animation, so you can't tell if they're sitting unless you walk away from them and they follow you (not sure if this is intentional; I just remember that they had it before)

-Hedgehogs and ferrets don't eat peafowl eggs (once again, not sure if this was intentional)

-"Gotta Go Fast!", "No Go Fastr!!!", and "Feels Bad Man" achievements listed under Minecraft achievements rather than Animania achievements

**Comment by capnkirok** [comment]
Thanks Ralia.

**Comment by capnkirok** [comment]
- Hedgehogs now eat peafowl eggs (1.10 - 1.12)
- 1.11 "special" achievements now show on Animania Page only.

working on other two

**Comment by RaliaTheWolf** [comment]
Huh, that's strange... I don't know if MrCrayfish uses a server or not (I assume not? But I don't know), but I noticed in his second Animania mod showcase that his hamster's cheeks weren't puffing up either. I can double check this in another world; maybe it's like that one world where I had a TON of weird stuff that wasn't messed up in other worlds...
