### ISSUE TITLE
Advancements: Goats

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#592]
### Expected Behavior
I expected for the Goats advancement to be completed when I fed my last goat.

### Actual Behavior
After feeding the 7th goat the goats advancement is not fulfilled.

### Steps to Reproduce
Tame all 7 goats

### Version of Minecraft, version of Animania, Single Player or Server

This is on the community server. 
Minecraft version: 1.12.2 
Animania version: 1.4.6 
Crafstudio version: 1.0.0 
Decocraft version: 2.5.4 
JEI version: 4.8.5.147 
Hwyala version: 1.8.23 
CarryOn version: 1.7 
AppleSkin version: 1.0.9 
FTBLib version: 4.2.5 
FTBUtils version: 4.3.4 
Morpheus version: 3.3.2

### Screenshots
![2018-03-04_12 47 36](https://user-images.githubusercontent.com/10565800/36945170-4bd26d16-1faa-11e8-90d5-f2b833ca296d.png)

**Comment by Tschipp** [comment]
iirc, that last one is a root advancement that cannot be completed

**Comment by Deshiba** [comment]
Shouldn't the root be completed when all the other advancements are done?

**Comment by capnkirok** [comment]
With the new advancement system, I don't know of a way to make a root advancement trigger once the child advancements are all triggered (when they are custom triggers).

**Comment by capnkirok** [comment]
Other than using reflection to access advancements directly :(

**Comment by capnkirok** [comment]
I'm going to leave this as is and see what 1.13 Advancement Improvements look like.
