### ISSUE TITLE
Advancement: Ferrets

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#593]
### Expected Behavior
I expect the advancement to trigger when I feed a ferret chicken because it states "feed a grey/white ferret"

### Actual Behavior
The advancement for taming ferrets only complete when feeding them their favourite foods.

### Steps to Reproduce
Tame a ferret with chicken, then feed it an egg and see when the advancement triggers

### Version of Minecraft, version of Animania, Single Player or Server
This is on the community server.
Minecraft version: 1.12.2
Animania version: 1.4.6
Crafstudio version: 1.0.0
Decocraft version: 2.5.4
JEI version: 4.8.5.147
Hwyala version: 1.8.23
CarryOn version: 1.7
AppleSkin version: 1.0.9
FTBLib version: 4.2.5
FTBUtils version: 4.3.4
Morpheus version: 3.3.2

**Comment by capnkirok** [comment]
Yeah, the way it works in 1.11 and 1.10 is that you just have to feed their favorite food. Right now, only one food is listed in 1.12, whereas we know they eat much more than that.

**Comment by capnkirok** [comment]
Ok, I have added multiple food types for ferrets. I need to do this for the other animals as well.

**Comment by capnkirok** [comment]
Ok, all the animals are in, using the default Animania favorite food values.

**Comment by Deshiba** [comment]
Ty, I suppose 1.13 will change a bunch about advancements. Hopefully making modding life easier.
