### ISSUE TITLE
Purple Peacock drops Peach feathers

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animania#595]
### Expected Behavior
I expect purple peacocks to randomly shed purple feathers

### Actual Behavior
Purple peacocks randomly shed peach feathers

### Steps to Reproduce
Tame a purple peacock and wait till it looses a feather.

### Version of Minecraft, version of Animania, Single Player or Server
This is on the community server.
Minecraft version: 1.12.2
Animania version: 1.4.6
Crafstudio version: 1.0.0
Decocraft version: 2.5.4
JEI version: 4.8.5.147
Hwyala version: 1.8.23
CarryOn version: 1.7
AppleSkin version: 1.0.9
FTBLib version: 4.2.5
FTBUtils version: 4.3.4
Morpheus version: 3.3.2

### Screenshots encouraged
![2018-03-06_09 18 37](https://user-images.githubusercontent.com/10565800/37021402-b3e4944e-211f-11e8-8636-9ecd93b51df3.png)

**Comment by capnkirok** [comment]
Fixed in next release
