### ISSUE TITLE
A Few Bugs To Squish

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#598]
**Expected Behavior**
-Peafowl nests have feathers in them (unless this was removed but to my knowledge it wasn't)
-All the goats are shearable (I actually only tested a few bucks but I assume that all of the goats do this)

**Actual Behavior**
-Peafowl nests don't have feathers, only eggs
-Goats give white vanilla wool when "sheared"

**Steps to Reproduce**
-Have a peahen lay an egg in a nest
-Grab any goat (besides Angora because they're supposed to be shearable) and shear it

**Version of Minecraft, version of Animania, Single Player or Server**
Singleplayer, Animania version 1.4.6, Minecraft version 1.11.2

**Some Screenshots**
-Peafowl eggs
![2018-03-10_21 24 02 - copy](https://user-images.githubusercontent.com/28816115/37313837-f8b3b02e-261e-11e8-9c12-e76818903059.png)

**Comment by Tschipp** [comment]
iirc this was removed, right @capnkirok ?

**Comment by RaliaTheWolf** [comment]
Oh, why were they removed? They always made it easier for me to tell my peafowl eggs apart from my chicken eggs XD
Ah okay! That's good ^^

**Comment by capnkirok** [comment]
Well, back when there were only two different colored peacocks (blue and white), it made sense, but then we added several more varieties... and it didn't make sense anymore... (true story)

**Comment by RaliaTheWolf** [comment]
Oh I didn't even think of that... ^^; My bad!
