### ISSUE TITLE
troughs fill randomly with water

### ISSUE THREAD

**Issue by PumaBlack** [capnkirok/animania#599]
### Expected Behavior
Empty troughs stay empty

### Actual Behavior
empty troughs fill themself with water afer time. Don't know if it could be the rain, but they fill also in rooms with roofs.

### Steps to Reproduce
place a trough under a roof and wait.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.12
forge 14.23.2.2611
animania-1.12.2-1.4.6
on the server

Server
private server

**Comment by capnkirok** [comment]
Clearly you have a leaky roof... 😄
