### ISSUE TITLE
Minecolonies compat

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#600]
### Expected Behavior

pretty please add in compatability for minecolonies? pretty plz

**Comment by Deshiba** [comment]
You might have to elaborate a bit more on what exactly isn't compatibele now and what you want support for...

**Comment by Tschipp** [comment]
Does minecolonies add animals?

**Comment by CharCharthemonkey** [comment]
it uses the vanilla versions atm but cause of compat issues cant exactly distinguish between male and female for animania

**Comment by capnkirok** [comment]
You are going to have to ask the Minecolonies team to work on this one @CharCharthemonkey . They can pull the Entity Name and filter male from female from that. We can't really do much here, unfortunately. I would cross-post this issue on their github so at least we could communicate if necessary.

**Comment by capnkirok** [comment]
I cross posted this see link above. Looks like there was already a thread.

**Comment by CharCharthemonkey** [comment]
thank you @capnkirok

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#151
