### ISSUE TITLE
[1.12.2][1.4.6] Hamster wheel insane network usage

### ISSUE THREAD

**Issue by FailMelon** [capnkirok/animania#601]
### Expected Behavior
Low network usage if at all barely anything at most maybe like 32 bytes/s

### Actual Behavior
While hamster is in the wheel it uses around 100 kBps

### Steps to Reproduce
Create multiplayer server and connect using a none local ip
Place hamster in Hamster Wheel and watch network usage of java climb

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2
Animania: 1.4.6
Dedicated Server

### Screenshots encouraged
Not in wheel:
https://i.imgur.com/zBZahoy.png

In wheel:
https://i.imgur.com/A3GAtuD.png

### Extra notes
I have also tried this on a new server with just Animania installed it seems to be a Animania only related issue.

**Comment by Deshiba** [comment]
Is this still an issue with 1.4.7?

**Comment by FailMelon** [comment]
This is still an issue in 1.4.7 sadly

**Comment by Tschipp** [comment]
How do other machines compare to the wheel? The wheel is sending packets every tick when it's running, because the client continuously needs to know the RF amount

**Comment by FailMelon** [comment]
The RF amount even if sent over to the client would be what, just a single 4 byte value at most a 8 byte value. We're talking here a 5 kilobyte a tick amount of network usage. Example a room full of RF machines and a massive ME system would use around the same as a single hamster wheel.

**Comment by Tschipp** [comment]
we're not sending 4 bytes of data. We're sending the animation, rf and other metadata of the wheel. But I agree it seems rather large

**Comment by capnkirok** [comment]
@Tschipp i'll do some testing on this too... wonder what's going on... never seen this reported.

**Comment by capnkirok** [comment]
@FailMelon do you have any other mods installed? I just tested (on my Mac) and saw no difference in memory usage. Will test on the PC tomorrow, but just wanted to see if there are any other variables I am missing...

**Comment by FailMelon** [comment]
I tested it with only Animania installed in case that was an issue and i still saw it occurring.

**Comment by capnkirok** [comment]
Ah, yes, see your note above. I will try to replicate your setup.

**Comment by tterrag1098** [comment]
Why is the RF amount needed on the client? Animation should be clientside as well.

**Comment by Corosauce** [comment]
I've also confirmed this huge issue with hamster wheel, as soon as I started using 2 of them an EU player couldnt play without getting lagged out after a minute of joining.

**Comment by Corosauce** [comment]
Sure: https://gist.github.com/Corosauce/99cc3b663b88e2b02bc8611ded8f9327

**Comment by capnkirok** [comment]
Ok! Got it and testing. Yes WAY too much data going through per/sec. It's definitely the Wheel and not a conflict with another mod. Working on it!

**Comment by capnkirok** [comment]
For the record, if anyone is keeping record:
- Animation sync with the CraftStudio API was not the problem. Animation still takes some network, but it is negligent.
- As @tterrag1098  suspected, sending a full NBT packet every tick is a huge problem. I've spaced this out so that the sync happens much less frequently (50 ticks).

I still see a slight increase in network usage when using a Hamster Wheel, but I believe this issue to be solved. I will try to get a build out tonight. Thanks for the inputs everyone.
