### ISSUE TITLE
Hamsters Floating

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#603]
**Expected Behavior**
Hamsters sitting on a player's shoulder would stay on their shoulder when they sit using More Player Models (I haven't tested if this happens when sitting on a couch from Decocraft or a horse)

**Actual Behavior**
The hamster floats in the place where it would be if the player were standing

**Steps to Reproduce**
Place a hamster on shoulder and use MPM to sit

**Version of Minecraft, version of Animania, Single Player or Server**
Animania version 1.4.7; Minecraft version 1.12.2; Single player

![2018-03-31_18 56 56](https://user-images.githubusercontent.com/28816115/38169030-f697cc94-3523-11e8-8f07-b3755176588a.png)

*I'm not sure if this is on Animania's end or MPM's end, but as you can see, the Vanilla parrots are okay, so I'm assuming it may be Animania.

**Comment by Tschipp** [comment]
Yeah this is MPM. MPM builds on the vanilla model, which includes the parrots.
