### ISSUE TITLE
Mooshroom drops missing in config

### ISSUE THREAD

**Issue by Ash70** [capnkirok/animania#604]
MC 1.12.2
Animania 1.4.7

There are no settings in the config file for mooshroom drops. This causes a problem with compatibility with other mods; e.g. like leatherworks drops regular cowhides when killing an animania mooshroom.

**Comment by capnkirok** [comment]
Hey Ash. Yeah, the Mooshrooms use the same drops as the Cows. I had honestly thought they used the same loot table as cows. Can add this as an enhancement.

**Comment by capnkirok** [comment]
Looking at this again. Here's the story. It does use the same drops as the other Cows. However, because it's a custom entity, you can't modify the loot table. So, will add a separate entry for Mooshroom that can be further configured.

**Comment by capnkirok** [comment]
Added in next release
