### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by lifeiseasy** [capnkirok/animania#605]
Hello, do you think you could update the 1.12 version of animania to 1.4.7 so it is still compatible with the forge I am currently using for my pack?

**Comment by Tschipp** [comment]
I’m missing information here... What is the forge version of your pack?

**Comment by lifeiseasy** [comment]
I have forge 14.21.1.2387

**Comment by Tschipp** [comment]
That won't be possible. Please update the forge version of your pack,

**Comment by lifeiseasy** [comment]
Do I have to update it to a 1.12.2 version? Because if I do I will lose a lot of my mods. I can update it to the most recent 1.12 but that’s about it.

**Comment by Tschipp** [comment]
Yes, you have to update to 1.12.2. If that is too much of a problem, you can stick to an older version of Animania, or bug the authors of the mods that you want to have updated.

**Comment by capnkirok** [comment]
Hey @lifeiseasy I've done some testing this weekend, and it looks like Animania still works in the older versions of Forge as well. I'm going to remove the requirement in the next update (which is still a week away). But... I would still recommend you work with other mod creators to update their versions. There are many issues with the earlier versions.
