### ISSUE TITLE
Animals don't spawn in old chunks.

### ISSUE THREAD

**Issue by MrFarrelll** [capnkirok/animania#607]

**Comment by capnkirok** [comment]
Hey @MrFarrelll yeah, if you add Animania to an existing world they won't spawn in the old areas. Is that what you are saying is going on with you?

**Comment by Marfjeh** [comment]
i can say this happend to me to an existing world, it removed all the vanilla mobs instead replacing them. (what is enabled in the config)

**Comment by capnkirok** [comment]
Yes, I see the problem. Animania used to replace animals in old chunks but that led to overspwaning. Now it removes them without replacing, leaving the world barren. Need to fix this for existing worlds. Thanks, both.

**Comment by Deshiba** [comment]
@capnkirok On a similar note. If you have animania installed and remove it for some reason, all animals will despawn and vanilla animals take a while to respawn in old chunks.

Would there be a way to replace animania animals with vanilla ones when animania is removed?

**Comment by Marfjeh** [comment]
> @capnkirok On a similar note. If you have animania installed and remove it for some reason, all animals >will despawn and vanilla animals take a while to respawn in old chunks.
>
>Would there be a way to replace animania animals with vanilla ones when animania is removed?

The way forge and minecraft works in my understanding, if it cannot find the entity and or block it will just silently remove them. and there is no way to replace them back to vanilla animales. Or what you can do is maybe that they are still registered as a vanilla mob, but problem is you probably need to rewrite the mod i'm afraid for that.




> Yes, I see the problem. Animania used to replace animals in old chunks but that led to overspwaning. Now it removes them without replacing, leaving the world barren. Need to fix this for existing worlds. Thanks, both.

Awesome. because i'm playing my modpack and wanted to install this mod, it just removed all the mobs D: and it doesnt seem they respawn, but i havent checked everywhere. My world is pre-generated for around 1000 chunks x 1000 chunks

**Comment by capnkirok** [comment]
One way to do this would be through commands. Was thinking of the following:

- Spawn Animania animals (in an existing world)
- Replace vanilla animals with Animania versions
- Remove Animania animals of type X
- Replace Animania animals with vanilla versions
- Reduce Animania animal of type X by X percent (or something)

**Comment by Marfjeh** [comment]
that would be awesome. so i can add animania to my existing world :D

**Comment by Crowfooted** [comment]
Is this still an issue with Animania? Is it because animals only spawn when the chunk generates, or is it something to do with the chunk itself?

**Comment by Marfjeh** [comment]
Every existing vanilla mob gets purged and it doesnt get replaced with animania mobs. but i do not know that they fixed it.

**Comment by capnkirok** [comment]
In the latest version, there's now a small chance that a vanilla animal will be replaced with Animania even in existing chunks. I have to be very careful about this due to overspawning (there are so many checks and balances right now).

But the new commands are not in yet.
