### ISSUE TITLE
Creative Item Bugs

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#608]
**Expected Behavior**
IDK... Correctly colored and named items/spawn eggs I guess?

 **Actual Behavior**
The Suffolk spawn egg is a different color and the Raw Chicken (Orpington) has some random text added on the end.

**Steps to Reproduce**
Look at the Suffolk spawn egg and Raw Chicken (Orpington) in the creative menu.

**Version of Minecraft, version of Animania, Single Player or Server**
Minecraft Version 1.12.2; Animania Version 1.4.7; Singleplayer

Wrong Name:
![2018-04-07_16 27 39](https://user-images.githubusercontent.com/28816115/38461163-005023e2-3a8f-11e8-9eb5-59c09524b898.png)

Wrong Color (with a different spawn egg of the same breed for clarification):
![2018-04-07_17 54 17](https://user-images.githubusercontent.com/28816115/38461168-17de44c6-3a8f-11e8-9322-6c2722e8567d.png)
![2018-04-07_17 54 19](https://user-images.githubusercontent.com/28816115/38461169-1a595722-3a8f-11e8-849f-49ec6a4bed23.png)

**Comment by capnkirok** [comment]
Thank you once gain, @RaliaTheWolf ! These are fixed and in next release (1.4.8).

**Comment by RaliaTheWolf** [comment]
You're welcome! ^^
