### ISSUE TITLE
Reduced Draft Horse Speed

### ISSUE THREAD

**Issue by zerafox** [capnkirok/animania#609]
### Expected Behavior
To be able to lead Horse / Horse + Cart with relative ease

### Actual Behavior
Directions in which are 'diagnal' across the world cause severely slow movement when attempting to ride or lead a Draft Horse, especially when pulling a cart.

Water Movement incredibly difficult/slow as well

### Steps to Reproduce
Ride/Lead Draft Horse
Move in a Diagnal fashion across terrain

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2
1.4.7
Single Player + LAN

**Comment by capnkirok** [comment]
Yeah, after a lot of testing, I'm considering this a bug. It's pretty annoying. Same for Bulls when pulling the tiller.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#153
