### ISSUE TITLE
Animals models

### ISSUE THREAD

**Issue by Gerbil12** [capnkirok/animania#611]
Good day I would like to ask if it would be done to make an animal model (aurochs) and it would feed be a favorite food and then it would become a random breed because it would be easier, and easier for the generation of the world 😄 And that's how it would be for all mobs in fashion thanks for reading

**Comment by mser7** [comment]
Wait, we can post suggestions here?

**Comment by Deshiba** [comment]
@mser7 Yes, there's more then 1 open suggestion on the git.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#154
