### ISSUE TITLE
how to stop the animals breeding? 

### ISSUE THREAD

**Issue by MonsterRa** [capnkirok/animania#612]
I tried to stop the cows breeding and overpopulate by separating the females in one side and the males in the other side. They kept on breeding through one block, so then I put two blocks and they still were breeding.

**Comment by Deshiba** [comment]
The code checks if the mate is in range, in order to breed at all this area has to be somewhat bigger. Try putting them apart about 10ish blocks

**Comment by Tschipp** [comment]
@capnkirok How about we add sterilisation?

**Comment by capnkirok** [comment]
@Tschipp that, my friend, is an excellent idea

**Comment by capnkirok** [comment]
I did not add sterilization yet, but I did fix it so they can't mate unless they can see each other and touch. So, original intent is fixed in next release.
