### ISSUE TITLE
Cats Breeds

### ISSUE THREAD

**Issue by Gerbil12** [capnkirok/animania#613]
Hello, I wanted to ask in which version the cats will be added, because I can not wait :) and how many breeds will it be? and I also have a suggestions for breeds.
Breeds:
Maine coon
Sphynx
British Shorthair
Bengal
Aegean
Norwegian Forest cat
Nebelung
Persian
Ragdoll
Savannah
Siamese
Siberian
Snowshoe
Tonkinese
Thai Lilac

Thanks for reading:)

**Comment by capnkirok** [comment]
Hey @Gerbil12 cats are coming this summer :) no date set yet tho. We have some of these breeds on the list, but not all. Thanks for the suggestion. Going to close this one, but keep an eye out!
