### ISSUE TITLE
Sheep wont breed at all

### ISSUE THREAD

**Issue by redwolf41** [capnkirok/animania#614]
### Expected Behavior

The sheep are supposed to breed when they're happy

### Actual Behavior

The male sheep continue to run in circles, like sheep do after you hit them. There are lots of troughs and food available, and the males and females are in the same pen together. This is happening for all the breeds of sheep. All the sheep say Well-Fed.

### Steps to Reproduce

I have one male and one female of each sheep breed in pens in my underground base. The pens were originally about 4x6 or so, with each pen having its own trough in it, and each breed was in its own pen. When the males wouldnt stop running around like madmen. I thought it might be the other males setting them off, so I put solid blocks around a few pens to see if they would stop. They didnt. 

At that point, I removed all the fence posts and blocks separating them and now have them all in one giant pen together. The males have not stopped running around like mad. 

Since its an underground base, I wasnt sure if they might have been reacting to any hostile mobs in caves I have yet to light up, so I did. I lit up every cave or dark area within a 50-block radius. I've checked using Spectator and Creative modes to make sure I got everything covered.

The males are still running around like they've been hit. I've tried killing them and spawning in new males, but it doesnt stop. 

### Version of Minecraft, version of Animania, Single Player or Server

Magiculture 2
Minecraft 1.12.2
Single player game
Animania 1.4.5

**Comment by redwolf41** [comment]
Issue seems to have resolved itself. Closed.

**Comment by capnkirok** [comment]
I love it when this happens :)
