### ISSUE TITLE
Covered Wagon Keeps Coming Detached

### ISSUE THREAD

**Issue by andrewminer** [capnkirok/animania#615]
### Expected Behavior

The wagon remains attached to the horse so long as you don't deliberately disconnect them.

### Actual Behavior

Every few dozen meters, the wagon becomes disconnected (especially when going uphill), and the player shifts to riding the horse while the wagon just stops where it is.

### Steps to Reproduce

1. Click on the wagon so that it starts following the player
2. Click on a draft horse with a riding crop so that the wagon is attached to the horse
3. Drive the wagon around on smooth flat ground as well as 1-step hills

### Version of Minecraft, version of Animania, Single Player or Server

* Minecraft 1.12.2
* Animania 1.4.7
* [Server](http://andrewminer.github.com/brunel)

**Comment by capnkirok** [comment]
Have you tried this on the latest version?
