### ISSUE TITLE
Animals spawning even though it is disabled in the config

### ISSUE THREAD

**Issue by EmeraldTiger64** [capnkirok/animania#617]
Hello, I am having an issue with animals spawning in my city. I have disabled the spawning of animals, seen in the screenshot. I guess the expected behavior is for them to stop spawning, but they still spawn every little while, but not in big clusters like they did before I disabled the spawning. The steps to reproduce are to create a world with spawning enabled, then disable the spawning in the config.

Minecraft Version: 1.12.2
Animania Version: 1.4.6
Single Player world

![image](https://user-images.githubusercontent.com/31394546/41780546-9df3ef42-75fa-11e8-9230-1dbee199755f.png)

**Comment by capnkirok** [comment]
Yeah, I accidentally disabled this a couple of builds ago. This is fixed in the next release.
