### ISSUE TITLE
Suggestion - Hungry Animals compat

### ISSUE THREAD

**Issue by lsi5974** [capnkirok/animania#618]
### Steps to Reproduce
Manure, mature animal weight, weight gain, block regrowth for grass, predatory animals vs other animals, hunted animal behavior/taming behavior.  I think this would fit nicely with Animania,  a bit more realism to the farm.

**Comment by LunariusH** [comment]
Yes, this, please.  Let's not forget the disease mechanic they were playing with as well.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#156
