### ISSUE TITLE
Suggestion - Meat processing/butchering

### ISSUE THREAD

**Issue by lsi5974** [capnkirok/animania#619]
### Steps to Reproduce
A suggestion for butchering/meat processing. Their was  a mod that would have fit in with both your mod and Hungry Animals, but  it has not been updated,  it, was  a butchering (or meat processing  mod if you prefer) named Fantastic Beasts and How To Eat Them.  Im wondering/hoping you could implement this in your mod for a more realistic feel.  Adding a dynamic like this would make your mod a little more hardcore for the survival mod packs and if one so desired they could add in new recipes and add-on recipes to go with different mods, salted ribs cut into strips and hung on drying racks from Tinkerers Construct, BBQ chicken wings for Pams Harvestcraft, etc etc, lots of possibilities.

**Comment by LunariusH** [comment]
This is an excellent idea, and I would love to see it implemented.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#157
