### ISSUE TITLE
Chickens don't lay eggs in Twilight Forest

### ISSUE THREAD

**Issue by st753m** [capnkirok/animania#621]
I have 4 animania chickens (2 roosters, 2 hens) that I collected and put in a pen.  Despite waiting for several real-time hours, not a single egg has been laid.  

My house is in the Twilight Forest, since I'm playing with Ice and Fire and the overworld isn't safe to build farms in.  The animania cows I brought in are breeding normally, it's only chickens that are causing problems.  There are no other chickens in the entire dimension, so I shouldn't be running into a cap. 

Their pen includes food and water troughs as well as a water pond and seeds on the ground.  I've also fed and watered them manually.  The pen has multiple nests.  

I tested in a creative world, and it seems like chickens and peafowl lay eggs normally when in the overworld, but don't when in the Twilight Forest.  

### Version of Minecraft, version of Animania, Single Player or Server

I'm playing single player
Minecraft 1.12.2
Animania 1.4.8
Twilight Forest 3.7.424

**Comment by capnkirok** [comment]
Hmmm... chickens only lay eggs during daytime. Is the twilight forest a 'constant' nighttime?

**Comment by capnkirok** [comment]
Well, since you didn't respond, I took a look. Indeed, Twilight Forest is a constant nighttime.
