### ISSUE TITLE
Draft horses doesnt have armor skin

### ISSUE THREAD

**Issue by mser7** [capnkirok/animania#622]
### Expected Behavior
When tame a draft horse, then equip it with a horse armor, a armor texture will cover the horse

### Actual Behavior
Nothing happened when does so, despite the horse register the armor in the slot, and even have the extra armor points

### Version of Minecraft, version of Animania, Single Player or Server
MC version 1.12.2
Animania 1.4.8
SSP

### Screenshots encouraged
I will provide later

**Comment by mser7** [comment]
Sorry for late responding. here is the screenshots
https://imgur.com/a/Jyn82ww

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#159
