### ISSUE TITLE
[Suggestion] Mooshroom Stuff

### ISSUE THREAD

**Issue by ghost** [capnkirok/animania#623]
Some Mooshroom Ideas

- There should be a Brown Breed of Mooshroom with brown mushrooms. _Maybe it can interbreed with Reds to get a calf of either type at random._

- Feed a cow a mushroom to turn it into a red or brown Mooshroom. _Could make configurable._

- Unless this is a thing, make Mooshrooms also eat mycelium, too.

- And maybe a config to let sheers just take mushrooms off instead of making them cows.

**Comment by Deshiba** [comment]
If this ever becomes a thing, I'd like this to be extended to nether warts too.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#160
