### ISSUE TITLE
[Suggestion] Added items in S:troughFood should also attract animals. 

### ISSUE THREAD

**Issue by LukeSkywaIker** [capnkirok/animania#624]
I´m building a modpack and try to find a way that cows follow me when i have Naturas Barley in my hand. As it works with barley from harvestcraft i thought adding it to S:troughFood in the config will help. But no .D

Maybe u can add this functionality or add another config option for it. :)

Thanks in advance!

**Comment by Deshiba** [comment]
Can you include a snippet of the config lines you added?

**Comment by LukeSkywaIker** [comment]
Ofc:

        # Food Items that can be placed in the trough (use # for meta)
        S:troughFood <
            harvestcraft:barleyitem
            biomesoplenty:turnip_seeds
            natura:materials#0
         >

**Comment by Tschipp** [comment]
There are separate food lists for cows, pigs, sheep etc. If I did things properly, adding entries to those lists will make the animals attracted to that item.

**Comment by capnkirok** [comment]
Yeah, the Tempt AI doesn't refer to troughFood. Let me see if this is possible.

**Comment by Tschipp** [comment]
@capnkirok This already exists: 
`	public static final Set<Item> TEMPTATION_ITEMS = Sets.newHashSet(AnimaniaHelper.getItemArray(AnimaniaConfig.careAndFeeding.cowFood));
`

**Comment by capnkirok** [comment]
Ok, this wasn't in for all of the animals, though it was in for cows. Could be the loading sequence (I added in a loading dependency after natura and harvestcraft). Any way, this works for me in next release.

**Comment by capnkirok** [comment]
To be clear, added support for Peacocks, Rabbits, Hamsters, Ferrets, and Hedgehogs, and added a loading dependency.
