### ISSUE TITLE
[Suggestion] Support for other mods buckets

### ISSUE THREAD

**Issue by LukeSkywaIker** [capnkirok/animania#625]
It would be cool to get milk from cows, goats and sheeps with other mods bucket. Like the clay bucket (Ceramics), the weedwood bucket (The Betweenlands) or the wood bucket ([SBM] Wooden Buckets).

Additionally using a bowl (Minecraft) to get a bowl of milk, would be awesome.

Thanks in advance!

**Comment by capnkirok** [comment]
If the mod uses Forge Buckets... this should work. Which version of MC/Animania are you on ?

**Comment by LukeSkywaIker** [comment]
MC 1.12.2 
Forge 14.23.4.2705 
Animania-1.12.2-1.4.8

After further testing i found out that it works with cows, but not with goats or sheep.  Both of the mods (Ceramics/The Betweenlands) use Forge Buckets. I can find all Milk Buckets (different cow milk and sheep/goat milk) for both mods in JEI.

**Comment by capnkirok** [comment]
There was a slight difference between the code of Cows vs. Sheep/Goats. I've updated it. Hopefully this solves it.

**Comment by LukeSkywaIker** [comment]
Let´s see :) Thanks!!
