### ISSUE TITLE
Hamsters are cause hard crash when panic

### ISSUE THREAD

**Issue by mser7** [capnkirok/animania#629]
### Expected Behavior
Hamster running in panic?

### Actual Behavior
Hamster crashes the game

### Steps to Reproduce
Simply attack a hamster in survival mode

### Version of Minecraft, version of Animania, Single Player or Server
SSP
Minecraft 1.12.2
Animania 1.5.0

### Screenshots encouraged
No screenshots, but crash reports
https://pastebin.com/stRmPfN5

**Comment by capnkirok** [comment]
Duplicate in other repository. Hotfix coming.

**Comment by capnkirok** [comment]
Fixed in 1.5.1
