### ISSUE TITLE
More bugs

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animania#63]
Hey, It's me again, and I have another list for you:

Major:
- Throughs can destroy (indestructible) blocks: https://gyazo.com/111724a23acbe8c699405c80d52b1224

Minor:
- Arm is swung when trying to throw eggs, even though it's disabled in the config.
- Tamed animals show a death message even if they're not renamed (Hamsters, Hedgehogs and Ferrets)
- Tamed renamed animals don't show their custom name when killed (Hamsters, Hedgehogs and Ferrets)
- Hedgehogs have a huge hitbox and can therefore not fit in 1 block gaps. Their eye-height is also off by miles. 
- The ferret's eyeheight is also off
- The Through can be clicked with any item and the arm will swing, even if it's not a valid item.

Old:
- Seeds still can float in midair, even when the block under them is removed. In my opinion, this should be changed.

Suggestions:
- Allow cheese molds to be placed and be filled with milk. The cheese has an aging process, and can also be placed on the ground (like cake).
- When attacked, Hedgehogs should pull in their head and stop moving, also inflicting a thorns effect on the attacker.

Other:
- The cheese wheel and the cheese wedge both share the same OreDict name, which is... weird, considering you get four wedges per wheel.
- Throwing eggs can create fully grown chickens (intended?)

**Comment by capnkirok** [comment]
Cheers

**Comment by capnkirok** [comment]
- Hedgehog hitboxes fixed

**Comment by Tschipp** [comment]
Yes, if throwing eggs is enabled it creates Male, Female and baby chickens

**Comment by capnkirok** [comment]
Ah yes, this is intentional.

**Comment by Tschipp** [comment]
A falling block? So like sand? I would rather implement it as a carpet type block.

**Comment by capnkirok** [comment]
Yeah, that's better. Thanks. The seed block fix will be in 1.0.4.1

**Comment by Tschipp** [comment]
You really need to get on that first issue though. It is gamebreaking. TileEntities can be destroyed without dropping inventories and of course all unbreakable blocks can be destroyed. This would also bypass protections.

**Comment by capnkirok** [comment]
Yeah, you are right. But it's a pain.
