### ISSUE TITLE
[1.10]Animania + Biome Bundle

### ISSUE THREAD

**Issue by darknat** [capnkirok/animania#633]
### Expected Behavior
More passive animania's animal

### Actual Behavior

No animals or just a little(1 or 2) in specific biome like savanna or desert.

### Steps to Reproduce

Since I added Open Terrain Generator with biome bundle.

### Version of Minecraft, version of Animania, Single Player or Server

Minecraft : 1.10.2 
Animania : animania-1.10.2-1.4.8
Forge : 12.18.3.2511

### Lists of mods
https://pastebin.com/FYJifgHa

### Config File

https://pastebin.com/K1zec9Wj

Thank you

**Comment by Deshiba** [comment]
A couple of notes.
- 1.10 is not supported anymore iirc.
- You have a lot of mods in there. Maybe try it with just animania OTG and biome bundle.

**Comment by Tschipp** [comment]
Yeah sorry, 1.10 is no longer supported and won't receive any updates. Try changing the config values for spawning.

**Comment by darknat** [comment]
:'( i saw that in Biome Bundle, we can found biome's files with spawning informations, but I don't know how i can write this for animania.

This is a example : 

> SpawnCreatures: [{"mob": "Sheep", "weight": 12, "min": 4, "max": 4}, {"mob": "Pig", "weight": 10, "min": 4, "max": 4}, {"mob": "Chicken", "weight": 10, "min": 4, "max": 4}, {"mob": "Cow", "weight": 8, "min": 4, "max": 4}, {"mob": "Wolf", "weight": 8, "min": 4, "max": 4}]

**Comment by Deshiba** [comment]
Try {"mob":"animania:ewe_dorper","weight:" 40, "min":1,"max":1}
This should spawn you a bunch of single dorper ewes. If that works then you could do that for every single type of animal there is. Allthough thats a ton of work.
