### ISSUE TITLE
Farm animals beside sheep and goat can be fed food repeatedly

### ISSUE THREAD

**Issue by mser7** [capnkirok/animania#635]
### Expected Behavior
Hand feeding an animal the food, then it won't accept anymore for a while after feeding

### Actual Behavior
They keep eating the food, wasting it

### Steps to Reproduce
Find a farm animal beside sheep or goat
Hold down the feeding key with the food in your hand
The animal keep consuming it.

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2
1.5.1, hot sleep release
SSP

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#163
