### ISSUE TITLE
Unusual lag with stuck mobs

### ISSUE THREAD

**Issue by claw4oo** [capnkirok/animania#637]
### Expected Behavior
N/A

### Actual Behavior
Animals that are stuck in water pools, naturally generated or not, cannot expect and lag quite a bit, using tickprofiler to find the problem

### Steps to Reproduce
Throw an animal, like a chicken, cow, sheep, or goat into a naturally generated pool that cannot be escaped without building out. Keep the chunk loaded for a while, and run a tick profiler to confirm it's the animal.

Moving the animal outside of the stuck area seems to fix the problem.

Unsure of how to reliable reproduce quickly.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.5.1.1
Server

### Screenshots encouraged
https://gyazo.com/f877704097715d3ca61ef4445f929ee7

**Comment by capnkirok** [comment]
Thanks for the report. I thought I had addressed this, but will take another look.

**Comment by Deshiba** [comment]
Last I saw anything about this the problem was that animals walked into water pools with 2 high walls with natural gen. The solution then was to have their AI prevent going down in the hole on their own.

If they are forced in however, the original issue will still be the same.

**Comment by claw4oo** [comment]
Several versions back, I had this problem with chickens getting stuck in very odd places, sometimes I couldn't even find the chicken despite having the coordinates. Most of the chickens were around the spawn chunk.
I fixed this problem temporarily by bringing down natural chicken spawns, and killing all already existing chickens in the map.

**Comment by claw4oo** [comment]
https://gyazo.com/ff0dde929ce8d926cdbad0c1c36aad85
Got a new picture confirming this.

https://gyazo.com/6900bdec7baa973794b94657ce42404d
This is with the problem fixed.

**Comment by Tschipp** [comment]
This issue was moved to capnkirok/animaniamod#165
