### ISSUE TITLE
There is no way to enable vanilla breeding

### ISSUE THREAD

**Issue by mser7** [capnkirok/animania#640]
I want to play with this mod, but in some cases, I want to keep the easy breeding mechanic of vanilla where feed two animals then they mate, for automation, but there is no way to do that.

**Comment by Deshiba** [comment]
There is. Turn on manual breeding in the configuration file.

**Comment by capnkirok** [comment]
Ah you want them not only to get pregnant, you want them to make animals faster. In that case, you need to lower the gestation timer to say 20 (instead of 20000). That's also under Care and Feeding.

Recommend you look through the config file and try things out :)
