### ISSUE TITLE
Animania bugs

### ISSUE THREAD

**Issue by GeorgeOoi** [capnkirok/animania#641]
### Expected Behavior
-Chickens lay eggs on their nest.
-Animals breed only when they're Well Fed.

### Actual Behavior
-Chickens don't lay eggs on their Nest. (i did fed them until they're well fed)
-Animals keep breeding non-stop. i left them about 3-4 mc days but when i came back i saw my farms is flooding with animals until some of them glitch out of the wall. (they only have access to Water)
-Sometimes i don't fed animals food or water about a few MC days but they still being well fed.
-sometimes animals seems to have troubles drinking water from water sources. i made a 6x3 water sources for them but every times i went to see them they're still thirsty.
(sorry for bad english)

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.5.1.1
Single Player/Lan

**Comment by Deshiba** [comment]
To prevent chickens form overspawning, separate the rooster.

**Comment by capnkirok** [comment]
Hey George -

I'm not seeing either of these things (and haven't seen these posted by the community), so I need more info.

- What other mods do you have installed? This could be a conflict.
- Are you sure the animals are 'breeding'? Meaning are you seeing babies? Or are you seeing just new adults (i.e., 'spawning')
- Chickens don't lay eggs during the night time, not sure if that affects you. Can you post a screenshot of your chicken farm?

Things you can do:
- Move to hand feeding animals (in the config, under Care and Feeding, set manual breeding to True
- Move your nests to a new location, spread them out.

Please let me know the answers to the first two questions.

**Comment by GeorgeOoi** [comment]
@capnkirok 
![2018-09-10_13 46 10](https://user-images.githubusercontent.com/42521945/45290283-d19bd880-b521-11e8-87ca-85e5cb78ec7f.png)
![2018-09-10_16 22 26](https://user-images.githubusercontent.com/42521945/45290284-d19bd880-b521-11e8-806a-fe9883623ac0.png)
![2018-09-10_16 54 40](https://user-images.githubusercontent.com/42521945/45290286-d2346f00-b521-11e8-95e4-4d48620d1579.png)

**Comment by GeorgeOoi** [comment]
@capnkirok Cow breeding non stop and i didn't feed them i don't know why they're always well fed.

**Comment by capnkirok** [comment]
- Did you set:
 # Mammals mate/breed only after hand-feeding
        B:manualBreeding=true
They shouldn't breed unless you feed them by hand. Unless there is a conflict that is.

- Cows are happy to eat grass from the ground. You can see an empty patch there.
- I see some Quark textures on vanilla mobs, which means you have other mods installed. I think we have a conflict somewhere. Can you please post your modlist?
- Is the bottom photo here where you started? Was there only one cow in the pen?

**Comment by GeorgeOoi** [comment]
![capture](https://user-images.githubusercontent.com/42521945/45295024-e2534b00-b52f-11e8-81d6-3fb3c0dc6ba1.PNG)

**Comment by GeorgeOoi** [comment]
@capnkirok

**Comment by GeorgeOoi** [comment]
@capnkirok I replaced grass blocks with wooden planks seems to stop them from breeding, So i don't think there're any conflicts with other mods.

**Comment by capnkirok** [comment]
Where are these animals from?
![image](https://user-images.githubusercontent.com/9628379/45357884-ffd3f380-b5c7-11e8-8562-b944e94a524f.png)

**Comment by GeorgeOoi** [comment]
Vanilla Minecraft I just disabled animania cow replaced vanilla cows

**Comment by Deshiba** [comment]
That texture is definitely not vanilla.
