### ISSUE TITLE
Cannot open Config Menu

### ISSUE THREAD

**Issue by scotty9090** [capnkirok/animania#642]
Having issues with opening the Animania config menu in game.  Mod Options -> Animania -> Config ... menu does not open.  This is, I think, the only mod this is happening with.

I searched to see if someone else reported this and came up dry so I'm wondering if this is on my end, but no idea what to check.

### Version of Minecraft, version of Animania, Single Player or Server
MC: 1.12.2
Forge: 14.23.4.2751
Animania: 1.12.2-1.5.1.1
Mod Pack: Enigmatica 2 Expert 1.36

**Comment by Tschipp** [comment]
Can you show a screenshot? How does it "not open"? Is the button clickable, but nothing happens? Is the button grayed out?

**Comment by capnkirok** [comment]
This is the only report of this issue. You might try deleting the existing config file and restarting from scratch.

**Comment by scotty9090** [comment]
Not much to show in a screenshot - just the standard list of mods with an enabled config button. The button is clickable - it even makes the click noise - but the menu simply doesn't open.  I will try deleting the config and see what happens when I'm back at my computer.
