### ISSUE TITLE
Extremly low TPS with animania added on existing modpack (With Sleep ON)

### ISSUE THREAD

**Issue by marciox25** [capnkirok/animania#644]
### Expected Behavior
No TPS

### Actual Behavior
Low TPS

### Steps to Reproduce
Having a good amount of animals,
Wait till the night -> they go to sleep, 
The tps on the server goes down till the 4~5tps.
Fixed with disabling sleep on animals. But then another problem appeared. Chichens dont lay eggs if this option is set to false. 

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, animania 1.5.1.1

**Comment by capnkirok** [comment]
Chickens don't lay eggs at night, could be the issue. I will double check the logic regardless and post again. 

The sleep lag issue is known (only occurs for some), and a fix is in progress. Cross reference: https://github.com/capnkirok/animaniamod/issues/104
