### ISSUE TITLE
Suggestion: Automation Machines for Animania

### ISSUE THREAD

**Issue by Guinaro** [capnkirok/animania#65]
If you want to provide automation for the animals, some machines would be nice.
Autofeeder: filling of troughs with water, slop or other feed.
Autobreeder: providing animals which are ready to breed with the correct feed.
An MFR like chronotyper: auto seperation by age (baby, juvenile, adult), seperation by gender (male or female), later on it can tie in with genetics, filtering animals based on specific genetic typing, ...
An auto milker, auto shearer, auto egg harvester, ... .
An if you really would love to do it, maybe make them even multiblock machines. Like for instance: a milking machine in which the cows step on a carroussel, get automatically feeded and milked at the same time, ... just like in real life.
Animania: the Minecraft farming simulator.

**Comment by capnkirok** [comment]
- Autofeeder is already in progress. Technically you can do this now with redstone, as the trough emits a redstone signal when empty. But we're working on a way to use a Hopper.
- Autobreeder interesting!
- MFR - nice!
- Auto-milker/shearer/harvester - yes, have been suggested... great idea!

Automation is coming... need to get more animals in first :). I will keep this open.

**Comment by OreCruncher** [comment]
If/when you add automation could make sure there are ways to disable automation features? :)

**Comment by Divineaspect** [comment]
can this include compatibility with things like vanilla hoppers for troughs?

**Comment by capnkirok** [comment]
Yes, will do :)

**Comment by calloatti** [comment]
Just a suggestion: Instead of reinventing the wheel, make the troughs work with standard pipes from other mods like EnderIO or XNET or Refined storage exporters, etc.

That way you achieve instant automation with not  that much work (I think). 

The trough should accept wheat from pipes, or slop (in this case it should hold on to the bucket and let a pipe take it out I guess)

Also, seeds for chickens in troughs should be a thing.

If troughs take pipes and connectors, all you have to do is send them wheat, seeds, and set up an autocrafter from any mod to make slop.

The only thing left would be milking the cows. I will test it with the mecanical user from Extra Utilies 2 and report back.

**Comment by capnkirok** [comment]
Will need to add infinite water source as well

**Comment by darthvader45** [comment]
Infinite water is already a vanilla thing, so it's fine, though a special infinite water block/multiblock would be cool.  The multiblock auto-milker is definitely my fave idea, considering how dairy farms are these days.

**Comment by Jomik** [comment]
The auto breeder is more or less already a thing it feels like? I mean, the animals breed when they are happy?
I do miss some way to actually separate adults from the babies. As I usually want to keep a population and then slaughter the excess 😈

**Comment by capnkirok** [comment]
You can use leads?

**Comment by Jomik** [comment]
@capnkirok I meant automatically without my interference :)

**Comment by darthvader45** [comment]
Still, love the auto-milker idea, and the fact that it could be implemented.  Cannot wait to see what it could turn out like.  Maybe ask IE's modeler for a model?

**Comment by Jomik** [comment]
I personally like the Animania models. Don't you think the designer of Animania can do an awesome auto-milker block? Or multiblock, if they intend to go that route.

**Comment by darthvader45** [comment]
True, but multiblocks might be a bit new for him.  Looking at IE's models might give him some inspiration.

**Comment by capnkirok** [comment]
Dispenser will dispense Seeds for Chickens in tonight's build (1.1.5)

**Comment by Ash70** [comment]
A versatile chronotyper is very high on my wishlist :)  But also, would you consider a different trough or model for when it is connected to a pipe? It is rather ugly looking when a pipe or conduit connects to the sides or bottom.

**Comment by RaliaTheWolf** [comment]
Just wanted to pop in and say that if you put a hopper with a chest under it and a nest on top, it will collect your eggs for you! I'm sure you could do something with that ^^

**Comment by capnkirok** [comment]
These are on our offline suggestion list... (some of the ideas are on the to do list even) going to close it here so we can focus the git on bugs. Thanks for the great ideas!
