### ISSUE TITLE
Placing seeds compatibility issues

### ISSUE THREAD

**Issue by Erinbutt** [capnkirok/animania#67]
Using the latest version (Animania-1.10.2-1.0.3)
The new way of planting seeds is causing another compatibility issue with a few other mods:
- Agricraft - creates a duplicate of the seed on top of the crop sticks when trying to place them within the crop sticks. 
- Forestry - Unable to place seeds on hummus soil, Animania takes priority over placement, making it impossible to place as a crop

Will post these bugs to the other mods as well 

Possible suggestions for solutions

- Shift right click instead of right clicking alone?
- Entirely new recipe for placing seeds? 4 seeds in a 2x2 square = seed pile?

**Comment by capnkirok** [comment]
Oh phooey. Shift-Right-Click might be the easiest option...

**Comment by capnkirok** [comment]
Fastest fix you've ever seen I am sure :)
