### ISSUE TITLE
Animal sounds being stereo

### ISSUE THREAD

**Issue by Lordician** [capnkirok/animania#69]
This is not a big issue, but if you can make the sounds mono this would make the mod automatically work with mods that add a bit of sound physics (reverb, echo all that) to Minecraft.
I am currently using one (literally called ["Sound Physics" by sonicether](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2771480-sound-physics-realistic-sound-reverberation)) and due to the sounds being stereo, i cannot enjoy the sound physics doing their work on the many sounds of these animals.

**Comment by capnkirok** [comment]
If I gave you a folder with all the sounds in it... would you convert to mono (you know, for the community)?

**Comment by Lordician** [comment]
I was thinking of seeing if i could somehow find the sounds and making them mono to create a resourcepack, just getting the files right away would make it easier and i am pretty sure i would be able to do so in a day.
I am not saying i am an audio professional, but certain other games required soundfiles to be in mono so i had to convert some.
I would do it with pleasure, love the mod and would love to help out with this. :)

**Comment by Lordician** [comment]
I extracted the sounds from the 1.0.4 jar file myself already and converted all the sounds that were in stereo form to mono and put all the sounds (i accidentally kept the unchanged files as well) in a resource pack:
[Animania MonoSounds.zip](https://github.com/capnkirok/animania/files/860341/Animania.MonoSounds.zip)
Seems to work well from my tests.
If there are any issues with it or you want me to check some sound because it is like borked for some weird reason or something, feel free to say it or contact me or whatever.

**Comment by capnkirok** [comment]
Hey! This is great! Thank you so much. I may put this in as a config option... Really Great that you did this !

**Comment by WesCook** [comment]
Thanks @Lordician!  I was testing Sound Physics earlier and noticed the animal sounds were super loud too.

**Comment by Lordician** [comment]
No problem!
It is good to see more people finding use for this.
I personally love sound physics ever since i found it, just like the Animania mod so it was only logical for me to help out.
Once the draft horses and/or other mobs are added i suppose i will have to update the resource pack again, but that would be no problem.

**Comment by capnkirok** [comment]
Ok, this will be in the next update :)

**Comment by WesCook** [comment]
Woo.  :)
