### ISSUE TITLE
Breeding Genetics

### ISSUE THREAD

**Issue by YaibaToKen** [capnkirok/animania#7]
Any chance we could have genetics influence the breeding process? 
Perhaps even using crossbreeding, similar to forestry's bees and trees.

Apologies, only noticed you already have genetics planned.

**Comment by capnkirok** [comment]
No worries! Glad to see someone who likes the idea.

The answer is YES!

**Comment by YaibaToKen** [comment]
well, I really liked the way the genetics were implemented in forestry and doing something similar for animals might give players a new reason to breed animals aside from food ;) like better/more food xD

**Comment by capnkirok** [comment]
Yes, we actually have a plan for this, just decided to de-prioritize for launch.

**Comment by YaibaToKen** [comment]
Well, keep up with the good work :D

**Comment by capnkirok** [comment]
Hey, I'm going to close this one for now. It's on our original todo list, and trying to clean up git so it shows bugs only. Thanks!
