### ISSUE TITLE
Server side tick lag?

### ISSUE THREAD

**Issue by OreCruncher** [capnkirok/animania#71]
I am profiling a modpack I am putting together and noticed that the following were in the top 5/6 when looking at hotspots in the server thread of execution:
+ com.animania.entities.pigs.EntityAIFollowParentPigs.func_75250_a()
+ com.animania.entities.cows.EntityAIFollowMateCows.func_75250_a()
+ com.animania.entities.cows.EntityAIFollowParentCows.func_75250_a()

(func_75250_a() => shouldExecute())

The server side TPS gets cut down to about 11 (from 20) while I am in the area of animals.  As soon as I clear the TPS pops back up to 20.

Not sure what else you would like in terms of information.  Let me know.

EDIT: I should mention that there are things in the way like logs and what not since it is in a wooded area.

**Comment by capnkirok** [comment]
Hey, this is great! What did you use to show this? I'm very curious for my own testing.

I've put delays and release valves for other AI scripts... but not these, so it makes sense. I will try to get these in the next release. Cheers!

**Comment by OreCruncher** [comment]
I used the NetBeans IDE to profile the Minecraft process.  I normally use Eclipse for development, but I like the NetBeans one for profiling.

**Comment by capnkirok** [comment]
Thanks! Yes, these methods all had the same issues. I've put in:
- A delay counter so it doesn't run as often
- A release valve, animals can (occasionally) choose not to follow the AI instructions, even though all the conditions are met. This allows them to move on to other scripts if necessary.

Let me know how it works! S/B available in a couple of hours.

**Comment by OreCruncher** [comment]
If the change is in the 1.0.4.1 version on CurseForge it does not appear to fix the issue.  Timings stills how a lot of tick time spent in the shouldExecute() method.

**Comment by capnkirok** [comment]
Bummer. Ok, I guess I'll have to install NetBeans :)

**Comment by OreCruncher** [comment]
Another tool you can try is [WarmRoast](https://github.com/sk89q/WarmRoast).  It's an older tool for profiling Bukkit servers, but it isn't tied strictly to Bukkit.  (I haven't used it - just aware of it.)

**Comment by BakermanLP** [comment]
For a real life example just have a look at:
http://minecraft2.bakermanlp.de:23000/stack
This server is our development server with only a few players online

**Comment by Sunconure11** [comment]
Do you think that the absurd spawn rates that I've found could be exacerbating this?

https://github.com/capnkirok/animania/issues/62

I'm having major TPS lag in singleplayer and I think this mod could possibly be to blame. I'm considering just setting up BiomeTweaker scripts or EnderZoo configuration files for mob spawns to reduce their spawn rates a bit, but seeing how entities are handled in this mod, it'd be a bit difficult.

**Comment by capnkirok** [comment]
It could be. I'm working on these two today.

**Comment by OreCruncher** [comment]
Based on those numbers it would be difficult to rule out.  Any ETA as to when the code will be published to Github?  We could take a look to see if anything stands out as a potential problem.

**Comment by capnkirok** [comment]
Well good news is that these 3 AI scripts were missing the delay timer. That means the delay timer is working. 

Still working on spawn rates. It's definitely a compat issue. Implementing caps at the moment.

**Comment by capnkirok** [comment]
Ok, here's a release candidate 1.0.4.5. Plan to publish tomorrow after a bit more testing. Recommend you purge your config and try it out. You'll see new options in the config for spawn (all require restart). @Sunconure11 

https://www.dropbox.com/s/ejbhvez3wrb05bn/animania-1.10-1.0.4.5.jar?dl=0

**Comment by capnkirok** [comment]
Posting update on Curse shortly. Crossing fingers for good news.

**Comment by Sunconure11** [comment]
I'll test mob spawn rates in the morning, due to my horrifying sleep schedule.

**Comment by OreCruncher** [comment]
Did a quick check for lag.  So far it's looking good.

**Comment by Sunconure11** [comment]
Just to make sure I'm not completely losing it about an unrelated mod, I would advise sifting through all mobs added by the mod, to make sure they do not suffer the same error as the ones shown in the graph.

**Comment by capnkirok** [comment]
Thanks @OreCruncher , hope the lag is still good. Please @Sunconure11 , @BakermanLP let me know if you are still seeing lag. I've tested multiple scenarios, servers, entity types, biomes... it all seems good. But I'm not using all the mods you are, so would like confirmation before I close this one.

**Comment by capnkirok** [comment]
After much testing, I haven't seen any new issues on my end, and nothing new reported.

The only exception I see is if you set gestation period very low and birth a ton of animals, but that is to be expected with any entity.

I am closing this one. If you run across additional issues, please let me know and I'll re-open. Thanks to everyone on this thread for the help. This was a nasty one.

PC
