### ISSUE TITLE
Baby animals not recognized as babies by other mods.

### ISSUE THREAD

**Issue by ScottRadish** [capnkirok/animania#72]
The baby animals don't pass through the baby animal filter blocks from Dark Utilities, and the Dreadthorne from Botania, (which doesn't hurt babies) hurts babies.

Also, when they are struck by lightning, the pigs do not turn into pigmen. This is a problem.

It's an awesome looking mod.

**Comment by capnkirok** [comment]
Pigs turn into Zombies, I made sure of that. Not sure why you are not seeing it. Easy to test with the Cloud Pet from Inventory Pets... can you check again?

I'll see what I can do about the compat issues. Thanks!

**Comment by Tschipp** [comment]
If the Entities extend EntityAgeable, you can just override isChild and return true all the time for the baby animals.

**Comment by capnkirok** [comment]
Cheers Tschipp!

**Comment by Tschipp** [comment]
Keep in mind I don't know exactly how these machines wor, I'm just taking a wild guess here.

**Comment by capnkirok** [comment]
I'm pretty sure that's it. Other than EntityAge, there's no other variable.
