### ISSUE TITLE
[feature request] some kind of control over spawning amounts

### ISSUE THREAD

**Issue by Zygus42** [capnkirok/animania#73]
I know that you only just removed the spawning rates from the config in 1.10.2, but this has caused the mod to be a lot less attractive to me in my new build.  There really needs to be some kind of say for servers of the amount of stuff that spawns in the world.  Maybe a setting for each category of animal with Low, Medium, High or Insane spawn amounts ?

**Comment by capnkirok** [comment]
Ha!

Ok, I think I need to put in a better mechanism.

**Comment by Seth0067** [comment]
@Zygus42 - its some work, but you should be able to modify spawns with Biome Tweaker.

**Comment by capnkirok** [comment]
I think I need more control and predictability within the mod first... still seeing very weird stuff. But, I have some new config options coming in next release.

**Comment by BakermanLP** [comment]
A spawn limit would be very usefull. Then this could be prevented: 
https://cdn.discordapp.com/attachments/270989578414850058/296614953983672320/2017-03-29_14.00.00.png

**Comment by capnkirok** [comment]
Oh god. This is my worst nightmare. Do you have a modlist?
