### ISSUE TITLE
Bugs in v1.0.4.1

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animania#74]
Minor: 
- Throughs cannot be placed, even if the block next to it is replaceable (like grass or water) Just do a check for Block#isReplaceable instead of an air check.
- The seeds still have a solid hitbox. Override Block#getCollisionBoundingBox and return NULL_AABB.
- The seeds are always trying to get placed on top of the block clicked. You should offset the position and then check if it's replaceable. The example code is here: https://github.com/capnkirok/animania/issues/46.
- When renaming an Albino Hedgehog Sonic, he takes half a heart of damage (wat).
- When killing tamed and renamed Ferrets and Hedgehogs, the custom name only gets displayed in the chat message if the animal was first renamed, and then tamed. If you first tame the animal and then rename it, the custom name doesn't show up.
- Hamsters remove hamster food out of the inventory in creative mode if the player is only holding a single food item.

Old:
- Tamed Ferrets, Hamsters and Hedgehogs still show a death message, even if not renamed.

Also:
- You don't need to register an item for the trough (invisiblock) just don't register an ItemBlock for it, and it won't show up in JEI (like double slabs). Same for the seed block. This is just a compat thing, because some mods (like my mod ForgottenItems) rely on the fact that blocks that don't have an item, are internal blocks only. 

Suggestions:
- Feed Poisonous Potatos to pigs - I mean they eat slop, so surely also poisonous potatos.
- Eating raw chicken should sometimes inflict poison (salmonella)

Other:
- Is it intended that you get 5 Bacon pieces from large black, but 4 from all other pigs?

**Comment by capnkirok** [comment]
- Other (yes)

**Comment by Tschipp** [comment]
"I don't think I want to know how you found this one!" It sadly involved a lot of killing :P 
But most of the time I find the bugs in like 30mins, but that's only because I know (from experience) where common sources of error are.
