### ISSUE TITLE
How to get wool

### ISSUE THREAD

**Issue by DoughnutDev** [capnkirok/animania#75]
How are you suppose to get wool, if there isn't any sheep yet?

**Comment by capnkirok** [comment]
Vanilla sheep still spawn :)

**Comment by DoughnutDev** [comment]
Oh okay they just weren't spawning. I am actually using this mod in a pack on the ATLauncher called DonutCraft really adds more to Minecraft.




- Gunnar Stinson









On Fri, Mar 24, 2017 at 7:55 PM -0400, "Purplicious_Cow" <notifications@github.com> wrote:










Vanilla sheep still spawn :)
