### ISSUE TITLE
Looting enchantment doesn't work on animals from your mod

### ISSUE THREAD

**Issue by Zygus42** [capnkirok/animania#77]
Tested on Holstein cows, and always get 3 raw beef (vanilla) and 3 leather, whether with Looting 3 or not.
Old Spot Pigs always drop 1 raw pork (Old Spot).   Leghorn Chickens drop 3 raw chicken (vanilla) and 3 feathers.  Is this working as intended ?  I would assume not, particularly the chickens - a 3 for 1 deal seems unlikely :)

**Comment by capnkirok** [comment]
Cheers, will take a look.

**Comment by capnkirok** [comment]
Yes, I forgot. I made the drops all fixed based on the happiness of the animal. But, can certainly add loot chance in here. Thanks for the reminder.

**Comment by Tschipp** [comment]
You might want to rewrite everything as a loottable

**Comment by capnkirok** [comment]
@Tschipp yup

**Comment by capnkirok** [comment]
See #95
