### ISSUE TITLE
[Feature Request] Access to Vanilla Mobs/Mob grinding utilities support

### ISSUE THREAD

**Issue by mrdeadlocked** [capnkirok/animania#78]
Mobs Grinding Utilities (https://minecraft.curseforge.com/projects/mob-grinding-utils ) Uses chicken feed to have a chicken drop a spawn egg. This doesn't work with Animania modded chickens. Support for Mob grinding Utilities or a way to get vanilla mobs would be geat.

**Comment by capnkirok** [comment]
You can currently turn on vanilla chickens in the config, probably the easiest way.

**Comment by mrdeadlocked** [comment]
Alright. I'll give that a try.

**Comment by capnkirok** [comment]
Assuming this one worked. If you haven't tried it yet, just look for the config option under game settings that says 'replace vanilla chickens.'
