### ISSUE TITLE
[Suggestion] Starveable animals

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animania#79]
I think it would be neat to have a animal-starving mechanic. Every time an animal eats or drinks, its food value (stored in nbt) would go up. That same food value would also tick down over time. When it hits 0, the animal starts starving, like players would. For cows, eating and drinkin out of troughs, eating grass from the floor (grass should be replaced with dirt) and manual feeding would increase its hunger value.
Pigs would only get food from troughs and manually and chickens would also eat seeds from the ground. All foods should give a different amount of food value. This should probably all be configurable. (You could also turn the entire food system off in the config. Would allow lots of options for modpack makers.)
I think it would be a neat mechanic and probably not too hard to implement.

**Comment by capnkirok** [comment]
Actually, the mechanics are there, I just don't make the animal starve. Felt somewhat cruel when I tested it. However, it's a bit easier now, and could add via config.

**Comment by Tschipp** [comment]
Please do that! Maybe have it disabled by default, but it would offer great customizability

**Comment by capnkirok** [comment]
Ok, we will add this, have now seen 3 requests for it as config option.

**Comment by Guinaro** [comment]
If at all possible, maybe allow some configuration options to allow grazing from certain plants? Like Pigs would eat Pam's Harvestcraft Corn, Chickens would love to pick Lettuce, ... . All configurable by the mod maker.

**Comment by capnkirok** [comment]
@Guinaro can you make a separate entry for your suggestion?
