### ISSUE TITLE
Add compatibility with SimpleCorn Mod

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/animania#8]
Add ability to place corn in the trough or on the ground for pigs, cows, and chickens.

**Comment by capnkirok** [comment]
Ok this is partly done. You can now add corn to a trough for horses and cows in 1.1.2 (on 1.11.2)

**Comment by capnkirok** [comment]
Need to add it for troughs to pigs... and create a corn block (like seeds).

**Comment by cleverpanda** [comment]
:D

**Comment by darthvader45** [comment]
Sounds cool, can't wait to see what comes of this.  Definitely allow corn to be made into slop with the usual other ingredients.  Maybe allow for a mixing machine (maybe a multiblock) for making slop?  I'd love to see how slop could be automated.
