### ISSUE TITLE
Seeds get placed in air above seed beds

### ISSUE THREAD

**Issue by Zygus42** [capnkirok/animania#80]
After the last fix with being able to place the seeds instead of throwing them, it all seems to work, except that when you're planting vanilla wheat fields, you get seeds placed in the air above the fields once you have seeds planted.  So, plant seed on field, plant seed on same field again, ends up hanging above the first seed in the air.

**Comment by Tschipp** [comment]
@capnkirok Check if the block is a full block (Block#isFullBlock) and if the block is not replaceable (!Block#isReplaceable). That will probably do it.

**Comment by capnkirok** [comment]
Thanks @Tschipp will fix

**Comment by capnkirok** [comment]
Ready for next release. Thanks.
