### ISSUE TITLE
Making Chesse doesn't drop the bucket

### ISSUE THREAD

**Issue by BakermanLP** [capnkirok/animania#81]
Testes in the latest release. 

I just made some Cheese out of milk. The durability is lowered, but I think, the bucket should also be droppped and not consumed, as it is at the moment.

Michael (aka BakermanLP)

**Comment by capnkirok** [comment]
Definitely a bug... though I'd taken care of this. Thx.

**Comment by capnkirok** [comment]
This will be in next release. Fixing this also helped with #85 .
