### ISSUE TITLE
[Suggestion] Add mod features to vanilla mobs

### ISSUE THREAD

**Issue by Rafilondon** [capnkirok/animania#87]
I really enjoy the new features like happiness or egg nests but it seems like they only work with the animania mobs. If it's not too much work, could you let vanilla animals use those featurers too? for people who want to use them instead the new ones for reasons like texture packs, mod support etc. that would certainly be helpful.

**Comment by capnkirok** [comment]
Thanks! Hmmm... there's no way for vanilla animals to use these features unfortunately (at least none that I know of), which is one of the reasons we made the mod :)

**Comment by Rafilondon** [comment]
oh, well allright, i will use your animals then. i hope someone will eventually create a hd texturepack for them :)
