### ISSUE TITLE
[1.11.2 - 1.0.4.5] Trough placement bug

### ISSUE THREAD

**Issue by VallenFrostweaver** [capnkirok/animania#88]
When Placing the Trough it will not place unless it is next to a block and in doing so it destroys the block it is next to. To replicate, place a trough in a 1 block deep and wide pit. It may also just glitch through into the neighboring block as well. See image below.
![gravel trough](https://cloud.githubusercontent.com/assets/13642054/24703805/c9477b7e-19fc-11e7-8481-078e34725357.png)

**Comment by capnkirok** [comment]
Not good. Will have to do a hotfix.

**Comment by Tschipp** [comment]
I thought this was fixed?

**Comment by capnkirok** [comment]
It's different in 1.11.2, 1.10.2 is fine. Actually 5-6 issues in 1.11.2 around the trough that I'm working on...

**Comment by Tschipp** [comment]
Oh, ok. You know about the itemstack == null or !itemstack.isEmpty() change, right?

**Comment by capnkirok** [comment]
Yes, but this one is something else in onBlockPlacedBy ...

**Comment by capnkirok** [comment]
Ok, got it. Will roll it out tonight.
