### ISSUE TITLE
[1.10.2] Trough Placement Crash for LAN Player

### ISSUE THREAD

**Issue by MokahTGS** [capnkirok/animania#89]
Got a crash of a LAN player placing a trough down.  This did not crash the host game, just the LAN player.

Crash reports:

https://pastebin.com/Ef1uugiL

https://pastebin.com/B0Q6pnUJ

It does not crash consistently, just randomly.

**Comment by Tschipp** [comment]
This looks more like a problem with waila. Try uninstalling it.

**Comment by MokahTGS** [comment]
But only when placing tje troughs down.  WAILA is not having any other issues with other things.

**Comment by Tschipp** [comment]
It has also happened to me once, with microblocks. Try contacting waila authors, or do you have an explanation @capnkirok?

**Comment by capnkirok** [comment]
Just chatted with Prof. Mobius. Looks like something is going wrong with my BlockState, which causes a crash in WAILA. Will look into it and do some testing.

**Comment by Tschipp** [comment]
As I mentioned in #91, I think there's some error with the states. It just shows facing:north even though it couldn't even be considered to be facing north, no matter from where you look at it.

**Comment by capnkirok** [comment]
Yeah, this was a result of 'unregistering' the invisiblock... creates havoc with WAILA

**Comment by capnkirok** [comment]
Assuming this is closed.
