### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animania#9]
- There are no proper death messages when getting killed by a bull. Ex: "Tschipp died".
- Sometimes the mobs don't have a death animation.
- The spawnegg places the mobs on the edge of the block, just add 0.5 to the x and z of the BlockPos.
- It is often not possible to place Throughs next to each other if you are trying to place it on the block just  right of the through. It also doesn't want to get placed on the block right next to the player when looking towards negative X, even if the player hitbox is not touching.
- Middle-clicking Mobs doesn't do anything
- The ferret's name is: entity.animania.FerretGrey.name --> add to .lang file.
- When breeding ferrets with vanilla eggs, the egg also gets thrown (if you have more than one in the stack)
- Placed seeds don't break when they are floating in midair and have a solid hitbox.

Minor:
- The spawneggs don't swing the arm when spawing a mob.
- The peacock sounds have a lot of background noise.

Also:
- Brown Eggs are not throwable, idk if that's intended though.
- Hamsters and Chicks and other small animals suffocate in Mud :(
- The way to place seeds is rather annoying, I suggest changing it to a right click (Or make dispensers able to place them!)

**Comment by capnkirok** [comment]
Thanks for this list and the detail, extremely helpful!

**Comment by capnkirok** [comment]
- Ferret and Peacock names fixed in dev

**Comment by capnkirok** [comment]
- Right click won't work for throwing seeds... that is already reserved for something else. Working on dispensers though

**Comment by Tschipp** [comment]
Why won't it work? Just check in the event if the clicked block isn't farmland.

**Comment by capnkirok** [comment]
- Peacock sounds now quieter with reduced background noise (in 1.0.2)
- Working on a new way to throw seeds (also in 1.0.2)

**Comment by Tschipp** [comment]
Mhh... I might not be seeing what the problem is with the seeds.. Can't you just check in the PlayerInteractEven if the player is holding Seeds (and maybe also sneaking, to prevent accidental placement) and also check if the block clicked isn't farmland?

**Comment by capnkirok** [comment]
I have never used this event, or thought of using it. Thanks for the tip.

**Comment by Tschipp** [comment]
I'm glad I was able to help! Will you be releasing the sources for the mod?

**Comment by Animewolflover** [comment]
There is also a bug were you can not craft a bucket of slop. I have tried all the different food's that would work and it's not. Just thought I'll say something. :3

**Comment by capnkirok** [comment]
Still open here:
- Placing seeds (in 1.0.3)
- Eggs thrown when feeding ferrets/hedgehogs (1.0.3)
- Middle-click doesn't do anything (WONTFIX, this is a result of a custom spawn egg)

**Comment by capnkirok** [comment]
@Animewolflover not able to replicate your issue... all slop buckets are craftable, including using ingredients from other mods like Harvestcraft ... maybe a conflict? can you post your modlist and verify you are on 1.0.2?

**Comment by Tschipp** [comment]
Hey! I just released a mod, on which I have worked on for a while! If you have some spare time, it would make me very proud if you would take a look at it and tell me what you think! It's called [http://www.planetminecraft.com/mod/forgotten-items-1112/](Forgotten Items)

**Comment by capnkirok** [comment]
Hey, it looks really interesting! I love the idea of morphing recipes :)
