### ISSUE TITLE
Bugs in v1.0.4.5 for 1.11.2

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animania#91]
Major: 
- Trough can only be placed while facing North, I suppose you have already found this. The trough's Facing Property is then south, even though it shouldn't be.

Minor: 
- The seeds can be placed on top of the invisiblock.
- The seeds can still be placed on certain plants, like rose bushes, that have a full block bounding box. I suggest adding a Block#isOpaque() check also. (Note that this will prevent the seeds from being placed on glass and such)
- Seeds are planted on farmland even when shift-clicking.
- Small animals like chicks and hamsters don't sink in mud, they just bob up and down, looks quite buggy... I'm guessing this is because of the fix to stop them from suffocating?
- The trough cannot be filled in creative or survival when the player is holding only 1 wheat.

Old:
- Pet animals still show a death message even if they're not renamed.
- Seeds still have a solid hitbox. Im starting to wonder if this is intended.

**Comment by capnkirok** [comment]
Thanks! 

- Seeds have solid hitbox is eluding me, not intentional. The suggestion you made did not work, but haven't spent enough time on it.

**Comment by Tschipp** [comment]
If I could look at the sources that would really help :3

**Comment by capnkirok** [comment]
- Troughs now placed properly (also closes #88 )
-
