### ISSUE TITLE
[Suggestion?] The angus cattle.

### ISSUE THREAD

**Issue by Lairfite** [capnkirok/animania#92]
I'm sorry but the Angus just annoys me because they're polled, they don't have any horns, they're a hornless breed...

It would be fun if it was possible to randomize if the bulls got nose ring or not.
And randomize if Hereford got horns or not because there is two types of Hereford, horned and polled.
Other than that animania is and awesome mod.

**Comment by capnkirok** [comment]
We were thinking the ring would only appear after they had been tamed.  Make sense?

Good suggestion on Hereford. Thanks!
