### ISSUE TITLE
[1.10.2] Massive Spawn Rate of Chickens 1.0.4.6

### ISSUE THREAD

**Issue by MokahTGS** [capnkirok/animania#94]
So patched up today to 1.0.4.6 to fix the crash with WAILA and troughs and found this:

https://www.dropbox.com/s/cracrlj7ww4i9df/2017-04-07_13.21.00.png?dl=0

The chickens seem to have gone nuts.

**Comment by capnkirok** [comment]
Delete your config and then try adjusting limits.

**Comment by capnkirok** [comment]
@MokahTGS did the resetting of the config work?

**Comment by MokahTGS** [comment]
Yes this has to do with the birth rates.  They need to be set really high or just cut off their food.

Would it make sense to have a max number setting that you can set in the config to keep this from happening?

**Comment by capnkirok** [comment]
Well the mod automatically 'culls' extra entities once you hit a certain limit.

**Comment by capnkirok** [comment]
I'm going to close this one as I'm adding another feature somewhere else to help further control limits. Thanks for the help @MokahTGS !
