### ISSUE TITLE
[Feature Request] Add loottables for Animania animals.

### ISSUE THREAD

**Issue by Titus-Armillius** [capnkirok/animania#95]
Due to their being no loottables I can't add or remove items via loottweaker from animal drops for my modpack which is a problem. I'd appreciate it if you added a hotfix sometime soon for this.

I would also like a list of all the entity ID's since the names in the /.lanf file don't seem to work.

**Comment by Tschipp** [comment]
I belive all the entity id's are configurable

**Comment by Titus-Armillius** [comment]
@Tschipp The entity ID values are configurable in the config. In order for lootweaker to work I need the entity's name ID, e.g. 'Skeleton'.

Also, any word on this issue?

**Comment by Tschipp** [comment]
Ah, I believe to find out those names you can type a /summon command and hit tab to get all the names autocompleted

**Comment by Titus-Armillius** [comment]
@Tschipp So will you be adding loottables, the nameID's are only relevant if I can use them to reference an entity specific loottable.

**Comment by Tschipp** [comment]
@Titus-Armillius
If I was working on the mod, I sure would :P

**Comment by capnkirok** [comment]
I will add loot tables... but a bit later (in 1.5).

**Comment by capnkirok** [comment]
Argh.... Loot Tables don't work for custom entities. Well, I can add it to the config... or put in a custom JSON.

**Comment by Titus-Armillius** [comment]
A config option for the new drops would be nice, for the time being I'm using InContol to remove/change certain drops.

**Comment by capnkirok** [comment]
Connected to #116

**Comment by capnkirok** [comment]
Re-opening this as meta-data items weren't working

**Comment by capnkirok** [comment]
Ok, this is in 1.1.4

**Comment by CKFrosty** [comment]
/my loottables all doesn't seem to pull the loot tables for animania, is there a way I can get them?

**Comment by Leviathan143** [comment]
@CKFrosty You need to give more information than that. You haven't even mentioned that `/mt loottables` is added by LootTweaker. See my answer to Leviathan143/LootTweaker#37
