### ISSUE TITLE
[Suggestion] Happiness, gestation, time to maturity etc

### ISSUE THREAD

**Issue by Karmacopper** [capnkirok/animania#97]
I notice none of these states appear in The One Probe, is it possible to add support for TOP?

**Comment by Nephatrine** [comment]
This would be a tremendous benefit. Just recently switched to TOP from WAILA and this is the only thing I miss.

**Comment by capnkirok** [comment]
Yes, we have plans to add exactly these things. Right now they are not tracked in a usable way, so have to make a few changes.
