### ISSUE TITLE
[Question] Baby Chickens Feather Fountain.  Related?

### ISSUE THREAD

**Issue by MokahTGS** [capnkirok/animania#98]
We are having an issue with feathers dropping continually from baby chickens from the Chickens mod and I was curious if there was any connection that might be from Animania.  The Chicken issue is here:

https://github.com/setycz/ChickensMod/issues/79

**Comment by Tschipp** [comment]
@MokahTGS 

> So after deactivating Animania the problem still persists, so it's not an interaction with that mod that's causing this.

**Comment by capnkirok** [comment]
Animania doesn't touch vanilla drops. I have separate entities. But to be sure, have you tried the modpack without Animania to see what happens?

**Comment by Tschipp** [comment]
Yep. The author commented on the other thread that it is not related with Animania

**Comment by GenDeathrow** [comment]
Sorry this seems to be a mod interaction with something else, I don't believe this is related to your mod in anyway. This isn't a chickens mod issue either. It appears to be Hatchery and another mod possible Quark as that seems to be a common mod. You should be able to close this.

**Comment by capnkirok** [comment]
Ok, closing :)
