### ISSUE TITLE
Bugs in 1.0.4.6 for 1.11.2

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animania#99]
Major:
- Disabling male genitalia actually disables a bit more... the entire model for bulls is gone. Also, when you punch one, the screen turns red and minecraft freaks out... it's kind of scary... even the main menu is freaking out. I have a clip demonstrating the bug here: https://youtu.be/QzsoZTNvNEs

Minor:
- Bucket is not returned in cheese making recipe
- Vanilla spawnegg only sometimes spawns animals but always uses an egg

New Bugs:
- Milk has eating animation
- Drinking Milk doesn't clear effects
- Watering Pigs in creative does not empty the bucket but gives you a empty bucket back
- When spam-click placing troughs sometimes excess invisiblocks can be created.

Old:
- Bucket is still not returned in Cheese making recipe

But hey, it's already getting harder for me to find these! You are doing great work!s

**Comment by capnkirok** [comment]
- Minor bug is fixed now that recipe is registering properly (#93)

**Comment by SDUBZ** [comment]
dont know if this is the right section for this but on server side at least with pams and animania is installed it affects the eggs buy able in the market getting affected by animania so far its the cow/chickens/ etc basically all aniamls spawn eggs

**Comment by Tschipp** [comment]
@capnkirok the easy way to fix this would be to implement a crafting recipe to convert the vanilla spawn eggs

**Comment by capnkirok** [comment]
Well, the vanilla spawn eggs still exist, but they spawn the Animania equivalents. If you want the eggs to spawn vanilla animals, then the server 'game rules' config must be changed so that 'Replace vanilla [animal]' is false for all the animals you want to keep (right now that's cows, pigs, and chickens.

I am pretty sure that's what you mean @SDUBZ , but let me know if not.

**Comment by Tschipp** [comment]
Hmm, is it intended that the spawneggs only spawn one variant of pigs, but the egg sometimes gets used up and no pig spawns?

**Comment by capnkirok** [comment]
Well, no, not that part, but that is still another issue. I'd like to know more about @SDUBZ issue first. Perhaps you can add that last one to your list above?

**Comment by Tschipp** [comment]
Added

**Comment by capnkirok** [comment]
Ok, new issue with vanilla spawn egg is fixed in dev and will be available at next release. Thanks @SDUBZ !

**Comment by SDUBZ** [comment]
np :D

**Comment by capnkirok** [comment]
- Drinking Milk now uses Drink Animation
- Milk now clears potion effects
- Watering Pigs from water bucket now gives back empty bucket only when not in creative... and does not use water in Creative
- Ditto above on Cows
- Bucket now properly returned with Cheese Recipes

**Comment by capnkirok** [comment]
@Tschipp , I can't replicated this one on 1.11.2:
When spam-click placing troughs sometimes excess invisiblocks can be created.

Can you send video or some reliable repro method?

**Comment by Tschipp** [comment]
@capnkirok I'll see what I can do

**Comment by Tschipp** [comment]
- Drinking milk replenishes hunger (I guess it makes sense, just isn't like vanilla milk)
- Drinking milk doesn't give instant health, probably because it is cleared instantly
- Eating Hereford roast beef doesn't give health boost, only for a split second. Same with cooked steak

MAJOR:
- Crafting cheese crashes. ArrayIndexOutOfBounds, check the CheeseRecipe1/2.class, line 96

Video of the Invisiblock dupe coming soon

**Comment by capnkirok** [comment]
- Hunger replenish is intended 
- 
-
